(function(root){
  'use strict';
  root.LQCAccessibilityLocales=Object.freeze({
    en:{'aria.homeBack':'Back to home','aria.favorite':'Favorite','aria.more':'More','aria.marketChart':'LQC market chart','aria.marketInfo':'Market information','aria.marketSearch':'Search markets','aria.chartTimeframe':'Chart timeframe','aria.chartType':'Chart type','aria.tradeSettings':'Trade settings','aria.candleChart':'LQC testnet candle chart','aria.kdj':'KDJ indicator','aria.indicators':'Chart indicators','aria.account':'Account information','aria.closeOrder':'Close order','aria.tradeDirection':'Trade direction','aria.tradeFeatures':'LQC simple trade features','aria.slippageInput':'Custom slippage','aria.amountIn':'Amount to pay','aria.balancePercent':'Balance percentage','aria.flipTokens':'Reverse token order','aria.optimalRoute':'LQC optimal trade route','aria.tradeActions':'LQC buy and sell','aria.quickTrade':'Quick trade','aria.mainMenu':'Main menu','aria.close':'Close','aria.tokenSearch':'Search trade tokens','aria.closeMarket':'Close markets','aria.marketTokenSearch':'Search market tokens','aria.marketFilter':'Market filter','aria.closeHistory':'Close trade history'},
    ko:{'aria.homeBack':'홈으로 돌아가기','aria.favorite':'즐겨찾기','aria.more':'더보기','aria.marketChart':'LQC 시장 차트','aria.marketInfo':'시장 정보','aria.marketSearch':'시장 검색','aria.chartTimeframe':'차트 시간 단위','aria.chartType':'차트 유형','aria.tradeSettings':'거래 설정','aria.candleChart':'LQC 테스트넷 캔들 차트','aria.kdj':'KDJ 보조지표','aria.indicators':'차트 지표','aria.account':'계정 정보','aria.closeOrder':'주문창 닫기','aria.tradeDirection':'거래 방향','aria.tradeFeatures':'LQC 간편 거래 특징','aria.slippageInput':'직접 입력 슬리피지','aria.amountIn':'보낼 수량','aria.balancePercent':'보유 잔액 비율 선택','aria.flipTokens':'토큰 순서 변경','aria.optimalRoute':'LQC 최적 거래 경로','aria.tradeActions':'LQC 매수 및 매도','aria.quickTrade':'빠른 거래','aria.mainMenu':'주요 메뉴','aria.close':'닫기','aria.tokenSearch':'거래 토큰 검색','aria.closeMarket':'마켓 닫기','aria.marketTokenSearch':'마켓 토큰 검색','aria.marketFilter':'마켓 필터','aria.closeHistory':'거래 내역 닫기'},
    ja:{'aria.homeBack':'ホームへ戻る','aria.favorite':'お気に入り','aria.more':'その他','aria.marketChart':'LQCマーケットチャート','aria.marketInfo':'マーケット情報','aria.marketSearch':'マーケット検索','aria.chartTimeframe':'チャート時間足','aria.chartType':'チャートタイプ','aria.tradeSettings':'取引設定','aria.candleChart':'LQCテストネットのローソク足チャート','aria.kdj':'KDJ指標','aria.indicators':'チャート指標','aria.account':'アカウント情報','aria.closeOrder':'注文画面を閉じる','aria.tradeDirection':'取引方向','aria.tradeFeatures':'LQC簡単取引の特徴','aria.slippageInput':'カスタムスリッページ','aria.amountIn':'支払数量','aria.balancePercent':'残高比率','aria.flipTokens':'トークン順序を反転','aria.optimalRoute':'LQC最適取引ルート','aria.tradeActions':'LQC購入と売却','aria.quickTrade':'クイック取引','aria.mainMenu':'メインメニュー','aria.close':'閉じる','aria.tokenSearch':'取引トークンを検索','aria.closeMarket':'マーケットを閉じる','aria.marketTokenSearch':'マーケットトークンを検索','aria.marketFilter':'マーケットフィルター','aria.closeHistory':'取引履歴を閉じる'},
    zh:{'aria.homeBack':'返回首页','aria.favorite':'收藏','aria.more':'更多','aria.marketChart':'LQC市场图表','aria.marketInfo':'市场信息','aria.marketSearch':'搜索市场','aria.chartTimeframe':'图表周期','aria.chartType':'图表类型','aria.tradeSettings':'交易设置','aria.candleChart':'LQC测试网K线图','aria.kdj':'KDJ指标','aria.indicators':'图表指标','aria.account':'账户信息','aria.closeOrder':'关闭订单面板','aria.tradeDirection':'交易方向','aria.tradeFeatures':'LQC简易交易功能','aria.slippageInput':'自定义滑点','aria.amountIn':'支付数量','aria.balancePercent':'余额比例','aria.flipTokens':'反转代币顺序','aria.optimalRoute':'LQC最优交易路线','aria.tradeActions':'LQC买入和卖出','aria.quickTrade':'快速交易','aria.mainMenu':'主菜单','aria.close':'关闭','aria.tokenSearch':'搜索交易代币','aria.closeMarket':'关闭市场','aria.marketTokenSearch':'搜索市场代币','aria.marketFilter':'市场筛选','aria.closeHistory':'关闭交易记录'}
  });
})(typeof window==='undefined'?globalThis:window);
