(function(root){
  'use strict';
  const messages={
    en:{'chart.verifiedHistory':'{timeframe} verified market history','chart.examplePending':'{timeframe} example chart · live history pending','chart.live':'{timeframe} live · {time}','chart.rising':'rising','chart.falling':'falling','chart.health.healthy':'Live and healthy','chart.health.delayed':'Connection delayed','chart.health.interrupted':'Connection interrupted','chart.sync.synced':'On-chain synchronized','chart.sync.catching-up':'Block synchronization delayed','chart.sync.unverified':'On-chain verification unavailable','chart.sync.stale':'Block synchronization interrupted','chart.offlineRecovery':'{timeframe} {health} · auto-recovery when online','chart.loading':'Loading {timeframe} history','chart.isolated':' · {count} isolated','chart.syncDetail':'{sync} · {blocks} blocks · {hash} · RPC {healthy}/{total}{isolation}','chart.rpcConsensusFailed':'Multi-RPC block hash consensus failed','chart.status':'{timeframe} {health} · {latency}ms · {sync} · last healthy {last}','chart.noRecord':'no record','chart.retryLive':'{timeframe} {health} · last healthy {last} · auto-recovery in {seconds}s','chart.retryExample':'{timeframe} {health} · example chart · retry in {seconds}s','wallet.nonCustodial':'Non-custodial wallet','wallet.browser':'Browser wallet'},
    ko:{'chart.verifiedHistory':'{timeframe} 검증된 마켓 히스토리','chart.examplePending':'{timeframe} 예시 차트 · 실시간 히스토리 연동 전','chart.live':'{timeframe} 실시간 · {time}','chart.rising':'상승','chart.falling':'하락','chart.health.healthy':'실시간 정상','chart.health.delayed':'연결 지연','chart.health.interrupted':'연결 중단','chart.sync.synced':'온체인 동기화','chart.sync.catching-up':'블록 동기화 지연','chart.sync.unverified':'온체인 확인 불가','chart.sync.stale':'블록 동기화 중단','chart.offlineRecovery':'{timeframe} {health} · 연결되면 자동복구','chart.loading':'{timeframe} 히스토리 불러오는 중','chart.isolated':' · 격리 {count}','chart.syncDetail':'{sync} · {blocks}블록 · {hash} · RPC {healthy}/{total}{isolation}','chart.rpcConsensusFailed':'다중 RPC 블록 해시 합의 실패','chart.status':'{timeframe} {health} · {latency}ms · {sync} · 정상 갱신 {last}','chart.noRecord':'기록 없음','chart.retryLive':'{timeframe} {health} · 마지막 정상 {last} · {seconds}초 후 자동복구','chart.retryExample':'{timeframe} {health} · 예시 차트 · {seconds}초 후 재시도','wallet.nonCustodial':'비수탁형 지갑','wallet.browser':'브라우저 지갑'},
    ja:{'chart.verifiedHistory':'{timeframe} 検証済みマーケット履歴','chart.examplePending':'{timeframe} サンプルチャート · ライブ履歴は未接続','chart.live':'{timeframe} ライブ · {time}','chart.rising':'上昇','chart.falling':'下落','chart.health.healthy':'ライブ正常','chart.health.delayed':'接続遅延','chart.health.interrupted':'接続中断','chart.sync.synced':'オンチェーン同期済み','chart.sync.catching-up':'ブロック同期遅延','chart.sync.unverified':'オンチェーン検証不可','chart.sync.stale':'ブロック同期中断','chart.offlineRecovery':'{timeframe} {health} · オンライン時に自動復旧','chart.loading':'{timeframe} 履歴を読み込み中','chart.isolated':' · {count}件隔離','chart.syncDetail':'{sync} · {blocks}ブロック · {hash} · RPC {healthy}/{total}{isolation}','chart.rpcConsensusFailed':'複数RPCのブロックハッシュ合意に失敗','chart.status':'{timeframe} {health} · {latency}ms · {sync} · 最終正常 {last}','chart.noRecord':'記録なし','chart.retryLive':'{timeframe} {health} · 最終正常 {last} · {seconds}秒後に自動復旧','chart.retryExample':'{timeframe} {health} · サンプルチャート · {seconds}秒後に再試行','wallet.nonCustodial':'ノンカストディアルウォレット','wallet.browser':'ブラウザーウォレット'},
    zh:{'chart.verifiedHistory':'{timeframe} 已验证市场历史','chart.examplePending':'{timeframe} 示例图表 · 实时历史尚未连接','chart.live':'{timeframe} 实时 · {time}','chart.rising':'上涨','chart.falling':'下跌','chart.health.healthy':'实时正常','chart.health.delayed':'连接延迟','chart.health.interrupted':'连接中断','chart.sync.synced':'链上已同步','chart.sync.catching-up':'区块同步延迟','chart.sync.unverified':'无法进行链上验证','chart.sync.stale':'区块同步中断','chart.offlineRecovery':'{timeframe} {health} · 联网后自动恢复','chart.loading':'正在加载{timeframe}历史','chart.isolated':' · 已隔离{count}个','chart.syncDetail':'{sync} · {blocks}个区块 · {hash} · RPC {healthy}/{total}{isolation}','chart.rpcConsensusFailed':'多RPC区块哈希共识失败','chart.status':'{timeframe} {health} · {latency}ms · {sync} · 最近正常 {last}','chart.noRecord':'无记录','chart.retryLive':'{timeframe} {health} · 最近正常 {last} · {seconds}秒后自动恢复','chart.retryExample':'{timeframe} {health} · 示例图表 · {seconds}秒后重试','wallet.nonCustodial':'非托管钱包','wallet.browser':'浏览器钱包'}
  };
  root.LQCChartLocales=Object.freeze(messages);
})(typeof window==='undefined'?globalThis:window);
