(function(){
  'use strict';
  const cfg=window.LQC_FLOW_CONFIG,{ethers}=window,$=id=>document.getElementById(id);
  const routerAbi=['function getAmountsOut(uint256,address[]) view returns (uint256[])','function swapExactTokensForTokens(uint256,uint256,address[],address,uint256) returns (uint256[])','function swapExactBNBForTokens(uint256,address[],address,uint256) payable returns (uint256[])','function swapExactTokensForBNB(uint256,uint256,address[],address,uint256) returns (uint256[])'];
  const quoteRouterAbi=['function quoteBest(address,address,uint256,bytes[]) view returns ((bytes32 dexId,address adapter,uint256 amountOut,uint32 priority))'];
  const tokenAbi=['function balanceOf(address) view returns (uint256)','function allowance(address,address) view returns (uint256)','function approve(address,uint256) returns (bool)'];
  const ui={connect:$('connectButton'),settings:$('settingsButton'),settingsPanel:$('settingsPanel'),amountIn:$('amountIn'),amountOut:$('amountOut'),minimum:$('minimumReceived'),route:$('routeLabel'),selectedDex:$('selectedDex'),selectedPath:$('selectedPath'),routeStrategy:$('routeStrategy'),balanceIn:$('balanceIn'),balanceOut:$('balanceOut'),positionBalance:$('positionBalance'),portfolioValue:$('portfolioValue'),tokenInButton:$('tokenInButton'),tokenOutButton:$('tokenOutButton'),flip:$('flipButton'),max:$('maxButton'),buy:$('buyAction'),sell:$('sellAction'),quick:$('quickTrade'),order:$('orderPanel'),close:$('closeOrder'),title:$('orderTitle'),execute:$('executeButton'),status:$('statusBox'),statusText:$('statusText'),dialog:$('tokenDialog'),tokenList:$('tokenList'),slippage:$('slippageInput')};
  let provider,signer,account,router,quoteRouter,side='in',timer,mode='buy',tokenIn=cfg.tokens[0],tokenOut=cfg.tokens[2];
  const deployed=ethers.isAddress(cfg.routerAddress)&&cfg.tokens.filter(t=>t.address!=='native').every(t=>ethers.isAddress(t.address));
  const address=t=>t.address==='native'?(cfg.tokens.find(x=>x.symbol==='WBNB')?.address||''):t.address;
  const status=(m,type='')=>{ui.status.className=`status ${type}`.trim();ui.statusText.textContent=m};
  const disabled=v=>ui.execute.disabled=v;
  function render(){for(const [s,t] of [['In',tokenIn],['Out',tokenOut]]){$(`token${s}Label`).textContent=t.symbol;$(`token${s}Icon`).textContent=t.symbol.slice(0,4);$(`token${s}Icon`).classList.toggle('mint',t.symbol==='LQC')}const path=`${tokenIn.symbol} → ${tokenOut.symbol}`;ui.route.textContent=path;ui.selectedPath.textContent=path}
  function setMode(next,open=true){const lqc=cfg.tokens.find(t=>t.symbol==='LQC'),bnb=cfg.tokens.find(t=>t.symbol==='BNB');mode=next;[tokenIn,tokenOut]=next==='buy'?[bnb,lqc]:[lqc,bnb];ui.title.textContent=next==='buy'?'LQC 매수':'LQC 매도';ui.execute.textContent=ui.title.textContent;ui.execute.className=`execute-button ${next}`;ui.buy.classList.toggle('active',next==='buy');ui.sell.classList.toggle('active',next==='sell');if(open)ui.order.classList.add('open');render();balances();quoteSoon()}
  async function ensureNetwork(){const chain=await ethereum.request({method:'eth_chainId'});if(chain===cfg.chainIdHex)return;try{await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:cfg.chainIdHex}]})}catch(e){if(e.code!==4902)throw e;await ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:cfg.chainIdHex,chainName:cfg.chainName,rpcUrls:cfg.rpcUrls,nativeCurrency:cfg.nativeCurrency,blockExplorerUrls:cfg.blockExplorerUrls}]})}}
  async function connect(){if(!window.ethereum)return status('MetaMask 또는 호환 지갑이 필요합니다.','error');try{provider=new ethers.BrowserProvider(ethereum);await ensureNetwork();signer=await provider.getSigner();account=await signer.getAddress();ui.connect.textContent=`${account.slice(0,6)}…${account.slice(-4)}`;router=deployed?new ethers.Contract(cfg.routerAddress,routerAbi,signer):null;quoteRouter=ethers.isAddress(cfg.quoteRouterAddress)?new ethers.Contract(cfg.quoteRouterAddress,quoteRouterAbi,provider):null;disabled(!deployed);status(deployed?'지갑이 연결되었습니다.':'지갑 연결 완료 · 테스트넷 컨트랙트 배포 대기 중',deployed?'success':'');await balances();quoteSoon()}catch(e){status(e.shortMessage||e.message||'지갑 연결에 실패했습니다.','error')}}
  async function balance(t){if(!provider||!account)return null;if(t.address==='native')return provider.getBalance(account);if(!ethers.isAddress(t.address))return null;return new ethers.Contract(t.address,tokenAbi,provider).balanceOf(account)}
  const format=(v,t)=>v===null?'—':Number(ethers.formatUnits(v,t.decimals)).toLocaleString(undefined,{maximumFractionDigits:5});
  async function balances(){const lqc=cfg.tokens.find(t=>t.symbol==='LQC'),[a,b,l]=await Promise.all([balance(tokenIn),balance(tokenOut),balance(lqc)]);ui.balanceIn.textContent=format(a,tokenIn);ui.balanceOut.textContent=format(b,tokenOut);ui.positionBalance.textContent=l===null?'—':`${format(l,lqc)} LQC`;if(l!==null)ui.portfolioValue.textContent=`$${(Number(ethers.formatUnits(l,lqc.decimals))*.091348).toLocaleString(undefined,{maximumFractionDigits:2})}`}
  function quoteSoon(){clearTimeout(timer);timer=setTimeout(quote,300)}
  async function quote(){ui.amountOut.textContent='0.0';ui.minimum.textContent='—';ui.selectedDex.textContent='견적 확인 중';const raw=ui.amountIn.value.trim();if(!raw||Number(raw)<=0||!router){ui.selectedDex.textContent='LQC Flow · PancakeSwap 비교 대기';return}try{const path=[address(tokenIn),address(tokenOut)],value=ethers.parseUnits(raw,tokenIn.decimals);let out,dexName='LQC Flow AMM';if(quoteRouter&&cfg.dexes?.length){const data=ethers.AbiCoder.defaultAbiCoder().encode(['address[]'],[path]),best=await quoteRouter.quoteBest(path[0],path[1],value,cfg.dexes.map(()=>data));out=best.amountOut;dexName=cfg.dexes.find(d=>d.id.toLowerCase()===best.dexId.toLowerCase())?.name||'승인된 DEX'}else{const amounts=await router.getAmountsOut(value,path);out=amounts.at(-1)}const bps=Math.round(Number(ui.slippage.value)*100),min=out*BigInt(10000-bps)/10000n;ui.amountOut.textContent=ethers.formatUnits(out,tokenOut.decimals);ui.minimum.textContent=`${Number(ethers.formatUnits(min,tokenOut.decimals)).toLocaleString(undefined,{maximumFractionDigits:6})} ${tokenOut.symbol}`;ui.selectedDex.textContent=dexName;ui.routeStrategy.textContent=quoteRouter?'다중 DEX 비교 · 최적 수령량':'단일 경로 · LQC Flow';disabled(false)}catch{ui.selectedDex.textContent='유효한 경로 없음';disabled(true);status('이 거래쌍의 유동성을 확인할 수 없습니다.','error')}}
  async function swap(){if(!router||!account)return connect();const raw=ui.amountIn.value.trim();if(!raw||Number(raw)<=0)return status('보낼 수량을 입력하세요.','error');try{disabled(true);const value=ethers.parseUnits(raw,tokenIn.decimals),path=[address(tokenIn),address(tokenOut)],amounts=await router.getAmountsOut(value,path),bps=Math.round(Number(ui.slippage.value)*100),min=amounts.at(-1)*BigInt(10000-bps)/10000n,deadline=Math.floor(Date.now()/1000)+1200;let tx;if(tokenIn.address==='native')tx=await router.swapExactBNBForTokens(min,path,account,deadline,{value});else{const token=new ethers.Contract(tokenIn.address,tokenAbi,signer);if(await token.allowance(account,cfg.routerAddress)<value){status(`${tokenIn.symbol} 사용 승인을 확인하세요.`);await(await token.approve(cfg.routerAddress,value)).wait()}tx=tokenOut.address==='native'?await router.swapExactTokensForBNB(value,min,path,account,deadline):await router.swapExactTokensForTokens(value,min,path,account,deadline)}status('거래가 제출되었습니다. 블록 확인 중입니다.');await tx.wait();status(`${mode==='buy'?'매수':'매도'} 거래가 완료되었습니다.`,'success');ui.amountIn.value='';await balances();await quote()}catch(e){status(e.shortMessage||'거래가 취소되었거나 실패했습니다.','error')}finally{disabled(!deployed)}}
  function tokenList(){ui.tokenList.replaceChildren(...cfg.tokens.map(t=>{const b=document.createElement('button');b.type='button';b.className='token-option';b.innerHTML=`<span class="token-symbol ${t.symbol==='LQC'?'mint':''}">${t.symbol.slice(0,4)}</span><b>${t.symbol}</b><span>${t.name}</span>`;b.onclick=()=>{const other=side==='in'?tokenOut:tokenIn;if(address(t)&&address(t)===address(other))return status('BNB와 WBNB는 동시에 선택할 수 없습니다.','error');if(side==='in')tokenIn=t;else tokenOut=t;ui.dialog.close();mode=tokenIn.symbol==='LQC'?'sell':'buy';ui.title.textContent=mode==='buy'?'LQC 매수':'LQC 매도';ui.execute.textContent=ui.title.textContent;ui.execute.className=`execute-button ${mode}`;render();balances();quoteSoon()};return b}))}
  function chart(){const closes=[92,110,98,128,175,218,270,260,225,178,164,151,168,176,169,181,158,145,132,278,301,270,226,206,182,169,188,204,238,312,286,254,226,194,160,137,124,196,251,226,210,231,218,197,176,151,139],g=$('candles'),bars=$('volumeBars'),ns='http://www.w3.org/2000/svg';closes.forEach((close,i)=>{const open=i?closes[i-1]+((i%5)-2)*3:108,x=i*16+3,up=close<open,high=Math.max(50,Math.min(open,close)-5-(i%4)*3),low=Math.min(340,Math.max(open,close)+7+(i%3)*4),wick=document.createElementNS(ns,'line'),body=document.createElementNS(ns,'rect');wick.setAttribute('x1',x+5.5);wick.setAttribute('x2',x+5.5);wick.setAttribute('y1',high);wick.setAttribute('y2',low);wick.setAttribute('class',`wick ${up?'up':'down'}`);body.setAttribute('x',x);body.setAttribute('y',Math.min(open,close));body.setAttribute('width',11);body.setAttribute('height',Math.max(5,Math.abs(open-close)));body.setAttribute('rx','.5');body.setAttribute('class',`candle ${up?'up':'down'}`);g.append(wick,body);const bar=document.createElement('i');bar.style.height=`${Math.min(66,9+Math.abs(open-close)*.8+(i%5)*2)}px`;if(!up)bar.className='hot';bars.append(bar)})}
  ui.connect.onclick=connect;ui.buy.onclick=()=>setMode('buy');ui.sell.onclick=()=>setMode('sell');ui.quick.onclick=()=>setMode('buy');ui.close.onclick=()=>ui.order.classList.remove('open');ui.execute.onclick=swap;ui.tokenInButton.onclick=()=>{side='in';ui.dialog.showModal()};ui.tokenOutButton.onclick=()=>{side='out';ui.dialog.showModal()};ui.flip.onclick=()=>{[tokenIn,tokenOut]=[tokenOut,tokenIn];render();balances();quoteSoon()};ui.amountIn.oninput=quoteSoon;ui.slippage.oninput=quoteSoon;ui.settings.onclick=()=>{ui.settingsPanel.hidden=!ui.settingsPanel.hidden;ui.order.classList.add('open')};ui.max.onclick=async()=>{const b=await balance(tokenIn);if(b!==null){const reserve=tokenIn.address==='native'?ethers.parseEther('.01'):0n;ui.amountIn.value=ethers.formatUnits(b>reserve?b-reserve:0n,tokenIn.decimals);quoteSoon()}};
  document.querySelectorAll('.slippage-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slippage-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');ui.slippage.value=b.dataset.value;quoteSoon()});document.querySelectorAll('.timeframes button:not(.chart-tool),.indicators button,.section-tabs button,.position-tabs button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});window.ethereum?.on?.('accountsChanged',connect);window.ethereum?.on?.('chainChanged',()=>location.reload());
  if(deployed)status('컨트랙트가 설정되었습니다. 지갑을 연결하세요.');render();tokenList();chart();setMode('buy',false);
})();
