(function(){
  'use strict';
  const cfg=window.LQC_FLOW_CONFIG,{ethers,LQCRouterSDK:sdk,LQCCandleData:candleData,LQCChartIndicators:indicatorMath,LQCChartHealth:chartHealth,LQCRecoveryBackoff:recoveryBackoff,LQCRecoverySync:recoverySync,LQCWalletSessionGuard:walletSessionGuardFactory,LQCTradeGate:tradeGate,LQCQuoteSessionGuard:quoteSessionGuardFactory}=window,$=id=>document.getElementById(id),walletSessionGuard=walletSessionGuardFactory.create(),quoteSessionGuard=quoteSessionGuardFactory.create();
  const routerAbi=['function getAmountsOut(uint256,address[]) view returns (uint256[])','function swapExactTokensForTokens(uint256,uint256,address[],address,uint256) returns (uint256[])','function swapExactBNBForTokens(uint256,address[],address,uint256) payable returns (uint256[])','function swapExactTokensForBNB(uint256,uint256,address[],address,uint256) returns (uint256[])'];
  const quoteRouterAbi=['function quoteBest(address,address,uint256,bytes[]) view returns ((bytes32 dexId,address adapter,uint256 amountOut,uint32 priority))'];
  const executionRouterAbi=['function swapExactInput(bytes32,address,address,uint256,uint256,address,uint256,bytes) returns (uint256)'];
  const nativeRouterAbi=['function swapExactNativeForToken(bytes32,address,uint256,address,uint256,bytes) payable returns (uint256)','function swapExactTokenForNative(bytes32,address,uint256,uint256,address,uint256,bytes) returns (uint256)'];
  const splitOptimizerAbi=['function quoteOptimalSplitCapped(address,address,uint256,bytes[],uint256[],uint256,uint256) view returns ((bytes32[] dexIds,address[] adapters,uint256[] amountsIn,uint256[] amountsOut,uint256 totalAmountOut,uint256 totalNetAmountOut))'];
  const autoRouterAbi=['function swapOptimizedExactInput(address,address,uint256,address,uint256,bytes[],uint256[],uint256,uint256) returns (uint256)'];
  const gasCostOracleAbi=['function quoteRouteCosts(address,uint256[],uint256) view returns (uint256[])'];
  const tokenAbi=['function balanceOf(address) view returns (uint256)','function allowance(address,address) view returns (uint256)','function approve(address,uint256) returns (bool)'];
  const adapterAbi=['function quoteExactInput(address,address,uint256,bytes) view returns (uint256)'];
  const ui={connect:$('connectButton'),settings:$('settingsButton'),settingsPanel:$('settingsPanel'),amountIn:$('amountIn'),amountOut:$('amountOut'),minimum:$('minimumReceived'),gas:$('estimatedGas'),impact:$('priceImpact'),split:$('splitRatio'),route:$('routeLabel'),selectedDex:$('selectedDex'),selectedPath:$('selectedPath'),routeStrategy:$('routeStrategy'),alternativeRoute:$('alternativeRoute'),preflightState:$('preflightState'),lastTradeLink:$('lastTradeLink'),lastSettledOutput:$('lastSettledOutput'),lastEvidenceHash:$('lastEvidenceHash'),tradeHistoryButton:$('tradeHistoryButton'),tradeHistoryDialog:$('tradeHistoryDialog'),tradeHistoryList:$('tradeHistoryList'),tradeHistoryCount:$('tradeHistoryCount'),balanceIn:$('balanceIn'),balanceOut:$('balanceOut'),walletDialog:$('walletDialog'),walletList:$('walletList'),positionBalance:$('positionBalance'),portfolioValue:$('portfolioValue'),tokenInButton:$('tokenInButton'),tokenOutButton:$('tokenOutButton'),flip:$('flipButton'),max:$('maxButton'),buy:$('buyAction'),sell:$('sellAction'),buyTab:$('buyTab'),sellTab:$('sellTab'),quick:$('quickTrade'),marketNav:$('marketNav'),tradeNav:$('tradeNav'),walletNav:$('walletNav'),order:$('orderPanel'),close:$('closeOrder'),title:$('orderTitle'),execute:$('executeButton'),status:$('statusBox'),statusText:$('statusText'),recoveryRetry:$('recoveryRetryButton'),pendingTradeLink:$('pendingTradeLink'),dialog:$('tokenDialog'),tokenList:$('tokenList'),tokenSearch:$('tokenSearch'),tokenCount:$('tokenCount'),tokenEmpty:$('tokenEmpty'),marketSelector:$('marketSelector'),marketPair:$('marketPair'),marketDialog:$('marketDialog'),marketList:$('marketList'),marketSearch:$('marketSearch'),marketCount:$('marketCount'),marketEmpty:$('marketEmpty'),tickerPrice:$('tickerPrice'),tickerChange:$('tickerChange'),priceSourceLabel:$('priceSourceLabel'),quoteAssetStat:$('quoteAssetStat'),priceStatusStat:$('priceStatusStat'),high24h:$('high24hStat'),low24h:$('low24hStat'),volume24h:$('volume24hStat'),slippage:$('slippageInput')};
  const walletMemoryKey='lqc-flow-wallet-connected';
  const chartMemoryKey='lqc-flow-chart-preferences',supportedTimeframes=['1m','3m','5m','15m','1h','4h','1D','1W','1M'],supportedIndicators=['volume','ma','ema','boll','sar','macd','kdj'],lowerIndicators=['volume','macd','kdj'];
  function storedChartPreferences(){try{const value=JSON.parse(localStorage.getItem(chartMemoryKey)||'null');if(!value||!supportedTimeframes.includes(value.timeframe)||!Array.isArray(value.indicators))return null;const indicators=[...new Set(value.indicators.filter(name=>supportedIndicators.includes(name)))],lower=indicators.find(name=>lowerIndicators.includes(name));return{timeframe:value.timeframe,indicators:indicators.filter(name=>!lowerIndicators.includes(name)||name===lower)}}catch{return null}}
  const initialChartPreferences=storedChartPreferences();
  let walletProvider,provider,signer,account,router,executionRouter,nativeRouter,splitOptimizer,autoRouter,gasCostOracle,wallets=[],boundWallets=new WeakSet(),lastHealthyByChart=new Map(),side='in',timer,chartRefreshTimer,chartFailureCount=0,verifiedChartKey='',marketPriceRequest=0,chartRequest=0,pendingRecoveryTimer,pendingRecoveryAttempts=0,pendingRecoveryActive=false,swapInFlight=false,unverifiedTransactionHash='',walletContextVersion=0,selectedTimeframe=initialChartPreferences?.timeframe||'1m',mode='buy',selectedAsset=cfg.tokens.find(t=>t.symbol==='LQC')||cfg.tokens[0],quoteToken=cfg.tokens.find(t=>t.symbol==='USDT')||cfg.tokens.find(t=>t.symbol==='BNB')||cfg.tokens[0],tokenIn=quoteToken,tokenOut=selectedAsset;
  const deployed=ethers.isAddress(cfg.quoteRouterAddress)&&ethers.isAddress(cfg.executionRouterAddress)&&ethers.isAddress(cfg.nativeRouterAddress)&&ethers.isAddress(cfg.splitOptimizerAddress)&&ethers.isAddress(cfg.autoRouterAddress)&&ethers.isAddress(cfg.gasCostOracleAddress)&&cfg.tokens.filter(t=>t.address!=='native').every(t=>ethers.isAddress(t.address));
  const readProviders=deployed?cfg.rpcUrls.map(url=>new ethers.JsonRpcProvider(url,cfg.chainId,{staticNetwork:true})):[],marketQuoteRouters=deployed?readProviders.map(source=>new ethers.Contract(cfg.quoteRouterAddress,quoteRouterAbi,source)):[];
  const rpcHealthMemoryKey=`lqc-flow-rpc-health:${cfg.deploymentFingerprint||'unconfigured'}`;
  const executionEvidenceMemoryKey=`lqc-flow-execution-evidence:${cfg.deploymentFingerprint||'unconfigured'}`;
  const pendingExecutionMemoryKey=`lqc-flow-pending-execution:${cfg.deploymentFingerprint||'unconfigured'}`;
  const swapLockName=`lqc-flow-swap:${cfg.deploymentFingerprint||'unconfigured'}`;
  const validRecoveryPayload=window.LQCRecoveryValidator.create({config:cfg,ethers,chartHealth});
  const recoveryStore=window.LQCRecoveryStore.create({storage:localStorage,key:pendingExecutionMemoryKey,deploymentFingerprint:cfg.deploymentFingerprint,isTransactionHash:value=>ethers.isHexString(value,32),validatePayload:validRecoveryPayload});
  function pendingExecutionState(){return recoveryStore.state()}
  function storedPendingExecution(){const record=pendingExecutionState();return record.state==='valid'?record.value:null}
  function rememberPendingExecution(transactionHash,anchorQuote,settlementContext){recoveryStore.remember(transactionHash,anchorQuote,settlementContext)}
  function rememberPendingCancellation(transactionHash,cancellationHash){recoveryStore.rememberCancellation(transactionHash,cancellationHash)}
  function assertPendingExecutionStorageAvailable(anchorQuote){recoveryStore.assertAvailable(anchorQuote)}
  function clearPendingExecution(transactionHash){return recoveryStore.clear(transactionHash)}
  function storedExecutionEvidence(){try{const values=JSON.parse(localStorage.getItem(executionEvidenceMemoryKey)||'[]');return Array.isArray(values)?values.filter(value=>sdk.verifyExecutionEvidence(value,cfg.deploymentFingerprint,ethers)).slice(0,10):[]}catch{return[]}}
  function renderExecutionEvidence(evidence=storedExecutionEvidence()[0]){if(!evidence)return;const token=cfg.tokens.find(item=>address(item).toLowerCase()===evidence.request.tokenOut);ui.lastTradeLink.textContent=`${evidence.settlement.transactionHash.slice(0,8)}…${evidence.settlement.transactionHash.slice(-6)}`;ui.lastTradeLink.href=`${cfg.blockExplorerUrls[0]}/tx/${evidence.settlement.transactionHash}`;ui.lastSettledOutput.textContent=`${ethers.formatUnits(evidence.settlement.actualAmountOut,token?.decimals||18)} ${token?.symbol||'TOKEN'}`;ui.lastEvidenceHash.textContent=`${evidence.evidenceHash.slice(0,10)}…${evidence.evidenceHash.slice(-8)}`}
  function rememberExecutionEvidence(evidence){const values=[evidence,...storedExecutionEvidence().filter(item=>item.evidenceHash!==evidence.evidenceHash)].slice(0,10);localStorage.setItem(executionEvidenceMemoryKey,JSON.stringify(values));renderExecutionEvidence(evidence)}
  function downloadExecutionEvidence(evidence){if(!sdk.verifyExecutionEvidence(evidence,cfg.deploymentFingerprint,ethers))return;const blob=new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`lqc-swap-${evidence.evidenceHash.slice(2,14)}.json`;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}
  function renderExecutionHistory(){const values=storedExecutionEvidence();ui.tradeHistoryCount.textContent=`${values.length}건`;ui.tradeHistoryList.replaceChildren(...values.map(evidence=>{const item=document.createElement('article'),head=document.createElement('div'),txLink=document.createElement('a'),amount=document.createElement('strong'),meta=document.createElement('div'),time=document.createElement('span'),confirmations=document.createElement('span'),actions=document.createElement('div'),hash=document.createElement('code'),download=document.createElement('button'),token=cfg.tokens.find(entry=>address(entry).toLowerCase()===evidence.request.tokenOut);item.className='trade-history-item';head.className='trade-history-head';txLink.href=`${cfg.blockExplorerUrls[0]}/tx/${evidence.settlement.transactionHash}`;txLink.target='_blank';txLink.rel='noopener';txLink.textContent=`${evidence.settlement.transactionHash.slice(0,8)}…${evidence.settlement.transactionHash.slice(-6)}`;amount.textContent=`${ethers.formatUnits(evidence.settlement.actualAmountOut,token?.decimals||18)} ${token?.symbol||'TOKEN'}`;head.append(txLink,amount);meta.className='trade-history-meta';time.textContent=new Date(evidence.completedAt).toLocaleString();confirmations.textContent=`${evidence.settlement.confirmations}블록 확인`;meta.append(time,confirmations);actions.className='trade-history-actions';hash.textContent=evidence.evidenceHash;download.type='button';download.textContent='JSON 다운로드';download.onclick=()=>downloadExecutionEvidence(evidence);actions.append(hash,download);item.append(head,meta,actions);return item}))}
  function openExecutionHistory(){renderExecutionHistory();ui.tradeHistoryDialog.showModal()}
  function storedRpcSourceHealth(){try{return chartHealth.restoreSourceHealth(JSON.parse(localStorage.getItem(rpcHealthMemoryKey)||'null'),cfg.deploymentFingerprint,readProviders.length)||null}catch{return null}}
  const rpcSourceHealth=storedRpcSourceHealth()||readProviders.map(()=>Object.freeze({failures:0,quarantinedUntil:0}));
  let trustedReadProviderIndexes=[],trustedReadBlock=null,trustedReadHash='',trustedReadVerifiedAt=0;
  function saveRpcSourceHealth(now=Date.now()){try{if(readProviders.length)localStorage.setItem(rpcHealthMemoryKey,JSON.stringify(chartHealth.sourceHealthSnapshot(rpcSourceHealth,cfg.deploymentFingerprint,now)))}catch{}}
  function recordRpcSource(index,healthy,now){rpcSourceHealth[index]=chartHealth.sourceHealth(rpcSourceHealth[index],healthy,now);saveRpcSourceHealth(now)}
  const address=t=>t.address==='native'?(cfg.tokens.find(x=>x.symbol==='WBNB')?.address||''):t.address;
  const status=(m,type='')=>{ui.status.className=`status ${type}`.trim();ui.statusText.textContent=m};
  const t=(key,values={})=>window.LQCI18n.t(key,values);
  const translatedSwapError=error=>{const guidance=sdk.explainSwapError(error),key=`error.${guidance.code.toLowerCase()}`;return`${t(`${key}.message`)} ${t(`${key}.action`)}`};
  const disabled=v=>ui.execute.disabled=tradeGate.disabled({requestedDisabled:Boolean(v),deployed,account,swapInFlight});
  const tradeControls=()=>[ui.amountIn,ui.slippage,ui.tokenInButton,ui.tokenOutButton,ui.flip,ui.max,ui.buy,ui.sell,ui.buyTab,ui.sellTab,ui.marketSelector,...document.querySelectorAll('.amount-presets button,.slippage-option')];
  function setSwapInFlight(value){swapInFlight=Boolean(value);ui.execute.setAttribute('aria-busy',String(swapInFlight));for(const control of tradeControls())control.disabled=swapInFlight;if(swapInFlight){if(ui.dialog.open)ui.dialog.close();if(ui.marketDialog.open)ui.marketDialog.close()}disabled(!deployed)}
  function invalidateWalletContext(){walletContextVersion++}
  function assertCurrentWalletConnection(target,version){walletSessionGuard.assertCurrent(target,version);if(target!==walletProvider)throw new Error('WalletConnectionSuperseded')}
  function clearConnectedWallet(){walletSessionGuard.invalidate();quoteSessionGuard.invalidate();invalidateWalletContext();account=null;signer=null;provider=null;router=null;executionRouter=null;nativeRouter=null;splitOptimizer=null;autoRouter=null;gasCostOracle=null;ui.connect.textContent=t('wallet.connect');disabled(true)}
  function snapshotWalletContext(){return Object.freeze({version:walletContextVersion,account:String(account||'').toLowerCase(),chainId:cfg.chainId})}
  async function assertWalletContext(context){const[currentAccount,network]=await Promise.all([signer.getAddress(),provider.getNetwork()]);if(context.version!==walletContextVersion||currentAccount.toLowerCase()!==context.account||Number(network.chainId)!==context.chainId)throw new Error('WalletContextChangedDuringSwap')}
  function render(){for(const [s,t] of [['In',tokenIn],['Out',tokenOut]]){$(`token${s}Label`).textContent=t.symbol;$(`token${s}Icon`).textContent=t.symbol.slice(0,4);$(`token${s}Icon`).classList.toggle('mint',t.symbol==='LQC')}const path=`${tokenIn.symbol} → ${tokenOut.symbol}`;ui.route.textContent=path;ui.selectedPath.textContent=path;ui.marketPair.textContent=`${selectedAsset.symbol} / ${quoteToken.symbol}`}
  function setMode(next,open=true){mode=next;[tokenIn,tokenOut]=next==='buy'?[quoteToken,selectedAsset]:[selectedAsset,quoteToken];const label=t('trade.action',{symbol:selectedAsset.symbol,side:t(next==='buy'?'side.buy':'side.sell')});ui.title.textContent=label;ui.execute.textContent=label;ui.execute.className=`execute-button ${next}`;for(const button of [ui.buy,ui.buyTab])button.classList.toggle('active',next==='buy');for(const button of [ui.sell,ui.sellTab])button.classList.toggle('active',next==='sell');if(open)ui.order.classList.add('open');render();balances();refreshMarketPrice();quoteSoon()}
  function pairApproved(a,b){
    const endpoints=[address(a).toLowerCase(),address(b).toLowerCase()].sort();
    if(endpoints[0]===endpoints[1])return false;
    if(!a.reviewed&&!b.reviewed)return true;
    return (cfg.reviewedPairs||[]).some(pair=>[pair.tokenA.toLowerCase(),pair.tokenB.toLowerCase()].sort().every((value,index)=>value===endpoints[index]));
  }
  function preferredQuote(asset){return ['USDT','BNB','LQC','WBNB'].map(symbol=>cfg.tokens.find(token=>token.symbol===symbol)).find(token=>token&&pairApproved(asset,token))}
  function marketList(query=''){
    const needle=query.trim().toLowerCase(),tokens=cfg.tokens.filter(token=>preferredQuote(token)&&(!needle||[token.symbol,token.name,token.address].some(value=>String(value).toLowerCase().includes(needle))));
    ui.marketCount.textContent=t('market.count',{count:tokens.length});ui.marketEmpty.hidden=tokens.length>0;
    ui.marketList.replaceChildren(...tokens.map((token,index)=>{const button=document.createElement('button'),rank=document.createElement('span'),identity=document.createElement('span'),icon=document.createElement('i'),names=document.createElement('span'),symbol=document.createElement('b'),name=document.createElement('small'),price=document.createElement('span'),state=document.createElement('span');button.type='button';button.className='market-row';button.setAttribute('role','option');rank.textContent=String(index+1);icon.textContent=token.symbol.slice(0,2);symbol.textContent=token.symbol;name.textContent=token.name;names.append(symbol,name);identity.append(icon,names);price.textContent='—';state.textContent=t(token.address==='native'?'market.native':'market.reviewed');button.append(rank,identity,price,state);button.onclick=()=>selectMarket(token);return button}))
  }
  function selectMarket(token){const fallback=preferredQuote(token);if(!fallback)return status(t('market.noBase'),'error');selectedAsset=token;quoteToken=fallback;ui.marketDialog.close();setMode(mode,false);loadChartHistory();window.scrollTo({top:0,behavior:'smooth'})}
  function openMarkets(){ui.order.classList.remove('open');ui.marketSearch.value='';marketList();ui.marketDialog.showModal();setTimeout(()=>ui.marketSearch.focus(),0)}
  async function ensureNetwork(target,interactive=true){const chain=await target.request({method:'eth_chainId'});if(chain.toLowerCase()===cfg.chainIdHex.toLowerCase())return true;if(!interactive)return false;try{await target.request({method:'wallet_switchEthereumChain',params:[{chainId:cfg.chainIdHex}]})}catch(e){if(e.code!==4902)throw e;await target.request({method:'wallet_addEthereumChain',params:[{chainId:cfg.chainIdHex,chainName:cfg.chainName,rpcUrls:cfg.rpcUrls,nativeCurrency:cfg.nativeCurrency,blockExplorerUrls:cfg.blockExplorerUrls}]})}return true}
  async function connect(target=walletProvider||wallets[0]?.provider||window.ethereum,interactive=true){
    if(!target)return status(t('status.noWallet'),'error');
    if(walletProvider&&target!==walletProvider)clearConnectedWallet();walletProvider=target;const connectionVersion=walletSessionGuard.begin(target);
    try{
      const accounts=await target.request({method:interactive?'eth_requestAccounts':'eth_accounts'});assertCurrentWalletConnection(target,connectionVersion);const chain=await target.request({method:'eth_chainId'});assertCurrentWalletConnection(target,connectionVersion);const remembered=localStorage.getItem(walletMemoryKey)==='1',session=sdk.walletSessionState(accounts,interactive||remembered,chain,cfg.chainIdHex);
      if(session==='disconnected'){clearConnectedWallet();status(t(interactive?'status.approveConnection':'status.disconnected'));return}
      if(session==='wrong_network'&&!interactive){clearConnectedWallet();ui.connect.textContent='BSC Testnet';status(t('status.switchNetwork'));return}
      await ensureNetwork(target,interactive);assertCurrentWalletConnection(target,connectionVersion);const nextProvider=new ethers.BrowserProvider(target),nextSigner=await nextProvider.getSigner(),nextAccount=await nextSigner.getAddress();assertCurrentWalletConnection(target,connectionVersion);provider=nextProvider;signer=nextSigner;account=nextAccount;localStorage.setItem(walletMemoryKey,'1');bindWalletEvents(target);ui.connect.textContent=`${account.slice(0,6)}…${account.slice(-4)}`;router=ethers.isAddress(cfg.routerAddress)?new ethers.Contract(cfg.routerAddress,routerAbi,signer):null;executionRouter=deployed?new ethers.Contract(cfg.executionRouterAddress,executionRouterAbi,signer):null;nativeRouter=deployed?new ethers.Contract(cfg.nativeRouterAddress,nativeRouterAbi,signer):null;splitOptimizer=deployed?new ethers.Contract(cfg.splitOptimizerAddress,splitOptimizerAbi,provider):null;autoRouter=deployed?new ethers.Contract(cfg.autoRouterAddress,autoRouterAbi,signer):null;gasCostOracle=deployed?new ethers.Contract(cfg.gasCostOracleAddress,gasCostOracleAbi,provider):null;disabled(!deployed);status(t(deployed?'status.walletReady':'status.walletWaiting'),deployed?'success':'');await balances();quoteSoon()
    }catch(e){if(e?.message!=='WalletConnectionSuperseded')status(translatedSwapError(e),'error')}
  }
  async function balance(t){if(!provider||!account)return null;if(t.address==='native')return provider.getBalance(account);if(!ethers.isAddress(t.address))return null;return new ethers.Contract(t.address,tokenAbi,provider).balanceOf(account)}
  const format=(v,t)=>v===null?'—':Number(ethers.formatUnits(v,t.decimals)).toLocaleString(undefined,{maximumFractionDigits:5});
  async function balances(){const lqc=cfg.tokens.find(t=>t.symbol==='LQC'),[a,b,l]=await Promise.all([balance(tokenIn),balance(tokenOut),balance(lqc)]);ui.balanceIn.textContent=format(a,tokenIn);ui.balanceOut.textContent=format(b,tokenOut);ui.positionBalance.textContent=l===null?'—':`${format(l,lqc)} LQC`;if(l!==null)ui.portfolioValue.textContent=`$${(Number(ethers.formatUnits(l,lqc.decimals))*.091348).toLocaleString(undefined,{maximumFractionDigits:2})}`}
  async function applyBalancePercent(percent){const current=await balance(tokenIn);if(current===null)return status(t('status.connectFirst'),'error');const reserve=tokenIn.address==='native'?ethers.parseEther('.01'):0n,available=current>reserve?current-reserve:0n,value=available*BigInt(percent)/100n;ui.amountIn.value=ethers.formatUnits(value,tokenIn.decimals);quoteSoon()}
  function quoteContext(raw=ui.amountIn.value.trim()){return{tokenIn:address(tokenIn).toLowerCase(),tokenOut:address(tokenOut).toLowerCase(),amount:raw,slippage:String(ui.slippage.value),wallet:walletContextVersion}}
  function quoteSoon(){quoteSessionGuard.invalidate();clearTimeout(timer);timer=setTimeout(quote,300)}
  function approvedRoutesFor(inputToken,outputToken,path){
    const restricted=[inputToken,outputToken].filter(token=>token.reviewed);
    let allowed=cfg.dexes;
    if(restricted.length){
      const endpoints=[path[0].toLowerCase(),path.at(-1).toLowerCase()].sort(),pair=(cfg.reviewedPairs||[]).find(item=>
        [item.tokenA.toLowerCase(),item.tokenB.toLowerCase()].sort().every((value,index)=>value===endpoints[index]));
      if(!pair)throw new Error('No approved token pair');
      const pairDexIds=new Set(pair.dexIds.map(value=>value.toLowerCase()));
      allowed=cfg.dexes.filter(dex=>pairDexIds.has(dex.id.toLowerCase())&&restricted.every(token=>(token.routeDexIds||[]).includes(dex.id.toLowerCase())));
    }
    if(allowed.length===0)throw new Error('No mutually approved DEX route');
    const allowedIds=new Set(allowed.map(dex=>dex.id.toLowerCase())),encoded=sdk.encodeRoutes(cfg.dexes,path,ethers);
    return encoded.map((route,index)=>allowedIds.has(cfg.dexes[index].id.toLowerCase())?route:'0x');
  }
  function approvedRoutes(path){return approvedRoutesFor(tokenIn,tokenOut,path)}
  async function readOnlyBestQuote(tokenA,tokenB,value,routes){if(!trustedReadProviderIndexes.length||!Number.isSafeInteger(trustedReadBlock)||Date.now()-trustedReadVerifiedAt>5000)await chainHeadWithin();if(!trustedReadProviderIndexes.length||!Number.isSafeInteger(trustedReadBlock)||!trustedReadHash)throw new Error('Browser RPC quorum unavailable');const now=Date.now(),observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{return{index,quote:await marketQuoteRouters[index].quoteBest(tokenA,tokenB,value,routes,{blockTag:trustedReadBlock})}}catch{return null}}))).filter(Boolean),consensus=chartHealth.consensusQuote(observations,readProviders.length);if(!consensus){for(const index of trustedReadProviderIndexes.filter(value=>!observations.some(item=>item.index===value)))recordRpcSource(index,false,now);trustedReadProviderIndexes=[];trustedReadBlock=null;trustedReadHash='';throw new Error('Browser RPC quote consensus unavailable')}for(const item of observations.filter(item=>!consensus.sourceIndexes.includes(item.index)))recordRpcSource(item.index,false,now);trustedReadProviderIndexes=trustedReadProviderIndexes.filter(index=>consensus.sourceIndexes.includes(index));return chartHealth.bindQuote(consensus,trustedReadBlock,trustedReadHash,now)}
  function quoteRequest(tokenA,tokenB,value,routes,slippageBps){return{chainId:cfg.chainId,router:cfg.quoteRouterAddress,tokenIn:tokenA,tokenOut:tokenB,amountIn:value,routes,slippageBps}}
  function executionRequest(router,minimumAmountOut,deadline,kind){return{sender:account,recipient:account,router,minimumAmountOut,deadline,kind}}
  function bindAndCheckExecution(anchorQuote,request){const binding=chartHealth.bindExecutionPlan(anchorQuote,request);if(!chartHealth.executionPlanMatches(binding,request))throw new Error('ExecutionPlanChangedBeforeSigning');return binding}
  async function simulateSwapTransaction(anchorQuote,request,gasCeiling){const callRequest={...request,from:account},observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{const [result,gas]=await Promise.all([readProviders[index].call({...callRequest,blockTag:anchorQuote.blockNumber}),readProviders[index].estimateGas(callRequest)]);return{index,result,gas}}catch{return null}}))).filter(Boolean),consensus=chartHealth.consensusSimulation(observations,readProviders.length,gasCeiling);if(!consensus)throw new Error('TransactionSimulationConsensusFailed');return consensus}
  function fixedFeeFields(fee){if(typeof fee?.maxFeePerGas==='bigint'&&fee.maxFeePerGas>0n&&typeof fee.maxPriorityFeePerGas==='bigint'&&fee.maxPriorityFeePerGas>=0n&&fee.maxPriorityFeePerGas<=fee.maxFeePerGas)return{type:2,gasPrice:null,maxFeePerGas:fee.maxFeePerGas,maxPriorityFeePerGas:fee.maxPriorityFeePerGas};if(typeof fee?.gasPrice==='bigint'&&fee.gasPrice>0n)return{type:0,gasPrice:fee.gasPrice,maxFeePerGas:null,maxPriorityFeePerGas:null};throw new Error('WalletFeeDataUnavailable')}
  async function consensusFeeFields(){const observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{return{index,...await readProviders[index].getFeeData()}}catch{return null}}))).filter(Boolean),consensus=chartHealth.consensusFeeData(observations,readProviders.length);if(!consensus)throw new Error('TransactionFeeConsensusFailed');return fixedFeeFields(consensus)}
  async function consensusTransactionCount(){const observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{return{index,nonce:await readProviders[index].getTransactionCount(account,'pending')}}catch{return null}}))).filter(Boolean),consensus=chartHealth.consensusTransactionCount(observations,readProviders.length);if(!consensus)throw new Error('TransactionNonceConsensusFailed');return consensus.nonce}
  async function prepareSwapTransaction(anchorQuote,method,args,gasCeiling){const populated=await method.populateTransaction(...args),base={...populated,chainId:cfg.chainId,value:populated.value??0n},gasProbe=await simulateSwapTransaction(anchorQuote,base,gasCeiling),[nonce,walletNonce,fees]=await Promise.all([consensusTransactionCount(),provider.getTransactionCount(account,'pending'),consensusFeeFields()]);if(walletNonce!==nonce)throw new Error('WalletNonceConsensusMismatch');const request=Object.freeze({...base,...fees,gasLimit:gasProbe.gasLimit,nonce}),finalSimulation=await simulateSwapTransaction(anchorQuote,request,gasCeiling);if(finalSimulation.gasEstimate>request.gasLimit)throw new Error('FinalTransactionGasLimitInsufficient');const binding=chartHealth.bindTransaction(anchorQuote,request),maximumNetworkFee=request.gasLimit*(request.type===2?request.maxFeePerGas:request.gasPrice);if(!chartHealth.transactionMatches(binding,request))throw new Error('WalletTransactionChangedBeforeSigning');ui.gas.textContent=t('quote.maximumGas',{amount:Number(ethers.formatEther(maximumNetworkFee)).toFixed(6)});return{binding,request}}
  async function sendPreparedTransaction(prepared,walletContext){await assertWalletContext(walletContext);assertPendingExecutionStorageAvailable(prepared.binding);if(!chartHealth.transactionMatches(prepared.binding,prepared.request))throw new Error('WalletTransactionChangedBeforeSigning');const[nonce,walletNonce]=await Promise.all([consensusTransactionCount(),provider.getTransactionCount(account,'pending')]);if(nonce!==prepared.request.nonce||walletNonce!==nonce)throw new Error('WalletNonceChangedBeforeSigning');return signer.sendTransaction(prepared.request)}
  async function verifySubmittedTransaction(transactionHash,anchorQuote,settlementContext,requiredConfirmations=3){const transferTopic=ethers.id('Transfer(address,address,uint256)'),nativeEventTopic=ethers.id('NativeSwapExecuted(address,address,address,bool,uint256,uint256)'),context={...settlementContext,transferTopic,nativeEventTopic},observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{const[transaction,receipt]=await Promise.all([readProviders[index].getTransaction(transactionHash),readProviders[index].waitForTransaction(transactionHash,requiredConfirmations,90000)]);if(!transaction||!receipt)return null;const[block,head]=await Promise.all([readProviders[index].getBlock(receipt.blockNumber),readProviders[index].getBlockNumber()]),receiptHash=String(receipt.hash||receipt.transactionHash||'').toLowerCase();if(receiptHash!==transactionHash.toLowerCase()||Number(receipt.status)!==1||String(block?.hash||'').toLowerCase()!==String(receipt.blockHash||'').toLowerCase()||head-receipt.blockNumber+1<requiredConfirmations)return null;return{index,transaction,receipt,block,head,amountOut:chartHealth.decodeSettlementOutput(receipt,context)}}catch{return null}}))).filter(Boolean),submitted=chartHealth.consensusSubmittedTransaction(anchorQuote,observations,readProviders.length,transactionHash),submittedIndexes=new Set(submitted?.sourceIndexes||[]),submittedObservations=observations.filter(item=>submittedIndexes.has(item.index)),consensus=chartHealth.consensusTransactionReceipt(submittedObservations,readProviders.length,transactionHash,requiredConfirmations),receiptIndexes=new Set(consensus?.sourceIndexes||[]),output=chartHealth.consensusSettlementOutput(submittedObservations.filter(item=>receiptIndexes.has(item.index)),readProviders.length,settlementContext.minimumAmountOut);if(!submitted||!consensus||!output)throw new Error('TransactionConsensusFailed');const settledAnchorQuote=chartHealth.transactionMatches(anchorQuote,submitted)?anchorQuote:chartHealth.bindReplacementTransaction(anchorQuote,submitted);return Object.freeze({settlement:Object.freeze({...consensus,amountOut:output.amountOut}),anchorQuote:settledAnchorQuote})}
  async function verifyFailedSubmittedTransaction(transactionHash,anchorQuote,requiredConfirmations=3){const observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{const[transaction,receipt]=await Promise.all([readProviders[index].getTransaction(transactionHash),readProviders[index].getTransactionReceipt(transactionHash)]);if(!transaction||!receipt||Number(receipt.status)!==0)return null;const[block,head]=await Promise.all([readProviders[index].getBlock(receipt.blockNumber),readProviders[index].getBlockNumber()]);return{index,transaction,receipt,block,head}}catch{return null}}))).filter(Boolean),submitted=chartHealth.consensusSubmittedTransaction(anchorQuote,observations,readProviders.length,transactionHash),submittedIndexes=new Set(submitted?.sourceIndexes||[]);if(!submitted)return null;return chartHealth.consensusFailedTransactionReceipt(observations.filter(item=>submittedIndexes.has(item.index)),readProviders.length,transactionHash,requiredConfirmations)}
  async function verifyCancelledSubmittedTransaction(transactionHash,anchorQuote,requiredConfirmations=3){const observations=(await Promise.all(trustedReadProviderIndexes.map(async index=>{try{const[transaction,receipt]=await Promise.all([readProviders[index].getTransaction(transactionHash),readProviders[index].waitForTransaction(transactionHash,requiredConfirmations,90000)]);if(!transaction||!receipt||Number(receipt.status)!==1)return null;const[block,head]=await Promise.all([readProviders[index].getBlock(receipt.blockNumber),readProviders[index].getBlockNumber()]);return{index,transaction,receipt,block,head}}catch{return null}}))).filter(Boolean),cancelled=chartHealth.consensusCancellationTransaction(anchorQuote,observations,readProviders.length,transactionHash),indexes=new Set(cancelled?.sourceIndexes||[]);if(!cancelled)return null;return chartHealth.consensusTransactionReceipt(observations.filter(item=>indexes.has(item.index)),readProviders.length,transactionHash,requiredConfirmations)}
  async function waitForFinalTransactionHash(tx){try{const receipt=await tx.wait();if(!receipt||Number(receipt.status)!==1)throw new Error('SubmittedTransactionFailed');return tx.hash}catch(error){if(error?.code!=='TRANSACTION_REPLACED')throw error;if(error.cancelled){const cancellation=new Error('TransactionReplacementCancelled');cancellation.replacementHash=error.replacement?.hash;throw cancellation}const replacement=error.replacement,receipt=error.receipt;if(!replacement||!ethers.isHexString(replacement.hash,32)||!receipt||Number(receipt.status)!==1||String(receipt.hash||receipt.transactionHash||'').toLowerCase()!==replacement.hash.toLowerCase())throw new Error('InvalidTransactionReplacement');return replacement.hash}}
  function setPendingTradeControls(pending,visible){ui.recoveryRetry.hidden=!visible;ui.pendingTradeLink.hidden=!visible;if(visible&&pending){const activeHash=pending.cancellationHash||pending.transactionHash;ui.pendingTradeLink.href=`${cfg.blockExplorerUrls[0]}/tx/${activeHash}`}else ui.pendingTradeLink.removeAttribute('href')}
  function pendingRecoveryDelay(){const delay=recoveryBackoff.delay(pendingRecoveryAttempts);pendingRecoveryAttempts++;return delay}
  function schedulePendingRecoveryRetry(delay=pendingRecoveryDelay()){clearTimeout(pendingRecoveryTimer);if(document.hidden||navigator.onLine===false)return;pendingRecoveryTimer=setTimeout(()=>recoverPendingExecution(),delay)}
  async function recoverPendingExecution(){clearTimeout(pendingRecoveryTimer);const pending=storedPendingExecution();if(pendingRecoveryActive||!pending||!deployed)return false;pendingRecoveryActive=true;setPendingTradeControls(pending,true);ui.recoveryRetry.disabled=true;setSwapInFlight(true);unverifiedTransactionHash=pending.transactionHash;status(t('status.recovering',{hash:`${(pending.cancellationHash||pending.transactionHash).slice(0,10)}…`}));try{if(!trustedReadProviderIndexes.length)await chainHeadWithin();if(pending.cancellationHash){const cancelled=await verifyCancelledSubmittedTransaction(pending.cancellationHash,pending.anchorQuote);if(!cancelled)throw new Error('CancellationConsensusPending');if(!clearPendingExecution(pending.transactionHash))throw new Error('PendingExecutionStorageConflict');setPendingTradeControls(null,false);pendingRecoveryAttempts=0;unverifiedTransactionHash='';status(t('status.recoveredCancellation',{confirmations:cancelled.confirmations}),'success');return true}const verified=await verifySubmittedTransaction(pending.transactionHash,pending.anchorQuote,pending.settlementContext),evidence=sdk.buildExecutionEvidence(verified.anchorQuote,verified.settlement,cfg.deploymentFingerprint,Date.now(),ethers);rememberExecutionEvidence(evidence);if(!clearPendingExecution(pending.transactionHash))throw new Error('PendingExecutionStorageConflict');setPendingTradeControls(null,false);pendingRecoveryAttempts=0;unverifiedTransactionHash='';status(t('status.recovered',{confirmations:verified.settlement.confirmations}),'success');if(account)await balances();return true}catch{try{if(!pending.cancellationHash){if(!trustedReadProviderIndexes.length)await chainHeadWithin();const failure=await verifyFailedSubmittedTransaction(pending.transactionHash,pending.anchorQuote);if(failure&&clearPendingExecution(pending.transactionHash)){setPendingTradeControls(null,false);pendingRecoveryAttempts=0;unverifiedTransactionHash='';status(t('status.recoveredFailure',{confirmations:failure.confirmations}),'error');return true}}}catch{}const latest=storedPendingExecution();if(!latest)return false;unverifiedTransactionHash=latest.transactionHash;status(t('status.resultUnknown',{hash:`${(latest.cancellationHash||latest.transactionHash).slice(0,10)}…`}),'error');setPendingTradeControls(latest,true);schedulePendingRecoveryRetry();return false}finally{pendingRecoveryActive=false;ui.recoveryRetry.disabled=false;if(!unverifiedTransactionHash)setSwapInFlight(false)}}
  function handlePendingExecutionStorage(event){const record=event.newValue===null?{state:'none'}:pendingExecutionState(),action=recoverySync.storageAction({expectedStorage:event.storageArea===localStorage,keyMatches:event.key===pendingExecutionMemoryKey,newValue:event.newValue,record,unverifiedTransactionHash,pendingRecoveryActive});if(action==='ignore'||action==='retain')return;if(action==='release'){clearTimeout(pendingRecoveryTimer);pendingRecoveryAttempts=0;setPendingTradeControls(null,false);setSwapInFlight(false);return}if(action==='invalid'){invalidateWalletContext();setSwapInFlight(true);status(t('status.pendingRecordInvalid'),'error');return}invalidateWalletContext();setPendingTradeControls(record.value,true);setSwapInFlight(true);setTimeout(()=>recoverPendingExecution(),0)}
  async function verifyQuoteBeforeSigning(bound,tokenA,tokenB,value,routes,slippageBps,timeoutMs=2500){if(!bound||Date.now()>bound.expiresAt)throw new Error('QuoteExpiredBeforeSigning');if(!chartHealth.quoteRequestMatches(bound,quoteRequest(tokenA,tokenB,value,routes,slippageBps)))throw new Error('QuoteContextChangedBeforeSigning');const deadline=performance.now()+timeoutMs,probe=promise=>new Promise(resolve=>{const timeout=setTimeout(()=>resolve(null),Math.max(0,deadline-performance.now()));promise.then(resolve,()=>resolve(null)).finally(()=>clearTimeout(timeout))}),indexes=readProviders.map((_,index)=>index).filter(index=>rpcSourceHealth[index].quarantinedUntil<=Date.now()),checks=await Promise.all(indexes.map(async index=>{const [block,quote]=await Promise.all([probe(readProviders[index].getBlock(bound.blockNumber)),probe(marketQuoteRouters[index].quoteBest(tokenA,tokenB,value,routes,{blockTag:bound.blockNumber}))]);return{index,block,quote}})),hashes=checks.map(item=>item.block?.hash).filter(hash=>typeof hash==='string'&&/^0x[0-9a-fA-F]{64}$/.test(hash)),hashConsensus=chartHealth.consensusHash(hashes,readProviders.length),quoteObservations=checks.filter(item=>item.quote&&item.block?.hash?.toLowerCase()===bound.blockHash).map(item=>({index:item.index,quote:item.quote})),quoteConsensus=chartHealth.consensusQuote(quoteObservations,readProviders.length);if(!hashConsensus||!quoteConsensus||!chartHealth.quoteBindingMatches(bound,quoteConsensus,hashConsensus.blockHash))throw new Error('QuoteChangedBeforeSigning');return true}
  async function bestQuote(value,path,routes=approvedRoutes(path)){const best=await readOnlyBestQuote(path[0],path.at(-1),value,routes),index=cfg.dexes.findIndex(d=>d.id.toLowerCase()===best.dexId.toLowerCase());if(index<0||routes[index]==='0x')throw new Error('Unknown or unapproved DEX');return{best,routeData:routes[index],dex:cfg.dexes[index]}}
  async function refreshMarketPrice(){const request=++marketPriceRequest,asset=selectedAsset,quoteAsset=quoteToken;ui.tickerPrice.textContent='—';ui.quoteAssetStat.textContent=quoteAsset.symbol;ui.priceStatusStat.textContent=t(deployed?'market.quoteChecking':'market.deploymentPending');ui.priceSourceLabel.textContent='Router spot price';if(!marketQuoteRouters.length)return;try{const path=[address(asset),address(quoteAsset)],routes=approvedRoutesFor(asset,quoteAsset,path),unit=ethers.parseUnits('1',asset.decimals),best=await readOnlyBestQuote(path[0],path[1],unit,routes),index=cfg.dexes.findIndex(d=>d.id.toLowerCase()===best.dexId.toLowerCase());if(request!==marketPriceRequest)return;if(index<0||routes[index]==='0x'||best.amountOut<=0n)throw new Error('No approved market quote');const value=Number(ethers.formatUnits(best.amountOut,quoteAsset.decimals));ui.tickerPrice.textContent=`${value.toLocaleString(undefined,{maximumSignificantDigits:8})} ${quoteAsset.symbol}`;ui.priceSourceLabel.textContent=`${cfg.dexes[index].name} · 1 ${asset.symbol}`;ui.priceStatusStat.textContent=t('market.liveQuote')}catch{if(request===marketPriceRequest)ui.priceStatusStat.textContent=t(trustedReadProviderIndexes.length?'market.noLiquidity':'market.rpcPending')}}
  async function rankedRoutes(value,path,routes,costs){
    const candidates=await Promise.all(cfg.dexes.map(async(dex,index)=>{
      if(!ethers.isAddress(dex.adapter))return null;
      try{
        const amountOut=await new ethers.Contract(dex.adapter,adapterAbi,provider).quoteExactInput(path[0],path.at(-1),value,routes[index]);
        return{name:dex.name,dex,index,routeData:routes[index],amountOut,cost:costs?.[index]||0n,priority:Number(dex.priority||0)};
      }catch{return null}
    }));
    return sdk.rankRouteQuotes(candidates);
  }
  async function executionPlan(value,path){
    const routes=approvedRoutes(path),grossSingle=await bestQuote(value,path,routes),slippageBps=Math.round(Number(ui.slippage.value)*100),anchorQuote=chartHealth.bindQuoteRequest(grossSingle.best,quoteRequest(path[0],path.at(-1),value,routes,slippageBps));
    if(tokenIn.address==='native'||tokenOut.address==='native')return{kind:'single',single:grossSingle,anchorQuote,routes,costs:cfg.dexes.map(()=>0n),oracleReady:false};
    let costs;try{const feeData=await provider.getFeeData(),gasUnits=cfg.dexes.map(dex=>BigInt(dex.gasUnits||220000));costs=await gasCostOracle.quoteRouteCosts(path.at(-1),gasUnits,feeData.gasPrice||0n)}catch{return{kind:'single',single:grossSingle,anchorQuote,routes,costs:cfg.dexes.map(()=>0n),oracleReady:false}}
    const ranked=await rankedRoutes(value,path,routes,costs),netBest=ranked[0];
    if(!netBest)throw new Error('No executable route after gas');
    const single={best:{dexId:netBest.dex.id,adapter:netBest.dex.adapter,amountOut:netBest.amountOut,priority:netBest.priority},routeData:netBest.routeData,dex:netBest.dex};
    const split=await splitOptimizer.quoteOptimalSplitCapped(path[0],path.at(-1),value,routes,costs,10,4);
    if(!sdk.isSplitNetBetter(single.best.amountOut,netBest.cost,split.totalNetAmountOut))return{kind:'single',single,anchorQuote,routes,costs,ranked,oracleReady:true};
    return{kind:'split',single,anchorQuote,split,routes,costs,ranked,oracleReady:true,summary:sdk.summarizeSplit(cfg.dexes,split.amountsIn,value)};
  }
  async function planPriceImpact(value,out,probe,path,plan){
    if(plan.kind==='single'){
      const probeOut=await new ethers.Contract(plan.single.dex.adapter,adapterAbi,provider).quoteExactInput(path[0],path.at(-1),probe,plan.single.routeData);
      return sdk.priceImpactBps(value,out,probe,probeOut);
    }
    const expectedParts=await Promise.all(plan.summary.map(async item=>{
      const index=cfg.dexes.indexOf(item.dex),probeOut=await new ethers.Contract(item.dex.adapter,adapterAbi,provider).quoteExactInput(path[0],path.at(-1),probe,plan.routes[index]);
      return item.amountIn*probeOut/probe;
    }));
    return sdk.priceImpactFromExpected(out,expectedParts.reduce((total,part)=>total+part,0n));
  }
  async function quote(){
    ui.amountOut.textContent='0.0';ui.minimum.textContent='—';ui.gas.textContent='—';ui.impact.textContent='—';ui.split.textContent=t('quote.single');ui.selectedDex.textContent=t('quote.checking');ui.alternativeRoute.textContent=t('quote.routeChecking');ui.alternativeRoute.classList.remove('alternative-ready');ui.preflightState.textContent=t('quote.preflightChecking');ui.preflightState.className='';
    const raw=ui.amountIn.value.trim(),ticket=quoteSessionGuard.begin(quoteContext(raw));if(!raw||Number(raw)<=0||!deployed){ui.selectedDex.textContent=t('quote.comparisonPending');ui.alternativeRoute.textContent=t('quote.shownAfterQuote');ui.preflightState.textContent=t('quote.pending');return}
    try{
      const path=[address(tokenIn),address(tokenOut)],value=ethers.parseUnits(raw,tokenIn.decimals),probe=value>1000n?value/1000n:1n,plan=await executionPlan(value,path),out=plan.kind==='split'?plan.split.totalAmountOut:plan.single.best.amountOut,[impact,feeData]=await Promise.all([planPriceImpact(value,out,probe,path,plan),provider.getFeeData()]),ranked=plan.ranked||await rankedRoutes(value,path,plan.routes,plan.costs),min=sdk.minimumAmountOut(out,ui.slippage.value),gasDex=plan.kind==='split'?{gasUnits:plan.summary.reduce((total,item)=>total+Number(item.dex.gasUnits||220000),0)}:plan.single.dex,gasWei=sdk.estimatedGasWei(gasDex,feeData.gasPrice||0n,tokenIn.address==='native'||tokenOut.address==='native');
      if(!quoteSessionGuard.isCurrent(ticket,quoteContext()))return;
      ui.amountOut.textContent=ethers.formatUnits(out,tokenOut.decimals);ui.minimum.textContent=`${Number(ethers.formatUnits(min,tokenOut.decimals)).toLocaleString(undefined,{maximumFractionDigits:6})} ${tokenOut.symbol}`;ui.gas.textContent=`≈ ${Number(ethers.formatEther(gasWei)).toFixed(6)} BNB`;ui.impact.textContent=`≈ ${(impact/100).toFixed(2)}%`;ui.impact.classList.toggle('warning',impact>=300);ui.selectedDex.textContent=plan.kind==='split'?plan.summary.map(item=>item.dex.name).join(' + '):plan.single.dex.name;ui.split.textContent=plan.kind==='split'?plan.summary.map(item=>`${item.dex.name} ${item.percent.toFixed(1)}%`).join(' · '):t('quote.singleFull');ui.routeStrategy.textContent=t(plan.kind==='split'?'quote.strategySplit':plan.oracleReady?'quote.strategySingle':'quote.strategyOraclePending');const fallback=ranked.find(item=>item.name!==ranked[0]?.name);ui.alternativeRoute.textContent=fallback?t('quote.fallback',{name:fallback.name}):t('quote.noFallback');ui.alternativeRoute.classList.toggle('alternative-ready',Boolean(fallback));ui.preflightState.textContent=t(impact>=300?'quote.highImpact':plan.oracleReady?'quote.ready':'quote.limited');ui.preflightState.className=impact>=300||!plan.oracleReady?'preflight-warning':'preflight-safe';status(t(impact>=300?'quote.impactWarning':'quote.preflightPassed'),impact>=300?'':'success');disabled(false);
    }catch{if(!quoteSessionGuard.isCurrent(ticket,quoteContext()))return;ui.selectedDex.textContent=t('quote.noValidRoute');ui.alternativeRoute.textContent=t('quote.noAlternative');ui.preflightState.textContent=t('quote.unavailable');ui.preflightState.className='preflight-warning';disabled(true);status(t('quote.noLiquidity'),'error')}
  }
  async function executeSwap(){
    if(swapInFlight)return status(t('status.swapBusy'));
    if(!executionRouter||!account)return connect();const raw=ui.amountIn.value.trim();if(!raw||Number(raw)<=0)return status(t('status.amountRequired'),'error');setSwapInFlight(true);
    try{
      disabled(true);const walletContext=snapshotWalletContext(),value=ethers.parseUnits(raw,tokenIn.decimals),path=[address(tokenIn),address(tokenOut)];let plan=await executionPlan(value,path),deadline=Math.floor(Date.now()/1000)+1200,bps=Math.round(Number(ui.slippage.value)*100),tx,settlementContext;
      if(tokenIn.address==='native'){const min=sdk.minimumAmountOut(plan.single.best.amountOut,ui.slippage.value),execution=executionRequest(cfg.nativeRouterAddress,min,deadline,'native-in');plan.anchorQuote=bindAndCheckExecution(plan.anchorQuote,execution);await verifyQuoteBeforeSigning(plan.anchorQuote,path[0],path[1],value,plan.routes,bps);if(!chartHealth.executionPlanMatches(plan.anchorQuote,execution))throw new Error('ExecutionPlanChangedBeforeSigning');const gasCeiling=BigInt(plan.single.dex.gasUnits||220000)*2n,prepared=await prepareSwapTransaction(plan.anchorQuote,nativeRouter.swapExactNativeForToken,[plan.single.best.dexId,path[1],min,account,deadline,plan.single.routeData,{value}],gasCeiling);plan.anchorQuote=prepared.binding;settlementContext={kind:'erc20',tokenOut:path[1],recipient:account,minimumAmountOut:min};tx=await sendPreparedTransaction(prepared,walletContext)}
      else{let spender=tokenOut.address==='native'?cfg.nativeRouterAddress:plan.kind==='split'?cfg.autoRouterAddress:cfg.executionRouterAddress,token=new ethers.Contract(tokenIn.address,tokenAbi,signer),allowance=await token.allowance(account,spender);if(sdk.requiresTokenApproval(allowance,value)){await assertWalletContext(walletContext);status(t('status.approveToken',{symbol:tokenIn.symbol}));await(await token.approve(spender,value)).wait();await assertWalletContext(walletContext);status(t('status.approvalDone'));plan=await executionPlan(value,path);const refreshedSpender=tokenOut.address==='native'?cfg.nativeRouterAddress:plan.kind==='split'?cfg.autoRouterAddress:cfg.executionRouterAddress;if(refreshedSpender.toLowerCase()!==spender.toLowerCase()){spender=refreshedSpender;allowance=await token.allowance(account,spender);if(sdk.requiresTokenApproval(allowance,value)){await assertWalletContext(walletContext);status(t('status.routeApproval'));await(await token.approve(spender,value)).wait();await assertWalletContext(walletContext);plan=await executionPlan(value,path);const finalSpender=tokenOut.address==='native'?cfg.nativeRouterAddress:plan.kind==='split'?cfg.autoRouterAddress:cfg.executionRouterAddress;if(finalSpender.toLowerCase()!==spender.toLowerCase())throw new Error('RouteChangedDuringApproval')}}}deadline=Math.floor(Date.now()/1000)+1200;const output=plan.kind==='split'?plan.split.totalAmountOut:plan.single.best.amountOut,min=sdk.minimumAmountOut(output,ui.slippage.value),kind=tokenOut.address==='native'?'native-out':plan.kind,execution=executionRequest(spender,min,deadline,kind);plan.anchorQuote=bindAndCheckExecution(plan.anchorQuote,execution);await verifyQuoteBeforeSigning(plan.anchorQuote,path[0],path[1],value,plan.routes,bps);if(!chartHealth.executionPlanMatches(plan.anchorQuote,execution))throw new Error('ExecutionPlanChangedBeforeSigning');let method,args;if(tokenOut.address==='native'){method=nativeRouter.swapExactTokenForNative;args=[plan.single.best.dexId,path[0],value,min,account,deadline,plan.single.routeData]}else if(plan.kind==='split'){method=autoRouter.swapOptimizedExactInput;args=[path[0],path[1],value,account,deadline,plan.routes,plan.costs,10,bps]}else{method=executionRouter.swapExactInput;args=[plan.single.best.dexId,path[0],path[1],value,min,account,deadline,plan.single.routeData]}const plannedGas=plan.kind==='split'?plan.summary.reduce((total,item)=>total+BigInt(item.dex.gasUnits||220000),0n):BigInt(plan.single.dex.gasUnits||220000),prepared=await prepareSwapTransaction(plan.anchorQuote,method,args,plannedGas*2n);plan.anchorQuote=prepared.binding;settlementContext=tokenOut.address==='native'?{kind:'native-out',nativeRouter:cfg.nativeRouterAddress,tokenIn:path[0],recipient:account,amountIn:value,minimumAmountOut:min}:{kind:'erc20',tokenOut:path[1],recipient:account,minimumAmountOut:min};tx=await sendPreparedTransaction(prepared,walletContext)}
      unverifiedTransactionHash=tx.hash;rememberPendingExecution(tx.hash,plan.anchorQuote,settlementContext);status(t(plan.kind==='split'?'status.splitSubmitted':'status.swapSubmitted'));const finalTransactionHash=await waitForFinalTransactionHash(tx);unverifiedTransactionHash=finalTransactionHash;if(finalTransactionHash!==tx.hash)rememberPendingExecution(finalTransactionHash,plan.anchorQuote,settlementContext);status(t('status.confirming'));const verified=await verifySubmittedTransaction(finalTransactionHash,plan.anchorQuote,settlementContext),evidence=sdk.buildExecutionEvidence(verified.anchorQuote,verified.settlement,cfg.deploymentFingerprint,Date.now(),ethers);rememberExecutionEvidence(evidence);if(!clearPendingExecution(finalTransactionHash))throw new Error('PendingExecutionStorageConflict');unverifiedTransactionHash='';status(t('status.swapComplete',{side:t(mode==='buy'?'side.buy':'side.sell'),confirmations:verified.settlement.confirmations}),'success');ui.amountIn.value='';await balances();await quote();
    }catch(e){if(e?.message==='TransactionReplacementCancelled'&&ethers.isHexString(e.replacementHash,32)){try{rememberPendingCancellation(unverifiedTransactionHash,e.replacementHash);const cancelled=await verifyCancelledSubmittedTransaction(e.replacementHash,plan.anchorQuote);if(cancelled&&clearPendingExecution(unverifiedTransactionHash))unverifiedTransactionHash=''}catch{}}if(unverifiedTransactionHash){const pending=storedPendingExecution();status(t('status.resultUnknown',{hash:`${(pending?.cancellationHash||unverifiedTransactionHash).slice(0,10)}…`}),'error');schedulePendingRecoveryRetry(0)}else{status(translatedSwapError(e),'error')}}finally{if(!unverifiedTransactionHash)setSwapInFlight(false)}
  }
  async function swap(){
    if(swapInFlight)return status(t('status.swapBusy'));
    if(!navigator.locks?.request)return status(t('status.lockUnsupported'),'error');
    return navigator.locks.request(swapLockName,{mode:'exclusive',ifAvailable:true},lock=>{
      if(!lock)return status(t('status.otherTabBusy'),'error');
      return executeSwap();
    });
  }
  function tokenList(query=''){
    const other=side==='in'?tokenOut:tokenIn,term=query.trim().toLowerCase(),tokens=cfg.tokens.filter(t=>pairApproved(t,other)&&
      [t.symbol,t.name,t.address].some(value=>String(value||'').toLowerCase().includes(term)));
    ui.tokenCount.textContent=t('token.count',{count:tokens.length});ui.tokenEmpty.hidden=tokens.length!==0;
    ui.tokenList.replaceChildren(...tokens.map(token=>{const b=document.createElement('button'),icon=document.createElement('span'),symbol=document.createElement('b'),meta=document.createElement('span');b.type='button';b.className='token-option';b.setAttribute('role','option');icon.className=`token-symbol ${token.symbol==='LQC'?'mint':''}`.trim();icon.textContent=token.symbol.slice(0,4);symbol.textContent=token.symbol;meta.textContent=`${token.name} · ${t(token.address==='native'?'token.native':'token.verified')}`;b.append(icon,symbol,meta);b.onclick=()=>{if(side==='in')tokenIn=token;else tokenOut=token;mode=tokenIn.symbol==='LQC'?'sell':'buy';selectedAsset=mode==='buy'?tokenOut:tokenIn;quoteToken=mode==='buy'?tokenIn:tokenOut;ui.dialog.close();const label=t('trade.action',{symbol:selectedAsset.symbol,side:t(mode==='buy'?'side.buy':'side.sell')});ui.title.textContent=label;ui.execute.textContent=label;ui.execute.className=`execute-button ${mode}`;render();balances();refreshMarketPrice();loadChartHistory();quoteSoon()};return b}));
  }
  function openTokenDialog(nextSide){side=nextSide;ui.tokenSearch.value='';tokenList();ui.dialog.showModal();setTimeout(()=>ui.tokenSearch.focus(),0)}
  const baseChartSeries=[92,110,98,128,175,218,270,260,225,178,164,151,168,176,169,181,158,145,132,278,301,270,226,206,182,169,188,204,238,312,286,254,226,194,160,137,124,196,251,226,210,231,218,197,176,151,139];
  const chartSeries=Object.fromEntries(['1m','3m','5m','15m','1h','4h','1D','1W','1M'].map((timeframe,offset)=>[timeframe,baseChartSeries.map((value,index)=>Math.max(54,Math.min(330,value+Math.round(Math.sin((index+offset*3)/4)*offset*3))) )]));
  function chart(closes=chartSeries['1m'],timeframe='1m',source='example'){const g=$('candles'),bars=$('volumeBars'),ns='http://www.w3.org/2000/svg';g.replaceChildren();bars.replaceChildren();clearLiveChartLabels();$('chartDataBadge').textContent=source==='live'?`${timeframe} 검증된 마켓 히스토리`:`${timeframe} 예시 차트 · 실시간 히스토리 연동 전`;closes.forEach((close,i)=>{const open=i?closes[i-1]+((i%5)-2)*3:108,x=i*16+3,up=close<open,high=Math.max(50,Math.min(open,close)-5-(i%4)*3),low=Math.min(340,Math.max(open,close)+7+(i%3)*4),wick=document.createElementNS(ns,'line'),body=document.createElementNS(ns,'rect');wick.setAttribute('x1',x+5.5);wick.setAttribute('x2',x+5.5);wick.setAttribute('y1',high);wick.setAttribute('y2',low);wick.setAttribute('class',`wick ${up?'up':'down'}`);body.setAttribute('x',x);body.setAttribute('y',Math.min(open,close));body.setAttribute('width',11);body.setAttribute('height',Math.max(5,Math.abs(open-close)));body.setAttribute('rx','.5');body.setAttribute('class',`candle ${up?'up':'down'}`);g.append(wick,body);const bar=document.createElement('i');bar.style.height=`${Math.min(66,9+Math.abs(open-close)*.8+(i%5)*2)}px`;if(!up)bar.className='hot';bars.append(bar)})}
  function chartLive(candles,timeframe){
    const recent=candles.slice(-47),bands=bollingerBands(recent),sar=parabolicSar(recent),values=[...recent.flatMap(item=>[item.high,item.low]),...bands.flatMap(item=>[item.upper,item.lower]),...sar.map(item=>item.value)],min=Math.min(...values),max=Math.max(...values),range=max-min||1,maxVolume=Math.max(...recent.map(item=>item.volume),1),g=$('candles'),bars=$('volumeBars'),ns='http://www.w3.org/2000/svg',step=680/recent.length,width=Math.max(3,Math.min(11,step*.68)),y=value=>330-(value-min)/range*270;
    const refreshedAt=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
    g.replaceChildren();bars.replaceChildren();$('chartDataBadge').textContent=`${timeframe} 실시간 · ${refreshedAt}`;
    recent.forEach((item,index)=>{const x=index*step+3,open=y(item.open),close=y(item.close),high=y(item.high),low=y(item.low),up=item.close>=item.open,wick=document.createElementNS(ns,'line'),body=document.createElementNS(ns,'rect'),bar=document.createElement('i');wick.setAttribute('x1',x+width/2);wick.setAttribute('x2',x+width/2);wick.setAttribute('y1',high);wick.setAttribute('y2',low);wick.setAttribute('class',`wick ${up?'up':'down'}`);body.setAttribute('x',x);body.setAttribute('y',Math.min(open,close));body.setAttribute('width',width);body.setAttribute('height',Math.max(2,Math.abs(open-close)));body.setAttribute('rx','.5');body.setAttribute('class',`candle ${up?'up':'down'}`);g.append(wick,body);bar.style.height=`${Math.max(3,item.volume/maxVolume*66)}px`;if(!up)bar.className='hot';bars.append(bar)});
    renderSar(sar,y,step,ns);renderMacd(recent);renderKdj(recent);renderLiveChartLabels(recent,min,max,y,timeframe);
  }
  function chartPrice(value){return Number(value).toLocaleString(undefined,{maximumSignificantDigits:7})}
  function movingAverage(items,period){if(items.length<period)return null;return items.slice(-period).reduce((sum,item)=>sum+item.close,0)/period}
  function clearLiveChartLabels(){
    [5,10,20].forEach(period=>{$(`ma${period}Legend`).textContent=`MA${period}: —`;$(`ma${period}Line`).setAttribute('d','')});[9,21].forEach(period=>{$(`ema${period}Legend`).textContent=`EMA${period}: —`;$(`ema${period}Line`).setAttribute('d','')});for(const band of ['Upper','Middle','Lower']){$(`boll${band}Legend`).textContent=`${band==='Upper'?'BOLL U':band[0]}: —`;$(`boll${band}Line`).setAttribute('d','')}$('sarLegend').textContent='SAR: —';$('sarPoints').replaceChildren();$('macdLabel').textContent='MACD (12, 26, 9): —';$('macdBars').replaceChildren();$('kdjLabel').textContent='KDJ (9, 3, 3): —';for(const key of ['K','D','J'])$(`kdj${key}Line`).setAttribute('d','');$('priceArea').setAttribute('d','');$('priceAxis').querySelectorAll('text').forEach(node=>node.textContent='—');$('timeAxis').querySelectorAll('span').forEach(node=>node.textContent='—');$('currentPriceLine').style.visibility='hidden';$('currentPriceLabel').textContent='—';$('chartVolumeLabel').textContent='VOL: —';
  }
  function chartPath(candles,y,step,period=1){
    const points=[];for(let index=period-1;index<candles.length;index++){const window=candles.slice(index-period+1,index+1),value=window.reduce((sum,item)=>sum+item.close,0)/period;points.push(`${points.length?'L':'M'}${(index*step+step/2).toFixed(2)} ${y(value).toFixed(2)}`)}return points.join(' ')
  }
  function exponentialMovingAverage(items,period){
    return indicatorMath.exponentialMovingAverage(items,period)
  }
  function emaPath(candles,y,step,period){return exponentialMovingAverage(candles,period).map((item,index)=>`${index?'L':'M'}${(item.index*step+step/2).toFixed(2)} ${y(item.value).toFixed(2)}`).join(' ')}
  function bollingerBands(items,period=20,deviations=2){
    return indicatorMath.bollingerBands(items,period,deviations)
  }
  function bollingerPath(bands,key,y,step){return bands.map((item,index)=>`${index?'L':'M'}${(item.index*step+step/2).toFixed(2)} ${y(item[key]).toFixed(2)}`).join(' ')}
  function parabolicSar(items,step=.02,maximum=.2){
    return indicatorMath.parabolicSar(items,step,maximum)
  }
  function renderSar(points,y,step,ns){const group=$('sarPoints');group.replaceChildren(...points.map(point=>{const node=document.createElementNS(ns,'circle');node.setAttribute('cx',point.index*step+step/2);node.setAttribute('cy',y(point.value));node.setAttribute('r','2.2');node.setAttribute('class',`sar-point ${point.rising?'rising':'falling'}`);return node}));const latest=points.at(-1);$('sarLegend').textContent=latest?`SAR: ${chartPrice(latest.value)} · ${latest.rising?'상승':'하락'}`:'SAR: —'}
  function emaSequence(values,period){return indicatorMath.emaSequence(values,period)}
  function macdSeries(items,fastPeriod=12,slowPeriod=26,signalPeriod=9){return indicatorMath.macdSeries(items,fastPeriod,slowPeriod,signalPeriod)}
  function renderMacd(candles){const series=macdSeries(candles),latest=series.at(-1),max=Math.max(...series.map(item=>Math.abs(item.histogram)),1e-12),bars=$('macdBars');bars.replaceChildren(...series.map(item=>{const slot=document.createElement('i'),bar=document.createElement('b');bar.className=item.histogram>=0?'positive':'negative';bar.style.height=`${Math.max(1,Math.abs(item.histogram)/max*32)}px`;slot.append(bar);return slot}));$('macdLabel').textContent=latest?`MACD (12, 26, 9) · DIF ${chartPrice(latest.dif)} · DEA ${chartPrice(latest.dea)} · MACD ${chartPrice(latest.histogram)}`:'MACD (12, 26, 9): —'}
  function kdjSeries(items,period=9){return indicatorMath.kdjSeries(items,period)}
  function kdjPath(series,key){const step=series.length>1?680/(series.length-1):0,y=value=>68-(Math.max(-20,Math.min(120,value))+20)/140*60;return series.map((item,index)=>`${index?'L':'M'}${(index*step).toFixed(2)} ${y(item[key]).toFixed(2)}`).join(' ')}
  function renderKdj(candles){const series=kdjSeries(candles),latest=series.at(-1);for(const key of ['K','D','J'])$(`kdj${key}Line`).setAttribute('d',kdjPath(series,key.toLowerCase()));$('kdjLabel').textContent=latest?`KDJ (9, 3, 3) · K ${latest.k.toFixed(2)} · D ${latest.d.toFixed(2)} · J ${latest.j.toFixed(2)}`:'KDJ (9, 3, 3): —'}
  function renderLiveChartLabels(candles,min,max,y,timeframe){
    const last=candles.at(-1),axis=$('priceAxis').querySelectorAll('text'),line=$('currentPriceLine'),label=$('currentPriceLabel'),timeLabels=$('timeAxis').querySelectorAll('span');
    line.style.visibility='visible';axis.forEach((node,index)=>node.textContent=chartPrice(max-(max-min)*(index/(axis.length-1))));
    const currentY=Math.max(16,Math.min(366,y(last.close)));line.setAttribute('y1',currentY);line.setAttribute('y2',currentY);label.setAttribute('y',Math.max(14,currentY-6));label.textContent=chartPrice(last.close);
    [5,10,20].forEach(period=>{const value=movingAverage(candles,period),node=$(`ma${period}Legend`);node.textContent=`MA${period}: ${value===null?'—':chartPrice(value)}`});
    const step=680/candles.length;$('priceArea').setAttribute('d',`${chartPath(candles,y,step)} L${(candles.length*step).toFixed(2)} 330 L0 330 Z`);[5,10,20].forEach(period=>$(`ma${period}Line`).setAttribute('d',chartPath(candles,y,step,period)));
    [9,21].forEach(period=>{const series=exponentialMovingAverage(candles,period),value=series.at(-1)?.value;$(`ema${period}Legend`).textContent=`EMA${period}: ${value===undefined?'—':chartPrice(value)}`;$(`ema${period}Line`).setAttribute('d',emaPath(candles,y,step,period))});
    const bands=bollingerBands(candles),latestBand=bands.at(-1);for(const [name,key,label] of [['Upper','upper','BOLL U'],['Middle','middle','M'],['Lower','lower','L']]){$(`boll${name}Legend`).textContent=`${label}: ${latestBand?chartPrice(latestBand[key]):'—'}`;$(`boll${name}Line`).setAttribute('d',bollingerPath(bands,key,y,step))}
    $('chartVolumeLabel').textContent=`VOL (${selectedAsset.symbol}): ${chartPrice(candles.reduce((sum,item)=>sum+item.volume,0))}`;
    const indexes=[0,Math.floor((candles.length-1)/3),Math.floor((candles.length-1)*2/3),candles.length-1],options=['1D','1W','1M'].includes(timeframe)?{month:'2-digit',day:'2-digit'}:{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'};
    timeLabels.forEach((node,index)=>node.textContent=new Date(candles[indexes[index]].time*1000).toLocaleString('ko-KR',options));
  }
  function clearMarketStats(){ui.tickerChange.textContent='24h —';ui.tickerChange.classList.remove('negative');ui.high24h.textContent='—';ui.low24h.textContent='—';ui.volume24h.textContent='—'}
  function chartState(message,state){const badge=$('chartDataBadge');badge.textContent=message;badge.dataset.state=state}
  function chartRetryDelay(){return Math.min(60000,3000*(2**Math.min(Math.max(0,chartFailureCount-1),4)))}
  async function chainHeadWithin(timeoutMs=2500){
    const now=Date.now(),deadline=performance.now()+timeoutMs,probe=promise=>new Promise(resolve=>{const remaining=Math.max(0,deadline-performance.now()),timeout=setTimeout(()=>resolve(null),remaining);promise.then(value=>resolve(value),()=>resolve(null)).finally(()=>clearTimeout(timeout))}),active=readProviders.map((provider,index)=>({provider,index})).filter(item=>rpcSourceHealth[item.index].quarantinedUntil<=now),observations=await Promise.all(active.map(async item=>{const started=performance.now(),head=await probe(item.provider.getBlockNumber());return{...item,head,latencyMs:Math.max(0,performance.now()-started)}})),heads=observations.map(item=>item.head).filter(Number.isSafeInteger),headConsensus=chartHealth.consensusHead(heads,readProviders.length);if(!headConsensus){trustedReadProviderIndexes=[];trustedReadBlock=null;trustedReadHash='';observations.filter(item=>!Number.isSafeInteger(item.head)).forEach(item=>recordRpcSource(item.index,false,now));return null}
    const blockObservations=await Promise.all(observations.filter(item=>Number.isSafeInteger(item.head)&&item.head>=headConsensus.head).map(async item=>({...item,block:await probe(item.provider.getBlock(headConsensus.head))}))),hashes=blockObservations.map(item=>item.block?.hash).filter(hash=>typeof hash==='string'&&/^0x[0-9a-fA-F]{64}$/.test(hash)),hashConsensus=chartHealth.consensusHash(hashes,readProviders.length);if(!hashConsensus){trustedReadProviderIndexes=[];trustedReadBlock=null;trustedReadHash='';blockObservations.filter(item=>!item.block?.hash).forEach(item=>recordRpcSource(item.index,false,now));return null}
    const ranked=chartHealth.rankCanonicalSources(blockObservations.map(item=>({index:item.index,head:item.head,latencyMs:item.latencyMs,blockHash:item.block?.hash||''})),headConsensus.head,hashConsensus.blockHash);trustedReadProviderIndexes=[...ranked];trustedReadBlock=headConsensus.head;trustedReadHash=hashConsensus.blockHash;trustedReadVerifiedAt=now;for(const item of observations){recordRpcSource(item.index,ranked.includes(item.index),now)}
    const quarantinedSources=rpcSourceHealth.filter(state=>state.quarantinedUntil>now).length;return Object.freeze({...headConsensus,blockHash:hashConsensus.blockHash,healthySources:hashConsensus.healthySources,quarantinedSources});
  }
  function renderMarketStats(candles,asset,quote){
    const last=candles.at(-1),cutoff=last.time-86400,window24h=candles.filter(item=>item.time>=cutoff);
    if(candles[0].time>cutoff||window24h.length<2)return clearMarketStats();
    const first=window24h[0],change=(last.close-first.open)/first.open*100,format=value=>Number(value).toLocaleString(undefined,{maximumSignificantDigits:8});
    ui.tickerChange.textContent=`${change>=0?'+':''}${change.toFixed(2)}%`;ui.tickerChange.classList.toggle('negative',change<0);
    ui.high24h.textContent=`${format(Math.max(...window24h.map(item=>item.high)))} ${quote.symbol}`;
    ui.low24h.textContent=`${format(Math.min(...window24h.map(item=>item.low)))} ${quote.symbol}`;
    ui.volume24h.textContent=`${format(window24h.reduce((sum,item)=>sum+item.volume,0))} ${asset.symbol}`;
  }
  function scheduleChartRefresh(delay){
    clearTimeout(chartRefreshTimer);
    if(!cfg.candleDataUrl||document.hidden||navigator.onLine===false)return;
    const wait=delay||(['1D','1W','1M'].includes(selectedTimeframe)?60000:15000);
    chartRefreshTimer=setTimeout(()=>{loadChartHistory();refreshMarketPrice()},wait);
  }
  async function loadChartHistory(){
    const request=++chartRequest,asset=selectedAsset,quote=quoteToken,timeframe=selectedTimeframe,chartKey=`${cfg.chainId}:${address(asset)}:${address(quote)}:${timeframe}`,startedAt=performance.now();let retryDelay;
    clearMarketStats();if(!cfg.candleDataUrl||!candleData)return chart(chartSeries[timeframe],timeframe);
    if(navigator.onLine===false){const quality=chartHealth.classify({online:false});chartState(`${timeframe} ${quality.label} · 연결되면 자동복구`,quality.level);return}
    chartState(`${timeframe} 히스토리 불러오는 중`,'loading');
    try{
      const params={chainId:cfg.chainId,base:address(asset),quote:address(quote)},proof={expectedSigner:cfg.candleSignerAddress,ethersLib:ethers},primaryRequest=candleData.loadEnvelope(cfg.candleDataUrl,{...params,timeframe,limit:120},proof),statisticsRequest=timeframe==='1h'?primaryRequest:candleData.loadEnvelope(cfg.candleDataUrl,{...params,timeframe:'1h',limit:26},proof),[primary,statistics]=await Promise.all([primaryRequest,statisticsRequest]),candles=primary.candles,stats=statistics.candles;
      if(request!==chartRequest||asset!==selectedAsset||quote!==quoteToken||timeframe!==selectedTimeframe)return;
      const latencyMs=Math.max(0,Math.round(performance.now()-startedAt)),ageSeconds=Math.max(0,Math.floor(Date.now()/1000)-primary.issuedAt),quality=chartHealth.classify({latencyMs,ageSeconds}),updatedAt=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});chartFailureCount=0;verifiedChartKey=chartKey;chartLive(candles,timeframe);renderMarketStats(stats,asset,quote);
      const consensus=await chainHeadWithin();if(request!==chartRequest)return;const sync=consensus?chartHealth.chainSync(primary.finalizedBlock,consensus.head,cfg.candleFinalityBlocks):null,hashLabel=consensus?`${consensus.blockHash.slice(0,8)}…${consensus.blockHash.slice(-6)}`:'',isolationLabel=consensus?.quarantinedSources?` · 격리 ${consensus.quarantinedSources}`:'',syncText=sync?`${sync.label} · ${sync.lagBlocks}블록 · ${hashLabel} · RPC ${consensus.healthySources}/${consensus.configuredSources}${isolationLabel}`:'다중 RPC 블록 해시 합의 실패',finalLevel=!consensus?'delayed':sync?.level==='stale'?'interrupted':['catching-up','unverified'].includes(sync?.level)?'delayed':quality.level;if(quality.level==='healthy'&&sync?.level==='synced')lastHealthyByChart.set(chartKey,updatedAt);chartState(`${timeframe} ${quality.label} · ${latencyMs}ms · ${syncText} · 정상 갱신 ${lastHealthyByChart.get(chartKey)||'기록 없음'}`,finalLevel);
    }catch{if(request===chartRequest){chartFailureCount++;retryDelay=chartRetryDelay();const quality=chartHealth.classify({consecutiveFailures:chartFailureCount}),lastHealthy=lastHealthyByChart.get(chartKey)||'기록 없음';if(verifiedChartKey===chartKey)chartState(`${timeframe} ${quality.label} · 마지막 정상 ${lastHealthy} · ${retryDelay/1000}초 후 자동복구`,quality.level);else{chart(chartSeries[timeframe],timeframe);chartState(`${timeframe} ${quality.label} · 예시 차트 · ${retryDelay/1000}초 후 재시도`,quality.level)}}}
    finally{if(request===chartRequest)scheduleChartRefresh(retryDelay)}
  }
  function saveChartPreferences(){try{localStorage.setItem(chartMemoryKey,JSON.stringify({timeframe:selectedTimeframe,indicators:[...document.querySelectorAll('.indicators [data-indicator][aria-pressed="true"]')].map(button=>button.dataset.indicator)}))}catch{}
  }
  function setIndicatorVisibility(name,visible){const button=document.querySelector(`.indicators [data-indicator="${name}"]`);if(button){button.setAttribute('aria-pressed',String(visible));button.classList.toggle('active',visible)}if(name==='volume')$('volumeIndicator').classList.toggle('indicator-hidden',!visible);else if(name==='ma'){document.querySelector('.ma-legend').classList.toggle('indicator-hidden',!visible);[5,10,20].forEach(period=>$(`ma${period}Line`).classList.toggle('indicator-hidden',!visible))}else if(name==='ema'){document.querySelector('.ema-legend').classList.toggle('indicator-hidden',!visible);[9,21].forEach(period=>$(`ema${period}Line`).classList.toggle('indicator-hidden',!visible))}else if(name==='boll'){document.querySelector('.boll-legend').classList.toggle('indicator-hidden',!visible);for(const band of ['Upper','Middle','Lower'])$(`boll${band}Line`).classList.toggle('indicator-hidden',!visible)}else if(name==='sar'){$('sarLegend').classList.toggle('indicator-hidden',!visible);$('sarPoints').classList.toggle('indicator-hidden',!visible)}else if(name==='macd')$('macdIndicator').classList.toggle('indicator-hidden',!visible);else if(name==='kdj')$('kdjIndicator').classList.toggle('indicator-hidden',!visible)}
  function restoreChartPreferences(){const active=new Set(initialChartPreferences?.indicators||['volume','ma']);document.querySelectorAll('.timeframes [data-timeframe]').forEach(button=>button.classList.toggle('active',button.dataset.timeframe===selectedTimeframe));supportedIndicators.forEach(name=>setIndicatorVisibility(name,active.has(name)))}
  function selectTimeframe(timeframe){if(!chartSeries[timeframe])return;selectedTimeframe=timeframe;document.querySelectorAll('.timeframes [data-timeframe]').forEach(button=>button.classList.toggle('active',button.dataset.timeframe===timeframe));saveChartPreferences();loadChartHistory()}
  function toggleIndicator(button){
    const name=button.dataset.indicator,visible=button.getAttribute('aria-pressed')!=='true';if(visible&&lowerIndicators.includes(name))lowerIndicators.filter(other=>other!==name).forEach(other=>setIndicatorVisibility(other,false));setIndicatorVisibility(name,visible);saveChartPreferences();
  }
  function bindWalletEvents(target){
    if(boundWallets.has(target)||typeof target.on!=='function')return;boundWallets.add(target);
    target.on('accountsChanged',accounts=>{if(target!==walletProvider)return;invalidateWalletContext();if(accounts.length===0){localStorage.removeItem(walletMemoryKey);clearConnectedWallet();status(t('status.disconnected'))}else connect(target,false)});
    target.on('chainChanged',()=>{if(target===walletProvider){invalidateWalletContext();connect(target,false)}});
    target.on('disconnect',()=>{if(target!==walletProvider)return;localStorage.removeItem(walletMemoryKey);clearConnectedWallet();status(t('status.disconnected'))});
  }
  function addWallet(detail){
    if(!detail?.provider||!detail?.info)return;
    const key=detail.info.uuid||detail.info.rdns||detail.info.name;
    if(wallets.some(wallet=>(wallet.info.uuid||wallet.info.rdns||wallet.info.name)===key))return;
    wallets.push(detail);renderWallets();
  }
  function renderWallets(){
    ui.walletList.replaceChildren(...wallets.map(wallet=>{
      const button=document.createElement('button'),label=document.createElement('span'),name=document.createElement('b'),kind=document.createElement('small'),safeName=String(wallet.info.name||'비수탁형 지갑');
      button.type='button';button.className='wallet-option';name.textContent=safeName;kind.textContent='비수탁형 지갑';label.append(name,kind);
      if(typeof wallet.info.icon==='string'&&wallet.info.icon.startsWith('data:image/')){const image=document.createElement('img');image.src=wallet.info.icon;image.alt='';button.append(image)}
      else{const fallback=document.createElement('span');fallback.className='wallet-fallback';fallback.textContent=safeName.slice(0,1);button.append(fallback)}
      button.append(label);button.onclick=()=>{ui.walletDialog.close();connect(wallet.provider,true)};return button;
    }));
  }
  function chooseWallet(){
    if(wallets.length===0&&window.ethereum)addWallet({info:{uuid:'legacy-injected',name:'브라우저 지갑',rdns:'legacy.injected'},provider:window.ethereum});
    if(wallets.length===1)return connect(wallets[0].provider,true);
    if(wallets.length>1)return ui.walletDialog.showModal();
    status(t('status.noWallet'),'error');
  }
  window.addEventListener('eip6963:announceProvider',event=>addWallet(event.detail));
  window.addEventListener('storage',handlePendingExecutionStorage);
  window.addEventListener('lqc:languagechange',()=>{marketList(ui.marketSearch.value);tokenList(ui.tokenSearch.value);setMode(mode,false)});
  document.addEventListener('visibilitychange',()=>{clearTimeout(chartRefreshTimer);clearTimeout(pendingRecoveryTimer);if(!document.hidden){loadChartHistory();refreshMarketPrice();if(storedPendingExecution())schedulePendingRecoveryRetry(0)}});
  window.addEventListener('offline',()=>{clearTimeout(chartRefreshTimer);clearTimeout(pendingRecoveryTimer);const quality=chartHealth.classify({online:false});chartState(`${selectedTimeframe} ${quality.label} · 연결되면 자동복구`,quality.level)});
  window.addEventListener('online',()=>{chartFailureCount=0;loadChartHistory();refreshMarketPrice();if(storedPendingExecution()){pendingRecoveryAttempts=0;schedulePendingRecoveryRetry(0)}});
  window.dispatchEvent(new Event('eip6963:requestProvider'));
  if(window.ethereum)setTimeout(()=>{if(wallets.length===0)addWallet({info:{uuid:'legacy-injected',name:'브라우저 지갑',rdns:'legacy.injected'},provider:window.ethereum})},0);
  ui.recoveryRetry.onclick=()=>{if(storedPendingExecution()){pendingRecoveryAttempts=0;schedulePendingRecoveryRetry(0)}};ui.connect.onclick=chooseWallet;ui.buy.onclick=ui.buyTab.onclick=()=>setMode('buy');ui.sell.onclick=ui.sellTab.onclick=()=>setMode('sell');ui.quick.onclick=ui.tradeNav.onclick=()=>setMode(mode);ui.walletNav.onclick=chooseWallet;ui.marketNav.onclick=ui.marketSelector.onclick=openMarkets;ui.tradeHistoryButton.onclick=openExecutionHistory;ui.marketSearch.oninput=()=>marketList(ui.marketSearch.value);ui.close.onclick=()=>ui.order.classList.remove('open');ui.execute.onclick=swap;ui.tokenInButton.onclick=()=>openTokenDialog('in');ui.tokenOutButton.onclick=()=>openTokenDialog('out');ui.tokenSearch.oninput=()=>tokenList(ui.tokenSearch.value);ui.flip.onclick=()=>{[tokenIn,tokenOut]=[tokenOut,tokenIn];selectedAsset=mode==='buy'?tokenOut:tokenIn;quoteToken=mode==='buy'?tokenIn:tokenOut;render();balances();refreshMarketPrice();loadChartHistory();quoteSoon()};ui.amountIn.oninput=quoteSoon;ui.slippage.oninput=quoteSoon;ui.settings.onclick=()=>{ui.settingsPanel.hidden=!ui.settingsPanel.hidden;ui.order.classList.add('open')};ui.max.onclick=()=>applyBalancePercent(100);
  document.querySelectorAll('.amount-presets button').forEach(button=>button.onclick=()=>applyBalancePercent(button.dataset.percent));
  document.querySelectorAll('.slippage-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slippage-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');ui.slippage.value=b.dataset.value;quoteSoon()});document.querySelectorAll('.timeframes [data-timeframe]').forEach(b=>b.onclick=()=>selectTimeframe(b.dataset.timeframe));document.querySelectorAll('.indicators [data-indicator]').forEach(b=>b.onclick=()=>toggleIndicator(b));document.querySelectorAll('.section-tabs button,.position-tabs button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  if(deployed)status(t('status.contractReady'));restoreChartPreferences();render();renderExecutionEvidence();tokenList();marketList();loadChartHistory();setMode('buy',false);const pendingRecord=pendingExecutionState();if(pendingRecord.state==='valid')setTimeout(()=>recoverPendingExecution(),0);else if(pendingRecord.state==='invalid'){setSwapInFlight(true);status(t('status.pendingRecordInvalid'),'error')}if(localStorage.getItem(walletMemoryKey)==='1')setTimeout(()=>{const remembered=wallets[0]?.provider||window.ethereum;if(remembered)connect(remembered,false)},100);
})();
