(function(){
  'use strict';
  const cfg=window.LQC_FLOW_CONFIG,{ethers,LQCRouterSDK:sdk}=window,$=id=>document.getElementById(id);
  const routerAbi=['function getAmountsOut(uint256,address[]) view returns (uint256[])','function swapExactTokensForTokens(uint256,uint256,address[],address,uint256) returns (uint256[])','function swapExactBNBForTokens(uint256,address[],address,uint256) payable returns (uint256[])','function swapExactTokensForBNB(uint256,uint256,address[],address,uint256) returns (uint256[])'];
  const quoteRouterAbi=['function quoteBest(address,address,uint256,bytes[]) view returns ((bytes32 dexId,address adapter,uint256 amountOut,uint32 priority))'];
  const executionRouterAbi=['function swapExactInput(bytes32,address,address,uint256,uint256,address,uint256,bytes) returns (uint256)'];
  const nativeRouterAbi=['function swapExactNativeForToken(bytes32,address,uint256,address,uint256,bytes) payable returns (uint256)','function swapExactTokenForNative(bytes32,address,uint256,uint256,address,uint256,bytes) returns (uint256)'];
  const splitOptimizerAbi=['function quoteOptimalSplitCapped(address,address,uint256,bytes[],uint256[],uint256,uint256) view returns ((bytes32[] dexIds,address[] adapters,uint256[] amountsIn,uint256[] amountsOut,uint256 totalAmountOut,uint256 totalNetAmountOut))'];
  const autoRouterAbi=['function swapOptimizedExactInput(address,address,uint256,address,uint256,bytes[],uint256[],uint256,uint256) returns (uint256)'];
  const gasCostOracleAbi=['function quoteRouteCosts(address,uint256[],uint256) view returns (uint256[])'];
  const tokenAbi=['function balanceOf(address) view returns (uint256)','function allowance(address,address) view returns (uint256)','function approve(address,uint256) returns (bool)'];
  const ui={connect:$('connectButton'),settings:$('settingsButton'),settingsPanel:$('settingsPanel'),amountIn:$('amountIn'),amountOut:$('amountOut'),minimum:$('minimumReceived'),gas:$('estimatedGas'),impact:$('priceImpact'),split:$('splitRatio'),route:$('routeLabel'),selectedDex:$('selectedDex'),selectedPath:$('selectedPath'),routeStrategy:$('routeStrategy'),balanceIn:$('balanceIn'),balanceOut:$('balanceOut'),positionBalance:$('positionBalance'),portfolioValue:$('portfolioValue'),tokenInButton:$('tokenInButton'),tokenOutButton:$('tokenOutButton'),flip:$('flipButton'),max:$('maxButton'),buy:$('buyAction'),sell:$('sellAction'),quick:$('quickTrade'),order:$('orderPanel'),close:$('closeOrder'),title:$('orderTitle'),execute:$('executeButton'),status:$('statusBox'),statusText:$('statusText'),dialog:$('tokenDialog'),tokenList:$('tokenList'),slippage:$('slippageInput')};
  let provider,signer,account,router,quoteRouter,executionRouter,nativeRouter,splitOptimizer,autoRouter,gasCostOracle,side='in',timer,mode='buy',tokenIn=cfg.tokens[0],tokenOut=cfg.tokens[2];
  const deployed=ethers.isAddress(cfg.quoteRouterAddress)&&ethers.isAddress(cfg.executionRouterAddress)&&ethers.isAddress(cfg.nativeRouterAddress)&&ethers.isAddress(cfg.splitOptimizerAddress)&&ethers.isAddress(cfg.autoRouterAddress)&&ethers.isAddress(cfg.gasCostOracleAddress)&&cfg.tokens.filter(t=>t.address!=='native').every(t=>ethers.isAddress(t.address));
  const address=t=>t.address==='native'?(cfg.tokens.find(x=>x.symbol==='WBNB')?.address||''):t.address;
  const status=(m,type='')=>{ui.status.className=`status ${type}`.trim();ui.statusText.textContent=m};
  const disabled=v=>ui.execute.disabled=v;
  function render(){for(const [s,t] of [['In',tokenIn],['Out',tokenOut]]){$(`token${s}Label`).textContent=t.symbol;$(`token${s}Icon`).textContent=t.symbol.slice(0,4);$(`token${s}Icon`).classList.toggle('mint',t.symbol==='LQC')}const path=`${tokenIn.symbol} → ${tokenOut.symbol}`;ui.route.textContent=path;ui.selectedPath.textContent=path}
  function setMode(next,open=true){const lqc=cfg.tokens.find(t=>t.symbol==='LQC'),bnb=cfg.tokens.find(t=>t.symbol==='BNB');mode=next;[tokenIn,tokenOut]=next==='buy'?[bnb,lqc]:[lqc,bnb];ui.title.textContent=next==='buy'?'LQC 매수':'LQC 매도';ui.execute.textContent=ui.title.textContent;ui.execute.className=`execute-button ${next}`;ui.buy.classList.toggle('active',next==='buy');ui.sell.classList.toggle('active',next==='sell');if(open)ui.order.classList.add('open');render();balances();quoteSoon()}
  async function ensureNetwork(){const chain=await ethereum.request({method:'eth_chainId'});if(chain===cfg.chainIdHex)return;try{await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:cfg.chainIdHex}]})}catch(e){if(e.code!==4902)throw e;await ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:cfg.chainIdHex,chainName:cfg.chainName,rpcUrls:cfg.rpcUrls,nativeCurrency:cfg.nativeCurrency,blockExplorerUrls:cfg.blockExplorerUrls}]})}}
  async function connect(){if(!window.ethereum)return status('MetaMask 또는 호환 지갑이 필요합니다.','error');try{provider=new ethers.BrowserProvider(ethereum);await ensureNetwork();signer=await provider.getSigner();account=await signer.getAddress();ui.connect.textContent=`${account.slice(0,6)}…${account.slice(-4)}`;router=ethers.isAddress(cfg.routerAddress)?new ethers.Contract(cfg.routerAddress,routerAbi,signer):null;quoteRouter=deployed?new ethers.Contract(cfg.quoteRouterAddress,quoteRouterAbi,provider):null;executionRouter=deployed?new ethers.Contract(cfg.executionRouterAddress,executionRouterAbi,signer):null;nativeRouter=deployed?new ethers.Contract(cfg.nativeRouterAddress,nativeRouterAbi,signer):null;splitOptimizer=deployed?new ethers.Contract(cfg.splitOptimizerAddress,splitOptimizerAbi,provider):null;autoRouter=deployed?new ethers.Contract(cfg.autoRouterAddress,autoRouterAbi,signer):null;gasCostOracle=deployed?new ethers.Contract(cfg.gasCostOracleAddress,gasCostOracleAbi,provider):null;disabled(!deployed);status(deployed?'Router 2.0 테스트넷 연결 완료':'지갑 연결 완료 · 테스트넷 컨트랙트 배포 대기 중',deployed?'success':'');await balances();quoteSoon()}catch(e){status(e.shortMessage||e.message||'지갑 연결에 실패했습니다.','error')}}
  async function balance(t){if(!provider||!account)return null;if(t.address==='native')return provider.getBalance(account);if(!ethers.isAddress(t.address))return null;return new ethers.Contract(t.address,tokenAbi,provider).balanceOf(account)}
  const format=(v,t)=>v===null?'—':Number(ethers.formatUnits(v,t.decimals)).toLocaleString(undefined,{maximumFractionDigits:5});
  async function balances(){const lqc=cfg.tokens.find(t=>t.symbol==='LQC'),[a,b,l]=await Promise.all([balance(tokenIn),balance(tokenOut),balance(lqc)]);ui.balanceIn.textContent=format(a,tokenIn);ui.balanceOut.textContent=format(b,tokenOut);ui.positionBalance.textContent=l===null?'—':`${format(l,lqc)} LQC`;if(l!==null)ui.portfolioValue.textContent=`$${(Number(ethers.formatUnits(l,lqc.decimals))*.091348).toLocaleString(undefined,{maximumFractionDigits:2})}`}
  function quoteSoon(){clearTimeout(timer);timer=setTimeout(quote,300)}
  async function bestQuote(value,path){const routes=sdk.encodeRoutes(cfg.dexes,path,ethers),best=await quoteRouter.quoteBest(path[0],path.at(-1),value,routes),index=cfg.dexes.findIndex(d=>d.id.toLowerCase()===best.dexId.toLowerCase());if(index<0)throw new Error('Unknown DEX');return{best,routeData:routes[index],dex:cfg.dexes[index]}}
  async function executionPlan(value,path){
    const single=await bestQuote(value,path),routes=sdk.encodeRoutes(cfg.dexes,path,ethers);
    if(tokenIn.address==='native'||tokenOut.address==='native')return{kind:'single',single,routes,costs:cfg.dexes.map(()=>0n),oracleReady:false};
    let costs;try{const feeData=await provider.getFeeData(),gasUnits=cfg.dexes.map(dex=>BigInt(dex.gasUnits||220000));costs=await gasCostOracle.quoteRouteCosts(path.at(-1),gasUnits,feeData.gasPrice||0n)}catch{return{kind:'single',single,routes,costs:cfg.dexes.map(()=>0n),oracleReady:false}}
    const split=await splitOptimizer.quoteOptimalSplitCapped(path[0],path.at(-1),value,routes,costs,10,4);
    const singleIndex=cfg.dexes.findIndex(d=>d.id.toLowerCase()===single.best.dexId.toLowerCase());
    if(!sdk.isSplitNetBetter(single.best.amountOut,costs[singleIndex],split.totalNetAmountOut))return{kind:'single',single,routes,costs,oracleReady:true};
    return{kind:'split',single,split,routes,costs,oracleReady:true,summary:sdk.summarizeSplit(cfg.dexes,split.amountsIn,value)};
  }
  async function quote(){
    ui.amountOut.textContent='0.0';ui.minimum.textContent='—';ui.gas.textContent='—';ui.impact.textContent='—';ui.split.textContent='단일 경로';ui.selectedDex.textContent='견적 확인 중';
    const raw=ui.amountIn.value.trim();if(!raw||Number(raw)<=0||!deployed){ui.selectedDex.textContent='LQC Flow · PancakeSwap 비교 대기';return}
    try{
      const path=[address(tokenIn),address(tokenOut)],value=ethers.parseUnits(raw,tokenIn.decimals),probe=value>1000n?value/1000n:1n,[plan,probeResult,feeData]=await Promise.all([executionPlan(value,path),bestQuote(probe,path),provider.getFeeData()]),out=plan.kind==='split'?plan.split.totalAmountOut:plan.single.best.amountOut,min=sdk.minimumAmountOut(out,ui.slippage.value),impact=sdk.priceImpactBps(value,out,probe,probeResult.best.amountOut),gasDex=plan.kind==='split'?{gasUnits:plan.summary.reduce((total,item)=>total+Number(item.dex.gasUnits||220000),0)}:plan.single.dex,gasWei=sdk.estimatedGasWei(gasDex,feeData.gasPrice||0n,tokenIn.address==='native'||tokenOut.address==='native');
      ui.amountOut.textContent=ethers.formatUnits(out,tokenOut.decimals);ui.minimum.textContent=`${Number(ethers.formatUnits(min,tokenOut.decimals)).toLocaleString(undefined,{maximumFractionDigits:6})} ${tokenOut.symbol}`;ui.gas.textContent=`≈ ${Number(ethers.formatEther(gasWei)).toFixed(6)} BNB`;ui.impact.textContent=`≈ ${(impact/100).toFixed(2)}%`;ui.impact.classList.toggle('warning',impact>=300);ui.selectedDex.textContent=plan.kind==='split'?plan.summary.map(item=>item.dex.name).join(' + '):plan.single.dex.name;ui.split.textContent=plan.kind==='split'?plan.summary.map(item=>`${item.dex.name} ${item.percent.toFixed(1)}%`).join(' · '):'단일 경로 100%';ui.routeStrategy.textContent=plan.kind==='split'?'Router 2.0 · 가스 차감 후 원자적 분할':plan.oracleReady?'Router 2.0 · 가스 차감 후 단일 최적':'가스 오라클 대기 · 안전 단일 경로';disabled(false);
    }catch{ui.selectedDex.textContent='유효한 경로 없음';disabled(true);status('이 거래쌍의 유동성을 확인할 수 없습니다.','error')}
  }
  async function swap(){
    if(!executionRouter||!account)return connect();const raw=ui.amountIn.value.trim();if(!raw||Number(raw)<=0)return status('보낼 수량을 입력하세요.','error');
    try{
      disabled(true);const value=ethers.parseUnits(raw,tokenIn.decimals),path=[address(tokenIn),address(tokenOut)],plan=await executionPlan(value,path),deadline=Math.floor(Date.now()/1000)+1200,bps=Math.round(Number(ui.slippage.value)*100);let tx;
      if(tokenIn.address==='native'){const min=sdk.minimumAmountOut(plan.single.best.amountOut,ui.slippage.value);tx=await nativeRouter.swapExactNativeForToken(plan.single.best.dexId,path[1],min,account,deadline,plan.single.routeData,{value})}
      else{const spender=tokenOut.address==='native'?cfg.nativeRouterAddress:plan.kind==='split'?cfg.autoRouterAddress:cfg.executionRouterAddress,token=new ethers.Contract(tokenIn.address,tokenAbi,signer);if(await token.allowance(account,spender)<value){status(`${tokenIn.symbol} 사용 승인을 확인하세요.`);await(await token.approve(spender,value)).wait()}if(tokenOut.address==='native'){const min=sdk.minimumAmountOut(plan.single.best.amountOut,ui.slippage.value);tx=await nativeRouter.swapExactTokenForNative(plan.single.best.dexId,path[0],value,min,account,deadline,plan.single.routeData)}else if(plan.kind==='split')tx=await autoRouter.swapOptimizedExactInput(path[0],path[1],value,account,deadline,plan.routes,plan.costs,10,bps);else{const min=sdk.minimumAmountOut(plan.single.best.amountOut,ui.slippage.value);tx=await executionRouter.swapExactInput(plan.single.best.dexId,path[0],path[1],value,min,account,deadline,plan.single.routeData)}}
      status(plan.kind==='split'?'Router 2.0 분할 거래가 제출되었습니다.':'Router 2.0 거래가 제출되었습니다.');await tx.wait();status(`${mode==='buy'?'매수':'매도'} 거래가 완료되었습니다.`,'success');ui.amountIn.value='';await balances();await quote();
    }catch(e){const guidance=sdk.explainSwapError(e);status(`${guidance.message} ${guidance.action}`,'error')}finally{disabled(!deployed)}
  }
  function tokenList(){ui.tokenList.replaceChildren(...cfg.tokens.map(t=>{const b=document.createElement('button');b.type='button';b.className='token-option';b.innerHTML=`<span class="token-symbol ${t.symbol==='LQC'?'mint':''}">${t.symbol.slice(0,4)}</span><b>${t.symbol}</b><span>${t.name}</span>`;b.onclick=()=>{const other=side==='in'?tokenOut:tokenIn;if(address(t)&&address(t)===address(other))return status('BNB와 WBNB는 동시에 선택할 수 없습니다.','error');if(side==='in')tokenIn=t;else tokenOut=t;ui.dialog.close();mode=tokenIn.symbol==='LQC'?'sell':'buy';ui.title.textContent=mode==='buy'?'LQC 매수':'LQC 매도';ui.execute.textContent=ui.title.textContent;ui.execute.className=`execute-button ${mode}`;render();balances();quoteSoon()};return b}))}
  function chart(){const closes=[92,110,98,128,175,218,270,260,225,178,164,151,168,176,169,181,158,145,132,278,301,270,226,206,182,169,188,204,238,312,286,254,226,194,160,137,124,196,251,226,210,231,218,197,176,151,139],g=$('candles'),bars=$('volumeBars'),ns='http://www.w3.org/2000/svg';closes.forEach((close,i)=>{const open=i?closes[i-1]+((i%5)-2)*3:108,x=i*16+3,up=close<open,high=Math.max(50,Math.min(open,close)-5-(i%4)*3),low=Math.min(340,Math.max(open,close)+7+(i%3)*4),wick=document.createElementNS(ns,'line'),body=document.createElementNS(ns,'rect');wick.setAttribute('x1',x+5.5);wick.setAttribute('x2',x+5.5);wick.setAttribute('y1',high);wick.setAttribute('y2',low);wick.setAttribute('class',`wick ${up?'up':'down'}`);body.setAttribute('x',x);body.setAttribute('y',Math.min(open,close));body.setAttribute('width',11);body.setAttribute('height',Math.max(5,Math.abs(open-close)));body.setAttribute('rx','.5');body.setAttribute('class',`candle ${up?'up':'down'}`);g.append(wick,body);const bar=document.createElement('i');bar.style.height=`${Math.min(66,9+Math.abs(open-close)*.8+(i%5)*2)}px`;if(!up)bar.className='hot';bars.append(bar)})}
  ui.connect.onclick=connect;ui.buy.onclick=()=>setMode('buy');ui.sell.onclick=()=>setMode('sell');ui.quick.onclick=()=>setMode('buy');ui.close.onclick=()=>ui.order.classList.remove('open');ui.execute.onclick=swap;ui.tokenInButton.onclick=()=>{side='in';ui.dialog.showModal()};ui.tokenOutButton.onclick=()=>{side='out';ui.dialog.showModal()};ui.flip.onclick=()=>{[tokenIn,tokenOut]=[tokenOut,tokenIn];render();balances();quoteSoon()};ui.amountIn.oninput=quoteSoon;ui.slippage.oninput=quoteSoon;ui.settings.onclick=()=>{ui.settingsPanel.hidden=!ui.settingsPanel.hidden;ui.order.classList.add('open')};ui.max.onclick=async()=>{const b=await balance(tokenIn);if(b!==null){const reserve=tokenIn.address==='native'?ethers.parseEther('.01'):0n;ui.amountIn.value=ethers.formatUnits(b>reserve?b-reserve:0n,tokenIn.decimals);quoteSoon()}};
  document.querySelectorAll('.slippage-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.slippage-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');ui.slippage.value=b.dataset.value;quoteSoon()});document.querySelectorAll('.timeframes button:not(.chart-tool),.indicators button,.section-tabs button,.position-tabs button').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});window.ethereum?.on?.('accountsChanged',connect);window.ethereum?.on?.('chainChanged',()=>location.reload());
  if(deployed)status('컨트랙트가 설정되었습니다. 지갑을 연결하세요.');render();tokenList();chart();setMode('buy',false);
})();
