(function(root){
  'use strict';
  function classify({latencyMs=0,ageSeconds=0,consecutiveFailures=0,online=true}={}){
    if(typeof online!=='boolean'||!Number.isFinite(latencyMs)||latencyMs<0||!Number.isFinite(ageSeconds)||ageSeconds<0||!Number.isInteger(consecutiveFailures)||consecutiveFailures<0)throw new Error('Chart health input is invalid');
    if(!online)return Object.freeze({level:'interrupted',label:'연결 중단',retry:true});
    if(consecutiveFailures>=3)return Object.freeze({level:'interrupted',label:'연결 중단',retry:true});
    if(consecutiveFailures>0||latencyMs>1500||ageSeconds>15)return Object.freeze({level:'delayed',label:'연결 지연',retry:true});
    return Object.freeze({level:'healthy',label:'실시간 정상',retry:false});
  }
  function chainSync(finalizedBlock,chainHead,confirmations=12){
    if(!Number.isSafeInteger(finalizedBlock)||finalizedBlock<0||!Number.isSafeInteger(chainHead)||chainHead<0||!Number.isSafeInteger(confirmations)||confirmations<2)throw new Error('Chart chain sync input is invalid');
    if(finalizedBlock>chainHead)return Object.freeze({level:'unverified',label:'온체인 확인 불가',lagBlocks:0});
    const lagBlocks=chainHead-finalizedBlock;
    if(lagBlocks<=confirmations+3)return Object.freeze({level:'synced',label:'온체인 동기화',lagBlocks});
    if(lagBlocks<=confirmations+20)return Object.freeze({level:'catching-up',label:'블록 동기화 지연',lagBlocks});
    return Object.freeze({level:'stale',label:'블록 동기화 중단',lagBlocks});
  }
  function consensusHead(heads,configuredSources=heads?.length,maxSpread=3){
    if(!Array.isArray(heads)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<heads.length||!Number.isSafeInteger(maxSpread)||maxSpread<0||heads.some(head=>!Number.isSafeInteger(head)||head<0))throw new Error('Chart RPC consensus input is invalid');
    const ordered=[...heads].sort((a,b)=>a-b),quorum=Math.floor(configuredSources/2)+1;let best=[];
    for(let start=0;start<ordered.length;start++){const cluster=ordered.slice(start).filter(head=>head-ordered[start]<=maxSpread);if(cluster.length>best.length)best=cluster}
    if(best.length<quorum)return null;
    return Object.freeze({head:best[0],healthySources:best.length,configuredSources,independent:configuredSources>1});
  }
  function consensusHash(hashes,configuredSources=hashes?.length){
    if(!Array.isArray(hashes)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<hashes.length||hashes.some(hash=>typeof hash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(hash)))throw new Error('Chart RPC block hash consensus input is invalid');
    const quorum=Math.floor(configuredSources/2)+1,counts=new Map();let bestHash=null,bestCount=0;
    for(const value of hashes){const hash=value.toLowerCase(),count=(counts.get(hash)||0)+1;counts.set(hash,count);if(count>bestCount){bestHash=hash;bestCount=count}}
    if(bestCount<quorum)return null;
    return Object.freeze({blockHash:bestHash,healthySources:bestCount,configuredSources,independent:configuredSources>1});
  }
  function sourceHealth(current,healthy,now=Date.now(),failureThreshold=3,quarantineMs=60000){
    if(!current||!Number.isSafeInteger(current.failures)||current.failures<0||!Number.isFinite(current.quarantinedUntil)||current.quarantinedUntil<0||typeof healthy!=='boolean'||!Number.isFinite(now)||now<0||!Number.isSafeInteger(failureThreshold)||failureThreshold<1||!Number.isFinite(quarantineMs)||quarantineMs<1000)throw new Error('Chart RPC source health input is invalid');
    if(healthy)return Object.freeze({failures:0,quarantinedUntil:0});
    if(current.quarantinedUntil>now)return Object.freeze({failures:current.failures,quarantinedUntil:current.quarantinedUntil});
    const failures=(current.quarantinedUntil>0?0:current.failures)+1;
    return Object.freeze({failures:failures>=failureThreshold?0:failures,quarantinedUntil:failures>=failureThreshold?now+quarantineMs:0});
  }
  function sourceHealthSnapshot(sources,fingerprint,now=Date.now()){
    if(!Array.isArray(sources)||typeof fingerprint!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(fingerprint)||!Number.isFinite(now)||now<0||sources.some(item=>!item||!Number.isSafeInteger(item.failures)||item.failures<0||item.failures>2||!Number.isFinite(item.quarantinedUntil)||item.quarantinedUntil<0||item.quarantinedUntil>now+60000))throw new Error('Chart RPC health snapshot input is invalid');
    return Object.freeze({version:1,fingerprint:fingerprint.toLowerCase(),savedAt:now,sources:sources.map(item=>Object.freeze({failures:item.failures,quarantinedUntil:item.quarantinedUntil}))});
  }
  function restoreSourceHealth(snapshot,fingerprint,sourceCount,now=Date.now(),maxAgeMs=300000){
    if(typeof fingerprint!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(fingerprint)||!Number.isSafeInteger(sourceCount)||sourceCount<0||!Number.isFinite(now)||now<0||!Number.isFinite(maxAgeMs)||maxAgeMs<60000)return null;
    if(!snapshot||snapshot.version!==1||snapshot.fingerprint!==fingerprint.toLowerCase()||!Number.isFinite(snapshot.savedAt)||snapshot.savedAt>now+5000||now-snapshot.savedAt>maxAgeMs||!Array.isArray(snapshot.sources)||snapshot.sources.length!==sourceCount)return null;
    if(snapshot.sources.some(item=>!item||!Number.isSafeInteger(item.failures)||item.failures<0||item.failures>2||!Number.isFinite(item.quarantinedUntil)||item.quarantinedUntil<0||item.quarantinedUntil>snapshot.savedAt+60000))return null;
    return Object.freeze(snapshot.sources.map(item=>item.quarantinedUntil>now?Object.freeze({failures:item.failures,quarantinedUntil:item.quarantinedUntil}):Object.freeze({failures:item.quarantinedUntil?0:item.failures,quarantinedUntil:0})));
  }
  function rankCanonicalSources(observations,canonicalHead,canonicalHash,maxSpread=3){
    if(!Array.isArray(observations)||!Number.isSafeInteger(canonicalHead)||canonicalHead<0||typeof canonicalHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(canonicalHash)||!Number.isSafeInteger(maxSpread)||maxSpread<0||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||!Number.isSafeInteger(item.head)||item.head<0||!Number.isFinite(item.latencyMs)||item.latencyMs<0||typeof item.blockHash!=='string')||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart RPC source ranking input is invalid');
    const hash=canonicalHash.toLowerCase();return Object.freeze(observations.filter(item=>item.head>=canonicalHead&&item.head<=canonicalHead+maxSpread&&item.blockHash.toLowerCase()===hash).sort((a,b)=>a.latencyMs-b.latencyMs||a.index-b.index).map(item=>item.index));
  }
  function consensusQuote(observations,configuredSources){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||!item.quote||typeof item.quote.dexId!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(item.quote.dexId)||typeof item.quote.adapter!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(item.quote.adapter)||typeof item.quote.amountOut!=='bigint'||item.quote.amountOut<=0n||!['bigint','number'].includes(typeof item.quote.priority))||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart RPC quote consensus input is invalid');
    const groups=new Map();for(const item of observations){const quote=item.quote,key=[quote.dexId.toLowerCase(),quote.adapter.toLowerCase(),quote.amountOut.toString(),BigInt(quote.priority).toString()].join(':');const group=groups.get(key)||[];group.push(item);groups.set(key,group)}
    const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;const quote=winner[0].quote;
    return Object.freeze({dexId:quote.dexId.toLowerCase(),adapter:quote.adapter.toLowerCase(),amountOut:quote.amountOut,priority:BigInt(quote.priority),sourceIndexes:Object.freeze(winner.map(item=>item.index))});
  }
  function bindQuote(quote,blockNumber,blockHash,issuedAt=Date.now(),ttlMs=10000){
    if(!quote||typeof quote.dexId!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(quote.dexId)||typeof quote.adapter!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(quote.adapter)||typeof quote.amountOut!=='bigint'||quote.amountOut<=0n||!['bigint','number'].includes(typeof quote.priority)||!Number.isSafeInteger(blockNumber)||blockNumber<0||typeof blockHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(blockHash)||!Number.isFinite(issuedAt)||issuedAt<0||!Number.isFinite(ttlMs)||ttlMs<1000||ttlMs>30000)throw new Error('Chart RPC quote binding input is invalid');
    return Object.freeze({...quote,dexId:quote.dexId.toLowerCase(),adapter:quote.adapter.toLowerCase(),priority:BigInt(quote.priority),blockNumber,blockHash:blockHash.toLowerCase(),issuedAt,expiresAt:issuedAt+ttlMs});
  }
  function quoteBindingMatches(bound,quote,blockHash,now=Date.now()){
    if(!bound||!quote||!Number.isFinite(now)||typeof blockHash!=='string'||!['bigint','number'].includes(typeof quote.priority))return false;return now>=bound.issuedAt&&now<=bound.expiresAt&&blockHash.toLowerCase()===bound.blockHash&&quote.dexId?.toLowerCase()===bound.dexId&&quote.adapter?.toLowerCase()===bound.adapter&&quote.amountOut===bound.amountOut&&BigInt(quote.priority)===bound.priority;
  }
  function normalizeQuoteRequest(request){
    if(!request||!Number.isSafeInteger(request.chainId)||request.chainId<1||typeof request.router!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(request.router)||typeof request.tokenIn!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(request.tokenIn)||typeof request.tokenOut!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(request.tokenOut)||request.tokenIn.toLowerCase()===request.tokenOut.toLowerCase()||typeof request.amountIn!=='bigint'||request.amountIn<=0n||!Array.isArray(request.routes)||request.routes.length<1||request.routes.length>32||request.routes.some(route=>typeof route!=='string'||!/^0x(?:[0-9a-fA-F]{2})*$/.test(route))||!Number.isSafeInteger(request.slippageBps)||request.slippageBps<0||request.slippageBps>5000)throw new Error('Chart RPC quote request input is invalid');
    return Object.freeze({chainId:request.chainId,router:request.router.toLowerCase(),tokenIn:request.tokenIn.toLowerCase(),tokenOut:request.tokenOut.toLowerCase(),amountIn:request.amountIn,routes:Object.freeze(request.routes.map(route=>route.toLowerCase())),slippageBps:request.slippageBps});
  }
  function bindQuoteRequest(bound,request){if(!bound||!Number.isFinite(bound.expiresAt))throw new Error('Chart RPC quote request binding is invalid');return Object.freeze({...bound,request:normalizeQuoteRequest(request)})}
  function quoteRequestMatches(bound,request){try{const expected=bound?.request,actual=normalizeQuoteRequest(request);return Boolean(expected)&&expected.chainId===actual.chainId&&expected.router===actual.router&&expected.tokenIn===actual.tokenIn&&expected.tokenOut===actual.tokenOut&&expected.amountIn===actual.amountIn&&expected.slippageBps===actual.slippageBps&&expected.routes.length===actual.routes.length&&expected.routes.every((route,index)=>route===actual.routes[index])}catch{return false}}
  function normalizeExecutionPlan(plan){
    if(!plan||typeof plan.sender!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(plan.sender)||typeof plan.recipient!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(plan.recipient)||typeof plan.router!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(plan.router)||typeof plan.minimumAmountOut!=='bigint'||plan.minimumAmountOut<=0n||!Number.isSafeInteger(plan.deadline)||plan.deadline<1||!['native-in','native-out','single','split'].includes(plan.kind))throw new Error('Chart execution plan input is invalid');
    return Object.freeze({sender:plan.sender.toLowerCase(),recipient:plan.recipient.toLowerCase(),router:plan.router.toLowerCase(),minimumAmountOut:plan.minimumAmountOut,deadline:plan.deadline,kind:plan.kind});
  }
  function bindExecutionPlan(bound,plan){if(!bound?.request)throw new Error('Chart execution plan binding is invalid');return Object.freeze({...bound,execution:normalizeExecutionPlan(plan)})}
  function executionPlanMatches(bound,plan,nowSeconds=Math.floor(Date.now()/1000)){try{const expected=bound?.execution,actual=normalizeExecutionPlan(plan);return Boolean(expected)&&Number.isSafeInteger(nowSeconds)&&nowSeconds<=actual.deadline&&expected.sender===actual.sender&&expected.recipient===actual.recipient&&expected.router===actual.router&&expected.minimumAmountOut===actual.minimumAmountOut&&expected.deadline===actual.deadline&&expected.kind===actual.kind}catch{return false}}
  function normalizeTransaction(request){
    const legacy=request?.type===0&&typeof request.gasPrice==='bigint'&&request.gasPrice>0n&&request.maxFeePerGas==null&&request.maxPriorityFeePerGas==null,dynamic=request?.type===2&&request.gasPrice==null&&typeof request.maxFeePerGas==='bigint'&&request.maxFeePerGas>0n&&typeof request.maxPriorityFeePerGas==='bigint'&&request.maxPriorityFeePerGas>=0n&&request.maxPriorityFeePerGas<=request.maxFeePerGas;
    if(!request||!Number.isSafeInteger(request.chainId)||request.chainId<1||typeof request.to!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(request.to)||typeof request.data!=='string'||!/^0x(?:[0-9a-fA-F]{2}){4,}$/.test(request.data)||typeof request.value!=='bigint'||request.value<0n||typeof request.gasLimit!=='bigint'||request.gasLimit<=0n||!Number.isSafeInteger(request.nonce)||request.nonce<0||legacy===dynamic)throw new Error('Chart wallet transaction input is invalid');
    return Object.freeze({chainId:request.chainId,to:request.to.toLowerCase(),data:request.data.toLowerCase(),value:request.value,gasLimit:request.gasLimit,nonce:request.nonce,type:request.type,gasPrice:legacy?request.gasPrice:null,maxFeePerGas:dynamic?request.maxFeePerGas:null,maxPriorityFeePerGas:dynamic?request.maxPriorityFeePerGas:null});
  }
  function bindTransaction(bound,request){const transaction=normalizeTransaction(request);if(!bound?.execution||!bound?.request||transaction.chainId!==bound.request.chainId||transaction.to!==bound.execution.router||(bound.execution.kind==='native-in'?transaction.value!==bound.request.amountIn:transaction.value!==0n))throw new Error('Chart wallet transaction binding is invalid');return Object.freeze({...bound,transaction})}
  function bindReplacementTransaction(bound,request,maxFeeMultiplier=5n){const expected=bound?.transaction,actual=normalizeTransaction(request);if(!expected||typeof maxFeeMultiplier!=='bigint'||maxFeeMultiplier<1n||maxFeeMultiplier>10n||actual.chainId!==expected.chainId||actual.to!==expected.to||actual.data!==expected.data||actual.value!==expected.value||actual.gasLimit!==expected.gasLimit||actual.nonce!==expected.nonce||actual.type!==expected.type)throw new Error('Chart replacement transaction binding is invalid');const priorityCeiling=expected.type===2?(expected.maxPriorityFeePerGas===0n?expected.maxFeePerGas:expected.maxPriorityFeePerGas*maxFeeMultiplier):0n,bounded=actual.type===0?actual.gasPrice>=expected.gasPrice&&actual.gasPrice<=expected.gasPrice*maxFeeMultiplier:actual.maxFeePerGas>=expected.maxFeePerGas&&actual.maxPriorityFeePerGas>=expected.maxPriorityFeePerGas&&actual.maxFeePerGas<=expected.maxFeePerGas*maxFeeMultiplier&&actual.maxPriorityFeePerGas<=priorityCeiling;if(!bounded)throw new Error('Chart replacement transaction fee is invalid');return Object.freeze({...bound,transaction:actual})}
  function transactionMatches(bound,request){try{const expected=bound?.transaction,actual=normalizeTransaction(request);return Boolean(expected)&&expected.chainId===actual.chainId&&expected.to===actual.to&&expected.data===actual.data&&expected.value===actual.value&&expected.gasLimit===actual.gasLimit&&expected.nonce===actual.nonce&&expected.type===actual.type&&expected.gasPrice===actual.gasPrice&&expected.maxFeePerGas===actual.maxFeePerGas&&expected.maxPriorityFeePerGas===actual.maxPriorityFeePerGas}catch{return false}}
  function consensusSubmittedTransaction(bound,observations,configuredSources,transactionHash){
    if(!bound?.execution||!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof transactionHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(transactionHash)||new Set(observations.map(item=>item?.index)).size!==observations.length)throw new Error('Chart submitted transaction consensus input is invalid');
    const expectedHash=transactionHash.toLowerCase(),normalized=[];for(const item of observations){try{const transaction=item?.transaction,hash=String(transaction?.hash||'').toLowerCase(),from=String(transaction?.from||'').toLowerCase(),request={chainId:Number(transaction?.chainId),to:transaction?.to,data:transaction?.data,value:transaction?.value,gasLimit:transaction?.gasLimit,nonce:Number(transaction?.nonce),type:Number(transaction?.type),gasPrice:transaction?.gasPrice??null,maxFeePerGas:transaction?.maxFeePerGas??null,maxPriorityFeePerGas:transaction?.maxPriorityFeePerGas??null};let replacement=false;try{bindReplacementTransaction(bound,request);replacement=true}catch{}if(!item||!Number.isSafeInteger(item.index)||item.index<0||hash!==expectedHash||from!==bound.execution.sender||(!transactionMatches(bound,request)&&!replacement))continue;normalized.push({index:item.index,transactionHash:hash,from,...normalizeTransaction(request)})}catch{}}
    const key=item=>[item.transactionHash,item.from,item.chainId,item.to,item.data,item.value,item.gasLimit,item.nonce,item.type,item.gasPrice,item.maxFeePerGas,item.maxPriorityFeePerGas].map(String).join(':'),groups=new Map();for(const item of normalized){const id=key(item),group=groups.get(id)||[];group.push(item);groups.set(id,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;const transaction=winner[0];return Object.freeze({transactionHash:transaction.transactionHash,from:transaction.from,chainId:transaction.chainId,to:transaction.to,data:transaction.data,value:transaction.value,gasLimit:transaction.gasLimit,nonce:transaction.nonce,type:transaction.type,gasPrice:transaction.gasPrice,maxFeePerGas:transaction.maxFeePerGas,maxPriorityFeePerGas:transaction.maxPriorityFeePerGas,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusCancellationTransaction(bound,observations,configuredSources,transactionHash){
    if(!bound?.transaction||!bound?.execution||!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof transactionHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(transactionHash)||new Set(observations.map(item=>item?.index)).size!==observations.length)throw new Error('Chart cancellation transaction consensus input is invalid');
    const expectedHash=transactionHash.toLowerCase(),original=bound.transaction,normalized=[];for(const item of observations){try{const tx=item?.transaction,hash=String(tx?.hash||'').toLowerCase(),from=String(tx?.from||'').toLowerCase(),chainId=Number(tx?.chainId),to=String(tx?.to||'').toLowerCase(),data=String(tx?.data??'').toLowerCase(),value=tx?.value,gasLimit=tx?.gasLimit,nonce=Number(tx?.nonce),type=Number(tx?.type),gasPrice=tx?.gasPrice??null,maxFeePerGas=tx?.maxFeePerGas??null,maxPriorityFeePerGas=tx?.maxPriorityFeePerGas??null,legacy=type===0&&typeof gasPrice==='bigint'&&gasPrice>0n&&maxFeePerGas==null&&maxPriorityFeePerGas==null,dynamic=type===2&&gasPrice==null&&typeof maxFeePerGas==='bigint'&&maxFeePerGas>0n&&typeof maxPriorityFeePerGas==='bigint'&&maxPriorityFeePerGas>=0n&&maxPriorityFeePerGas<=maxFeePerGas,sameCall=to===original.to&&data===original.data&&value===original.value;if(!item||!Number.isSafeInteger(item.index)||item.index<0||hash!==expectedHash||from!==bound.execution.sender||chainId!==original.chainId||nonce!==original.nonce||!/^0x[0-9a-f]{40}$/.test(to)||!/^0x(?:[0-9a-f]{2})*$/.test(data)||typeof value!=='bigint'||value<0n||typeof gasLimit!=='bigint'||gasLimit<=0n||legacy===dynamic||sameCall)continue;normalized.push({index:item.index,transactionHash:hash,from,chainId,to,data,value,gasLimit,nonce,type,gasPrice:legacy?gasPrice:null,maxFeePerGas:dynamic?maxFeePerGas:null,maxPriorityFeePerGas:dynamic?maxPriorityFeePerGas:null})}catch{}}
    const key=item=>[item.transactionHash,item.from,item.chainId,item.to,item.data,item.value,item.gasLimit,item.nonce,item.type,item.gasPrice,item.maxFeePerGas,item.maxPriorityFeePerGas].map(String).join(':'),groups=new Map();for(const item of normalized){const id=key(item),group=groups.get(id)||[];group.push(item);groups.set(id,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;return Object.freeze({transactionHash:winner[0].transactionHash,from:winner[0].from,nonce:winner[0].nonce,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusTransactionCount(observations,configuredSources){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||!Number.isSafeInteger(item.nonce)||item.nonce<0)||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart RPC transaction count consensus input is invalid');
    const groups=new Map();for(const item of observations){const group=groups.get(item.nonce)||[];group.push(item);groups.set(item.nonce,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;return Object.freeze({nonce:winner[0].nonce,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusTokenAllowance(observations,configuredSources,requiredAmount){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof requiredAmount!=='bigint'||requiredAmount<0n||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||typeof item.allowance!=='bigint'||item.allowance<0n)||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart RPC token allowance consensus input is invalid');
    const groups=new Map();for(const item of observations){const key=item.allowance.toString(),group=groups.get(key)||[];group.push(item);groups.set(key,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum||winner[0].allowance!==requiredAmount)return null;return Object.freeze({allowance:winner[0].allowance,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusSimulation(observations,configuredSources,gasCeiling,maxSpreadBps=2000){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof gasCeiling!=='bigint'||gasCeiling<=0n||!Number.isSafeInteger(maxSpreadBps)||maxSpreadBps<0||maxSpreadBps>5000||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||typeof item.result!=='string'||!/^0x(?:[0-9a-fA-F]{2})*$/.test(item.result)||typeof item.gas!=='bigint'||item.gas<=0n)||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart RPC simulation consensus input is invalid');
    const groups=new Map();for(const item of observations){const key=item.result.toLowerCase(),group=groups.get(key)||[];group.push(item);groups.set(key,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;
    const gasValues=winner.map(item=>item.gas),minimum=gasValues.reduce((a,b)=>a<b?a:b),maximum=gasValues.reduce((a,b)=>a>b?a:b);if(maximum>gasCeiling||(maximum-minimum)*10000n>maximum*BigInt(maxSpreadBps))return null;const buffered=maximum+maximum/5n;
    return Object.freeze({result:winner[0].result.toLowerCase(),gasEstimate:maximum,gasLimit:buffered>gasCeiling?gasCeiling:buffered,sourceIndexes:Object.freeze(winner.map(item=>item.index))});
  }
  function consensusFeeData(observations,configuredSources,maxSpreadBps=2000){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||!Number.isSafeInteger(maxSpreadBps)||maxSpreadBps<0||maxSpreadBps>5000||new Set(observations.map(item=>item?.index)).size!==observations.length)throw new Error('Chart RPC fee consensus input is invalid');
    const normalized=observations.map(item=>{if(!item||!Number.isSafeInteger(item.index)||item.index<0)throw new Error('Chart RPC fee consensus input is invalid');if(typeof item.maxFeePerGas==='bigint'&&item.maxFeePerGas>0n&&typeof item.maxPriorityFeePerGas==='bigint'&&item.maxPriorityFeePerGas>=0n&&item.maxPriorityFeePerGas<=item.maxFeePerGas)return{index:item.index,type:2,maxFeePerGas:item.maxFeePerGas,maxPriorityFeePerGas:item.maxPriorityFeePerGas};if(typeof item.gasPrice==='bigint'&&item.gasPrice>0n)return{index:item.index,type:0,gasPrice:item.gasPrice};throw new Error('Chart RPC fee consensus input is invalid')});
    const quorum=Math.floor(configuredSources/2)+1,groups=[0,2].map(type=>normalized.filter(item=>item.type===type)),winner=groups.sort((a,b)=>b.length-a.length)[0];if(winner.length<quorum)return null;const withinSpread=values=>{const minimum=values.reduce((a,b)=>a<b?a:b),maximum=values.reduce((a,b)=>a>b?a:b);return(maximum-minimum)*10000n<=maximum*BigInt(maxSpreadBps)};if(winner[0].type===0){const values=winner.map(item=>item.gasPrice);if(!withinSpread(values))return null;return Object.freeze({type:0,gasPrice:values.reduce((a,b)=>a>b?a:b),sourceIndexes:Object.freeze(winner.map(item=>item.index))})}const maximumFees=winner.map(item=>item.maxFeePerGas),priorityFees=winner.map(item=>item.maxPriorityFeePerGas);if(!withinSpread(maximumFees)||!withinSpread(priorityFees))return null;return Object.freeze({type:2,maxFeePerGas:maximumFees.reduce((a,b)=>a>b?a:b),maxPriorityFeePerGas:priorityFees.reduce((a,b)=>a>b?a:b),sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusTransactionReceipt(observations,configuredSources,transactionHash,requiredConfirmations=3){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof transactionHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(transactionHash)||!Number.isSafeInteger(requiredConfirmations)||requiredConfirmations<1||requiredConfirmations>100||new Set(observations.map(item=>item?.index)).size!==observations.length)throw new Error('Chart RPC transaction receipt consensus input is invalid');
    const expectedHash=transactionHash.toLowerCase(),normalized=observations.map(item=>{const receipt=item?.receipt,hash=String(receipt?.hash||receipt?.transactionHash||'').toLowerCase(),blockHash=String(receipt?.blockHash||'').toLowerCase(),blockNumber=Number(receipt?.blockNumber),head=Number(item?.head),canonicalHash=String(item?.block?.hash||'').toLowerCase();if(!item||!Number.isSafeInteger(item.index)||item.index<0||hash!==expectedHash||!/^0x[0-9a-f]{64}$/.test(blockHash)||!Number.isSafeInteger(blockNumber)||blockNumber<1||Number(receipt?.status)!==1||canonicalHash!==blockHash||!Number.isSafeInteger(head)||head-blockNumber+1<requiredConfirmations)throw new Error('Chart RPC transaction receipt consensus input is invalid');return{index:item.index,transactionHash:hash,blockHash,blockNumber}}),groups=new Map();for(const item of normalized){const key=`${item.transactionHash}:${item.blockHash}:${item.blockNumber}`,group=groups.get(key)||[];group.push(item);groups.set(key,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;return Object.freeze({transactionHash:winner[0].transactionHash,blockHash:winner[0].blockHash,blockNumber:winner[0].blockNumber,confirmations:requiredConfirmations,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function consensusFailedTransactionReceipt(observations,configuredSources,transactionHash,requiredConfirmations=3){
    if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof transactionHash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(transactionHash)||!Number.isSafeInteger(requiredConfirmations)||requiredConfirmations<1||requiredConfirmations>100||new Set(observations.map(item=>item?.index)).size!==observations.length)throw new Error('Chart RPC failed transaction consensus input is invalid');
    const expectedHash=transactionHash.toLowerCase(),normalized=observations.map(item=>{const receipt=item?.receipt,hash=String(receipt?.hash||receipt?.transactionHash||'').toLowerCase(),blockHash=String(receipt?.blockHash||'').toLowerCase(),blockNumber=Number(receipt?.blockNumber),head=Number(item?.head),canonicalHash=String(item?.block?.hash||'').toLowerCase();if(!item||!Number.isSafeInteger(item.index)||item.index<0||hash!==expectedHash||!/^0x[0-9a-f]{64}$/.test(blockHash)||!Number.isSafeInteger(blockNumber)||blockNumber<1||Number(receipt?.status)!==0||canonicalHash!==blockHash||!Number.isSafeInteger(head)||head-blockNumber+1<requiredConfirmations)throw new Error('Chart RPC failed transaction consensus input is invalid');return{index:item.index,transactionHash:hash,blockHash,blockNumber}}),groups=new Map();for(const item of normalized){const key=`${item.transactionHash}:${item.blockHash}:${item.blockNumber}`,group=groups.get(key)||[];group.push(item);groups.set(key,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum)return null;return Object.freeze({transactionHash:winner[0].transactionHash,blockHash:winner[0].blockHash,blockNumber:winner[0].blockNumber,confirmations:requiredConfirmations,sourceIndexes:Object.freeze(winner.map(item=>item.index))})
  }
  function decodeSettlementOutput(receipt,context){
    if(!receipt||!Array.isArray(receipt.logs)||!context||!['erc20','native-out'].includes(context.kind)||typeof context.recipient!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(context.recipient))throw new Error('Chart settlement output input is invalid');const recipientTopic=`0x${'0'.repeat(24)}${context.recipient.slice(2)}`.toLowerCase();
    if(context.kind==='erc20'){if(typeof context.tokenOut!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(context.tokenOut)||typeof context.transferTopic!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(context.transferTopic))throw new Error('Chart settlement output input is invalid');let amount=0n,matches=0;for(const log of receipt.logs){if(String(log?.address||'').toLowerCase()!==context.tokenOut.toLowerCase()||String(log?.topics?.[0]||'').toLowerCase()!==context.transferTopic.toLowerCase()||String(log?.topics?.[2]||'').toLowerCase()!==recipientTopic||typeof log.data!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(log.data))continue;amount+=BigInt(log.data);matches++}if(matches===0||amount<=0n)throw new Error('Chart settlement output event is invalid');return amount}
    if(typeof context.nativeRouter!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(context.nativeRouter)||typeof context.tokenIn!=='string'||!/^0x[0-9a-fA-F]{40}$/.test(context.tokenIn)||typeof context.nativeEventTopic!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(context.nativeEventTopic)||typeof context.amountIn!=='bigint'||context.amountIn<=0n)throw new Error('Chart settlement output input is invalid');const tokenTopic=`0x${'0'.repeat(24)}${context.tokenIn.slice(2)}`.toLowerCase(),matches=receipt.logs.filter(log=>String(log?.address||'').toLowerCase()===context.nativeRouter.toLowerCase()&&String(log?.topics?.[0]||'').toLowerCase()===context.nativeEventTopic.toLowerCase()&&String(log?.topics?.[2]||'').toLowerCase()===recipientTopic&&String(log?.topics?.[3]||'').toLowerCase()===tokenTopic&&typeof log.data==='string'&&/^0x[0-9a-fA-F]{192}$/.test(log.data));if(matches.length!==1)throw new Error('Chart settlement output event is invalid');const data=matches[0].data.slice(2),nativeIn=BigInt(`0x${data.slice(0,64)}`),amountIn=BigInt(`0x${data.slice(64,128)}`),amountOut=BigInt(`0x${data.slice(128,192)}`);if(nativeIn!==0n||amountIn!==context.amountIn||amountOut<=0n)throw new Error('Chart settlement output event is invalid');return amountOut
  }
  function consensusSettlementOutput(observations,configuredSources,minimumAmountOut){if(!Array.isArray(observations)||!Number.isSafeInteger(configuredSources)||configuredSources<1||configuredSources<observations.length||typeof minimumAmountOut!=='bigint'||minimumAmountOut<=0n||observations.some(item=>!item||!Number.isSafeInteger(item.index)||item.index<0||typeof item.amountOut!=='bigint'||item.amountOut<=0n)||new Set(observations.map(item=>item.index)).size!==observations.length)throw new Error('Chart settlement output consensus input is invalid');const groups=new Map();for(const item of observations){const key=item.amountOut.toString(),group=groups.get(key)||[];group.push(item);groups.set(key,group)}const winner=[...groups.values()].sort((a,b)=>b.length-a.length)[0]||[],quorum=Math.floor(configuredSources/2)+1;if(winner.length<quorum||winner[0].amountOut<minimumAmountOut)return null;return Object.freeze({amountOut:winner[0].amountOut,minimumAmountOut,sourceIndexes:Object.freeze(winner.map(item=>item.index))})}
  root.LQCChartHealth=Object.freeze({classify,chainSync,consensusHead,consensusHash,sourceHealth,sourceHealthSnapshot,restoreSourceHealth,rankCanonicalSources,consensusQuote,bindQuote,quoteBindingMatches,bindQuoteRequest,quoteRequestMatches,bindExecutionPlan,executionPlanMatches,bindTransaction,bindReplacementTransaction,transactionMatches,consensusSubmittedTransaction,consensusCancellationTransaction,consensusTransactionCount,consensusTokenAllowance,consensusSimulation,consensusFeeData,consensusTransactionReceipt,consensusFailedTransactionReceipt,decodeSettlementOutput,consensusSettlementOutput});
})(typeof window==='undefined'?globalThis:window);
