(function () {
  'use strict';

  const dictionaries = Object.freeze({
    ko: Object.freeze({
      backHome: '홈으로 돌아가기', connectWallet: '지갑 연결', favorite: '즐겨찾기', more: '더보기',
      marketChart: 'tLQC 테스트넷 시장 차트', price: '가격 ⇌', marketCap: '시가총액', liquidity: '유동성', volume24h: '24시간 거래량', holders: '보유자',
      charts: '차트', info: '정보', data: '데이터', risk: '위험', routes: '경로', marketInfo: '시장 정보', marketSearch: '시장 검색', lpFee: 'LP 수수료', route: '경로', optimalPath: '최적 경로', chartIntervals: '차트 시간 단위', moreIntervals: '더보기⌄', chartType: '차트 유형', tradeSettings: '거래 설정',
      accountInfo: '계정 정보', myPositions: '내 포지션', topTraders: '상위 거래자', activities: '활동', lqcBalance: 'tLQC 잔액', unrealizedPnl: '미실현 손익', holdings: '보유 수량', network: '네트워크',
      buyLqc: 'tLQC 매수', sellLqc: 'tLQC 매도', closeOrder: '주문창 닫기', slippageTolerance: '슬리피지 허용 범위', customSlippage: '직접 입력 슬리피지', sendToken: '보내는 토큰', amountToSend: '보낼 수량', balance: '잔액', flipTokens: '토큰 순서 변경', receiveToken: '받는 토큰', estimatedAmount: '예상 수량',
      minimumReceived: '최소 수령량', dexFee: 'DEX 수수료', quoteIncluded: '견적 포함', estimatedGas: '예상 가스비', priceImpact: '가격 영향', selectedDex: '선택된 DEX', splitRatio: '분할 비율', alternativeRoute: '대체 경로', executionReady: '실행 준비', executionStrategy: '실행 전략', comparePending: 'LQC Flow · PancakeSwap 비교 대기', singleRoute100: '단일 경로 100%', showAfterQuote: '견적 후 표시', checkPending: '확인 대기', singleQuoteFirst: '단일 경로 · 견적 우선', deploymentPending: '테스트넷 배포 주소를 연결하면 거래가 활성화됩니다.',
      testnetWarning: '테스트넷 MVP · 실제 자금을 보내지 마세요. 독립 보안감사 전에는 메인넷에서 사용할 수 없습니다.', deploymentState: '배포 대기', buy: '매수', sell: '매도', quickTrade: '빠른 거래', selectToken: '토큰 선택', searchToken: '토큰 이름·티커·주소 검색', verifiedToken: '검증됨', noTokensFound: '등록된 토큰을 찾을 수 없습니다.', close: '닫기', selectWallet: '지갑 선택', walletHelp: '기기에 설치되었거나 앱 내부에서 제공되는 비수탁형 지갑을 선택하세요.', language: '언어', korean: '한국어', english: 'English',
      walletNotFound: '설치된 비수탁형 지갑을 찾지 못했습니다. 지갑 앱 또는 브라우저 확장 프로그램을 확인하세요.', approveConnection: '지갑에서 연결을 승인해 주세요.', switchNetwork: '네트워크 전환', walletDetected: '지갑이 감지되었습니다. BSC 테스트넷으로 전환하면 바로 연결됩니다.', routerReady: '지갑 자동 연결 완료 · Router 2.0 준비됨', contractsPending: '지갑 연결 완료 · 테스트넷 컨트랙트 배포 대기 중', walletDisconnected: '지갑 연결이 해제되었습니다.', browserWallet: '브라우저 지갑', nonCustodialWallet: '비수탁형 지갑', contractsReady: '컨트랙트가 설정되었습니다. 지갑을 연결하세요.',
      singleRoute: '단일 경로', quoteChecking: '견적 확인 중', routeChecking: '경로 확인 중', executionChecking: '실행 조건 확인 중', noExtraRoute: '사용 가능한 추가 경로 없음', fallbackAvailable: '{name} · 자동 재견적 가능', splitStrategy: 'Router 2.0 · 가스 차감 후 원자적 분할', bestSingleStrategy: 'Router 2.0 · 가스 차감 후 단일 최적', oraclePendingStrategy: '가스 오라클 대기 · 안전 단일 경로', highImpact: '주의 · 가격영향 3% 이상', readyGasVerified: '준비 완료 · 가스 검증됨', limitedOraclePending: '제한적 준비 · 가스 오라클 대기', highImpactHelp: '가격영향이 높습니다. 수량을 줄이거나 대체 경로를 확인하세요.', preflightPassed: '거래 실행 전 점검을 통과했습니다.', noValidRoute: '유효한 경로 없음', noFallbackRoute: '대체 경로도 없음', unavailable: '실행 불가', liquidityUnavailable: '이 거래쌍의 유동성을 확인할 수 없습니다. 수량을 줄이거나 다른 토큰을 선택하세요.', enterAmount: '보낼 수량을 입력하세요.', approveToken: '{token} 사용 승인을 확인하세요.', approvalComplete: '승인 완료 · 최신 가격과 경로를 다시 확인합니다.', newApprovalRequired: '최적 경로 변경으로 새 실행 컨트랙트 승인이 필요합니다.', splitSubmitted: 'Router 2.0 분할 거래가 제출되었습니다.', tradeSubmitted: 'Router 2.0 거래가 제출되었습니다.', tradeComplete: '{side} 거래가 완료되었습니다.', pendingTransaction: '확인되지 않은 거래가 있습니다. 새 거래를 중단했습니다.', networkPendingTransaction: '지갑에 처리 중인 거래가 있습니다. 완료 또는 취소를 확인하기 전에는 새 거래를 만들 수 없습니다.', pendingCheckFailed: '보류 거래 상태를 확인하지 못했습니다. 안전을 위해 새 거래를 중단했습니다.', transactionStillPending: '거래가 아직 처리 중입니다. 새 거래를 만들지 말고 BscScan에서 상태를 확인하세요.', viewTransaction: 'BscScan에서 확인', insufficientMaxGas: 'MAX 거래에 필요한 tBNB 가스비가 부족합니다.', invalidAmount: '수량을 숫자로 정확하게 입력하세요. 음수·지수표기·과도한 소수 자릿수는 사용할 수 없습니다.', invalidSlippage: '슬리피지는 0.1%에서 5% 사이로 입력하세요.', incompatibleNativeTokens: 'BNB와 WBNB는 동시에 선택할 수 없습니다.',
      error_STALE_QUOTE: '표시된 견적이 만료되었거나 거래 조건이 변경되었습니다. 최신 견적을 확인한 뒤 다시 실행하세요.',
      simulatingTrade: '거래 실행 가능성을 사전 점검하고 있습니다.', simulationPassed: '사전 시뮬레이션 통과 · 지갑 서명을 준비합니다.', error_SIMULATION_FAILED: '사전 시뮬레이션에서 거래 실패가 예상되어 제출을 중단했습니다. 최신 견적과 잔액·승인 상태를 확인하세요.',
      error_USER_REJECTED: '지갑에서 거래가 취소되었습니다. 원하시면 견적을 다시 확인한 뒤 재시도하세요.', error_INSUFFICIENT_GAS: '거래를 실행할 BNB 가스비가 부족합니다. 소량의 tBNB를 준비한 뒤 다시 시도하세요.', error_PRICE_MOVED: '가격이 변해 최소 수령 조건을 충족하지 못했습니다. 새 견적을 받은 뒤 슬리피지를 확인하고 재시도하세요.', error_NO_ROUTE: '현재 실행 가능한 유동성 경로가 없습니다. 수량을 줄이거나 다른 거래쌍을 선택하세요.', error_RISK_BLOCKED: 'LQC 위험관리 정책이 이 거래를 차단했습니다. 거래 한도와 토큰·DEX 활성 상태를 확인하세요.', error_APPROVAL_REQUIRED: '토큰 사용 승인이 완료되지 않았습니다. 승인 거래를 완료한 뒤 Swap을 다시 실행하세요.', error_ROUTE_CHANGED: '승인 중 최적 거래 경로가 다시 변경되었습니다. 최신 견적을 확인한 뒤 Swap을 다시 실행하세요.', error_NETWORK_ERROR: 'BSC 테스트넷 연결을 확인할 수 없습니다. 지갑 네트워크를 BSC Testnet으로 전환하세요.', error_UNKNOWN: '거래를 실행하지 못했습니다. 최신 견적과 지갑 상태를 확인한 뒤 다시 시도하세요.'
    }),
    en: Object.freeze({
      backHome: 'Back to home', connectWallet: 'Connect wallet', favorite: 'Favorite', more: 'More',
      marketChart: 'tLQC testnet market chart', price: 'Price ⇌', marketCap: 'Market cap', liquidity: 'Liquidity', volume24h: '24h volume', holders: 'Holders',
      charts: 'Charts', info: 'Info', data: 'Data', risk: 'Risk', routes: 'Routes', marketInfo: 'Market information', marketSearch: 'Search market', lpFee: 'LP Fee', route: 'Route', optimalPath: 'Optimal Path', chartIntervals: 'Chart intervals', moreIntervals: 'More⌄', chartType: 'Chart type', tradeSettings: 'Trade settings',
      accountInfo: 'Account information', myPositions: 'My positions', topTraders: 'Top traders', activities: 'Activities', lqcBalance: 'tLQC balance', unrealizedPnl: 'Unrealized PnL', holdings: 'Holdings', network: 'Network',
      buyLqc: 'Buy tLQC', sellLqc: 'Sell tLQC', closeOrder: 'Close order panel', slippageTolerance: 'Slippage tolerance', customSlippage: 'Custom slippage', sendToken: 'You pay', amountToSend: 'Amount to send', balance: 'Balance', flipTokens: 'Switch tokens', receiveToken: 'You receive', estimatedAmount: 'Estimated amount',
      minimumReceived: 'Minimum received', dexFee: 'DEX fee', quoteIncluded: 'Included in quote', estimatedGas: 'Estimated gas', priceImpact: 'Price impact', selectedDex: 'Selected DEX', splitRatio: 'Split ratio', alternativeRoute: 'Alternative route', executionReady: 'Execution readiness', executionStrategy: 'Execution strategy', comparePending: 'Waiting to compare LQC Flow · PancakeSwap', singleRoute100: 'Single route 100%', showAfterQuote: 'Shown after quote', checkPending: 'Waiting for checks', singleQuoteFirst: 'Single route · quote first', deploymentPending: 'Trading activates after testnet deployment addresses are connected.',
      testnetWarning: 'Testnet MVP · Do not send real funds. Mainnet use is disabled until an independent security audit.', deploymentState: 'Awaiting deployment', buy: 'Buy', sell: 'Sell', quickTrade: 'Quick trade', selectToken: 'Select token', searchToken: 'Search name, symbol, or address', verifiedToken: 'Verified', noTokensFound: 'No listed tokens found.', close: 'Close', selectWallet: 'Select wallet', walletHelp: 'Choose a non-custodial wallet installed on this device or provided by the host app.', language: 'Language', korean: '한국어', english: 'English',
      walletNotFound: 'No installed non-custodial wallet was found. Check your wallet app or browser extension.', approveConnection: 'Approve the connection in your wallet.', switchNetwork: 'Switch network', walletDetected: 'Wallet detected. Switch to BSC Testnet to connect.', routerReady: 'Wallet connected · Router 2.0 ready', contractsPending: 'Wallet connected · waiting for testnet contracts', walletDisconnected: 'Wallet disconnected.', browserWallet: 'Browser wallet', nonCustodialWallet: 'Non-custodial wallet', contractsReady: 'Contracts configured. Connect your wallet.',
      singleRoute: 'Single route', quoteChecking: 'Checking quotes', routeChecking: 'Checking routes', executionChecking: 'Checking execution conditions', noExtraRoute: 'No additional route available', fallbackAvailable: '{name} · automatic requote available', splitStrategy: 'Router 2.0 · atomic split after gas', bestSingleStrategy: 'Router 2.0 · best single route after gas', oraclePendingStrategy: 'Gas oracle pending · safe single route', highImpact: 'Caution · price impact is at least 3%', readyGasVerified: 'Ready · gas verified', limitedOraclePending: 'Limited readiness · gas oracle pending', highImpactHelp: 'Price impact is high. Reduce the amount or review the alternative route.', preflightPassed: 'Pre-trade checks passed.', noValidRoute: 'No valid route', noFallbackRoute: 'No fallback route', unavailable: 'Unavailable', liquidityUnavailable: 'Liquidity for this pair could not be confirmed. Reduce the amount or select another token.', enterAmount: 'Enter an amount to send.', approveToken: 'Confirm {token} spending approval.', approvalComplete: 'Approval complete · refreshing price and route.', newApprovalRequired: 'The optimal route changed and requires approval for a new execution contract.', splitSubmitted: 'Router 2.0 split trade submitted.', tradeSubmitted: 'Router 2.0 trade submitted.', tradeComplete: '{side} trade completed.', pendingTransaction: 'An unconfirmed transaction exists. A new transaction was blocked.', networkPendingTransaction: 'The wallet has a pending transaction. New trades are blocked until it is confirmed or cancelled.', pendingCheckFailed: 'Pending transaction status could not be verified. A new trade was blocked for safety.', transactionStillPending: 'The transaction is still pending. Do not create another trade; check its status on BscScan.', viewTransaction: 'View on BscScan', insufficientMaxGas: 'Not enough tBNB is available to reserve gas for a MAX trade.', invalidAmount: 'Enter an exact numeric amount. Negative values, exponent notation, and excess decimal places are not allowed.', invalidSlippage: 'Enter slippage between 0.1% and 5%.', incompatibleNativeTokens: 'BNB and WBNB cannot be selected together.',
      error_STALE_QUOTE: 'The displayed quote expired or the trade changed. Review the latest quote and submit again.',
      simulatingTrade: 'Simulating the trade before submission.', simulationPassed: 'Simulation passed · preparing wallet signature.', error_SIMULATION_FAILED: 'The preflight simulation predicts failure, so the trade was not submitted. Check the latest quote, balance, and approval.',
      error_USER_REJECTED: 'The transaction was cancelled in your wallet. Review the quote and try again when ready.', error_INSUFFICIENT_GAS: 'Not enough BNB for transaction gas. Add a small amount of tBNB and try again.', error_PRICE_MOVED: 'The price moved below the minimum received. Refresh the quote, review slippage, and try again.', error_NO_ROUTE: 'No executable liquidity route is available. Reduce the amount or select another pair.', error_RISK_BLOCKED: 'LQC risk controls blocked this trade. Check trade limits and token/DEX availability.', error_APPROVAL_REQUIRED: 'Token approval is incomplete. Complete approval and submit the swap again.', error_ROUTE_CHANGED: 'The optimal route changed during approval. Review the latest quote and submit again.', error_NETWORK_ERROR: 'BSC Testnet could not be reached. Switch your wallet to BSC Testnet.', error_UNKNOWN: 'The trade could not be executed. Check the latest quote and wallet status, then try again.'
    })
  });

  const storageKey = 'lqc-flow-locale';
  const supported = Object.keys(dictionaries);
  const normalize = value => supported.includes(String(value || '').toLowerCase().split('-')[0]) ? String(value).toLowerCase().split('-')[0] : 'ko';
  let locale = normalize(localStorage.getItem(storageKey) || 'ko');
  const t = (key, values = {}) => String(dictionaries[locale][key] || dictionaries.ko[key] || key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
  function apply(root = document) {
    document.documentElement.lang = locale;
    root.querySelectorAll('[data-i18n]').forEach(node => { node.textContent = t(node.dataset.i18n); });
    root.querySelectorAll('[data-i18n-aria]').forEach(node => { node.setAttribute('aria-label', t(node.dataset.i18nAria)); });
    root.querySelectorAll('[data-i18n-placeholder]').forEach(node => { node.setAttribute('placeholder', t(node.dataset.i18nPlaceholder)); });
    root.querySelectorAll('[data-i18n-title]').forEach(node => { node.setAttribute('title', t(node.dataset.i18nTitle)); });
  }
  function setLocale(next) {
    locale = normalize(next); localStorage.setItem(storageKey, locale); apply();
    window.dispatchEvent(new CustomEvent('lqc:localechange', { detail: { locale } }));
  }
  window.LQCI18N = Object.freeze({ t, apply, setLocale, getLocale: () => locale, supported: Object.freeze([...supported]) });
})();
