(function(root){
  'use strict';
  function create({storage,key,deploymentFingerprint,isTransactionHash,validatePayload=()=>true,now=Date.now}){
    if(!storage||typeof key!=='string'||!key||typeof deploymentFingerprint!=='string'||typeof isTransactionHash!=='function'||typeof validatePayload!=='function'||typeof now!=='function')throw new Error('Invalid recovery store configuration');
    const reservationKey=`${key}:reservation`;
    const jsonSafe=value=>JSON.parse(JSON.stringify(value,(_,item)=>typeof item==='bigint'?`${item}n`:item));
    const revive=value=>{if(Array.isArray(value))return value.map(revive);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([name,item])=>[name,revive(item)]));return typeof value==='string'&&/^\d+n$/.test(value)?BigInt(value.slice(0,-1)):value};
    const sameHash=(left,right)=>typeof left==='string'&&typeof right==='string'&&left.toLowerCase()===right.toLowerCase();
    const payload=(transactionHash,anchorQuote,settlementContext)=>({version:1,deploymentFingerprint,transactionHash,anchorQuote,settlementContext,submittedAt:now()});
    function validRecord(value){const submittedAt=Number(value?.submittedAt);return Boolean(value&&value.version===1&&value.deploymentFingerprint===deploymentFingerprint&&isTransactionHash(value.transactionHash)&&(value.cancellationHash===undefined||isTransactionHash(value.cancellationHash))&&!sameHash(value.cancellationHash,value.transactionHash)&&value.anchorQuote&&value.settlementContext&&Number.isSafeInteger(submittedAt)&&submittedAt>0&&submittedAt<=now()+300000&&validatePayload(value))}
    function state(){let raw;try{raw=storage.getItem(key)}catch{return Object.freeze({state:'invalid'})}if(raw===null)return Object.freeze({state:'none'});try{const value=revive(JSON.parse(raw));return validRecord(value)?Object.freeze({state:'valid',value,serialized:raw}):Object.freeze({state:'invalid'})}catch{return Object.freeze({state:'invalid'})}}
    function remember(transactionHash,anchorQuote,settlementContext,previousTransactionHash){let value=payload(transactionHash,anchorQuote,settlementContext);if(!validRecord(value))throw new Error('InvalidPendingExecutionRecord');try{const current=state();if(current.state==='invalid'||current.state==='valid'&&current.value.cancellationHash!==undefined)throw new Error('PendingExecutionStorageConflict');if(current.state==='valid'){const priorPlan=JSON.stringify(jsonSafe([current.value.anchorQuote,current.value.settlementContext])),nextPlan=JSON.stringify(jsonSafe([anchorQuote,settlementContext]));if(priorPlan!==nextPlan)throw new Error('PendingExecutionStorageConflict');if(sameHash(current.value.transactionHash,transactionHash))return;if(!sameHash(previousTransactionHash,current.value.transactionHash))throw new Error('PendingExecutionStorageConflict');value={...value,submittedAt:current.value.submittedAt}}const serialized=JSON.stringify(jsonSafe(value)),expected=current.state==='valid'?current.serialized:null;if(storage.getItem(key)!==expected)throw new Error('PendingExecutionStorageConflict');storage.setItem(key,serialized);if(storage.getItem(key)!==serialized)throw new Error('PendingExecutionStorageUnavailable')}catch(error){if(error?.message==='PendingExecutionStorageConflict')throw error;throw new Error('PendingExecutionStorageUnavailable')}}
    function clear(transactionHash,expectedRecord){try{const current=state();if(current.state==='none')return true;if(current.state!=='valid'||!sameHash(current.value.transactionHash,transactionHash))return false;if(expectedRecord!==undefined&&JSON.stringify(jsonSafe(current.value))!==JSON.stringify(jsonSafe(expectedRecord)))return false;if(storage.getItem(key)!==current.serialized)return false;storage.removeItem(key);return storage.getItem(key)===null}catch{return false}}
    function rememberCancellation(transactionHash,cancellationHash){const current=state();if(current.state!=='valid'||!sameHash(current.value.transactionHash,transactionHash)||!isTransactionHash(cancellationHash)||sameHash(cancellationHash,transactionHash)||(current.value.cancellationHash!==undefined&&!sameHash(current.value.cancellationHash,cancellationHash)))throw new Error('PendingExecutionStorageConflict');const value={...current.value,cancellationHash};if(!validRecord(value))throw new Error('InvalidPendingExecutionRecord');const serialized=JSON.stringify(jsonSafe(value));try{if(storage.getItem(key)!==current.serialized)throw new Error('PendingExecutionStorageConflict');storage.setItem(key,serialized);if(storage.getItem(key)!==serialized)throw new Error('PendingExecutionStorageUnavailable')}catch(error){if(error?.message==='PendingExecutionStorageConflict')throw error;throw new Error('PendingExecutionStorageUnavailable')}}
    function assertAvailable(anchorQuote){const reservation=JSON.stringify(jsonSafe(payload(`0x${'00'.repeat(32)}`,anchorQuote,anchorQuote.execution)));try{storage.setItem(reservationKey,reservation);if(storage.getItem(reservationKey)!==reservation)throw new Error('PendingExecutionStorageUnavailable');storage.removeItem(reservationKey);if(storage.getItem(reservationKey)!==null)throw new Error('PendingExecutionStorageUnavailable')}catch{try{storage.removeItem(reservationKey)}catch{}throw new Error('PendingExecutionStorageUnavailable')}}
    return Object.freeze({key,reservationKey,state,remember,rememberCancellation,clear,assertAvailable});
  }
  root.LQCRecoveryStore=Object.freeze({create});
})(typeof window==='undefined'?globalThis:window);
