import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = fs.readFileSync(path.join(root, "app/index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "app/app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "app/styles.css"), "utf8");
const i18n = fs.readFileSync(path.join(root, "app/i18n.js"), "utf8");
const english = fs.readFileSync(path.join(root, "app/locales/en.js"), "utf8");
const korean = fs.readFileSync(path.join(root, "app/locales/ko.js"), "utf8");
const englishRuntime = fs.readFileSync(path.join(root, "app/locales/en-runtime.js"), "utf8");
const koreanRuntime = fs.readFileSync(path.join(root, "app/locales/ko-runtime.js"), "utf8");
const englishTrading = fs.readFileSync(path.join(root, "app/locales/en-trading.js"), "utf8");
const koreanTrading = fs.readFileSync(path.join(root, "app/locales/ko-trading.js"), "utf8");
const recoveryLocale = fs.readFileSync(path.join(root, "app/locales/recovery.js"), "utf8");
const recoveryStoreSource = fs.readFileSync(path.join(root, "app/recovery-store.js"), "utf8");
const recoveryValidatorSource = fs.readFileSync(path.join(root, "app/recovery-validator.js"), "utf8");

describe("LQC simple trading UI", function () {
  it("provides an extensible English-first localization boundary", function () {
    assert.match(html, /<html lang="en">/);
    assert.match(html, /id="languageSelect"/);
    assert.match(html, /locales\/en\.js.*locales\/ko\.js.*i18n\.js/);
    assert.match(html, /recovery-validator\.js.*recovery-store\.js.*approval-reservation-store\.js.*recovery-sync\.js.*wallet-session-guard\.js.*trade-gate\.js.*quote-session-guard\.js.*app\.js/);
    assert.match(i18n, /lqc-flow-language/);
    assert.match(i18n, /navigator\.languages/);
    assert.match(i18n, /data-i18n-placeholder/);
    assert.match(i18n, /lqc:languagechange/);
    assert.match(english, /'wallet\.connect':'Connect wallet'/);
    assert.match(korean, /'wallet\.connect':'지갑 연결'/);
    assert.match(i18n, /replace\(\/\\\{\(\\w\+\)\\\}\/g/);
    assert.match(englishRuntime, /'status\.swapComplete'/);
    assert.match(koreanRuntime, /'status\.swapComplete'/);
    for (const code of ["user_rejected", "insufficient_gas", "price_moved", "no_route", "risk_blocked", "approval_required", "route_changed", "network_error", "unknown"]) {
      assert.match(englishRuntime, new RegExp(`'error\\.${code}\\.message'`));
      assert.match(englishRuntime, new RegExp(`'error\\.${code}\\.action'`));
      assert.match(koreanRuntime, new RegExp(`'error\\.${code}\\.message'`));
      assert.match(koreanRuntime, new RegExp(`'error\\.${code}\\.action'`));
    }
    assert.match(script, /const translatedSwapError=error=>/);
    assert.match(script, /guidance\.code\.toLowerCase\(\)/);
    for (const key of ["market.count", "token.count", "trade.action", "quote.strategySplit", "quote.noLiquidity", "quote.maximumGas"]) {
      assert.match(englishTrading, new RegExp(`'${key.replace(".", "\\.")}'`));
      assert.match(koreanTrading, new RegExp(`'${key.replace(".", "\\.")}'`));
    }
    assert.match(script, /addEventListener\('lqc:languagechange'/);
  });
  it("keeps the primary trade flow simple while preserving optional Router evidence", function () {
    assert.match(html, /id="buyTab"[^>]*>Buy<\/button>/);
    assert.match(html, /id="sellTab"[^>]*>Sell<\/button>/);
    assert.match(html, /<details class="trade-details"/);
    assert.match(html, /id="routeSummary"[^>]*>Best route selected automatically/);
    assert.match(html, /data-i18n="trade\.bestPrice"/);
    assert.match(html, /data-i18n="trade\.nonCustodial"/);
    assert.match(html, /data-i18n="trade\.gasless"/);
    assert.match(html, /<nav class="mobile-nav" aria-label="주요 메뉴">/);
    assert.match(html, /id="tokenSearch"[^>]*data-i18n-placeholder="dialog\.tokenSearch"/);
    assert.match(html, /data-i18n="dialog\.tokenPolicy"/);
    assert.match(script, /ui\.buy\.onclick=ui\.buyTab\.onclick/);
    assert.match(script, /ui\.walletNav\.onclick=chooseWallet/);
    assert.match(script, /\[token\.symbol,token\.name,token\.address\]/);
    assert.match(script, /ui\.tokenSearch\.oninput=/);
    assert.match(script, /function approvedRoutes\(path\)/);
    assert.match(script, /No mutually approved DEX route/);
    assert.match(script, /No approved token pair/);
    assert.doesNotMatch(script, /token-option[^\n]*innerHTML/);
  });

  it("locks one swap submission until its wallet and settlement flow finishes", function () {
    assert.match(script, /swapInFlight=false/);
    assert.match(script, /const disabled=v=>ui\.execute\.disabled=tradeGate\.disabled\(\{requestedDisabled:Boolean\(v\),deployed,account,swapInFlight\}\)/);
    assert.match(script, /function setSwapInFlight\(value\)/);
    assert.match(script, /setAttribute\('aria-busy',String\(swapInFlight\)\)/);
    assert.match(script, /if\(swapInFlight\)return status\(t\('status\.swapBusy'\)\)/);
    assert.match(script, /setSwapInFlight\(true\)/);
    assert.match(script, /function canReleaseSwapLock\(\)\{return !unverifiedTransactionHash&&pendingApprovalState\(\)\.state==='none'&&pendingExecutionState\(\)\.state==='none'&&approvalReservationState\(\)\.state==='none'&&executionReservationState\(\)\.state==='none'\}/);
    assert.match(script, /finally\{if\(canReleaseSwapLock\(\)\)setSwapInFlight\(false\)\}/);
  });

  it("serializes swap submission across browser tabs", function () {
    assert.match(script, /lqc-flow-swap:\$\{cfg\.deploymentFingerprint\|\|'unconfigured'\}/);
    assert.match(script, /async function executeSwap\(\)/);
    assert.match(script, /navigator\.locks\?\.request/);
    assert.match(script, /if\(!navigator\.locks\?\.request\)return status\(t\('status\.lockUnsupported'\),'error'\)/);
    assert.doesNotMatch(script, /if\(!navigator\.locks\?\.request\)return executeSwap\(\)/);
    assert.match(script, /navigator\.locks\.request\(swapLockName,\{mode:'exclusive',ifAvailable:true\}/);
    assert.match(script, /if\(!lock\)return status\(t\('status\.otherTabBusy'\)/);
    assert.match(script, /return executeSwap\(\)/);
    assert.match(script, /window\.addEventListener\('storage',handlePendingExecutionStorage\)/);
    assert.match(script, /recoverySync\.storageAction/);
    assert.match(script, /if\(action==='ignore'\|\|action==='retain'\)return/);
    assert.match(script, /if\(action==='release'\)\{clearTimeout\(pendingRecoveryTimer\);pendingRecoveryAttempts=0;setPendingTradeControls\(null,false\);if\(canReleaseSwapLock\(\)\)setSwapInFlight\(false\);return\}/);
    assert.match(script, /invalidateWalletContext\(\);setPendingTradeControls\(record\.value,true\);setSwapInFlight\(true\);setTimeout\(\(\)=>recoverPendingExecution\(\),0\)/);
    assert.match(recoveryLocale, /'status\.lockUnsupported'/);
    assert.match(recoveryLocale, /탭 간 거래 잠금을 안전하게 보장하지 못합니다/);
  });

  it("freezes every order control while a wallet signature is pending", function () {
    assert.match(script, /const tradeControls=\(\)=>\[ui\.amountIn,ui\.slippage,ui\.tokenInButton,ui\.tokenOutButton,ui\.flip,ui\.max,ui\.buy,ui\.sell,ui\.buyTab,ui\.sellTab,ui\.marketSelector/);
    assert.match(script, /\.amount-presets button,.slippage-option/);
    assert.match(script, /for\(const control of tradeControls\(\)\)control\.disabled=swapInFlight/);
    assert.match(script, /if\(ui\.dialog\.open\)ui\.dialog\.close\(\)/);
    assert.match(script, /if\(ui\.marketDialog\.open\)ui\.marketDialog\.close\(\)/);
  });

  it("invalidates pre-sign execution when the wallet account or chain changes", function () {
    assert.match(script, /walletContextVersion=0/);
    assert.match(script, /function invalidateWalletContext\(\)\{walletContextVersion\+\+\}/);
    assert.match(script, /function snapshotWalletContext\(\)/);
    assert.match(script, /async function assertWalletContext\(context\)/);
    assert.match(script, /WalletContextChangedDuringSwap/);
    assert.match(script, /sendPreparedTransaction\(prepared,walletContext,settlementContext\)/);
    assert.match(script, /accountsChanged[^\n]*invalidateWalletContext\(\)/);
    assert.match(script, /chainChanged[^\n]*invalidateWalletContext\(\)/);
    assert.match(script, /function assertCurrentWalletConnection\(target,version\)/);
    assert.match(script, /WalletConnectionSuperseded/);
    assert.match(script, /walletSessionGuard\.assertCurrent\(target,version\)/);
    assert.match(script, /walletSessionGuard\.begin\(target\)/);
    assert.match(script, /walletSessionGuard\.invalidate\(\)/);
    assert.match(script, /const nextProvider=new ethers\.BrowserProvider\(target\),nextSigner=await nextProvider\.getSigner\(\),nextAccount=await nextSigner\.getAddress\(\);assertCurrentWalletConnection\(target,connectionVersion\);provider=nextProvider;signer=nextSigner;account=nextAccount/);
    assert.match(script, /target\.on\('disconnect'/);
    assert.match(script, /function clearConnectedWallet\(\)/);
    assert.match(script, /provider=null;router=null;executionRouter=null;nativeRouter=null;splitOptimizer=null;autoRouter=null;gasCostOracle=null/);
    assert.match(script, /if\(walletProvider&&target!==walletProvider\)clearConnectedWallet\(\);walletProvider=target/);
    assert.match(script, /if\(session==='disconnected'\)\{clearConnectedWallet\(\);status\(t\(interactive\?'status\.approveConnection':'status\.disconnected'\)\);return\}/);
  });

  it("tracks a successful speed-up replacement and rejects cancelled or malformed replacements", function () {
    assert.match(script, /async function waitForFinalTransactionHash\(tx\)/);
    assert.match(script, /error\?\.code!==['"]TRANSACTION_REPLACED['"]/);
    assert.match(script, /if\(error\.cancelled\)\{const cancellation=new Error\('TransactionReplacementCancelled'\);cancellation\.replacementHash=error\.replacement\?\.hash;throw cancellation\}/);
    assert.match(script, /throw new Error\('InvalidTransactionReplacement'\)/);
    assert.match(script, /return replacement\.hash/);
    assert.match(script, /const finalTransactionHash=await waitForFinalTransactionHash\(tx\)/);
    assert.match(script, /rememberPendingExecution\(finalTransactionHash,plan\.anchorQuote,settlementContext,tx\.hash\)/);
    assert.match(script, /verifySubmittedTransaction\(finalTransactionHash,plan\.anchorQuote,settlementContext\)/);
    assert.match(script, /sdk\.buildExecutionEvidence\(verified\.anchorQuote,verified\.settlement/);
    assert.doesNotMatch(script, /await tx\.wait\(\);status\('거래 포함 완료/);
  });

  it("keeps trading locked when a submitted settlement cannot be verified", function () {
    assert.match(script, /unverifiedTransactionHash=''/);
    assert.match(script, /unverifiedTransactionHash=tx\.hash/);
    assert.match(script, /unverifiedTransactionHash=finalTransactionHash/);
    assert.match(script, /rememberExecutionEvidence\(evidence\);if\(!clearPendingExecution\(finalTransactionHash\)\)throw new Error\('PendingExecutionStorageConflict'\);unverifiedTransactionHash=''/);
    assert.doesNotMatch(script, /Number\(e\?\.receipt\?\.status\)===0\)&&clearPendingExecution\(unverifiedTransactionHash\)\)unverifiedTransactionHash=''/);
    assert.match(script, /if\(unverifiedTransactionHash\)\{const pending=storedPendingExecution\(\);status\(t\('status\.resultUnknown'/);
    assert.match(script, /pending\?\.cancellationHash\|\|unverifiedTransactionHash.*schedulePendingRecoveryRetry\(0\)/);
    assert.match(koreanRuntime, /중복 거래를 보내지 말고 블록 탐색기에서 먼저 확인하세요/);
    assert.match(script, /finally\{if\(canReleaseSwapLock\(\)\)setSwapInFlight\(false\)\}/);
  });

  it("proves durable recovery storage before requesting a swap signature", function () {
    assert.match(script, /recoveryStore\.assertAvailable\(anchorQuote\)/);
    assert.match(script, /function assertPendingExecutionStorageAvailable\(anchorQuote\)/);
    assert.match(recoveryStoreSource, /storage\.setItem\(reservationKey,reservation\)/);
    assert.match(recoveryStoreSource, /storage\.getItem\(reservationKey\)!==reservation/);
    assert.match(recoveryStoreSource, /storage\.removeItem\(reservationKey\)/);
    assert.match(recoveryStoreSource, /throw new Error\('PendingExecutionStorageUnavailable'\)/);
    assert.match(script, /assertPendingExecutionStorageAvailable\(prepared\.binding\)/);
    assert.match(script, /if\(!chartHealth\.transactionMatches\(prepared\.binding,prepared\.request\)\)/);
    assert.match(recoveryLocale, /'error\.storage_unavailable\.message'/);
  });

  it("persists the complete Swap plan before opening the wallet", function () {
    assert.match(script, /executionReservationStore\.reserve\(prepared\.binding,settlementContext\)/);
    assert.match(script, /return Object\.freeze\(\{transaction,reservation\}\)/);
    assert.match(script, /rememberPendingExecution\(tx\.hash,plan\.anchorQuote,settlementContext\);if\(!executionReservationStore\.clear\(submission\.reservation\)\)/);
    assert.match(script, /clearedReservedExecution=recoverableReservedExecution&&executionReservationStore\.clear\(executionReservationRecord\.serialized\)/);
    assert.match(script, /executionReservationRecord\.state!=='none'&&!clearedReservedExecution/);
    assert.match(script, /executionReservationMatchesPending\(executionReservationRecord\.value,pendingRecord\.value\)/);
    assert.match(script, /else if\(storedPendingExecution\(\)\)\{setSwapInFlight\(true\);setTimeout\(\(\)=>recoverPendingExecution\(\),0\)\}/);
    assert.match(script, /approvalReservationState\(\)\.state!=='none'\|\|executionReservationState\(\)\.state!=='none'/);
    assert.match(script, /status\.swapSigningUnknown/);
    assert.match(recoveryLocale, /'status\.swapSigningUnknown'/);
    assert.match(script, /else if\(approvalReservationState\(\)\.state!=='none'\)\{const state=approvalReservationState\(\);status\(t\(state\.state==='valid'\?'status\.approvalSigningUnknown':'status\.approvalReservationInvalid'\),'error'\)\}/);
  });

  it("recovers and verifies a submitted trade after page reload", function () {
    assert.match(script, /function blockRecoveryForSigningReservation\(\)/);
    assert.match(script, /pendingRecoveryActive\|\|!pending\|\|!deployed\|\|blockRecoveryForSigningReservation\(\)/);
    assert.match(script, /catch\{if\(blockRecoveryForSigningReservation\(\)\)return false;try\{if\(!pending\.cancellationHash\)/);
    assert.match(script, /if\(blockRecoveryForSigningReservation\(\)\)throw new Error\('PendingExecutionReservationConflict'\);rememberExecutionEvidence\(evidence\)/);
    assert.match(script, /lqc-flow-pending-execution:/);
    assert.match(script, /function pendingExecutionState\(\)/);
    assert.match(script, /function storedPendingExecution\(\)/);
    assert.match(recoveryStoreSource, /value\.deploymentFingerprint===deploymentFingerprint/);
    assert.match(script, /LQCRecoveryValidator\.create\(\{config:cfg,ethers,chartHealth\}\)/);
    assert.match(recoveryValidatorSource, /request\.chainId!==config\.chainId/);
    assert.match(recoveryValidatorSource, /execution\.minimumAmountOut!==settlement\.minimumAmountOut/);
    assert.match(recoveryValidatorSource, /chartHealth\.transactionMatches\(quote,transaction\)/);
    assert.match(script, /validatePayload:validRecoveryPayload/);
    assert.match(recoveryStoreSource, /value\.version===1/);
    assert.match(recoveryStoreSource, /Number\.isSafeInteger\(submittedAt\)/);
    assert.match(recoveryStoreSource, /submittedAt<=now\(\)\+300000/);
    assert.doesNotMatch(script, /Date\.now\(\)-Number\(value\.submittedAt\)>/);
    assert.match(script, /rememberPendingExecution\(tx\.hash,plan\.anchorQuote,settlementContext\)/);
    assert.match(script, /async function recoverPendingExecution\(\)\{clearTimeout\(pendingRecoveryTimer\);const pending=storedPendingExecution\(\)/);
    assert.match(html, /recovery-backoff\.js[^\n]*app\.js/);
    assert.match(script, /LQCRecoveryBackoff:recoveryBackoff/);
    assert.match(script, /function pendingRecoveryDelay\(\)\{const delay=recoveryBackoff\.delay\(pendingRecoveryAttempts\)/);
    assert.match(script, /function schedulePendingRecoveryRetry\(delay=pendingRecoveryDelay\(\)\)/);
    assert.match(script, /setTimeout\(\(\)=>recoverPendingExecution\(\),delay\)/);
    assert.match(script, /const latest=storedPendingExecution\(\);if\(!latest\)return false/);
    assert.match(script, /schedulePendingRecoveryRetry\(\);return false/);
    assert.match(html, /id="recoveryRetryButton"[^>]*data-i18n="recovery\.retry"[^>]*hidden/);
    assert.match(html, /id="pendingTradeLink"[^>]*target="_blank"[^>]*rel="noopener noreferrer"[^>]*data-i18n="recovery\.explorer"[^>]*hidden/);
    assert.match(script, /function setPendingTradeControls\(pending,visible\)/);
    assert.match(script, /const activeHash=pending\.cancellationHash\|\|pending\.transactionHash/);
    assert.match(script, /cfg\.blockExplorerUrls\[0\][^\n]*activeHash/);
    assert.match(script, /pendingTradeLink\.removeAttribute\('href'\)/);
    assert.match(recoveryLocale, /'recovery\.retry':'제출한 거래 다시 확인'/);
    assert.match(recoveryLocale, /'recovery\.explorer':'제출한 거래 탐색기에서 보기'/);
    assert.match(script, /setPendingTradeControls\(latest,true\);schedulePendingRecoveryRetry\(\)/);
    assert.match(script, /ui\.recoveryRetry\.onclick=\(\)=>\{if\(storedPendingExecution\(\)\)\{pendingRecoveryAttempts=0;schedulePendingRecoveryRetry\(0\)\}\}/);
    assert.match(script, /document\.hidden\|\|navigator\.onLine===false/);
    assert.match(script, /pendingRecoveryActive\|\|!pending\|\|!deployed/);
    assert.match(script, /clearTimeout\(pendingRecoveryTimer\);clearTimeout\(pendingApprovalTimer\);if\(!document\.hidden\)/);
    assert.match(script, /window\.addEventListener\('offline',[^\n]*clearTimeout\(pendingRecoveryTimer\)/);
    assert.match(script, /window\.addEventListener\('online',[^\n]*pendingRecoveryAttempts=0;schedulePendingRecoveryRetry\(0\)/);
    assert.match(script, /if\(!trustedReadProviderIndexes\.length\)await chainHeadWithin\(\)/);
    assert.match(script, /verifySubmittedTransaction\(pending\.transactionHash,pending\.anchorQuote,pending\.settlementContext\)/);
    assert.match(script, /sdk\.buildExecutionEvidence\(verified\.anchorQuote,verified\.settlement/);
    assert.match(script, /else if\(pendingRecord\.state==='valid'\)setTimeout\(\(\)=>recoverPendingExecution\(\),0\)/);
    assert.match(recoveryLocale, /'status\.recovering'/);
    assert.match(recoveryLocale, /'status\.recovered'/);
  });

  it("never silently expires an unresolved submitted trade", function () {
    assert.match(script, /async function recoverPendingExecution\(\)/);
    assert.match(script, /unverifiedTransactionHash=pending\.transactionHash/);
    assert.match(script, /clearPendingExecution\(pending\.transactionHash\)/);
    assert.doesNotMatch(script, /submittedAt\)>[0-9]+/);
  });

  it("fails closed when the saved submitted-trade record is invalid", function () {
    assert.match(recoveryStoreSource, /if\(raw===null\)return Object\.freeze\(\{state:'none'\}\)/);
    assert.match(recoveryStoreSource, /Object\.freeze\(\{state:'invalid'\}\)/);
    assert.match(script, /else if\(pendingRecord\.state==='invalid'\)\{setSwapInFlight\(true\);status\(t\('status\.pendingRecordInvalid'\),'error'\)\}/);
    assert.match(recoveryLocale, /'status\.pendingRecordInvalid'/);
    assert.match(recoveryLocale, /재전송하지 않도록 거래를 잠갔습니다/);
    assert.match(script, /if\(action==='invalid'\)\{invalidateWalletContext\(\);setSwapInFlight\(true\);status\(t\('status\.pendingRecordInvalid'\),'error'\);return\}/);
  });

  it("unlocks a recovered failed trade only after canonical RPC consensus", function () {
    assert.match(script, /async function verifyFailedSubmittedTransaction\(transactionHash,anchorQuote,requiredConfirmations=3\)/);
    assert.match(script, /getTransactionReceipt\(transactionHash\)/);
    assert.match(script, /Number\(receipt\.status\)!==0/);
    assert.match(script, /consensusFailedTransactionReceipt\(observations\.filter\(item=>submittedIndexes\.has\(item\.index\)\),readProviders\.length,transactionHash,requiredConfirmations\)/);
    assert.match(script, /const failure=await verifyFailedSubmittedTransaction\(pending\.transactionHash,pending\.anchorQuote\)/);
    assert.match(script, /function verifyFailedSubmittedTransaction\(transactionHash,anchorQuote/);
    assert.match(script, /getTransaction\(transactionHash\).*getTransactionReceipt\(transactionHash\)/);
    assert.match(script, /consensusSubmittedTransaction\(anchorQuote,observations,readProviders\.length,transactionHash\)/);
    assert.match(script, /if\(failure&&clearPendingExecution\(pending\.transactionHash\)\)\{setPendingTradeControls\(null,false\);pendingRecoveryAttempts=0;unverifiedTransactionHash=''/);
    assert.match(recoveryLocale, /'status\.recoveredFailure'/);
    assert.match(recoveryLocale, /여러 RPC가 \{confirmations\}블록 후 실패를 확인/);
    assert.match(script, /verifyCancelledSubmittedTransaction\(e\.replacementHash,plan\.anchorQuote\)/);
    assert.match(script, /rememberPendingCancellation\(unverifiedTransactionHash,e\.replacementHash\)/);
    assert.match(script, /if\(pending\.cancellationHash\)\{const cancelled=await verifyCancelledSubmittedTransaction\(pending\.cancellationHash,pending\.anchorQuote\)/);
    assert.match(script, /status\.recoveredCancellation/);
    assert.match(script, /consensusCancellationTransaction\(anchorQuote,observations,readProviders\.length,transactionHash\)/);
    assert.match(script, /if\(cancelled&&clearPendingExecution\(unverifiedTransactionHash\)\)/);
    assert.doesNotMatch(script, /e\?\.message==='SubmittedTransactionFailed'\|\|Number\(e\?\.receipt\?\.status\)===0/);
    assert.match(script, /status\(t\('status\.resultUnknown'.*schedulePendingRecoveryRetry\(0\)/);
  });

  it("offers a market-first order and familiar balance percentage controls", function () {
    assert.match(html, /data-i18n="trade\.marketOrder">Market order<\/strong>/);
    for (const percent of [25, 50, 75, 100]) assert.match(html, new RegExp(`data-percent="${percent}"`));
    assert.match(script, /async function applyBalancePercent\(percent\)/);
    assert.match(script, /available\*BigInt\(percent\)\/100n/);
    assert.match(script, /tokenIn\.address==='native'\?ethers\.parseEther\('\.01'\):0n/);
  });

  it("restores market selection and hides incompatible token pairs before quoting", function () {
    assert.match(html, /id="marketSelector"[^>]*aria-haspopup="dialog"/);
    assert.match(html, /id="marketSearch"[^>]*data-i18n-placeholder="dialog\.marketSearch"/);
    assert.match(script, /function pairApproved\(a,b\)/);
    assert.match(script, /function preferredQuote\(asset\)/);
    assert.match(script, /function marketList\(query=''\)/);
    assert.match(script, /ui\.marketNav\.onclick=ui\.marketSelector\.onclick=openMarkets/);
    assert.match(script, /tokens=cfg\.tokens\.filter\(t=>pairApproved\(t,other\)/);
    assert.match(script, /next==='buy'\?\[quoteToken,selectedAsset\]:\[selectedAsset,quoteToken\]/);
    assert.doesNotMatch(script, /market-row[^\n]*innerHTML/);
  });
  it("uses an approved Router quote for spot price and labels historical candles as examples", function () {
    assert.match(html, /id="tickerPrice">—<\/strong>/);
    assert.match(html, /예시 차트 · 실시간 히스토리 연동 전/);
    assert.match(script, /function approvedRoutesFor\(inputToken,outputToken,path\)/);
    assert.match(script, /async function refreshMarketPrice\(\)/);
    assert.match(script, /readOnlyBestQuote\(path\[0\],path\[1\],unit,routes\)/);
    assert.doesNotMatch(html, /\$0\.091138/);
  });

  it("prevents stale asynchronous quotes from changing the current market UI", function () {
    assert.match(script, /function quoteContext\(raw=ui\.amountIn\.value\.trim\(\)\)/);
    assert.match(script, /quoteSessionGuard\.invalidate\(\);clearTimeout\(timer\)/);
    assert.match(script, /ticket=quoteSessionGuard\.begin\(quoteContext\(raw\)\)/);
    assert.match(script, /if\(!quoteSessionGuard\.isCurrent\(ticket,quoteContext\(\)\)\)return/);
  });

  it("offers standard candle intervals with a validated history boundary and safe examples", function () {
    for (const interval of ["1m", "3m", "5m", "15m", "1h", "4h", "1D", "1W", "1M"])
      assert.match(html, new RegExp(`data-timeframe="${interval}"`));
    assert.match(html, /id="chartDataBadge"/);
    assert.match(script, /const chartSeries=/);
    assert.match(script, /function selectTimeframe\(timeframe\)/);
    assert.match(script, /async function loadChartHistory\(\)/);
    assert.match(script, /candleData\.loadEnvelope\(cfg\.candleDataUrl/);
    assert.match(script, /request!==chartRequest/);
    assert.match(script, /chart\(chartSeries\[timeframe\],timeframe\)/);
    assert.match(script, /dataset\.timeframe/);
    assert.match(html, /id="high24hStat"/);
    assert.match(html, /id="low24hStat"/);
    assert.match(html, /id="volume24hStat"/);
    assert.match(script, /function renderMarketStats\(candles,asset,quote\)/);
    assert.match(script, /timeframe:'1h',limit:26/);
    assert.match(html, /id="chartDataBadge"[^>]*aria-live="polite"/);
    assert.match(script, /function scheduleChartRefresh\(delay\)/);
    assert.match(script, /document\.hidden/);
    assert.match(script, /visibilitychange/);
    assert.match(script, /\?60000:15000/);
    assert.match(html, /id="priceAxis"/);
    assert.match(html, /id="currentPriceLine"/);
    assert.match(html, /id="currentPriceLabel"/);
    assert.match(html, /id="ma5Legend"/);
    assert.match(html, /id="timeAxis"/);
    assert.match(script, /function renderLiveChartLabels\(candles,min,max,y,timeframe\)/);
    assert.match(script, /function movingAverage\(items,period\)/);
    assert.match(html, /id="priceArea"/);
    assert.match(html, /id="ma5Line"/);
    assert.match(html, /id="ma10Line"/);
    assert.match(html, /id="ma20Line"/);
    assert.match(html, /id="chartVolumeLabel"/);
    assert.match(script, /function chartPath\(candles,y,step,period=1\)/);
    assert.match(script, /function clearLiveChartLabels\(\)/);
    assert.match(script, /chartVolumeLabel/);
    assert.match(html, /data-indicator="volume"[^>]*aria-pressed="true"/);
    assert.match(html, /data-indicator="ma"[^>]*aria-pressed="true"/);
    assert.match(html, /data-indicator="ema"[^>]*aria-pressed="false"/);
    assert.match(html, /id="ema9Legend"/);
    assert.match(html, /id="ema21Legend"/);
    assert.match(html, /id="ema9Line"/);
    assert.match(html, /id="ema21Line"/);
    assert.match(html, /data-indicator="boll"[^>]*aria-pressed="false"/);
    assert.match(html, /id="bollUpperLegend"/);
    assert.match(html, /id="bollMiddleLine"/);
    assert.match(html, /id="bollLowerLine"/);
    assert.match(html, /data-indicator="sar"[^>]*aria-pressed="false"/);
    assert.match(html, /id="sarLegend"/);
    assert.match(html, /id="sarPoints"/);
    assert.match(html, /data-indicator="macd"[^>]*aria-pressed="false"/);
    assert.match(html, /id="macdIndicator"/);
    assert.match(html, /id="macdLabel"/);
    assert.match(html, /id="macdBars"/);
    assert.match(html, /data-indicator="kdj"[^>]*aria-pressed="false"/);
    assert.match(html, /id="kdjIndicator"/);
    assert.match(html, /id="kdjKLine"/);
    assert.match(html, /id="kdjDLine"/);
    assert.match(html, /id="kdjJLine"/);
    assert.match(script, /function toggleIndicator\(button\)/);
    assert.match(script, /volumeIndicator/);
    assert.match(script, /ma\$\{period\}Line/);
    assert.match(script, /function exponentialMovingAverage\(items,period\)/);
    assert.match(script, /function emaPath\(candles,y,step,period\)/);
    assert.match(script, /ema\$\{period\}Line/);
    assert.match(script, /function bollingerBands\(items,period=20,deviations=2\)/);
    assert.match(script, /function bollingerPath\(bands,key,y,step\)/);
    assert.match(script, /boll\$\{band\}Line/);
    assert.match(script, /function parabolicSar\(items,step=\.02,maximum=\.2\)/);
    assert.match(script, /function renderSar\(points,y,step,ns\)/);
    assert.match(script, /sarPoints/);
    assert.match(script, /function emaSequence\(values,period\)/);
    assert.match(script, /function macdSeries\(items,fastPeriod=12,slowPeriod=26,signalPeriod=9\)/);
    assert.match(script, /function renderMacd\(candles\)/);
    assert.match(script, /macdIndicator/);
    assert.match(script, /function kdjSeries\(items,period=9\)/);
    assert.match(script, /function kdjPath\(series,key\)/);
    assert.match(script, /function renderKdj\(candles\)/);
    assert.match(script, /kdjIndicator/);
    assert.match(script, /lqc-flow-chart-preferences/);
    assert.match(script, /function storedChartPreferences\(\)/);
    assert.match(script, /function saveChartPreferences\(\)/);
    assert.match(script, /function restoreChartPreferences\(\)/);
    assert.match(script, /function setIndicatorVisibility\(name,visible\)/);
    assert.match(script, /lowerIndicators\.filter\(other=>other!==name\)/);
    assert.match(script, /supportedTimeframes\.includes\(value\.timeframe\)/);
    assert.match(html, /id="lastTradeLink"/);
    assert.match(html, /id="lastSettledOutput"/);
    assert.match(html, /id="lastEvidenceHash"/);
    assert.match(html, /id="tradeHistoryButton"/);
    assert.match(html, /id="tradeHistoryDialog"/);
    assert.match(html, /id="tradeHistoryList"/);
    assert.match(html, /id="tradeHistoryCount"/);
    assert.match(script, /function storedExecutionEvidence/);
    assert.match(script, /sdk\.verifyExecutionEvidence/);
    assert.match(script, /function rememberExecutionEvidence/);
    assert.match(script, /sdk\.buildExecutionEvidence\(verified\.anchorQuote,verified\.settlement,cfg\.deploymentFingerprint,Date\.now\(\),ethers\)/);
    assert.match(script, /\.slice\(0,10\)/);
    assert.match(script, /function downloadExecutionEvidence/);
    assert.match(script, /new Blob\(\[JSON\.stringify\(evidence,null,2\)\]/);
    assert.match(script, /URL\.createObjectURL\(blob\)/);
    assert.match(script, /URL\.revokeObjectURL\(url\)/);
    assert.match(script, /function renderExecutionHistory/);
    assert.match(script, /tradeHistoryList\.replaceChildren/);
    assert.match(script, /download\.onclick=\(\)=>downloadExecutionEvidence\(evidence\)/);
    assert.doesNotMatch(script, /trade-history-item[^\n]*innerHTML/);
  });

  it("shows candle connection health and retries failures with bounded backoff", function () {
    assert.match(script, /function chartRetryDelay\(\)/);
    assert.match(script, /Math\.min\(60000,3000\*/);
    assert.match(script, /chartHealth\.classify\(\{consecutiveFailures:chartFailureCount\}\)/);
    assert.match(script, /window\.addEventListener\('offline'/);
    assert.match(script, /window\.addEventListener\('online'/);
    assert.match(script, /if\(verifiedChartKey===chartKey\)chartState/);
    assert.match(script, /performance\.now\(\)-startedAt/);
    assert.match(script, /candleData\.loadEnvelope/);
    assert.match(script, /ageSeconds=Math\.max/);
    assert.match(script, /lastHealthyByChart\.set\(chartKey,updatedAt\)/);
    assert.match(script, /function chainHeadWithin\(timeoutMs=2500\)/);
    assert.match(script, /cfg\.rpcUrls\.map\(url=>new ethers\.JsonRpcProvider/);
    assert.match(script, /chartHealth\.consensusHead\(heads,readProviders\.length\)/);
    assert.match(script, /getBlock\(headConsensus\.head\)/);
    assert.match(script, /chartHealth\.consensusHash\(hashes,readProviders\.length\)/);
    assert.match(script, /chartHealth\.rankCanonicalSources/);
    assert.match(script, /chartHealth\.consensusQuote\(observations,readProviders\.length\)/);
    assert.match(script, /blockTag:trustedReadBlock/);
    assert.match(script, /Browser RPC quote consensus unavailable/);
    assert.match(script, /chartHealth\.bindQuote\(consensus,trustedReadBlock,trustedReadHash,now\)/);
    assert.match(script, /function verifyQuoteBeforeSigning/);
    assert.match(script, /chartHealth\.quoteBindingMatches/);
    assert.match(script, /await verifyQuoteBeforeSigning\(plan\.anchorQuote/);
    assert.match(script, /chartHealth\.bindQuoteRequest\(grossSingle\.best,quoteRequest/);
    assert.match(script, /chartHealth\.quoteRequestMatches\(bound,quoteRequest/);
    assert.match(script, /QuoteContextChangedBeforeSigning/);
    assert.match(script, /chartHealth\.bindExecutionPlan\(anchorQuote,request\)/);
    assert.match(script, /chartHealth\.executionPlanMatches\(plan\.anchorQuote,execution\)/);
    assert.match(script, /ExecutionPlanChangedBeforeSigning/);
    assert.match(script, /method\.populateTransaction\(\.\.\.args\)/);
    assert.match(script, /function simulateSwapTransaction/);
    assert.match(script, /blockTag:anchorQuote\.blockNumber/);
    assert.match(script, /chartHealth\.consensusSimulation\(observations,readProviders\.length,gasCeiling\)/);
    assert.match(script, /TransactionSimulationConsensusFailed/);
    assert.match(script, /gasLimit:gasProbe\.gasLimit/);
    assert.match(script, /finalSimulation=await simulateSwapTransaction\(anchorQuote,request,gasCeiling\)/);
    assert.match(script, /FinalTransactionGasLimitInsufficient/);
    assert.match(script, /function fixedFeeFields/);
    assert.match(script, /provider\.getTransactionCount\(account,'pending'\)/);
    assert.match(script, /provider\.getFeeData\(\)/);
    assert.match(script, /function consensusFeeFields/);
    assert.match(script, /readProviders\[index\]\.getFeeData\(\)/);
    assert.match(script, /chartHealth\.consensusFeeData\(observations,readProviders\.length\)/);
    assert.match(script, /TransactionFeeConsensusFailed/);
    assert.match(script, /maximumNetworkFee/);
    assert.match(script, /t\('quote\.maximumGas'/);
    assert.match(koreanTrading, /BNB · RPC 합의/);
    assert.match(script, /function sendPreparedTransaction/);
    assert.match(script, /WalletNonceChangedBeforeSigning/);
    assert.match(script, /chartHealth\.bindTransaction\(anchorQuote,request\)/);
    assert.match(script, /chartHealth\.transactionMatches\(binding,request\)/);
    assert.match(script, /signer\.sendTransaction\(prepared\.request\)/);
    assert.match(script, /submission=await sendPreparedTransaction\(prepared,walletContext,settlementContext\)/);
    assert.match(script, /function verifySubmittedTransaction/);
    assert.match(script, /getTransaction\(transactionHash\)/);
    assert.match(script, /consensusSubmittedTransaction\(anchorQuote,observations,readProviders\.length,transactionHash\)/);
    assert.match(script, /submittedIndexes\.has\(item\.index\)/);
    assert.match(script, /waitForTransaction\(transactionHash,requiredConfirmations,90000\)/);
    assert.match(script, /chartHealth\.consensusTransactionReceipt\(submittedObservations,readProviders\.length,transactionHash,requiredConfirmations\)/);
    assert.match(script, /TransactionConsensusFailed/);
    assert.match(script, /chartHealth\.decodeSettlementOutput\(receipt,context\)/);
    assert.match(script, /chartHealth\.consensusSettlementOutput/);
    assert.match(script, /kind:'native-out'/);
    assert.match(script, /kind:'erc20'/);
    assert.match(script, /status\(t\('status\.confirming'\)\)/);
    assert.match(koreanRuntime, /수령량과 다중 RPC 확정성을 확인합니다/);
    assert.match(script, /settlement\.confirmations/);
    assert.match(script, /'market\.rpcPending'/);
    assert.match(koreanTrading, /RPC 합의 대기/);
    assert.match(script, /chartHealth\.restoreSourceHealth\(JSON\.parse\(localStorage\.getItem\(rpcHealthMemoryKey\)/);
    assert.match(script, /chartHealth\.sourceHealthSnapshot\(rpcSourceHealth,cfg\.deploymentFingerprint,now\)/);
    assert.match(script, /rpcSourceHealth\[index\]=chartHealth\.sourceHealth/);
    assert.match(script, /quarantinedUntil<=now/);
    assert.match(script, /chartHealth\.chainSync\(primary\.finalizedBlock,consensus\.head,cfg\.candleFinalityBlocks\)/);
    assert.match(script, /sync\.lagBlocks/);
    assert.match(script, /RPC \$\{consensus\.healthySources\}\/\$\{consensus\.configuredSources\}/);
    assert.match(script, /다중 RPC 블록 해시 합의 실패/);
    assert.match(script, /격리 \$\{consensus\.quarantinedSources\}/);
    assert.match(script, /정상 갱신 \$\{lastHealthyByChart\.get\(chartKey\)\|\|'기록 없음'\}/);
    assert.match(html, /chart-health\.js/);
    assert.match(styles, /data-state="interrupted"/);
  });
});
