import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const html = fs.readFileSync(path.join(root, "app/index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "app/app.js"), "utf8");
const styles = fs.readFileSync(path.join(root, "app/styles.css"), "utf8");

describe("LQC simple trading UI", function () {
  it("keeps the primary trade flow simple while preserving optional Router evidence", function () {
    assert.match(html, /id="buyTab"[^>]*>Buy<\/button>/);
    assert.match(html, /id="sellTab"[^>]*>Sell<\/button>/);
    assert.match(html, /<details class="trade-details"/);
    assert.match(html, /id="routeSummary">최적 경로 자동 선택/);
    assert.match(html, /최적가 자동/);
    assert.match(html, /비수탁 거래/);
    assert.match(html, /Gasless 조건 확인/);
    assert.match(html, /<nav class="mobile-nav" aria-label="주요 메뉴">/);
    assert.match(html, /id="tokenSearch"[^>]*placeholder="이름, 심볼 또는 컨트랙트 주소"/);
    assert.match(html, /Router 위험 정책에 등록된 토큰만 표시/);
    assert.match(script, /ui\.buy\.onclick=ui\.buyTab\.onclick/);
    assert.match(script, /ui\.walletNav\.onclick=chooseWallet/);
    assert.match(script, /\[t\.symbol,t\.name,t\.address\]/);
    assert.match(script, /ui\.tokenSearch\.oninput=/);
    assert.match(script, /function approvedRoutes\(path\)/);
    assert.match(script, /No mutually approved DEX route/);
    assert.match(script, /No approved token pair/);
    assert.doesNotMatch(script, /token-option[^\n]*innerHTML/);
  });

  it("locks one swap submission until its wallet and settlement flow finishes", function () {
    assert.match(script, /swapInFlight=false/);
    assert.match(script, /const disabled=v=>ui\.execute\.disabled=Boolean\(v\)\|\|swapInFlight/);
    assert.match(script, /function setSwapInFlight\(value\)/);
    assert.match(script, /setAttribute\('aria-busy',String\(swapInFlight\)\)/);
    assert.match(script, /if\(swapInFlight\)return status\('이미 거래를 처리하고 있습니다/);
    assert.match(script, /setSwapInFlight\(true\)/);
    assert.match(script, /finally\{setSwapInFlight\(false\)\}/);
  });

  it("invalidates pre-sign execution when the wallet account or chain changes", function () {
    assert.match(script, /walletContextVersion=0/);
    assert.match(script, /function invalidateWalletContext\(\)\{walletContextVersion\+\+\}/);
    assert.match(script, /function snapshotWalletContext\(\)/);
    assert.match(script, /async function assertWalletContext\(context\)/);
    assert.match(script, /WalletContextChangedDuringSwap/);
    assert.match(script, /sendPreparedTransaction\(prepared,walletContext\)/);
    assert.match(script, /accountsChanged[^\n]*invalidateWalletContext\(\)/);
    assert.match(script, /chainChanged[^\n]*invalidateWalletContext\(\)/);
  });

  it("tracks a successful speed-up replacement and rejects cancelled or malformed replacements", function () {
    assert.match(script, /async function waitForFinalTransactionHash\(tx\)/);
    assert.match(script, /error\?\.code!==['"]TRANSACTION_REPLACED['"]/);
    assert.match(script, /if\(error\.cancelled\)throw new Error\('TransactionReplacementCancelled'\)/);
    assert.match(script, /throw new Error\('InvalidTransactionReplacement'\)/);
    assert.match(script, /return replacement\.hash/);
    assert.match(script, /const finalTransactionHash=await waitForFinalTransactionHash\(tx\)/);
    assert.match(script, /verifySubmittedTransaction\(finalTransactionHash,settlementContext\)/);
    assert.doesNotMatch(script, /await tx\.wait\(\);status\('거래 포함 완료/);
  });

  it("offers a market-first order and familiar balance percentage controls", function () {
    assert.match(html, /<strong>시장가<\/strong>/);
    for (const percent of [25, 50, 75, 100]) assert.match(html, new RegExp(`data-percent="${percent}"`));
    assert.match(script, /async function applyBalancePercent\(percent\)/);
    assert.match(script, /available\*BigInt\(percent\)\/100n/);
    assert.match(script, /tokenIn\.address==='native'\?ethers\.parseEther\('\.01'\):0n/);
  });

  it("restores market selection and hides incompatible token pairs before quoting", function () {
    assert.match(html, /id="marketSelector"[^>]*aria-haspopup="dialog"/);
    assert.match(html, /id="marketSearch"[^>]*placeholder="토큰 검색"/);
    assert.match(script, /function pairApproved\(a,b\)/);
    assert.match(script, /function preferredQuote\(asset\)/);
    assert.match(script, /function marketList\(query=''\)/);
    assert.match(script, /ui\.marketNav\.onclick=ui\.marketSelector\.onclick=openMarkets/);
    assert.match(script, /tokens=cfg\.tokens\.filter\(t=>pairApproved\(t,other\)/);
    assert.match(script, /next==='buy'\?\[quoteToken,selectedAsset\]:\[selectedAsset,quoteToken\]/);
    assert.doesNotMatch(script, /market-row[^\n]*innerHTML/);
  });
  it("uses an approved Router quote for spot price and labels historical candles as examples", function () {
    assert.match(html, /id="tickerPrice">—<\/strong>/);
    assert.match(html, /예시 차트 · 실시간 히스토리 연동 전/);
    assert.match(script, /function approvedRoutesFor\(inputToken,outputToken,path\)/);
    assert.match(script, /async function refreshMarketPrice\(\)/);
    assert.match(script, /readOnlyBestQuote\(path\[0\],path\[1\],unit,routes\)/);
    assert.doesNotMatch(html, /\$0\.091138/);
  });

  it("offers standard candle intervals with a validated history boundary and safe examples", function () {
    for (const interval of ["1m", "3m", "5m", "15m", "1h", "4h", "1D", "1W", "1M"])
      assert.match(html, new RegExp(`data-timeframe="${interval}"`));
    assert.match(html, /id="chartDataBadge"/);
    assert.match(script, /const chartSeries=/);
    assert.match(script, /function selectTimeframe\(timeframe\)/);
    assert.match(script, /async function loadChartHistory\(\)/);
    assert.match(script, /candleData\.loadEnvelope\(cfg\.candleDataUrl/);
    assert.match(script, /request!==chartRequest/);
    assert.match(script, /chart\(chartSeries\[timeframe\],timeframe\)/);
    assert.match(script, /dataset\.timeframe/);
    assert.match(html, /id="high24hStat"/);
    assert.match(html, /id="low24hStat"/);
    assert.match(html, /id="volume24hStat"/);
    assert.match(script, /function renderMarketStats\(candles,asset,quote\)/);
    assert.match(script, /timeframe:'1h',limit:26/);
    assert.match(html, /id="chartDataBadge"[^>]*aria-live="polite"/);
    assert.match(script, /function scheduleChartRefresh\(delay\)/);
    assert.match(script, /document\.hidden/);
    assert.match(script, /visibilitychange/);
    assert.match(script, /\?60000:15000/);
    assert.match(html, /id="priceAxis"/);
    assert.match(html, /id="currentPriceLine"/);
    assert.match(html, /id="currentPriceLabel"/);
    assert.match(html, /id="ma5Legend"/);
    assert.match(html, /id="timeAxis"/);
    assert.match(script, /function renderLiveChartLabels\(candles,min,max,y,timeframe\)/);
    assert.match(script, /function movingAverage\(items,period\)/);
    assert.match(html, /id="priceArea"/);
    assert.match(html, /id="ma5Line"/);
    assert.match(html, /id="ma10Line"/);
    assert.match(html, /id="ma20Line"/);
    assert.match(html, /id="chartVolumeLabel"/);
    assert.match(script, /function chartPath\(candles,y,step,period=1\)/);
    assert.match(script, /function clearLiveChartLabels\(\)/);
    assert.match(script, /chartVolumeLabel/);
    assert.match(html, /data-indicator="volume"[^>]*aria-pressed="true"/);
    assert.match(html, /data-indicator="ma"[^>]*aria-pressed="true"/);
    assert.match(html, /data-indicator="ema"[^>]*aria-pressed="false"/);
    assert.match(html, /id="ema9Legend"/);
    assert.match(html, /id="ema21Legend"/);
    assert.match(html, /id="ema9Line"/);
    assert.match(html, /id="ema21Line"/);
    assert.match(html, /data-indicator="boll"[^>]*aria-pressed="false"/);
    assert.match(html, /id="bollUpperLegend"/);
    assert.match(html, /id="bollMiddleLine"/);
    assert.match(html, /id="bollLowerLine"/);
    assert.match(html, /data-indicator="sar"[^>]*aria-pressed="false"/);
    assert.match(html, /id="sarLegend"/);
    assert.match(html, /id="sarPoints"/);
    assert.match(html, /data-indicator="macd"[^>]*aria-pressed="false"/);
    assert.match(html, /id="macdIndicator"/);
    assert.match(html, /id="macdLabel"/);
    assert.match(html, /id="macdBars"/);
    assert.match(html, /data-indicator="kdj"[^>]*aria-pressed="false"/);
    assert.match(html, /id="kdjIndicator"/);
    assert.match(html, /id="kdjKLine"/);
    assert.match(html, /id="kdjDLine"/);
    assert.match(html, /id="kdjJLine"/);
    assert.match(script, /function toggleIndicator\(button\)/);
    assert.match(script, /volumeIndicator/);
    assert.match(script, /ma\$\{period\}Line/);
    assert.match(script, /function exponentialMovingAverage\(items,period\)/);
    assert.match(script, /function emaPath\(candles,y,step,period\)/);
    assert.match(script, /ema\$\{period\}Line/);
    assert.match(script, /function bollingerBands\(items,period=20,deviations=2\)/);
    assert.match(script, /function bollingerPath\(bands,key,y,step\)/);
    assert.match(script, /boll\$\{band\}Line/);
    assert.match(script, /function parabolicSar\(items,step=\.02,maximum=\.2\)/);
    assert.match(script, /function renderSar\(points,y,step,ns\)/);
    assert.match(script, /sarPoints/);
    assert.match(script, /function emaSequence\(values,period\)/);
    assert.match(script, /function macdSeries\(items,fastPeriod=12,slowPeriod=26,signalPeriod=9\)/);
    assert.match(script, /function renderMacd\(candles\)/);
    assert.match(script, /macdIndicator/);
    assert.match(script, /function kdjSeries\(items,period=9\)/);
    assert.match(script, /function kdjPath\(series,key\)/);
    assert.match(script, /function renderKdj\(candles\)/);
    assert.match(script, /kdjIndicator/);
    assert.match(script, /lqc-flow-chart-preferences/);
    assert.match(script, /function storedChartPreferences\(\)/);
    assert.match(script, /function saveChartPreferences\(\)/);
    assert.match(script, /function restoreChartPreferences\(\)/);
    assert.match(script, /function setIndicatorVisibility\(name,visible\)/);
    assert.match(script, /lowerIndicators\.filter\(other=>other!==name\)/);
    assert.match(script, /supportedTimeframes\.includes\(value\.timeframe\)/);
    assert.match(html, /id="lastTradeLink"/);
    assert.match(html, /id="lastSettledOutput"/);
    assert.match(html, /id="lastEvidenceHash"/);
    assert.match(html, /id="tradeHistoryButton"/);
    assert.match(html, /id="tradeHistoryDialog"/);
    assert.match(html, /id="tradeHistoryList"/);
    assert.match(html, /id="tradeHistoryCount"/);
    assert.match(script, /function storedExecutionEvidence/);
    assert.match(script, /sdk\.verifyExecutionEvidence/);
    assert.match(script, /function rememberExecutionEvidence/);
    assert.match(script, /sdk\.buildExecutionEvidence\(plan\.anchorQuote,settlement,cfg\.deploymentFingerprint,Date\.now\(\),ethers\)/);
    assert.match(script, /\.slice\(0,10\)/);
    assert.match(script, /function downloadExecutionEvidence/);
    assert.match(script, /new Blob\(\[JSON\.stringify\(evidence,null,2\)\]/);
    assert.match(script, /URL\.createObjectURL\(blob\)/);
    assert.match(script, /URL\.revokeObjectURL\(url\)/);
    assert.match(script, /function renderExecutionHistory/);
    assert.match(script, /tradeHistoryList\.replaceChildren/);
    assert.match(script, /download\.onclick=\(\)=>downloadExecutionEvidence\(evidence\)/);
    assert.doesNotMatch(script, /trade-history-item[^\n]*innerHTML/);
  });

  it("shows candle connection health and retries failures with bounded backoff", function () {
    assert.match(script, /function chartRetryDelay\(\)/);
    assert.match(script, /Math\.min\(60000,3000\*/);
    assert.match(script, /chartHealth\.classify\(\{consecutiveFailures:chartFailureCount\}\)/);
    assert.match(script, /window\.addEventListener\('offline'/);
    assert.match(script, /window\.addEventListener\('online'/);
    assert.match(script, /if\(verifiedChartKey===chartKey\)chartState/);
    assert.match(script, /performance\.now\(\)-startedAt/);
    assert.match(script, /candleData\.loadEnvelope/);
    assert.match(script, /ageSeconds=Math\.max/);
    assert.match(script, /lastHealthyByChart\.set\(chartKey,updatedAt\)/);
    assert.match(script, /function chainHeadWithin\(timeoutMs=2500\)/);
    assert.match(script, /cfg\.rpcUrls\.map\(url=>new ethers\.JsonRpcProvider/);
    assert.match(script, /chartHealth\.consensusHead\(heads,readProviders\.length\)/);
    assert.match(script, /getBlock\(headConsensus\.head\)/);
    assert.match(script, /chartHealth\.consensusHash\(hashes,readProviders\.length\)/);
    assert.match(script, /chartHealth\.rankCanonicalSources/);
    assert.match(script, /chartHealth\.consensusQuote\(observations,readProviders\.length\)/);
    assert.match(script, /blockTag:trustedReadBlock/);
    assert.match(script, /Browser RPC quote consensus unavailable/);
    assert.match(script, /chartHealth\.bindQuote\(consensus,trustedReadBlock,trustedReadHash,now\)/);
    assert.match(script, /function verifyQuoteBeforeSigning/);
    assert.match(script, /chartHealth\.quoteBindingMatches/);
    assert.match(script, /await verifyQuoteBeforeSigning\(plan\.anchorQuote/);
    assert.match(script, /chartHealth\.bindQuoteRequest\(grossSingle\.best,quoteRequest/);
    assert.match(script, /chartHealth\.quoteRequestMatches\(bound,quoteRequest/);
    assert.match(script, /QuoteContextChangedBeforeSigning/);
    assert.match(script, /chartHealth\.bindExecutionPlan\(anchorQuote,request\)/);
    assert.match(script, /chartHealth\.executionPlanMatches\(plan\.anchorQuote,execution\)/);
    assert.match(script, /ExecutionPlanChangedBeforeSigning/);
    assert.match(script, /method\.populateTransaction\(\.\.\.args\)/);
    assert.match(script, /function simulateSwapTransaction/);
    assert.match(script, /blockTag:anchorQuote\.blockNumber/);
    assert.match(script, /chartHealth\.consensusSimulation\(observations,readProviders\.length,gasCeiling\)/);
    assert.match(script, /TransactionSimulationConsensusFailed/);
    assert.match(script, /gasLimit:simulation\.gasLimit/);
    assert.match(script, /function fixedFeeFields/);
    assert.match(script, /provider\.getTransactionCount\(account,'pending'\)/);
    assert.match(script, /provider\.getFeeData\(\)/);
    assert.match(script, /function consensusFeeFields/);
    assert.match(script, /readProviders\[index\]\.getFeeData\(\)/);
    assert.match(script, /chartHealth\.consensusFeeData\(observations,readProviders\.length\)/);
    assert.match(script, /TransactionFeeConsensusFailed/);
    assert.match(script, /maximumNetworkFee/);
    assert.match(script, /BNB · RPC 합의/);
    assert.match(script, /function sendPreparedTransaction/);
    assert.match(script, /WalletNonceChangedBeforeSigning/);
    assert.match(script, /chartHealth\.bindTransaction\(anchorQuote,request\)/);
    assert.match(script, /chartHealth\.transactionMatches\(binding,request\)/);
    assert.match(script, /signer\.sendTransaction\(prepared\.request\)/);
    assert.match(script, /tx=await sendPreparedTransaction\(prepared,walletContext\)/);
    assert.match(script, /function verifySubmittedTransaction/);
    assert.match(script, /waitForTransaction\(transactionHash,requiredConfirmations,90000\)/);
    assert.match(script, /chartHealth\.consensusTransactionReceipt\(observations,readProviders\.length,transactionHash,requiredConfirmations\)/);
    assert.match(script, /TransactionReceiptConsensusFailed/);
    assert.match(script, /chartHealth\.decodeSettlementOutput\(receipt,context\)/);
    assert.match(script, /chartHealth\.consensusSettlementOutput/);
    assert.match(script, /kind:'native-out'/);
    assert.match(script, /kind:'erc20'/);
    assert.match(script, /수령량과 다중 RPC 확정성을 확인합니다/);
    assert.match(script, /settlement\.confirmations/);
    assert.match(script, /RPC 합의 대기/);
    assert.match(script, /chartHealth\.restoreSourceHealth\(JSON\.parse\(localStorage\.getItem\(rpcHealthMemoryKey\)/);
    assert.match(script, /chartHealth\.sourceHealthSnapshot\(rpcSourceHealth,cfg\.deploymentFingerprint,now\)/);
    assert.match(script, /rpcSourceHealth\[index\]=chartHealth\.sourceHealth/);
    assert.match(script, /quarantinedUntil<=now/);
    assert.match(script, /chartHealth\.chainSync\(primary\.finalizedBlock,consensus\.head,cfg\.candleFinalityBlocks\)/);
    assert.match(script, /sync\.lagBlocks/);
    assert.match(script, /RPC \$\{consensus\.healthySources\}\/\$\{consensus\.configuredSources\}/);
    assert.match(script, /다중 RPC 블록 해시 합의 실패/);
    assert.match(script, /격리 \$\{consensus\.quarantinedSources\}/);
    assert.match(script, /정상 갱신 \$\{lastHealthyByChart\.get\(chartKey\)\|\|'기록 없음'\}/);
    assert.match(html, /chart-health\.js/);
    assert.match(styles, /data-state="interrupted"/);
  });
});
