import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),source=fs.readFileSync(path.join(root,'app/chart-health.js'),'utf8'),context={globalThis:null};context.globalThis=context;vm.runInNewContext(source,context);const health=context.LQCChartHealth;

describe('LQC live chart health classification',function(){
  it('marks signed responses at or below 1.5 seconds healthy',function(){assert.equal(health.classify({latencyMs:1500}).level,'healthy')});
  it('marks slow, stale, and initially failed responses delayed',function(){assert.equal(health.classify({latencyMs:1501}).level,'delayed');assert.equal(health.classify({ageSeconds:16}).level,'delayed');assert.equal(health.classify({consecutiveFailures:2}).level,'delayed')});
  it('marks offline or three consecutive failures interrupted',function(){assert.equal(health.classify({online:false}).level,'interrupted');assert.equal(health.classify({consecutiveFailures:3}).level,'interrupted')});
  it('rejects malformed measurements',function(){assert.throws(()=>health.classify({latencyMs:-1}),/invalid/);assert.throws(()=>health.classify({ageSeconds:-1}),/invalid/);assert.throws(()=>health.classify({consecutiveFailures:1.5}),/invalid/) });
  it('classifies finalized-block distance from the BSC testnet head',function(){assert.equal(health.chainSync(988,1000).level,'synced');assert.equal(health.chainSync(980,1000).level,'catching-up');assert.equal(health.chainSync(900,1000).level,'stale')});
  it('refuses to trust a browser RPC behind the signed finalized block',function(){assert.equal(health.chainSync(1001,1000).level,'unverified');assert.throws(()=>health.chainSync(-1,1000),/invalid/)});
  it('selects a conservative majority head while isolating an outlier',function(){const result=health.consensusHead([1002,1000,900],3);assert.equal(result.head,1000);assert.equal(result.healthySources,2);assert.equal(result.independent,true)});
  it('fails closed without a configured-source majority',function(){assert.equal(health.consensusHead([1000],3),null);assert.equal(health.consensusHead([1000,1010],2),null);assert.equal(health.consensusHead([1000],1).head,1000);assert.throws(()=>health.consensusHead([-1],1),/invalid/)});
  it('requires a configured-source majority for one canonical block hash',function(){const a=`0x${'ab'.repeat(32)}`,b=`0x${'cd'.repeat(32)}`,result=health.consensusHash([a,a.toUpperCase().replace('0X','0x'),b],3);assert.equal(result.blockHash,a);assert.equal(result.healthySources,2);assert.equal(result.independent,true)});
  it('fails closed for conflicting or malformed block hashes',function(){const a=`0x${'ab'.repeat(32)}`,b=`0x${'cd'.repeat(32)}`;assert.equal(health.consensusHash([a,b],3),null);assert.equal(health.consensusHash([a],1).blockHash,a);assert.throws(()=>health.consensusHash(['0x1234'],1),/invalid/)});
  it('quarantines a repeatedly unhealthy RPC and resets a recovered source',function(){let state={failures:0,quarantinedUntil:0};state=health.sourceHealth(state,false,1000);state=health.sourceHealth(state,false,1001);assert.equal(state.failures,2);state=health.sourceHealth(state,false,1002);assert.equal(state.quarantinedUntil,61002);assert.equal(state.failures,0);assert.equal(health.sourceHealth(state,false,2000).quarantinedUntil,61002);assert.equal(health.sourceHealth(state,true,2000).quarantinedUntil,0)});
  it('requires a fresh failure sequence after quarantine expires',function(){const state=health.sourceHealth({failures:0,quarantinedUntil:2000},false,2001);assert.equal(state.failures,1);assert.equal(state.quarantinedUntil,0);assert.throws(()=>health.sourceHealth({failures:-1,quarantinedUntil:0},false),/invalid/)});
  it('restores only fresh RPC health bound to the exact deployment',function(){const fingerprint=`0x${'12'.repeat(32)}`,snapshot=health.sourceHealthSnapshot([{failures:2,quarantinedUntil:0},{failures:0,quarantinedUntil:61000}],fingerprint,1000),restored=health.restoreSourceHealth(snapshot,fingerprint,2,2000);assert.equal(restored[0].failures,2);assert.equal(restored[1].quarantinedUntil,61000);assert.equal(health.restoreSourceHealth(snapshot,`0x${'34'.repeat(32)}`,2,2000),null);assert.equal(health.restoreSourceHealth(snapshot,fingerprint,2,400001),null)});
  it('discards expired quarantine and rejects forged long isolation',function(){const fingerprint=`0x${'12'.repeat(32)}`,snapshot=health.sourceHealthSnapshot([{failures:0,quarantinedUntil:2000}],fingerprint,1000);assert.equal(health.restoreSourceHealth(snapshot,fingerprint,1,2001)[0].quarantinedUntil,0);assert.equal(health.restoreSourceHealth({...snapshot,sources:[{failures:0,quarantinedUntil:70000}]},fingerprint,1,1001),null);assert.throws(()=>health.sourceHealthSnapshot([{failures:3,quarantinedUntil:0}],fingerprint,1000),/invalid/)});
  it('ranks only canonical RPC sources by measured latency',function(){const hash=`0x${'ab'.repeat(32)}`,other=`0x${'cd'.repeat(32)}`,ranked=health.rankCanonicalSources([{index:0,head:1001,latencyMs:90,blockHash:hash},{index:1,head:1000,latencyMs:20,blockHash:hash},{index:2,head:1000,latencyMs:1,blockHash:other}],1000,hash);assert.deepEqual([...ranked],[1,0])});
  it('rejects malformed or duplicate RPC ranking observations',function(){const hash=`0x${'ab'.repeat(32)}`;assert.deepEqual([...health.rankCanonicalSources([],1000,hash)],[]);assert.throws(()=>health.rankCanonicalSources([{index:0,head:1000,latencyMs:1,blockHash:hash},{index:0,head:1000,latencyMs:2,blockHash:hash}],1000,hash),/invalid/)});
});
