import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { createDemoLiquidationController } from '../app/futures/liquidation-controller.js';

function fixture({ liquidatable = false, settlementError = null, mutateBeforeRemove = false, rollbackError = null, badDebt = 0, sameSideCross = false } = {}) {
  const crossLong = Object.freeze({ symbol: 'BTCUSDT', side: 'LONG', marginMode: 'CROSS', quantity: 1 });
  const crossShort = Object.freeze({ symbol: 'SOLUSDT', side: sameSideCross ? 'LONG' : 'SHORT', marginMode: 'CROSS', quantity: 3 });
  const isolated = Object.freeze({ symbol: 'ETHUSDT', side: 'SHORT', marginMode: 'ISOLATED', quantity: 2 });
  const positions = [crossLong, crossShort, isolated];
  let settlements = 0, rollbacks = 0, accountState = Object.freeze({ availableBalance: 100, isolatedReserved: 0, crossReserved: 50, cumulativeFunding: 0, cumulativeTradingFees: 0 });
  const expectedCross = [crossLong, crossShort];
  const account = {
    health(received) { assert.deepEqual(received, expectedCross); return Object.freeze({ liquidatable, equity: badDebt > 0 ? -badDebt : (liquidatable ? 40 : 1000), maintenanceMargin: 50, positions: [] }); },
    previewCrossLiquidation(received) { assert.deepEqual(received, expectedCross); if (!liquidatable) throw new Error('CROSS_ACCOUNT_NOT_LIQUIDATABLE'); return Object.freeze({ survivingEquity: badDebt > 0 ? 0 : 40, badDebt, health: { positions: [] } }); },
    commitCrossLiquidation(preview) { settlements += 1; if (settlementError) throw settlementError; accountState = Object.freeze({ ...accountState, availableBalance: preview.survivingEquity, crossReserved: 0 }); return Object.freeze({ liquidated: true, survivingEquity: preview.survivingEquity, badDebt: preview.badDebt, liquidatedAt: '2026-09-16T00:00:00.000Z', health: preview.health, account: accountState }); },
    snapshot: () => accountState,
    restoreSnapshot(previous, expectedCurrent) { assert.deepEqual(accountState, expectedCurrent); accountState = previous; return accountState; }
  };
  const key = (p) => `${p.symbol}:${p.side}:${p.marginMode}`;
  const positionBook = {
    list: () => [...positions],
    removeCross(expected) { if (mutateBeforeRemove) positions.unshift(Object.freeze({ symbol: 'XRPUSDT', side: 'LONG', marginMode: 'CROSS', quantity: 1 })); const current = positions.filter((p) => p.marginMode === 'CROSS'); if (current.map(key).sort().join('|') !== expected.map(key).sort().join('|')) throw new Error('CROSS_POSITION_SET_CHANGED'); const closed = []; for (let i = positions.length - 1; i >= 0; i -= 1) if (positions[i].marginMode === 'CROSS') closed.unshift(positions.splice(i, 1)[0]); return Object.freeze(closed); },
    restoreCross(snapshot) { rollbacks += 1; if (rollbackError) throw rollbackError; for (const position of snapshot) { if (positions.some((current) => key(current) === key(position))) throw new Error('CROSS_POSITION_RESTORE_CONFLICT'); positions.splice(positions.length - 1, 0, position); } return Object.freeze([...snapshot]); }
  };
  return { account, positionBook, positions, crossLong, crossShort, isolated, settlements: () => settlements, rollbacks: () => rollbacks };
}

function insuranceFixture({ previewError = null, commitError = null } = {}) {
  let commits = 0;
  return { controller: { previewCoverAndPlan(input) { if (previewError) throw previewError; return Object.freeze({ input, insuranceCovered: 50, badDebt: Math.max(0, input.liquidationLoss - 50), adlPlan: { requiredBadDebt: Math.max(0, input.liquidationLoss - 50) } }); }, commitResolution(preview) { commits += 1; if (commitError) throw commitError; return Object.freeze({ insuranceCovered: preview.insuranceCovered, badDebt: preview.badDebt, adlPlan: preview.adlPlan }); } }, commits: () => commits };
}

describe('Futures cross-margin liquidation controller', () => {
  it('returns NO_CROSS_POSITIONS without settling the account', () => { let settled = false; const account = { health: () => ({ liquidatable: false }), previewCrossLiquidation: () => ({}), commitCrossLiquidation: () => { settled = true; } }; const controller = createDemoLiquidationController({ account, positionBook: { list: () => [{ symbol: 'ETHUSDT', side: 'LONG', marginMode: 'ISOLATED' }], removeCross: () => [], restoreCross: () => [] }, markPriceOf: () => 100 }); assert.deepEqual(controller.liquidateCrossIfRequired(), { liquidated: false, reason: 'NO_CROSS_POSITIONS' }); assert.equal(settled, false); });
  it('keeps healthy cross positions open', () => { const f = fixture(); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); const result = controller.liquidateCrossIfRequired(); assert.equal(result.liquidated, false); assert.equal(result.reason, 'ACCOUNT_HEALTHY'); assert.equal(f.settlements(), 0); assert.deepEqual(f.positions, [f.crossLong, f.crossShort, f.isolated]); });
  it('settles once, removes all cross positions, preserves isolated positions and emits one event', () => { const f = fixture({ liquidatable: true }), events = []; const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, onLiquidated: (event) => events.push(event) }); const result = controller.liquidateCrossIfRequired(); assert.equal(result.liquidated, true); assert.equal(result.badDebtResolution, null); assert.equal(f.settlements(), 1); assert.equal(f.rollbacks(), 0); assert.deepEqual(result.closedPositions, [f.crossLong, f.crossShort]); assert.deepEqual(f.positions, [f.isolated]); assert.equal(events.length, 1); });
  it('routes explicit bad debt through preview then commit using global ADL candidates', () => { const f = fixture({ liquidatable: true, badDebt: 75, sameSideCross: true }); const insurance = insuranceFixture(); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, insuranceAdl: insurance.controller, adlPositions: () => [{ id: 'global-short', side: 'SHORT', quantity: 2 }] }); const result = controller.liquidateCrossIfRequired(); assert.equal(insurance.commits(), 1); assert.equal(result.badDebtResolution.insuranceCovered, 50); });
  it('rolls back account and positions when insurance/ADL commit fails', () => { const f = fixture({ liquidatable: true, badDebt: 75, sameSideCross: true }); const insurance = insuranceFixture({ commitError: new Error('INSURANCE_FUND_CHANGED_SINCE_PREVIEW') }); const beforeAccount = f.account.snapshot(); const beforePositions = [...f.positions]; const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, insuranceAdl: insurance.controller, adlPositions: () => [] }); assert.throws(() => controller.liquidateCrossIfRequired(), (error) => { assert.equal(error.message, 'CROSS_LIQUIDATION_INSURANCE_COMMIT_FAILED'); assert.equal(error.cause.message, 'INSURANCE_FUND_CHANGED_SINCE_PREVIEW'); assert.equal(error.rolledBack, true); return true; }); assert.deepEqual(f.account.snapshot(), beforeAccount); assert.deepEqual(f.positions, beforePositions); assert.equal(f.rollbacks(), 1); });
  it('leaves account and positions uncommitted when insurance/ADL preview fails', () => { const f = fixture({ liquidatable: true, badDebt: 75, sameSideCross: true }); const insurance = insuranceFixture({ previewError: new Error('ADL_PLAN_UNAVAILABLE') }); const beforePositions = [...f.positions]; const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, insuranceAdl: insurance.controller, adlPositions: () => [] }); assert.throws(() => controller.liquidateCrossIfRequired(), /ADL_PLAN_UNAVAILABLE/); assert.equal(f.settlements(), 0); assert.deepEqual(f.positions, beforePositions); });
  it('requires bad-debt resolution before mutation', () => { const f = fixture({ liquidatable: true, badDebt: 10, sameSideCross: true }); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); assert.throws(() => controller.liquidateCrossIfRequired(), /BAD_DEBT_RESOLUTION_REQUIRED/); assert.equal(f.settlements(), 0); });
  it('rejects mixed-side bad debt before mutation', () => { const f = fixture({ liquidatable: true, badDebt: 10 }); const insurance = insuranceFixture(); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, insuranceAdl: insurance.controller, adlPositions: () => [] }); assert.throws(() => controller.liquidateCrossIfRequired(), /MIXED_SIDE_BAD_DEBT_REQUIRES_ALLOCATION/); assert.equal(insurance.commits(), 0); });
  it('requires a global ADL candidate provider before mutation', () => { const f = fixture({ liquidatable: true, badDebt: 10, sameSideCross: true }); const insurance = insuranceFixture(); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100, insuranceAdl: insurance.controller }); assert.throws(() => controller.liquidateCrossIfRequired(), /GLOBAL_ADL_POSITION_PROVIDER_REQUIRED/); });
  it('aborts before account settlement when the cross position set changed', () => { const f = fixture({ liquidatable: true, mutateBeforeRemove: true }); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); assert.throws(() => controller.liquidateCrossIfRequired(), /CROSS_POSITION_SET_CHANGED/); assert.equal(f.settlements(), 0); });
  it('restores all cross positions when account commit fails', () => { const f = fixture({ liquidatable: true, settlementError: new Error('LEDGER_UNAVAILABLE') }); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); assert.throws(() => controller.liquidateCrossIfRequired(), (error) => { assert.equal(error.message, 'CROSS_LIQUIDATION_SETTLEMENT_FAILED'); assert.equal(error.rolledBack, true); return true; }); assert.equal(f.rollbacks(), 1); assert.deepEqual(f.positions, [f.crossLong, f.crossShort, f.isolated]); });
  it('surfaces rollback failure separately from account commit failure', () => { const f = fixture({ liquidatable: true, settlementError: new Error('LEDGER_UNAVAILABLE'), rollbackError: new Error('RESTORE_CONFLICT') }); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); assert.throws(() => controller.liquidateCrossIfRequired(), (error) => { assert.equal(error.message, 'CROSS_LIQUIDATION_ROLLBACK_FAILED'); return true; }); });
  it('evaluateCross excludes isolated positions from shared-risk health', () => { const f = fixture(); const controller = createDemoLiquidationController({ account: f.account, positionBook: f.positionBook, markPriceOf: () => 100 }); assert.equal(controller.evaluateCross().liquidatable, false); });
});
