import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { validateBondSelectionSafeExecution } from "../scripts/verify-intent-bond-selection.mjs";

describe("LQC Intent Bond selection Safe verification",function(){
  const safeAddress="0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",selectionContract="0x0000000000000000000000000000000000000020",token="0x0000000000000000000000000000000000000030",txHash=ethers.id("selection-tx"),blockHash=ethers.id("selection-block"),safe=new ethers.Interface(["function execTransaction(address to,uint256 value,bytes data,uint8 operation,uint256 safeTxGas,uint256 baseGas,uint256 gasPrice,address gasToken,address refundReceiver,bytes signatures) returns(bool)","event ExecutionSuccess(bytes32 txHash,uint256 payment)"]),selection=new ethers.Interface(["function approveBondToken(address token,bytes32 digest)","event BondTokenApproved(address indexed bondToken,bytes32 indexed inspectionDigest,uint256 approvedAt)"]),types={SafeTx:[{name:"to",type:"address"},{name:"value",type:"uint256"},{name:"data",type:"bytes"},{name:"operation",type:"uint8"},{name:"safeTxGas",type:"uint256"},{name:"baseGas",type:"uint256"},{name:"gasPrice",type:"uint256"},{name:"gasToken",type:"address"},{name:"refundReceiver",type:"address"},{name:"nonce",type:"uint256"}]},inspection={results:[{token,network:{chainId:97},decimals:18,assessment:{eligible:true}}]},digest=canonicalDigest(inspection),digestBytes32=`0x${digest.slice(7)}`,record={approvedBondToken:token,inspectionDigest:digest},nonce=5n,inner=selection.encodeFunctionData("approveBondToken",[token,digestBytes32]),safeValue={to:selectionContract,value:0n,data:inner,operation:0,safeTxGas:0n,baseGas:0n,gasPrice:0n,gasToken:ethers.ZeroAddress,refundReceiver:ethers.ZeroAddress,nonce},safeTxHash=ethers.TypedDataEncoder.hash({chainId:97,verifyingContract:safeAddress},types,safeValue),data=safe.encodeFunctionData("execTransaction",[selectionContract,0,inner,0,0,0,0,ethers.ZeroAddress,ethers.ZeroAddress,"0x"]);
  const log=(iface,name,args,address)=>{const fragment=iface.getEvent(name),encoded=iface.encodeEventLog(fragment,args);return{address,topics:encoded.topics,data:encoded.data}};
  function fixture(){return{record,inspection,selectionContract,transaction:{hash:txHash,to:safeAddress,data},receipt:{hash:txHash,to:safeAddress,status:1,blockNumber:100,blockHash,logs:[log(safe,"ExecutionSuccess",[safeTxHash,0],safeAddress),log(selection,"BondTokenApproved",[token,digestBytes32,1789000000],selectionContract)]},canonicalBlockHash:blockHash,latestBlock:102,nonceBefore:nonce,nonceAfter:nonce+1n,onchainToken:token,onchainInspectionDigest:digestBytes32};}
  it("verifies Safe payload, nonce transition, events and state",function(){const result=validateBondSelectionSafeExecution(fixture());assert.equal(result.status,"VERIFIED");assert.equal(result.safeTransactionHash,safeTxHash);assert.equal(result.nonce,"5");assert.equal(result.confirmations,3);});
  it("rejects substituted tokens or inspection payloads",function(){assert.throws(()=>validateBondSelectionSafeExecution({...fixture(),onchainToken:"0x0000000000000000000000000000000000000040"}),/state/);const changed=fixture();changed.record={...record,inspectionDigest:canonicalDigest({changed:true})};assert.throws(()=>validateBondSelectionSafeExecution(changed),/state|payload/);});
  it("rejects nonce gaps, missing Safe success and weak finality",function(){assert.throws(()=>validateBondSelectionSafeExecution({...fixture(),nonceAfter:nonce+2n}),/nonce/);const missing=fixture();missing.receipt={...missing.receipt,logs:missing.receipt.logs.slice(1)};assert.throws(()=>validateBondSelectionSafeExecution(missing),/events/);assert.throws(()=>validateBondSelectionSafeExecution({...fixture(),latestBlock:100}),/finality/);});
  it("rejects a Safe transaction hash that does not commit the decoded call",function(){const changed=fixture();changed.receipt={...changed.receipt,logs:[log(safe,"ExecutionSuccess",[ethers.id("wrong"),0],safeAddress),changed.receipt.logs[1]]};assert.throws(()=>validateBondSelectionSafeExecution(changed),/hash/);});
});
