import assert from "node:assert/strict";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage1Readiness } from "../scripts/build-intent-stage1-readiness.mjs";

describe("LQC Intent Stage-1 readiness gate",function(){
  const safe="0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",token="0x0000000000000000000000000000000000000030",contract="0x0000000000000000000000000000000000000020",tx=`0x${"ab".repeat(32)}`,safeTx=`0x${"cd".repeat(32)}`,inspection={results:[{token,decimals:18,observedBlock:123,network:{chainId:97},assessment:{eligible:true}}]};
  const input=()=>{const inspectionDigest=canonicalDigest(inspection),selection={status:"PENDING_MULTI_RPC_VERIFICATION",verificationRequired:true,transactionOccurred:true,network:{chainId:97},governanceSafe:safe,approvedBondToken:token,selectionContract:contract,inspectionDigest,approvalTransaction:tx,safeTransactionHash:safeTx,safeNonce:"7"},verification={status:"VERIFIED",chainId:97,governanceSafe:safe,approvedBondToken:token,selectionContract:contract,inspectionDigest,transactionHash:tx,safeTransactionHash:safeTx,nonce:"7",rpcCount:2,confirmations:3,transactionOccurred:true};return{selection,inspection,verification};};
  it("allows only a fully cross-bound finalized selection into sealing",function(){const result=buildIntentStage1Readiness(input());assert.equal(result.status,"READY_FOR_REPRODUCIBILITY_SEAL");assert.equal(result.transactionOccurred,false);assert.match(result.readinessDigest,/^sha256:[0-9a-f]{64}$/);});
  it("rejects substituted selection contract, SafeTx hash and nonce",function(){for(const mutate of[value=>value.verification.selectionContract="0x0000000000000000000000000000000000000040",value=>value.verification.safeTransactionHash=`0x${"ef".repeat(32)}`,value=>value.verification.nonce="8"]){const value=input();mutate(value);assert.throws(()=>buildIntentStage1Readiness(value),/mismatch/);}});
  it("rejects unverified, weak-finality and noncanonical records",function(){let value=input();value.verification.status="PENDING";assert.throws(()=>buildIntentStage1Readiness(value),/verification/);value=input();value.verification.confirmations=2;assert.throws(()=>buildIntentStage1Readiness(value),/verification/);value=input();value.selection.status="VERIFIED";assert.throws(()=>buildIntentStage1Readiness(value),/pending/);});
});
