import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";

const artifact=()=>JSON.parse(fs.readFileSync(new URL("../artifacts/contracts/intent-v1/LQCFinalityVerifier.sol/LQCFinalityVerifier.json",import.meta.url)));

describe("LQC Intent v1 destination finality verifier",function(){
  this.timeout(30000);
  const mnemonic="test test test test test test test test test test test junk",types={FinalityAttestation:[{name:"destinationChainId",type:"uint256"},{name:"transactionHash",type:"bytes32"},{name:"blockHash",type:"bytes32"},{name:"canonicalReceiptHash",type:"bytes32"},{name:"observedBlock",type:"uint256"},{name:"finalizedBlock",type:"uint256"},{name:"observedAt",type:"uint256"},{name:"validUntil",type:"uint256"}]};
  let provider,owner,guardian,outsider,walletA,walletB,attesterA,attesterB,verifier,chainId,value;
  beforeEach(async function(){provider=new ethers.BrowserProvider(ganache.provider({wallet:{mnemonic},chain:{chainId:31337},logging:{quiet:true}}));owner=await provider.getSigner(0);guardian=await provider.getSigner(1);attesterA=await provider.getSigner(2);attesterB=await provider.getSigner(3);outsider=await provider.getSigner(4);walletA=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/2");walletB=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/3");chainId=(await provider.getNetwork()).chainId;verifier=await new ethers.ContractFactory(artifact().abi,artifact().bytecode,owner).deploy(await owner.getAddress(),await guardian.getAddress(),2);await verifier.waitForDeployment();await(await verifier.setAttester(await attesterA.getAddress(),true)).wait();await(await verifier.setAttester(await attesterB.getAddress(),true)).wait();await(await verifier.setChainPolicy(97,3,3600,true)).wait();const block=await provider.getBlock("latest");value={destinationChainId:97n,transactionHash:ethers.id("destination-tx"),blockHash:ethers.id("destination-block"),canonicalReceiptHash:ethers.id("destination-receipt"),observedBlock:1000n,finalizedBlock:1003n,observedAt:BigInt(block.timestamp),validUntil:BigInt(block.timestamp+600)};});
  const domain=async()=>({name:"LQC Finality Verifier",version:"1",chainId,verifyingContract:await verifier.getAddress()});
  async function signatures(attestation=value){const pairs=[[await walletA.getAddress(),await walletA.signTypedData(await domain(),types,attestation)],[await walletB.getAddress(),await walletB.signTypedData(await domain(),types,attestation)]];return pairs.sort((a,b)=>a[0].toLowerCase().localeCompare(b[0].toLowerCase())).map(x=>x[1]);}

  it("records quorum evidence only after the chain confirmation policy is met",async function(){const sigs=await signatures(),hash=await verifier.connect(outsider).submitAttestation.staticCall(value,sigs);await(await verifier.connect(outsider).submitAttestation(value,sigs)).wait();const stored=await verifier.verifiedFinality(hash);assert.equal(stored.destinationChainId,97n);assert.equal(stored.finalizedBlock,1003n);assert.ok(stored.verifiedAt>0n);await assert.rejects(verifier.submitAttestation(value,sigs));});
  it("rejects insufficient confirmations, disabled chains and stale observations",async function(){let index=0;for(const changed of [{finalizedBlock:1002n},{destinationChainId:56n},{observedAt:value.observedAt-3601n}]){const candidate={...value,...changed,transactionHash:ethers.id(`invalid-finality-${index++}`)};await assert.rejects(verifier.submitAttestation(candidate,await signatures(candidate)));}});
  it("rejects insufficient, duplicate and payload-substituted signatures",async function(){const sigs=await signatures();await assert.rejects(verifier.submitAttestation(value,[sigs[0]]));await assert.rejects(verifier.submitAttestation(value,[sigs[0],sigs[0]]));await assert.rejects(verifier.submitAttestation({...value,finalizedBlock:1004n},sigs));});
  it("allows Guardian pause but only Governance recovery",async function(){await(await verifier.connect(guardian).setPaused(true)).wait();await assert.rejects(verifier.submitAttestation(value,await signatures()));await assert.rejects(verifier.connect(guardian).setPaused(false));await(await verifier.setPaused(false)).wait();await(await verifier.submitAttestation(value,await signatures(),{gasLimit:500000n})).wait();});
});
