import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest, sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { preflightIntentStage2AcrossRpcs } from "../scripts/preflight-intent-stage2-deployment.mjs";

describe("LQC Intent Stage-2 deployment preflight", function () {
  const deployer = "0x0000000000000000000000000000000000000010", blockHash = ethers.id("stage2-block"), action = { id: 1, actor: "deployer", action: "deploy-internal-solver", to: null, value: "0", data: "0x60006000" }, manifest = { network: { chainId: 97 }, stage: "stage2-solver-deploy", orderedActions: [action] }, actionSummary = { id: 1, actor: "deployer", action: "deploy-internal-solver", to: null, value: "0", initCodeDigest: sha256(action.data), initCodeBytes: 4 }, reviewBody = { packageType: "LQC_INTENT_STAGE2_INTERNAL_SOLVER_REVIEW", status: "REVIEW_REQUIRED", network: { chainId: 97 }, readinessDigest: sha256("readiness"), action: actionSummary, transactionOccurred: false }, review = { ...reviewBody, reviewDigest: canonicalDigest(reviewBody) };
  const provider = (options = {}) => ({ getNetwork: async () => ({ chainId: BigInt(options.chainId || 97) }), getBlockNumber: async () => 500, getBlock: async () => ({ hash: options.blockHash || blockHash, baseFeePerGas: 1_000_000_000n }), getTransactionCount: async () => options.nonce ?? 9, getBalance: async () => options.balance ?? 1_000_000_000_000_000_000n, getCode: async () => options.code || "0x", estimateGas: async () => BigInt(options.gas || 200000) });
  it("pins one empty CREATE address and conservative gas across RPCs", async function () { const result = await preflightIntentStage2AcrossRpcs({ providers: [provider(), provider({ gas: 205000 })], review, manifest, deployer }); assert.equal(result.status, "PREFLIGHT_VERIFIED_FOR_INTERNAL_SOLVER_REVIEW"); assert.equal(result.deployment.predictedAddress, ethers.getCreateAddress({ from: deployer, nonce: 9 })); assert.equal(result.deployment.conservativeGas, "205000"); assert.equal(result.transactionOccurred, false); assert.equal(result.preflightDigest, canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key]) => key !== "preflightDigest")))); });
  it("rejects wrong chain, occupied address and nonce disagreement", async function () { await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider(), provider({ chainId: 56 })], review, manifest, deployer }), /chain/); await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider(), provider({ code: "0x6000" })], review, manifest, deployer }), /already has code/); await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider(), provider({ nonce: 10 })], review, manifest, deployer }), /disagreement/); });
  it("rejects material gas disagreement and reviewed init-code substitution", async function () { await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider(), provider({ gas: 300000 })], review, manifest, deployer }), /gas estimate/); const changed = structuredClone(manifest); changed.orderedActions[0].data = "0x60016000"; await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider(), provider()], review, manifest: changed, deployer }), /changed/); });
  it("requires enough tBNB for the conservative deployment budget", async function () { await assert.rejects(preflightIntentStage2AcrossRpcs({ providers: [provider({ balance: 1n }), provider({ balance: 1n })], review, manifest, deployer }), /insufficient/); });
});
