import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage4CompletionPackage } from "../scripts/build-intent-stage4-completion-package.mjs";
import { buildIntentStage4AuditHandoff, writeIntentStage4AuditHandoff } from "../scripts/build-intent-stage4-audit-handoff.mjs";
import { verifyIntentStage4AuditHandoff } from "../scripts/verify-intent-stage4-audit-handoff.mjs";
import { stage4CompletionFixture } from "./intent-v1-stage4-completion-package.test.mjs";
const seal=(body,field)=>({...body,[field]:canonicalDigest(body)});
function fixture(){const completion=buildIntentStage4CompletionPackage(stage4CompletionFixture()),auditRecord=seal({status:"PASS_STAGE4_AUDIT_GATE",network:{chainId:97},sourceRevision:"ab".repeat(20),packageLockDigest:"sha256:lock",completionDigest:completion.completionDigest,packageVerificationDigest:"sha256:package",intentHash:completion.intentHash,quoteHash:completion.quoteHash,executionHash:completion.executionHash,transactionOccurred:false},"auditGateDigest"),auditVerification=seal({status:"VERIFIED_STAGE4_AUDIT_GATE",network:{chainId:97},sourceRevision:auditRecord.sourceRevision,packageLockDigest:auditRecord.packageLockDigest,completionDigest:completion.completionDigest,packageVerificationDigest:auditRecord.packageVerificationDigest,intentHash:completion.intentHash,quoteHash:completion.quoteHash,executionHash:completion.executionHash,auditGateDigest:auditRecord.auditGateDigest,transactionOccurred:false},"auditVerificationDigest");return{completion,auditRecord,auditVerification}}
function directory(){const inputs=fixture(),handoff=buildIntentStage4AuditHandoff(inputs),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage4-handoff-"));writeIntentStage4AuditHandoff(dir,handoff,inputs);return dir}
describe("LQC Intent Stage-4 external audit handoff",function(){
  it("binds completion, audit gate and independent verification",function(){const handoff=buildIntentStage4AuditHandoff(fixture());assert.equal(handoff.status,"READY_FOR_EXTERNAL_STAGE4_AUDIT_HANDOFF");assert.equal(handoff.reviewerChecklist.length,6);assert.equal(handoff.transactionOccurred,false);assert.match(handoff.handoffDigest,/^sha256:[0-9a-f]{64}$/)});
  it("rejects tampered or cross-bound evidence",function(){let inputs=fixture();inputs.auditRecord.sourceRevision="cd".repeat(20);assert.throws(()=>buildIntentStage4AuditHandoff(inputs),/audit gate/);inputs=fixture();inputs.auditVerification.executionHash="0x"+"11".repeat(32);inputs.auditVerification.auditVerificationDigest=canonicalDigest(Object.fromEntries(Object.entries(inputs.auditVerification).filter(([key])=>key!=="auditVerificationDigest")));assert.throws(()=>buildIntentStage4AuditHandoff(inputs),/binding/)});
  it("writes and independently verifies five immutable files",function(){const inputs=fixture(),handoff=buildIntentStage4AuditHandoff(inputs),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage4-handoff-write-")),written=writeIntentStage4AuditHandoff(dir,handoff,inputs),verified=verifyIntentStage4AuditHandoff(dir);assert.equal(written.fileCount,5);assert.equal(verified.status,"VERIFIED_STAGE4_AUDIT_HANDOFF");assert.equal(Object.keys(verified.evidenceFileDigests).length,4);assert.match(verified.handoffVerificationDigest,/^sha256:[0-9a-f]{64}$/);assert.throws(()=>writeIntentStage4AuditHandoff(dir,handoff,inputs),/empty output/)});
  it("rejects missing, added, changed and rehashed evidence",function(){let dir=directory();fs.unlinkSync(path.join(dir,"HANDOFF.md"));assert.throws(()=>verifyIntentStage4AuditHandoff(dir),/file set/);dir=directory();fs.writeFileSync(path.join(dir,"extra.json"),"{}\n");assert.throws(()=>verifyIntentStage4AuditHandoff(dir),/file set/);dir=directory();fs.appendFileSync(path.join(dir,"HANDOFF.md"),"changed\n");assert.throws(()=>verifyIntentStage4AuditHandoff(dir),/file digest/);dir=directory();const file=path.join(dir,"handoff-manifest.json"),manifest=JSON.parse(fs.readFileSync(file));manifest.status="FORGED";manifest.bundleDigest=canonicalDigest(Object.fromEntries(Object.entries(manifest).filter(([key])=>key!=="bundleDigest")));fs.writeFileSync(file,JSON.stringify(manifest));assert.throws(()=>verifyIntentStage4AuditHandoff(dir),/manifest/)});
  it("contains no RPC, key, signing or transaction mechanism",function(){for(const file of["../scripts/build-intent-stage4-audit-handoff.mjs","../scripts/verify-intent-stage4-audit-handoff.mjs"]){const source=fs.readFileSync(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction/)} });
});
