import assert from "node:assert/strict";
import { ethers } from "ethers";
import {buildIntentTestnetManifest,INTENT_TESTNET_POLICY,validateIntentTestnetManifest} from "../scripts/prepare-intent-testnet-stack.mjs";

describe("LQC Intent v1.1 testnet deployment manifest",function(){
  const address=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),bondToken=address(100),attesters=[address(201),address(202)],core={LQCIntentHub:address(101),LQCQuoteManager:address(102),LQCSolverRegistry:address(103),LQCExecutionVerifier:address(104)},all={...core,LQCInternalSolver:address(105)};
  it("builds four independent constructor deployments for stage 1",async function(){const manifest=await buildIntentTestnetManifest({bondToken});assert.equal(manifest.stage,"stage1-core-deploy");assert.equal(manifest.orderedActions.length,4);assert.equal(manifest.orderedActions.every(action=>action.to===null&&action.actor==="deployer"),true);assert.equal(manifest.roles.governanceSafe,"0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A");assert.equal(manifest.dryRun.transactionOccurred,false);assert.equal(manifest.policy.attesterQuorum,2);});
  it("builds the Router-bound Internal Solver deployment only after core addresses exist",async function(){const manifest=await buildIntentTestnetManifest({bondToken,addresses:core});assert.equal(manifest.stage,"stage2-solver-deploy");assert.equal(manifest.orderedActions.length,1);assert.equal(manifest.orderedActions[0].action,"deploy-internal-solver");assert.equal(manifest.dependencies.executionRouter,"0x2e0a7f59ca65ed36977add5e71b8b64ba38d939f");});
  it("orders all governance bindings and attester activation for stage 3",async function(){const manifest=await buildIntentTestnetManifest({bondToken,addresses:all,attesters});assert.equal(manifest.stage,"stage3-governance-bindings");assert.equal(manifest.orderedActions.length,11);assert.deepEqual(manifest.orderedActions.slice(0,9).map(action=>action.action),["registry-set-exposure-manager","registry-set-verifier","registry-set-resolver","registry-set-slash-recipient","quote-set-registry","hub-set-quote-manager","hub-set-solver-registry","hub-begin-internal-solver","solver-accept-hub-role"]);assert.equal(manifest.orderedActions.every(action=>action.actor==="governance-safe"&&ethers.isAddress(action.to)),true);assert.equal(manifest.attesters.length,INTENT_TESTNET_POLICY.attesterQuorum);});
  it("fails closed on missing quorum, duplicate identities and malformed actions",async function(){await assert.rejects(buildIntentTestnetManifest({bondToken,addresses:all,attesters:[attesters[0]]}),/quorum/);await assert.rejects(buildIntentTestnetManifest({bondToken,addresses:all,attesters:[attesters[0],attesters[0]]}),/attesters/);await assert.rejects(buildIntentTestnetManifest({bondToken:ethers.ZeroAddress}),/Bond/);assert.throws(()=>validateIntentTestnetManifest({stage:"stage1-core-deploy",actions:[{actor:"deployer",to:null,data:"0x"}]}),/actions/);});
});
