import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildIntentReproducibilitySeal,canonicalDigest,sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage1Readiness } from "../scripts/build-intent-stage1-readiness.mjs";
import { buildIntentStage1ReviewPackage,writeIntentStage1ReviewPackage } from "../scripts/build-intent-stage1-review-package.mjs";

describe("LQC Intent Stage-1 deployment review package",function(){
  const safe="0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",token="0x0000000000000000000000000000000000000030",selectionContract="0x0000000000000000000000000000000000000020",tx=`0x${"ab".repeat(32)}`,safeTx=`0x${"cd".repeat(32)}`,digest=sha256("fixture"),revision="a".repeat(40),contracts=["LQCIntentHub","LQCQuoteManager","LQCSolverRegistry","LQCExecutionVerifier"],inspection={results:[{token,decimals:18,observedBlock:123,network:{chainId:97},assessment:{eligible:true}}]};
  const fixture=()=>{const inspectionDigest=canonicalDigest(inspection),selection={status:"PENDING_MULTI_RPC_VERIFICATION",verificationRequired:true,transactionOccurred:true,network:{chainId:97},governanceSafe:safe,approvedBondToken:token,selectionContract,inspectionDigest,approvalTransaction:tx,safeTransactionHash:safeTx,safeNonce:"7"},verification={status:"VERIFIED",chainId:97,governanceSafe:safe,approvedBondToken:token,selectionContract,inspectionDigest,transactionHash:tx,safeTransactionHash:safeTx,nonce:"7",rpcCount:2,confirmations:3,transactionOccurred:true},readiness=buildIntentStage1Readiness({selection,inspection,verification}),stage1Actions=contracts.map((name,index)=>({id:index+1,actor:"deployer",action:`deploy-${name}`,to:null,value:"0",data:`0x60${index.toString(16).padStart(2,"0")}`})),seal=buildIntentReproducibilitySeal({sourceRevision:revision,nodeVersion:"v22.0.0",packageLockDigest:digest,compilerVersion:"0.8.30+commit.73712a01",selection,inspection,selectionVerification:verification,stage1Readiness:readiness,sourceFiles:[{path:"contracts/intent-v1/A.sol",digest}],artifacts:contracts.map(contract=>({contract,abiDigest:digest,bytecodeDigest:digest,deployedBytecodeDigest:digest})),stage1Actions}),buildVerification={status:"VERIFIED_FOR_STAGE1_DEPLOYMENT_REVIEW",transactionOccurred:false,sealDigest:seal.sealDigest,sourceRevision:revision,readinessDigest:readiness.readinessDigest,bondToken:token},manifest={network:{chainId:97},stage:"stage1-core-deploy",dryRun:{transactionOccurred:false},dependencies:{bondToken:token,executionRouter:"0x0000000000000000000000000000000000000040"},roles:{governanceSafe:safe},policy:{attesterQuorum:2},orderedActions:stage1Actions};return{seal,buildVerification,manifest};};
  it("binds the verified seal to four human-reviewable deployments",function(){const review=buildIntentStage1ReviewPackage(fixture());assert.equal(review.status,"REVIEW_REQUIRED");assert.equal(review.actions.length,4);assert.equal(review.transactionOccurred,false);assert.match(review.reviewDigest,/^sha256:[0-9a-f]{64}$/);});
  it("rejects substituted verification, Bond token and init code",function(){let value=fixture();value.buildVerification.sealDigest=sha256("seal");assert.throws(()=>buildIntentStage1ReviewPackage(value),/binding/);value=fixture();value.manifest.dependencies.bondToken="0x0000000000000000000000000000000000000050";assert.throws(()=>buildIntentStage1ReviewPackage(value),/binding/);value=fixture();value.manifest.orderedActions[0].data="0x6009";assert.throws(()=>buildIntentStage1ReviewPackage(value),/init code/);});
  it("writes five immutable review files",function(){const inputs=fixture(),review=buildIntentStage1ReviewPackage(inputs),directory=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage1-review-")),result=writeIntentStage1ReviewPackage(directory,review,inputs);assert.equal(result.fileCount,5);assert.equal(fs.readdirSync(directory).length,5);assert.throws(()=>writeIntentStage1ReviewPackage(directory,review,inputs),/empty output/);});
});
