import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage2Readiness } from "../scripts/build-intent-stage2-readiness.mjs";

describe("LQC Intent Stage-2 readiness gate", function () {
  const a = index => ethers.getAddress(`0x${index.toString(16).padStart(40, "0")}`), governance = a(10), risk = a(11), guardian = a(12), treasury = a(13), bond = a(14), hub = a(20), quote = a(21), registry = a(22), verifier = a(23), escrow = a(24);
  const roles = { governanceSafe: governance, riskSafe: risk, guardianSafe: guardian, treasurySafe: treasury }, policy = { attesterQuorum: 2, maxGasOverrunBps: 2000, maxPriceImpactBps: 500, maxMarketDeviationBps: 300, minimumBond: ethers.parseUnits("10000", 18).toString(), solverExposureLimit: ethers.parseUnits("1000", 18).toString() };
  const reviewBody = { status: "REVIEW_REQUIRED", network: { chainId: 97 }, transactionOccurred: false, sealDigest: ethers.id("seal"), roles, policy, bondToken: bond, dependencies: { executionRouter: a(15) } }, review = { ...reviewBody, reviewDigest: canonicalDigest(reviewBody) };
  const deployed = [hub, quote, registry, verifier], actions = ["deploy-intent-hub", "deploy-quote-manager", "deploy-solver-registry", "deploy-execution-verifier"];
  const deploymentBody = { status: "VERIFIED_STAGE1_DEPLOYMENT", network: { chainId: 97 }, reviewDigest: review.reviewDigest, sealDigest: review.sealDigest, deployer: a(30), deployments: deployed.map((contractAddress, index) => ({ action: actions[index], contractAddress })) }, deployment = { ...deploymentBody, verificationDigest: canonicalDigest(deploymentBody) };
  const abi = new ethers.Interface(["function owner() view returns(address)", "function settler() view returns(address)", "function guardian() view returns(address)", "function sourceEscrow() view returns(address)", "function controller() view returns(address)", "function bondToken() view returns(address)", "function minimumBond() view returns(uint256)", "function challengeBond() view returns(uint256)", "function resolver() view returns(address)", "function slashRecipient() view returns(address)", "function quorum() view returns(uint256)", "function maxGasOverrunBps() view returns(uint256)", "function maxPriceImpactBps() view returns(uint256)", "function maxMarketDeviationBps() view returns(uint256)", "function paused() view returns(bool)", "function solverRegistry() view returns(address)", "function quoteManager() view returns(address)", "function internalSolver() view returns(address)", "function exposureManager() view returns(address)", "function executionVerifier() view returns(address)"]);
  const provider = (change = {}) => ({ getNetwork: async () => ({ chainId: BigInt(change.chainId || 97) }), getBlockNumber: async () => 300, getBlock: async () => ({ hash: change.blockHash || ethers.id("block") }), getCode: async address => change.noCode === address ? "0x" : "0x60016000", call: async tx => { const fn = abi.getFunction(tx.data.slice(0, 10)).name, target = tx.to.toLowerCase(); const zero = ethers.ZeroAddress, state = {
    [hub.toLowerCase()]: { owner: governance, settler: risk, guardian, sourceEscrow: escrow, quoteManager: zero, solverRegistry: zero, internalSolver: zero, paused: false },
    [quote.toLowerCase()]: { owner: governance, guardian, solverRegistry: zero, paused: false },
    [registry.toLowerCase()]: { owner: governance, guardian, bondToken: bond, minimumBond: BigInt(policy.minimumBond), challengeBond: BigInt(policy.minimumBond) / 100n, resolver: governance, slashRecipient: governance, exposureManager: zero, executionVerifier: zero, paused: false },
    [verifier.toLowerCase()]: { owner: governance, guardian, quorum: 2n, maxGasOverrunBps: 2000n, maxPriceImpactBps: 500n, maxMarketDeviationBps: 300n, paused: false },
    [escrow.toLowerCase()]: { controller: hub }
  }; let value = state[target]?.[fn]; if (change.target?.toLowerCase() === target && change.field === fn) value = change.value; if (value === undefined) throw new Error(`Missing mock ${target}.${fn}`); return abi.encodeFunctionResult(fn, [value]); } });
  it("admits only the pristine verified core into Internal Solver review", async function () { const result = await buildIntentStage2Readiness({ providers: [provider(), provider()], review, deployment }); assert.equal(result.status, "READY_FOR_INTERNAL_SOLVER_DEPLOYMENT_REVIEW"); assert.equal(result.addresses.LQCSourceEscrow, escrow); assert.equal(result.dependencies.executionRouter, review.dependencies.executionRouter); assert.equal(result.transactionOccurred, false); assert.equal(result.readinessDigest, canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key]) => key !== "readinessDigest")))); });
  it("rejects role, Bond policy, and premature binding changes", async function () { await assert.rejects(buildIntentStage2Readiness({ providers: [provider(), provider({ target: hub, field: "owner", value: a(99) })], review, deployment }), /RPC disagreement/); await assert.rejects(buildIntentStage2Readiness({ providers: [provider({ target: registry, field: "minimumBond", value: 1n }), provider({ target: registry, field: "minimumBond", value: 1n })], review, deployment }), /policy binding/); await assert.rejects(buildIntentStage2Readiness({ providers: [provider({ target: hub, field: "quoteManager", value: quote }), provider({ target: hub, field: "quoteManager", value: quote })], review, deployment }), /pristine/); });
  it("rejects missing runtime, wrong chain, and tampered verification evidence", async function () { await assert.rejects(buildIntentStage2Readiness({ providers: [provider(), provider({ noCode: verifier })], review, deployment }), /runtime/); await assert.rejects(buildIntentStage2Readiness({ providers: [provider(), provider({ chainId: 56 })], review, deployment }), /chain/); const changed = structuredClone(deployment); changed.deployments[0].contractAddress = a(90); await assert.rejects(buildIntentStage2Readiness({ providers: [provider(), provider()], review, deployment: changed }), /digest/); });
});
