import assert from "node:assert/strict";
import { ethers } from "ethers";
import {evaluateBondCandidate,inspectBondCandidate} from "../scripts/inspect-intent-bond-candidates.mjs";

describe("LQC Intent v1 Bond candidate inspection",function(){
  const address=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),token=address(1),quote=address(2),pool=address(3),feedA=address(4),feedB=address(5),now=1789000000,erc20=new ethers.Interface(["function decimals() view returns(uint8)","function totalSupply() view returns(uint256)","function balanceOf(address) view returns(uint256)"]),oracle=new ethers.Interface(["function decimals() view returns(uint8)","function latestRoundData() view returns(uint80,int256,uint256,uint256,uint80)"]),candidate={name:"Bond Candidate",token,liquidityVenues:[{address:pool,quoteToken:quote,minimumTokenBalance:"1000",minimumQuoteBalance:"500"}],oracleFeeds:[{address:feedA},{address:feedB}]};
  function provider(overrides={}){return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>100,getCode:async()=>"0x6000",call:async tx=>{const selector=tx.data.slice(0,10);if(selector===erc20.getFunction("decimals").selector)return erc20.encodeFunctionResult("decimals",[18]);if(selector===erc20.getFunction("totalSupply").selector)return erc20.encodeFunctionResult("totalSupply",[1000000n]);if(selector===erc20.getFunction("balanceOf").selector)return erc20.encodeFunctionResult("balanceOf",[tx.to.toLowerCase()===token.toLowerCase()?2000n:1000n]);if(selector===oracle.getFunction("latestRoundData").selector)return oracle.encodeFunctionResult("latestRoundData",[10n,100000000n,0n,BigInt(now-60),10n]);throw new Error("unknown call")},...overrides};}
  it("accepts only a two-RPC, liquid, dual-feed, 18-decimal candidate",async function(){const result=await inspectBondCandidate(candidate,[provider(),provider()],now);assert.equal(result.assessment.eligible,true);assert.equal(result.assessment.liquidVenueCount,1);assert.equal(result.assessment.freshOracleCount,2);assert.equal(result.rpcCount,2);assert.equal(result.transactionOccurred,false);});
  it("fails closed when independent RPC observations disagree",async function(){const changed=provider({call:async tx=>{if(tx.data.slice(0,10)===erc20.getFunction("totalSupply").selector)return erc20.encodeFunctionResult("totalSupply",[999999n]);return provider().call(tx)}});await assert.rejects(inspectBondCandidate(candidate,[provider(),changed],now),/disagreement/);});
  it("reports decimals, liquidity and stale-oracle blockers independently",function(){const assessment=evaluateBondCandidate({decimals:6,totalSupply:"100",venues:[{tokenBalance:"10",minimumTokenBalance:"100",quoteBalance:"10",minimumQuoteBalance:"100"}],feeds:[{complete:true,ageSeconds:4000}]});assert.equal(assessment.eligible,false);assert.equal(assessment.blockers.length,3);assert.match(assessment.blockers.join(" "),/18 decimals/);assert.match(assessment.blockers.join(" "),/liquidity/);assert.match(assessment.blockers.join(" "),/Oracle/);});
  it("normalizes feed decimals and rejects excessive Oracle divergence",function(){const assessment=evaluateBondCandidate({decimals:18,totalSupply:"100",venues:[{tokenBalance:"100",minimumTokenBalance:"100",quoteBalance:"100",minimumQuoteBalance:"100"}],feeds:[{complete:true,ageSeconds:1,decimals:8,answer:"100000000"},{complete:true,ageSeconds:1,decimals:18,answer:"1100000000000000000"}]});assert.equal(assessment.eligible,false);assert.equal(assessment.oracleDivergenceBps,1000);assert.match(assessment.blockers[0],/divergence/);});
  it("rejects one-RPC inspection and missing contract bytecode",async function(){await assert.rejects(inspectBondCandidate(candidate,[provider()],now),/Invalid/);await assert.rejects(inspectBondCandidate(candidate,[provider({getCode:async()=>"0x"}),provider()],now),/bytecode/);});
  it("rejects duplicate venue or feed identities",async function(){await assert.rejects(inspectBondCandidate({...candidate,oracleFeeds:[{address:feedA},{address:feedA}]},[provider(),provider()],now),/independent/);});
});
