import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";

const artifact=(name="LQCExecutionVerifier",source=`intent-v1/${name}`)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${source}.sol/${name}.json`,import.meta.url)));

describe("LQC Intent v1 public execution verifier",function(){
  this.timeout(30000);
  const mnemonic="test test test test test test test test test test test junk",types={ExecutionReport:[{name:"intentHash",type:"bytes32"},{name:"solver",type:"address"},{name:"quoteHash",type:"bytes32"},{name:"signedRouteHash",type:"bytes32"},{name:"observedRouteHash",type:"bytes32"},{name:"expectedExecutionHash",type:"bytes32"},{name:"observedExecutionHash",type:"bytes32"},{name:"transactionHash",type:"bytes32"},{name:"blockHash",type:"bytes32"},{name:"canonicalReceiptHash",type:"bytes32"},{name:"minimumAmountOut",type:"uint256"},{name:"actualAmountOut",type:"uint256"},{name:"estimatedGas",type:"uint256"},{name:"gasUsed",type:"uint256"},{name:"priceImpactBps",type:"uint256"},{name:"marketDeviationBps",type:"uint256"},{name:"observedBlock",type:"uint256"},{name:"deadline",type:"uint256"}]};
  let provider,owner,guardian,submitter,attesterA,attesterB,walletA,walletB,verifier,chainId,report;
  beforeEach(async function(){provider=new ethers.BrowserProvider(ganache.provider({wallet:{mnemonic},chain:{chainId:31337},logging:{quiet:true}}));owner=await provider.getSigner(0);guardian=await provider.getSigner(1);submitter=await provider.getSigner(4);attesterA=await provider.getSigner(2);attesterB=await provider.getSigner(3);walletA=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/2");walletB=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/3");chainId=(await provider.getNetwork()).chainId;const a=artifact();verifier=await new ethers.ContractFactory(a.abi,a.bytecode,owner).deploy(await owner.getAddress(),await guardian.getAddress(),2,2000,500,300);await verifier.waitForDeployment();await(await verifier.setAttester(await attesterA.getAddress(),true)).wait();await(await verifier.setAttester(await attesterB.getAddress(),true)).wait();const block=await provider.getBlock("latest"),route=ethers.id("route"),execution=ethers.id("execution");report={intentHash:ethers.id("intent"),solver:await submitter.getAddress(),quoteHash:ethers.id("quote"),signedRouteHash:route,observedRouteHash:route,expectedExecutionHash:execution,observedExecutionHash:execution,transactionHash:ethers.id("tx"),blockHash:block.hash,canonicalReceiptHash:ethers.id("canonical-receipt"),minimumAmountOut:990n,actualAmountOut:1000n,estimatedGas:100000n,gasUsed:110000n,priceImpactBps:100n,marketDeviationBps:100n,observedBlock:BigInt(block.number),deadline:BigInt(block.timestamp+120)};});
  const domain=async()=>({name:"LQC Execution Verifier",version:"1",chainId,verifyingContract:await verifier.getAddress()});
  async function signatures(value){const pairs=[[await walletA.getAddress(),await walletA.signTypedData(await domain(),types,value)],[await walletB.getAddress(),await walletB.signTypedData(await domain(),types,value)]];return pairs.sort((a,b)=>a[0].toLowerCase().localeCompare(b[0].toLowerCase())).map(x=>x[1]);}

  it("accepts a public quorum submission and records a no-fault verdict",async function(){const sigs=await signatures(report),hash=await verifier.connect(submitter).submitReport.staticCall(report,sigs);assert.equal(hash[1],0n);await(await verifier.connect(submitter).submitReport(report,sigs)).wait();const verdict=await verifier.verdicts(hash[0]);assert.equal(verdict.intentHash,report.intentHash);assert.equal(verdict.reason,0n);await assert.rejects(verifier.submitReport(report,sigs));});
  it("classifies minimum-output, route, receipt and quality faults deterministically",async function(){for(const [index,changed,reason] of [[1,{actualAmountOut:989n},2n],[2,{observedRouteHash:ethers.id("other-route")},3n],[3,{observedExecutionHash:ethers.id("forged")},4n],[4,{gasUsed:130001n},5n]]){const value={...report,...changed,intentHash:ethers.id(`intent-${index}`),transactionHash:ethers.id(`tx-${index}`)};const result=await verifier.submitReport.staticCall(value,await signatures(value));assert.equal(result[1],reason);await(await verifier.submitReport(value,await signatures(value))).wait();}});
  it("rejects insufficient, duplicate, disabled and tampered attestations",async function(){const sigs=await signatures(report);await assert.rejects(verifier.submitReport(report,[sigs[0]]));await assert.rejects(verifier.submitReport(report,[sigs[0],sigs[0]]));const changed={...report,actualAmountOut:999n};await assert.rejects(verifier.submitReport(changed,sigs));await(await verifier.setAttester(await attesterB.getAddress(),false)).wait();await assert.rejects(verifier.submitReport(report,sigs));});
  it("allows guardian pause but only owner resume",async function(){await(await verifier.connect(guardian).setPaused(true)).wait();await assert.rejects(verifier.submitReport(report,await signatures(report)));await assert.rejects(verifier.connect(guardian).setPaused(false));await(await verifier.setPaused(false)).wait();assert.equal((await verifier.submitReport.staticCall(report,await signatures(report)))[1],0n);});
  it("permissionlessly resolves a matching Registry challenge from the verified fault",async function(){const deploy=async(name,source,...args)=>{const a=artifact(name,source),c=await new ethers.ContractFactory(a.abi,a.bytecode,owner).deploy(...args);await c.waitForDeployment();return c},bond=await deploy("MockERC20","mocks/MockERC20","Bond","BOND"),registry=await deploy("LQCSolverRegistry","intent-v1/LQCSolverRegistry",await bond.getAddress(),await owner.getAddress(),await guardian.getAddress(),100n),solverAddress=await submitter.getAddress();await(await bond.mint(solverAddress,100n)).wait();await(await bond.connect(submitter).approve(await registry.getAddress(),100n)).wait();await(await registry.connect(submitter).depositBond(100n)).wait();await(await registry.configureSolver(solverAddress,true,1000n)).wait();await(await registry.setExposureManager(await owner.getAddress())).wait();await(await registry.setExecutionVerifier(await verifier.getAddress())).wait();await(await registry.openExposure(report.intentHash,solverAddress,100n)).wait();await(await registry.closeExposure(report.intentHash)).wait();const fault={...report,actualAmountOut:980n},sigs=await signatures(fault),result=await verifier.submitReport.staticCall(fault,sigs);await(await verifier.submitReport(fault,sigs)).wait();await(await bond.mint(await guardian.getAddress(),1n)).wait();await(await bond.connect(guardian).approve(await registry.getAddress(),1n)).wait();const challengeId=await registry.connect(guardian).fileChallenge.staticCall(fault.intentHash,2,result[0]);await(await registry.connect(guardian).fileChallenge(fault.intentHash,2,result[0])).wait();await(await registry.connect(attesterA).resolveChallengeWithVerifier(challengeId,5000)).wait();assert.equal((await registry.getSolver(solverAddress)).bond,50n);assert.equal((await registry.challenges(challengeId)).upheld,true);});
});
