import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { preflightIntentStage4SameChainExecution } from "../scripts/preflight-intent-stage4-same-chain-execution.mjs";

const qt = "(bytes32 intentHash,address solver,bytes32 dexId,uint256 amountOut,uint256 solverFeeOut,uint256 gasCostOut,bytes32 routeHash,uint256 issuedAt,uint256 deadline,uint256 nonce)", hub = new ethers.Interface([`function executeSameChainIntent(bytes32,${qt},bytes,bytes) returns(uint256)`, "function getIntent(bytes32) view returns((address user,address sourceToken,uint256 sourceAmount,uint256 destinationChainId,address destinationToken,address recipient,uint256 minAmountOut,uint256 deadline,uint8 status,address solver,uint256 actualAmountOut,bytes32 destinationTxHash,bytes32 executionHash,bytes32 quoteHash,bytes32 routeHash))", "function settler() view returns(address)", "function sourceEscrow() view returns(address)", "function quoteManager() view returns(address)", "function solverRegistry() view returns(address)", "function internalSolver() view returns(address)", "function paused() view returns(bool)"]), qm = new ethers.Interface([`function verifyQuote(bytes32,uint256,${qt},bytes) view returns(bytes32,uint256)`, "function solverRegistry() view returns(address)", "function paused() view returns(bool)"]), registry = new ethers.Interface(["function isSolverEligible(address,uint256) view returns(bool)", "function paused() view returns(bool)"]), escrow = new ethers.Interface(["function getDeposit(bytes32) view returns((address user,address token,uint256 amount,bool active))"]), a = n => ethers.getAddress(`0x${n.toString(16).padStart(40, "0")}`);
function fixture(change = {}) {
  const user=a(1),target=a(2),sourceToken=a(3),destinationToken=a(4),sourceEscrow=a(5),quoteManager=a(6),solverRegistry=a(7),internalSolver=a(8),settler=a(9),solver=a(10),intentHash=ethers.id("intent"),routeData=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[sourceToken,destinationToken]]),routeHash=ethers.keccak256(routeData),quoteHash=ethers.id("quote"),signature=`0x${"11".repeat(65)}`;
  const pilotBody={status:"READY_FOR_OFFLINE_REVIEW_ONLY",network:{chainId:97},intentHub:target,intent:{user,sourceToken,sourceAmount:"1000",destinationChainId:"97",destinationToken,recipient:user,minAmountOut:"990",deadline:"5000600"},intentHash,routeData,routeHash,transactionOccurred:false},pilotPlan={...pilotBody,pilotPlanDigest:canonicalDigest(pilotBody)};
  const submissionBody={status:"VERIFIED_STAGE4_INTENT_SUBMISSION",network:{chainId:97},pilotPlanDigest:pilotPlan.pilotPlanDigest,intentHash,transactionOccurred:true},submissionVerification={...submissionBody,submissionVerificationDigest:canonicalDigest(submissionBody)};
  const quote={intentHash,solver,dexId:ethers.id("LQC_FLOW"),amountOut:"1000",solverFeeOut:"5",gasCostOut:"5",routeHash,issuedAt:"5000300",deadline:String(change.expired?5000399:5000460),nonce:"7"},packetBody={status:"READY_FOR_SEPARATE_SOLVER_EIP712_REVIEW",network:{chainId:97},pilotPlanDigest:pilotPlan.pilotPlanDigest,submissionVerificationDigest:submissionVerification.submissionVerificationDigest,intentHash,routeHash,typedData:{domain:{verifyingContract:quoteManager},message:quote},quoteHash,quoteEconomics:{netAmountOut:"990"},transactionOccurred:false},solverQuotePacket={...packetBody,solverQuotePacketDigest:canonicalDigest(packetBody)};
  const sigBody={status:"VERIFIED_STAGE4_SOLVER_QUOTE_SIGNATURE",network:{chainId:97},solverQuotePacketDigest:solverQuotePacket.solverQuotePacketDigest,intentHash,routeHash,quoteHash,signature,signatureHash:ethers.keccak256(signature),transactionOccurred:false},solverQuoteSignatureVerification={...sigBody,solverQuoteSignatureVerificationDigest:canonicalDigest(sigBody)};
  const provider=(disagreement,gasDiff=false)=>({getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>800,getBlock:async()=>({hash:disagreement?ethers.id("other"):ethers.id("execution"),timestamp:5000400}),getCode:async target=>change.noCode?.toLowerCase()===target.toLowerCase()?"0x":"0x60016000",estimateGas:async()=>gasDiff?120000n:100000n,call:async tx=>{const selector=tx.data.slice(0,10),targetAddress=tx.to.toLowerCase();if(selector===hub.getFunction("executeSameChainIntent").selector)return hub.encodeFunctionResult("executeSameChainIntent",[BigInt(change.simulatedOut??1000)]);if(selector===hub.getFunction("settler").selector)return hub.encodeFunctionResult("settler",[settler]);if(selector===hub.getFunction("sourceEscrow").selector)return hub.encodeFunctionResult("sourceEscrow",[sourceEscrow]);if(selector===hub.getFunction("quoteManager").selector)return hub.encodeFunctionResult("quoteManager",[quoteManager]);if(selector===hub.getFunction("internalSolver").selector)return hub.encodeFunctionResult("internalSolver",[internalSolver]);if(selector===hub.getFunction("getIntent").selector)return hub.encodeFunctionResult("getIntent",[[user,sourceToken,1000n,97n,destinationToken,user,990n,5000600n,change.closed?2:1,ethers.ZeroAddress,0n,ethers.ZeroHash,ethers.ZeroHash,ethers.ZeroHash,ethers.ZeroHash]]);if(selector===escrow.getFunction("getDeposit").selector)return escrow.encodeFunctionResult("getDeposit",[[user,sourceToken,1000n,!change.inactiveDeposit]]);if(selector===qm.getFunction("verifyQuote").selector)return qm.encodeFunctionResult("verifyQuote",[change.badQuoteHash?ethers.id("bad"):quoteHash,990n]);if(selector===registry.getFunction("isSolverEligible").selector)return registry.encodeFunctionResult("isSolverEligible",[!change.ineligible]);if(selector===hub.getFunction("solverRegistry").selector){if(targetAddress===quoteManager.toLowerCase())return qm.encodeFunctionResult("solverRegistry",[solverRegistry]);return hub.encodeFunctionResult("solverRegistry",[solverRegistry]);}if(selector===hub.getFunction("paused").selector){const value=Boolean(change.paused);if(targetAddress===target.toLowerCase())return hub.encodeFunctionResult("paused",[value]);if(targetAddress===quoteManager.toLowerCase())return qm.encodeFunctionResult("paused",[value]);return registry.encodeFunctionResult("paused",[value]);}throw new Error(`Missing ${targetAddress}.${selector}`);}});
  return {providers:[provider(Boolean(change.rpcDisagreement)),provider(false,Boolean(change.gasDisagreement))],pilotPlan,submissionVerification,solverQuotePacket,solverQuoteSignatureVerification,expectedSolverQuoteSignatureVerificationDigest:solverQuoteSignatureVerification.solverQuoteSignatureVerificationDigest,addresses:{sourceToken}};
}
describe("LQC Intent Stage-4 same-chain execution preflight",function(){
  it("revalidates the OPEN Intent and simulates the exact execution on 2+ RPCs",async function(){const result=await preflightIntentStage4SameChainExecution(fixture());assert.equal(result.status,"READY_FOR_SEPARATE_SETTLER_EXECUTION");assert.equal(result.verifiedNetAmountOut,"990");assert.equal(result.simulatedAmountOut,"1000");assert.deepEqual(result.gasEstimates,["100000","100000"]);assert.equal(result.transactionOccurred,false);assert.match(result.executionPreflightDigest,/^sha256:[0-9a-f]{64}$/)});
  it("rejects unsafe state, stale quotes, failed simulation and RPC disagreement",async function(){for(const[change,pattern]of[[{paused:true},/paused/],[{ineligible:true},/eligible/],[{closed:true},/OPEN Intent/],[{inactiveDeposit:true},/deposit/],[{expired:true},/expired/],[{badQuoteHash:true},/quote verification/],[{simulatedOut:989},/output insufficient/],[{noCode:a(3)},/runtime/],[{rpcDisagreement:true},/RPC disagreement/],[{gasDisagreement:true},/gas estimate/]])await assert.rejects(preflightIntentStage4SameChainExecution(fixture(change)),pattern,JSON.stringify(change));const input=fixture();input.expectedSolverQuoteSignatureVerificationDigest="sha256:unreviewed";await assert.rejects(preflightIntentStage4SameChainExecution(input),/independently reviewed/)});
  it("contains no signing, wallet or transaction broadcast mechanism",function(){const source=fs.readFileSync(new URL("../scripts/preflight-intent-stage4-same-chain-execution.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/PRIVATE_KEY|signTypedData|eth_sendTransaction|sendTransaction/);assert.match(source,/eth_call simulation only/) });
});
