import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { prepareIntentStage4Submission } from "../scripts/prepare-intent-stage4-submission.mjs";

const types = { Intent: [{ name: "user", type: "address" }, { name: "sourceChainId", type: "uint256" }, { name: "sourceToken", type: "address" }, { name: "sourceAmount", type: "uint256" }, { name: "destinationChainId", type: "uint256" }, { name: "destinationToken", type: "address" }, { name: "recipient", type: "address" }, { name: "minAmountOut", type: "uint256" }, { name: "deadline", type: "uint256" }, { name: "nonce", type: "uint256" }, { name: "salt", type: "bytes32" }] };
async function fixture() {
  const wallet = ethers.Wallet.createRandom(), hubAddress = "0x0000000000000000000000000000000000000001", tokenIn = "0x0000000000000000000000000000000000000002", tokenOut = "0x0000000000000000000000000000000000000003", domain = { name: "LQC Intent Hub", version: "1", chainId: 97, verifyingContract: hubAddress }, message = { user: wallet.address, sourceChainId: "97", sourceToken: tokenIn, sourceAmount: "1000", destinationChainId: "97", destinationToken: tokenOut, recipient: wallet.address, minAmountOut: "990", deadline: "5000600", nonce: "12", salt: ethers.id("pilot-12") }, intentHash = ethers.TypedDataEncoder.hash(domain, types, message), signature = await wallet.signTypedData(domain, types, message);
  const packetBody = { status: "READY_FOR_SEPARATE_EIP712_WALLET_REVIEW", network: { chainId: 97 }, pilotPlanDigest: "sha256:pilot", typedData: { domain, types, primaryType: "Intent", message }, intentHash, walletReview: { expectedSigner: wallet.address, verifyingContract: hubAddress }, transactionOccurred: false }, signingPacket = { ...packetBody, signingPacketDigest: canonicalDigest(packetBody) };
  const verificationBody = { status: "VERIFIED_STAGE4_INTENT_SIGNATURE", network: { chainId: 97 }, signingPacketDigest: signingPacket.signingPacketDigest, pilotPlanDigest: signingPacket.pilotPlanDigest, intentHash, signer: wallet.address, signature, signatureHash: ethers.keccak256(signature), transactionOccurred: false }, signatureVerification = { ...verificationBody, signatureVerificationDigest: canonicalDigest(verificationBody) };
  return { signingPacket, signatureVerification, expectedSignatureVerificationDigest: signatureVerification.signatureVerificationDigest };
}

describe("LQC Intent Stage-4 submitIntent review plan", function () {
  it("encodes the exact reviewed Intent and public signature", async function () { const input = await fixture(), plan = prepareIntentStage4Submission(input), iface = new ethers.Interface(["function submitIntent((address user,uint256 sourceChainId,address sourceToken,uint256 sourceAmount,uint256 destinationChainId,address destinationToken,address recipient,uint256 minAmountOut,uint256 deadline,uint256 nonce,bytes32 salt),bytes)"]), decoded = iface.decodeFunctionData("submitIntent", plan.transaction.data); assert.equal(plan.status, "READY_FOR_FINAL_READ_ONLY_PREFLIGHT"); assert.equal(decoded[0].user, input.signingPacket.typedData.message.user); assert.equal(decoded[1], input.signatureVerification.signature); assert.equal(plan.transaction.value, "0"); assert.equal(plan.transactionOccurred, false); assert.match(plan.submissionPlanDigest, /^sha256:[0-9a-f]{64}$/); });
  it("rejects changed signature, signer, packet or independently reviewed digest", async function () { let input = await fixture(); input.signatureVerification.signature = `${input.signatureVerification.signature.slice(0, -2)}00`; assert.throws(() => prepareIntentStage4Submission(input), /verification|signature/); input = await fixture(); input.signatureVerification.signer = ethers.Wallet.createRandom().address; assert.throws(() => prepareIntentStage4Submission(input), /verification|binding/); input = await fixture(); input.expectedSignatureVerificationDigest = "sha256:other"; assert.throws(() => prepareIntentStage4Submission(input), /independently reviewed/); });
  it("contains no RPC, wallet, signing or send mechanism", function () { const source = fs.readFileSync(new URL("../scripts/prepare-intent-stage4-submission.mjs", import.meta.url), "utf8"); assert.doesNotMatch(source, /JsonRpcProvider|PRIVATE_KEY|signTypedData|eth_sendTransaction|sendTransaction/); assert.match(source, /Unsigned submission plan only/); });
});
