import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { verifyIntentStage4SameChainExecution } from "../scripts/verify-intent-stage4-same-chain-execution.mjs";

const qt="(bytes32 intentHash,address solver,bytes32 dexId,uint256 amountOut,uint256 solverFeeOut,uint256 gasCostOut,bytes32 routeHash,uint256 issuedAt,uint256 deadline,uint256 nonce)",hub=new ethers.Interface([`function executeSameChainIntent(bytes32,${qt},bytes,bytes) returns(uint256)`,"function getIntent(bytes32) view returns((address user,address sourceToken,uint256 sourceAmount,uint256 destinationChainId,address destinationToken,address recipient,uint256 minAmountOut,uint256 deadline,uint8 status,address solver,uint256 actualAmountOut,bytes32 destinationTxHash,bytes32 executionHash,bytes32 quoteHash,bytes32 routeHash))","event SameChainIntentExecuted(bytes32 indexed intentHash,address indexed solver,bytes32 indexed dexId,bytes32 quoteHash,bytes32 executionHash,uint256 actualAmountOut)"]),escrow=new ethers.Interface(["function getDeposit(bytes32) view returns((address user,address token,uint256 amount,bool active))","event SourceReleased(bytes32 indexed intentHash,address indexed solver,address indexed token,uint256 amount)"]),registry=new ethers.Interface(["function exposureSolver(bytes32) view returns(address)","function exposureAmount(bytes32) view returns(uint256)","function intentSolver(bytes32) view returns(address)","function exposureClosedAt(bytes32) view returns(uint256)","event ExposureOpened(bytes32 indexed intentHash,address indexed solver,uint256 amount)","event ExposureClosed(bytes32 indexed intentHash,address indexed solver,uint256 amount)"]),internal=new ethers.Interface(["function executionRouter() view returns(address)","event InternalRouteExecuted(bytes32 indexed intentHash,bytes32 indexed dexId,address indexed recipient,address tokenIn,address tokenOut,uint256 amountIn,uint256 amountOut)"]),token=new ethers.Interface(["function balanceOf(address) view returns(uint256)","function allowance(address,address) view returns(uint256)","event Transfer(address indexed from,address indexed to,uint256 value)"]),a=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`);
function log(address,encoded){return{address,topics:encoded.topics,data:encoded.data}}
function fixture(change={}){const user=a(1),target=a(2),sourceToken=a(3),destinationToken=a(4),sourceEscrow=a(5),solverRegistry=a(6),internalSolver=a(7),executionRouter=a(8),settler=a(9),solver=a(10),pool=a(11),intentHash=ethers.id("intent"),dexId=ethers.id("LQC_FLOW"),quoteHash=ethers.id("quote"),routeData=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[sourceToken,destinationToken]]),routeHash=ethers.keccak256(routeData),quote={intentHash,solver,dexId,amountOut:1000n,solverFeeOut:5n,gasCostOut:5n,routeHash,issuedAt:5000300n,deadline:5000460n,nonce:7n},signature=`0x${"11".repeat(65)}`,data=hub.encodeFunctionData("executeSameChainIntent",[intentHash,quote,signature,routeData]),actual=1000n,executionHash=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["bytes32","address","address","uint256","bytes32","bytes32","bytes32","uint256"],[intentHash,solver,internalSolver,97,dexId,quoteHash,routeHash,actual])),transactionHash=`0x${"55".repeat(32)}`;
  const body={status:"READY_FOR_SEPARATE_SETTLER_EXECUTION",network:{chainId:97},pilotPlanDigest:"sha256:pilot",submissionVerificationDigest:"sha256:submission",solverQuotePacketDigest:"sha256:quote-packet",solverQuoteSignatureVerificationDigest:"sha256:quote-signature",intentHash,quoteHash,routeHash,verifiedNetAmountOut:"990",addresses:{intentHub:target,sourceEscrow,solverRegistry,internalSolver,sourceToken,destinationToken},settler,transaction:{chainId:97,from:settler,to:target,value:"0",data},transactionOccurred:false},executionPreflight={...body,executionPreflightDigest:canonicalDigest(body)};
  const events=[log(target,hub.encodeEventLog("SameChainIntentExecuted",[intentHash,solver,dexId,quoteHash,executionHash,actual])),log(sourceEscrow,escrow.encodeEventLog("SourceReleased",[intentHash,internalSolver,sourceToken,1000n])),log(internalSolver,internal.encodeEventLog("InternalRouteExecuted",[intentHash,dexId,user,sourceToken,destinationToken,1000n,actual])),log(solverRegistry,registry.encodeEventLog("ExposureOpened",[intentHash,solver,1000n])),log(solverRegistry,registry.encodeEventLog("ExposureClosed",[intentHash,solver,1000n])),log(destinationToken,token.encodeEventLog("Transfer",[pool,user,change.badTransfer?999n:actual]))];
  const provider=disagreement=>({getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>102,getTransaction:async()=>({hash:transactionHash,from:settler,to:target,value:0n,data:change.badData?`0xdeadbeef${data.slice(10)}`:data}),getTransactionReceipt:async()=>({hash:transactionHash,from:settler,to:target,status:change.failed?0:1,blockNumber:change.weak?101:100,blockHash:disagreement?ethers.id("other"):ethers.id("executed"),logs:change.missingEvents?[]:events}),getBlock:async()=>({hash:disagreement?ethers.id("other"):ethers.id("executed")}),call:async tx=>{const s=tx.data.slice(0,10);if(s===hub.getFunction("getIntent").selector)return hub.encodeFunctionResult("getIntent",[[user,sourceToken,1000n,97n,destinationToken,user,990n,5000600n,change.open?1:2,solver,actual,ethers.ZeroHash,change.badExecutionHash?ethers.id("bad"):executionHash,quoteHash,routeHash]]);if(s===escrow.getFunction("getDeposit").selector)return escrow.encodeFunctionResult("getDeposit",[[user,sourceToken,1000n,Boolean(change.activeDeposit)]]);if(s===internal.getFunction("executionRouter").selector)return internal.encodeFunctionResult("executionRouter",[executionRouter]);if(s===registry.getFunction("exposureSolver").selector)return registry.encodeFunctionResult("exposureSolver",[change.openExposure?solver:ethers.ZeroAddress]);if(s===registry.getFunction("exposureAmount").selector)return registry.encodeFunctionResult("exposureAmount",[change.openExposure?1000n:0n]);if(s===registry.getFunction("intentSolver").selector)return registry.encodeFunctionResult("intentSolver",[solver]);if(s===registry.getFunction("exposureClosedAt").selector)return registry.encodeFunctionResult("exposureClosedAt",[700n]);if(s===token.getFunction("balanceOf").selector)return token.encodeFunctionResult("balanceOf",[change.residual?1n:0n]);if(s===token.getFunction("allowance").selector)return token.encodeFunctionResult("allowance",[0n]);throw new Error(`Missing ${s}`)}});
  return{providers:[provider(false),provider(Boolean(change.rpcDisagreement))],executionPreflight,expectedExecutionPreflightDigest:executionPreflight.executionPreflightDigest,transactionHash}}
describe("LQC Intent Stage-4 same-chain execution verification",function(){
  it("verifies canonical execution, recipient transfer, closed escrow and exposure",async function(){const result=await verifyIntentStage4SameChainExecution(fixture());assert.equal(result.status,"VERIFIED_STAGE4_SAME_CHAIN_EXECUTION");assert.equal(result.confirmations,3);assert.equal(result.intentStatus,"EXECUTED");assert.equal(result.recipientTransferAmount,"1000");assert.equal(result.transactionOccurred,true);assert.match(result.executionVerificationDigest,/^sha256:[0-9a-f]{64}$/)});
  it("rejects failed, changed, incomplete and disagreeing execution evidence",async function(){for(const[change,pattern]of[[{failed:true},/failed/],[{weak:true},/confirmations/],[{badData:true},/payload/],[{open:true},/executed Intent/],[{activeDeposit:true},/escrow/],[{openExposure:true},/exposure/],[{badExecutionHash:true},/execution hash/],[{residual:true},/retained/],[{missingEvents:true},/event/],[{badTransfer:true},/transfer/],[{rpcDisagreement:true},/disagreement/]])await assert.rejects(verifyIntentStage4SameChainExecution(fixture(change)),pattern,JSON.stringify(change));const input=fixture();input.expectedExecutionPreflightDigest="sha256:unreviewed";await assert.rejects(verifyIntentStage4SameChainExecution(input),/independently reviewed/)});
  it("contains no signing, wallet, settlement or transaction broadcast mechanism",function(){const source=fs.readFileSync(new URL("../scripts/verify-intent-stage4-same-chain-execution.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/PRIVATE_KEY|signTypedData|eth_sendTransaction|sendTransaction/);assert.match(source,/Read-only verification/) });
});
