import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest,sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { preflightIntentStage1AcrossRpcs } from "../scripts/preflight-intent-stage1-deployment.mjs";

describe("LQC Intent Stage-1 deployment preflight",function(){
  const deployer="0x0000000000000000000000000000000000000010",blockHash=ethers.id("block"),orderedActions=[0,1,2,3].map(index=>({id:index+1,actor:"deployer",action:`deploy-${index+1}`,to:null,value:"0",data:`0x60${index.toString(16).padStart(2,"0")}`})),manifest={network:{chainId:97},stage:"stage1-core-deploy",orderedActions},actionSummary=orderedActions.map(({id,actor,action,to,value,data})=>({id,actor,action,to,value,initCodeDigest:sha256(data),initCodeBytes:(data.length-2)/2})),reviewBody={status:"REVIEW_REQUIRED",network:{chainId:97},transactionOccurred:false,actions:actionSummary,sealDigest:sha256("seal")},review={...reviewBody,reviewDigest:canonicalDigest(reviewBody)};
  const provider=(options={})=>({getNetwork:async()=>({chainId:BigInt(options.chainId||97)}),getBlockNumber:async()=>205,getBlock:async()=>({hash:options.blockHash||blockHash,baseFeePerGas:1000000000n}),getTransactionCount:async()=>options.nonce??7,getBalance:async()=>options.balance??1000000000000000000n,getCode:async()=>options.code||"0x",estimateGas:async transaction=>{const index=orderedActions.findIndex(value=>value.data===transaction.data);return BigInt((options.gas||[100000,110000,120000,130000])[index]);}});
  it("agrees on one block, nonce, empty CREATE addresses and bounded gas",async function(){const result=await preflightIntentStage1AcrossRpcs({providers:[provider(),provider({gas:[101000,111000,121000,131000]})],review,manifest,deployer});assert.equal(result.status,"PREFLIGHT_VERIFIED_FOR_REVIEW");assert.equal(result.deployments.length,4);assert.equal(result.deployments[0].predictedAddress,ethers.getCreateAddress({from:deployer,nonce:7}));assert.equal(result.rpcCount,2);assert.equal(result.transactionOccurred,false);});
  it("rejects wrong chain, occupied address and RPC state disagreement",async function(){await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider(),provider({chainId:56})],review,manifest,deployer}),/chain/);await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider(),provider({code:"0x6000"})],review,manifest,deployer}),/already has code/);await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider(),provider({nonce:8})],review,manifest,deployer}),/disagreement/);});
  it("rejects material gas disagreement and a changed reviewed manifest",async function(){await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider(),provider({gas:[200000,110000,120000,130000]})],review,manifest,deployer}),/gas estimate/);const changed=structuredClone(manifest);changed.orderedActions[0].data="0x6009";await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider(),provider()],review,manifest:changed,deployer}),/changed/);});
  it("requires enough tBNB for the conservative four-deployment gas budget",async function(){await assert.rejects(preflightIntentStage1AcrossRpcs({providers:[provider({balance:1n}),provider({balance:1n})],review,manifest,deployer}),/insufficient/);});
});
