import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";

const artifact=(name,source)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${source}.sol/${name}.json`,import.meta.url)));

describe("LQC Intent v1 SettlementHub",function(){
  this.timeout(30000);
  const mnemonic="test test test test test test test test test test test junk",types={
    Intent:[{name:"user",type:"address"},{name:"sourceChainId",type:"uint256"},{name:"sourceToken",type:"address"},{name:"sourceAmount",type:"uint256"},{name:"destinationChainId",type:"uint256"},{name:"destinationToken",type:"address"},{name:"recipient",type:"address"},{name:"minAmountOut",type:"uint256"},{name:"deadline",type:"uint256"},{name:"nonce",type:"uint256"},{name:"salt",type:"bytes32"}],
    ExecutionReport:[{name:"intentHash",type:"bytes32"},{name:"solver",type:"address"},{name:"quoteHash",type:"bytes32"},{name:"signedRouteHash",type:"bytes32"},{name:"observedRouteHash",type:"bytes32"},{name:"expectedExecutionHash",type:"bytes32"},{name:"observedExecutionHash",type:"bytes32"},{name:"transactionHash",type:"bytes32"},{name:"blockHash",type:"bytes32"},{name:"canonicalReceiptHash",type:"bytes32"},{name:"minimumAmountOut",type:"uint256"},{name:"actualAmountOut",type:"uint256"},{name:"estimatedGas",type:"uint256"},{name:"gasUsed",type:"uint256"},{name:"priceImpactBps",type:"uint256"},{name:"marketDeviationBps",type:"uint256"},{name:"observedBlock",type:"uint256"},{name:"deadline",type:"uint256"}],
    FinalityAttestation:[{name:"destinationChainId",type:"uint256"},{name:"transactionHash",type:"bytes32"},{name:"blockHash",type:"bytes32"},{name:"canonicalReceiptHash",type:"bytes32"},{name:"observedBlock",type:"uint256"},{name:"finalizedBlock",type:"uint256"},{name:"observedAt",type:"uint256"},{name:"validUntil",type:"uint256"}]
  };
  let provider,owner,user,guardian,solver,attesterA,attesterB,userWallet,walletA,walletB,chainId,token,bond,registry,hub,escrow,verifier,finality,settlement;
  const deploy=async(name,source,signer,...args)=>{const a=artifact(name,source),c=await new ethers.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c};

  beforeEach(async function(){
    provider=new ethers.BrowserProvider(ganache.provider({wallet:{mnemonic},chain:{chainId:31337},logging:{quiet:true}}));owner=await provider.getSigner(0);user=await provider.getSigner(1);attesterA=await provider.getSigner(2);attesterB=await provider.getSigner(3);solver=await provider.getSigner(4);guardian=await provider.getSigner(5);userWallet=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/1");walletA=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/2");walletB=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/3");chainId=(await provider.getNetwork()).chainId;
    token=await deploy("MockERC20","mocks/MockERC20",owner,"Source","SRC");bond=await deploy("MockERC20","mocks/MockERC20",owner,"Bond","BOND");hub=await deploy("LQCIntentHub","intent-v1/LQCIntentHub",owner,await owner.getAddress(),await owner.getAddress(),await guardian.getAddress());escrow=new ethers.Contract(await hub.sourceEscrow(),artifact("LQCSourceEscrow","intent-v1/LQCSourceEscrow").abi,provider);verifier=await deploy("LQCExecutionVerifier","intent-v1/LQCExecutionVerifier",owner,await owner.getAddress(),await guardian.getAddress(),2,2000,500,300);await(await verifier.setAttester(await attesterA.getAddress(),true)).wait();await(await verifier.setAttester(await attesterB.getAddress(),true)).wait();finality=await deploy("LQCFinalityVerifier","intent-v1/LQCFinalityVerifier",owner,await owner.getAddress(),await guardian.getAddress(),2);await(await finality.setAttester(await attesterA.getAddress(),true)).wait();await(await finality.setAttester(await attesterB.getAddress(),true)).wait();await(await finality.setChainPolicy(97,3,3600,true)).wait();registry=await deploy("LQCSolverRegistry","intent-v1/LQCSolverRegistry",owner,await bond.getAddress(),await owner.getAddress(),await guardian.getAddress(),100n);await(await bond.mint(await solver.getAddress(),100n)).wait();await(await bond.connect(solver).approve(await registry.getAddress(),100n)).wait();await(await registry.connect(solver).depositBond(100n)).wait();await(await registry.configureSolver(await solver.getAddress(),true,10000n)).wait();await(await registry.setExecutionVerifier(await verifier.getAddress())).wait();settlement=await deploy("LQCSettlementHub","intent-v1/LQCSettlementHub",owner,await hub.getAddress(),await verifier.getAddress(),await registry.getAddress(),await finality.getAddress(),await owner.getAddress(),await guardian.getAddress(),await owner.getAddress(),3600);await(await registry.setExposureManager(await settlement.getAddress())).wait();await(await hub.setSettler(await settlement.getAddress())).wait();await assert.rejects(settlement.connect(user).acceptHubRole());await(await settlement.acceptHubRole()).wait();
  });

  const reportDomain=async()=>({name:"LQC Execution Verifier",version:"1",chainId,verifyingContract:await verifier.getAddress()});
  const finalityDomain=async()=>({name:"LQC Finality Verifier",version:"1",chainId,verifyingContract:await finality.getAddress()});
  async function reportSignatures(report){const reportTypes={ExecutionReport:types.ExecutionReport},pairs=[[await walletA.getAddress(),await walletA.signTypedData(await reportDomain(),reportTypes,report)],[await walletB.getAddress(),await walletB.signTypedData(await reportDomain(),reportTypes,report)]];return pairs.sort((a,b)=>a[0].toLowerCase().localeCompare(b[0].toLowerCase())).map(x=>x[1]);}
  async function submitIntent(nonce){const amount=ethers.parseEther("10"),block=await provider.getBlock("latest"),intent={user:await user.getAddress(),sourceChainId:chainId,sourceToken:await token.getAddress(),sourceAmount:amount,destinationChainId:97n,destinationToken:ethers.Wallet.createRandom().address,recipient:await user.getAddress(),minAmountOut:990n,deadline:BigInt(block.timestamp+10000),nonce:BigInt(nonce),salt:ethers.id(`settlement-${nonce}`)};await(await token.mint(await user.getAddress(),amount)).wait();await(await token.connect(user).approve(await escrow.getAddress(),amount)).wait();const signature=await userWallet.signTypedData({name:"LQC Intent Hub",version:"1",chainId,verifyingContract:await hub.getAddress()},{Intent:types.Intent},intent),intentHash=await hub.hashIntent(intent);await(await hub.submitIntent(intent,signature)).wait();return{amount,intent,intentHash};}
  async function verifiedReport(intentHash,index,changes={}){const block=await provider.getBlock("latest"),route=ethers.id(`route-${index}`),execution=ethers.id(`execution-${index}`),report={intentHash,solver:await solver.getAddress(),quoteHash:ethers.id(`quote-${index}`),signedRouteHash:route,observedRouteHash:route,expectedExecutionHash:execution,observedExecutionHash:execution,transactionHash:ethers.id(`tx-${index}`),blockHash:block.hash,canonicalReceiptHash:ethers.id(`receipt-${index}`),minimumAmountOut:990n,actualAmountOut:1000n,estimatedGas:100000n,gasUsed:110000n,priceImpactBps:100n,marketDeviationBps:100n,observedBlock:BigInt(block.number),deadline:BigInt(block.timestamp+7200),...changes},signatures=await reportSignatures(report),result=await verifier.submitReport.staticCall(report,signatures);await(await verifier.submitReport(report,signatures)).wait();const attestation={destinationChainId:97n,transactionHash:report.transactionHash,blockHash:report.blockHash,canonicalReceiptHash:report.canonicalReceiptHash,observedBlock:report.observedBlock,finalizedBlock:report.observedBlock+3n,observedAt:BigInt(block.timestamp),validUntil:BigInt(block.timestamp+600)},finalityTypes={FinalityAttestation:types.FinalityAttestation},pairs=[[await walletA.getAddress(),await walletA.signTypedData(await finalityDomain(),finalityTypes,attestation)],[await walletB.getAddress(),await walletB.signTypedData(await finalityDomain(),finalityTypes,attestation)]],finalitySignatures=pairs.sort((a,b)=>a[0].toLowerCase().localeCompare(b[0].toLowerCase())).map(x=>x[1]),finalityHash=await finality.submitAttestation.staticCall(attestation,finalitySignatures);await(await finality.submitAttestation(attestation,finalitySignatures)).wait();return{report,reportHash:result[0],reason:result[1],finalityHash};}
  async function reserve(intentHash,seconds=1800){const block=await provider.getBlock("latest");await(await settlement.reserveSettlement(intentHash,await solver.getAddress(),1000n,BigInt(block.timestamp+seconds))).wait();}

  it("locks Escrow during challenge and reimburses the Solver only after finalization",async function(){
    const value=await submitIntent(1);await reserve(value.intentHash,7200);const evidence=await verifiedReport(value.intentHash,1),solverBefore=await token.balanceOf(await solver.getAddress());await assert.rejects(settlement.proposeSettlement(evidence.report,ethers.id("wrong-finality")));await(await settlement.proposeSettlement(evidence.report,evidence.finalityHash)).wait();const pending=await settlement.getSettlement(value.intentHash),record=await hub.getIntent(value.intentHash);assert.equal(pending.status,2n);assert.equal(record.status,5n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,1000n);assert.equal((await escrow.getDeposit(value.intentHash)).active,true);assert.equal(await token.balanceOf(await solver.getAddress()),solverBefore);await assert.rejects(hub.connect(user).cancelIntent(value.intentHash));await assert.rejects(settlement.finalizeSettlement(value.intentHash));await provider.send("evm_increaseTime",[3601]);await provider.send("evm_mine",[]);await(await settlement.finalizeSettlement(value.intentHash,{gasLimit:500000n})).wait();assert.equal((await settlement.getSettlement(value.intentHash)).status,4n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,0n);assert.equal((await hub.getIntent(value.intentHash)).status,2n);assert.equal((await escrow.getDeposit(value.intentHash)).active,false);assert.equal((await token.balanceOf(await solver.getAddress()))-solverBefore,value.amount);await assert.rejects(settlement.finalizeSettlement(value.intentHash));
  });

  it("prevents transaction and canonical receipt reuse across Intents",async function(){
    const first=await submitIntent(2);await reserve(first.intentHash);const proof=await verifiedReport(first.intentHash,2);await(await settlement.proposeSettlement(proof.report,proof.finalityHash)).wait();const second=await submitIntent(3);await reserve(second.intentHash);const duplicate=await verifiedReport(second.intentHash,3,{transactionHash:proof.report.transactionHash,canonicalReceiptHash:proof.report.canonicalReceiptHash});await assert.rejects(settlement.proposeSettlement(duplicate.report,duplicate.finalityHash));assert.equal((await hub.getIntent(second.intentHash)).status,1n);assert.equal((await escrow.getDeposit(second.intentHash)).active,true);
  });

  it("uses a verified fault report to reject reimbursement and restore user control",async function(){
    const value=await submitIntent(4);await reserve(value.intentHash);const success=await verifiedReport(value.intentHash,4);await(await settlement.proposeSettlement(success.report,success.finalityHash)).wait();const fault=await verifiedReport(value.intentHash,5,{observedExecutionHash:ethers.id("forged-execution")});assert.equal(fault.reason,4n);await(await settlement.connect(user).challengeSettlement(value.intentHash,fault.reportHash)).wait();assert.equal((await settlement.getSettlement(value.intentHash)).status,3n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,0n);assert.equal((await hub.getIntent(value.intentHash)).status,1n);assert.equal((await escrow.getDeposit(value.intentHash)).active,true);await(await bond.mint(await user.getAddress(),1n)).wait();await(await bond.connect(user).approve(await registry.getAddress(),1n)).wait();const challengeId=await registry.connect(user).fileChallenge.staticCall(value.intentHash,4,fault.reportHash);await(await registry.connect(user).fileChallenge(value.intentHash,4,fault.reportHash)).wait();await(await registry.resolveChallengeWithVerifier(challengeId,5000)).wait();assert.equal((await registry.getSolver(await solver.getAddress())).bond,50n);const before=await token.balanceOf(await user.getAddress());await(await hub.connect(user).cancelIntent(value.intentHash)).wait();assert.equal((await token.balanceOf(await user.getAddress()))-before,value.amount);assert.equal(await token.balanceOf(await solver.getAddress()),0n);await assert.rejects(settlement.finalizeSettlement(value.intentHash));
  });

  it("pauses finalization without losing a retry after Governance recovery",async function(){
    const value=await submitIntent(6);await reserve(value.intentHash,7200);const evidence=await verifiedReport(value.intentHash,6);await(await settlement.proposeSettlement(evidence.report,evidence.finalityHash)).wait();await provider.send("evm_increaseTime",[3601]);await provider.send("evm_mine",[]);await(await settlement.connect(guardian).setPaused(true)).wait();await assert.rejects(settlement.finalizeSettlement(value.intentHash));assert.equal((await settlement.getSettlement(value.intentHash)).status,2n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,1000n);await assert.rejects(settlement.connect(guardian).setPaused(false));await(await settlement.setPaused(false)).wait();await(await settlement.finalizeSettlement(value.intentHash,{gasLimit:500000n})).wait();assert.equal((await hub.getIntent(value.intentHash)).status,2n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,0n);
  });

  it("expires an unproved reservation and releases Solver capacity without touching Escrow",async function(){
    const value=await submitIntent(7);await reserve(value.intentHash,60);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,1000n);await assert.rejects(settlement.connect(user).reserveSettlement(ethers.id("unauthorized"),await solver.getAddress(),1n,BigInt((await provider.getBlock("latest")).timestamp+60)));await provider.send("evm_increaseTime",[61]);await provider.send("evm_mine",[]);await(await settlement.expireReservation(value.intentHash,{gasLimit:300000n})).wait();assert.equal((await settlement.getSettlement(value.intentHash)).status,5n);assert.equal((await registry.getSolver(await solver.getAddress())).exposure,0n);assert.equal((await hub.getIntent(value.intentHash)).status,1n);assert.equal((await escrow.getDeposit(value.intentHash)).active,true);
  });
});
