import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest, sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { verifyIntentStage2DeploymentAcrossRpcs } from "../scripts/verify-intent-stage2-deployment.mjs";

describe("LQC Intent Stage-2 deployment verification", function () {
  const deployer = "0x0000000000000000000000000000000000000010", hub = "0x0000000000000000000000000000000000000020", router = "0x0000000000000000000000000000000000000030", governance = "0x0000000000000000000000000000000000000040", nonce = 9, txHash = ethers.id("stage2-deploy"), blockHash = ethers.id("stage2-deployment-block"), predictedAddress = ethers.getCreateAddress({ from: deployer, nonce }), action = { id: 1, actor: "deployer", action: "deploy-internal-solver", to: null, value: "0", data: "0x60006000" }, manifest = { network: { chainId: 97 }, stage: "stage2-solver-deploy", addresses: { LQCIntentHub: hub }, dependencies: { executionRouter: router }, roles: { governanceSafe: governance }, orderedActions: [action] };
  const reviewBody = { packageType: "LQC_INTENT_STAGE2_INTERNAL_SOLVER_REVIEW", status: "REVIEW_REQUIRED", network: { chainId: 97 }, readinessDigest: sha256("readiness"), dependencies: { intentHub: hub, executionRouter: router, governanceSafe: governance }, transactionOccurred: false }, review = { ...reviewBody, reviewDigest: canonicalDigest(reviewBody) };
  const preflightBody = { status: "PREFLIGHT_VERIFIED_FOR_INTERNAL_SOLVER_REVIEW", network: { chainId: 97 }, reviewDigest: review.reviewDigest, readinessDigest: review.readinessDigest, deployer, blockNumber: 490, blockHash: ethers.id("preflight"), deployerNonce: String(nonce), deployment: { action: action.action, predictedAddress, initCodeDigest: sha256(action.data) }, transactionOccurred: false }, preflight = { ...preflightBody, preflightDigest: canonicalDigest(preflightBody) };
  const view = new ethers.Interface(["function intentHub() view returns(address)", "function executionRouter() view returns(address)", "function administrator() view returns(address)"]);
  const provider = (options = {}) => ({ getNetwork: async () => ({ chainId: BigInt(options.chainId || 97) }), getBlockNumber: async () => options.head || 510, getTransaction: async hash => hash !== txHash ? null : { from: deployer, to: null, value: 0n, nonce, data: options.badData ? "0x6009" : action.data }, getTransactionReceipt: async hash => hash !== txHash ? null : { status: options.failed ? 0 : 1, contractAddress: options.badAddress ? ethers.ZeroAddress : predictedAddress, blockNumber: 500, blockHash, index: 0, gasUsed: 200000n, gasPrice: 1000000000n }, getBlock: async () => ({ hash: options.badBlock ? ethers.id("reorg") : blockHash }), getCode: async () => options.noCode ? "0x" : "0x6001600055", call: async tx => { const fn = view.getFunction(tx.data.slice(0, 10)).name, values = { intentHub: options.badBinding ? governance : hub, executionRouter: router, administrator: governance }; return view.encodeFunctionResult(fn, [values[fn]]); } });
  it("verifies one canonical Internal Solver deployment and immutable bindings", async function () { const result = await verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider()], review, manifest, preflight, transactionHash: txHash }); assert.equal(result.status, "VERIFIED_STAGE2_INTERNAL_SOLVER_DEPLOYMENT"); assert.equal(result.deployment.contractAddress, predictedAddress); assert.equal(result.deployment.intentHub, hub); assert.equal(result.deployment.confirmations, 11); assert.equal(result.transactionOccurred, true); assert.equal(result.verificationDigest, canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key]) => key !== "verificationDigest")))); });
  it("rejects init code, address, canonical block, runtime and immutable substitution", async function () { await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ badData: true })], review, manifest, preflight, transactionHash: txHash }), /init code/); await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ badAddress: true })], review, manifest, preflight, transactionHash: txHash }), /address/); await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ badBlock: true })], review, manifest, preflight, transactionHash: txHash }), /canonical/); await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ noCode: true })], review, manifest, preflight, transactionHash: txHash }), /runtime/); await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ badBinding: true })], review, manifest, preflight, transactionHash: txHash }), /immutable/); });
  it("rejects failed or weak-finality deployments and tampered preflight", async function () { await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider({ failed: true })], review, manifest, preflight, transactionHash: txHash }), /missing or failed/); await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider({ head: 501 }), provider({ head: 501 })], review, manifest, preflight, transactionHash: txHash }), /finality/); const changed = structuredClone(preflight); changed.deployerNonce = "10"; await assert.rejects(verifyIntentStage2DeploymentAcrossRpcs({ providers: [provider(), provider()], review, manifest, preflight: changed, transactionHash: txHash }), /preflight/); });
});
