import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest, sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { verifyIntentStage1DeploymentAcrossRpcs } from "../scripts/verify-intent-stage1-deployment.mjs";

describe("LQC Intent Stage-1 deployment verification", function () {
  const deployer = "0x0000000000000000000000000000000000000010", startingNonce = 7, blockHash = ethers.id("deployment-block"), hashes = [0, 1, 2, 3].map(index => ethers.id(`tx-${index}`));
  const orderedActions = [0, 1, 2, 3].map(index => ({ id: index + 1, actor: "deployer", action: `deploy-${index + 1}`, to: null, value: "0", data: `0x60${index.toString(16).padStart(2, "0")}` }));
  const manifest = { network: { chainId: 97 }, stage: "stage1-core-deploy", orderedActions };
  const reviewBody = { status: "REVIEW_REQUIRED", network: { chainId: 97 }, transactionOccurred: false, sealDigest: sha256("seal") }, review = { ...reviewBody, reviewDigest: canonicalDigest(reviewBody) };
  const deployments = orderedActions.map((action, index) => ({ id: action.id, action: action.action, predictedAddress: ethers.getCreateAddress({ from: deployer, nonce: startingNonce + index }), initCodeDigest: sha256(action.data) }));
  const preflight = { status: "PREFLIGHT_VERIFIED_FOR_REVIEW", network: { chainId: 97 }, transactionOccurred: false, reviewDigest: review.reviewDigest, deployer, deployerNonce: String(startingNonce), blockNumber: 190, blockHash: ethers.id("preflight"), deployments };
  const provider = (options = {}) => ({ getNetwork: async () => ({ chainId: BigInt(options.chainId || 97) }), getBlockNumber: async () => options.head || 210, getTransaction: async hash => { const index = hashes.indexOf(hash); return index < 0 ? null : { from: deployer, to: null, value: 0n, nonce: startingNonce + index, data: options.badData && index === 0 ? "0x6009" : orderedActions[index].data }; }, getTransactionReceipt: async hash => { const index = hashes.indexOf(hash); return index < 0 ? null : { status: options.failed && index === 0 ? 0 : 1, contractAddress: options.badAddress && index === 0 ? ethers.ZeroAddress : deployments[index].predictedAddress, blockNumber: 200 + index, blockHash, index, gasUsed: 100000n + BigInt(index), gasPrice: 1000000000n }; }, getBlock: async () => ({ hash: options.badBlock ? ethers.id("reorg") : blockHash }), getCode: async () => options.noCode ? "0x" : "0x6001600055" });
  it("verifies four ordered CREATE transactions across independent RPCs", async function () { const result = await verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider()], review, manifest, preflight, transactionHashes: hashes }); assert.equal(result.status, "VERIFIED_STAGE1_DEPLOYMENT"); assert.equal(result.deployments.length, 4); assert.equal(result.deployments[0].confirmations, 11); assert.equal(result.transactionOccurred, true); assert.equal(result.verificationDigest, canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key]) => key !== "verificationDigest")))); });
  it("rejects wrong init code, address, canonical block, and missing runtime", async function () { await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider({ badData: true })], review, manifest, preflight, transactionHashes: hashes }), /init code/); await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider({ badAddress: true })], review, manifest, preflight, transactionHashes: hashes }), /address/); await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider({ badBlock: true })], review, manifest, preflight, transactionHashes: hashes }), /canonical/); await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider({ noCode: true })], review, manifest, preflight, transactionHashes: hashes }), /runtime/); });
  it("rejects insufficient finality, failed receipts, and duplicate hashes", async function () { await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider({ head: 202 }), provider({ head: 202 })], review, manifest, preflight, transactionHashes: hashes }), /finality/); await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider({ failed: true })], review, manifest, preflight, transactionHashes: hashes }), /missing or failed/); await assert.rejects(verifyIntentStage1DeploymentAcrossRpcs({ providers: [provider(), provider()], review, manifest, preflight, transactionHashes: [hashes[0], hashes[0], hashes[2], hashes[3]] }), /unique/); });
});
