import assert from "node:assert/strict";
import {buildIntentReproducibilitySeal,canonicalDigest,sha256,validateBondSelection,verifyIntentReproducibilitySeal} from "../scripts/build-intent-reproducibility-seal.mjs";
import {buildIntentStage1Readiness} from "../scripts/build-intent-stage1-readiness.mjs";

describe("LQC Intent Stage-1 reproducibility seal",function(){
  const token="0x0000000000000000000000000000000000000010",inspection={schemaVersion:1,results:[{token,decimals:18,observedBlock:12345,network:{chainId:97},assessment:{eligible:true}}]},selection={network:{chainId:97},governanceSafe:"0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",approvedBondToken:token,approvalTransaction:`0x${"ab".repeat(32)}`,inspectionDigest:canonicalDigest(inspection)},verification={status:"VERIFIED",chainId:97,governanceSafe:selection.governanceSafe,approvedBondToken:token,inspectionDigest:selection.inspectionDigest,transactionHash:selection.approvalTransaction,selectionContract:"0x0000000000000000000000000000000000000020",safeTransactionHash:`0x${"cd".repeat(32)}`,nonce:"7",rpcCount:2,confirmations:3,transactionOccurred:true},digest=sha256("fixture"),contracts=["LQCIntentHub","LQCQuoteManager","LQCSolverRegistry","LQCExecutionVerifier"];
  const input=()=>{const canonicalSelection={...selection,status:"PENDING_MULTI_RPC_VERIFICATION",verificationRequired:true,transactionOccurred:true,selectionContract:verification.selectionContract,safeTransactionHash:verification.safeTransactionHash,safeNonce:verification.nonce};return{sourceRevision:"a".repeat(40),nodeVersion:"v22.0.0",packageLockDigest:digest,compilerVersion:"0.8.30+commit.73712a01",selection:canonicalSelection,inspection,selectionVerification:verification,stage1Readiness:buildIntentStage1Readiness({selection:canonicalSelection,inspection,verification}),sourceFiles:[{path:"contracts/intent-v1/A.sol",digest}],artifacts:contracts.map(contract=>({contract,abiDigest:digest,bytecodeDigest:digest,deployedBytecodeDigest:digest})),stage1Actions:contracts.map((contract,index)=>({action:`deploy-${contract}`,data:`0x60${index.toString(16).padStart(2,"0")}`}))};};
  it("binds the unique eligible Governance-selected token to all Stage-1 init code",function(){const seal=buildIntentReproducibilitySeal(input());assert.equal(seal.bondSelection.token,token);assert.equal(seal.stage1InitCode.length,4);assert.equal(seal.transactionOccurred,false);assert.equal(verifyIntentReproducibilitySeal(seal),true);});
  it("rejects a selection whose inspection digest or eligibility does not match",function(){assert.throws(()=>validateBondSelection({...selection,inspectionDigest:sha256("wrong")},inspection),/digest/);assert.throws(()=>validateBondSelection(selection,{...inspection,results:[{...inspection.results[0],assessment:{eligible:false}}]}),/digest|eligible/);});
  it("detects source, artifact, init-code and governance tampering",function(){for(const mutate of[seal=>seal.sourceFiles[0].digest=sha256("source"),seal=>seal.artifacts[0].bytecodeDigest=sha256("bytecode"),seal=>seal.stage1InitCode[0].initCodeDigest=sha256("init"),seal=>seal.governance.threshold=3]){const seal=structuredClone(buildIntentReproducibilitySeal(input()));mutate(seal);assert.equal(verifyIntentReproducibilitySeal(seal),false);}});
  it("requires the exact four reviewed Stage-1 artifacts",function(){const value=input();value.artifacts.pop();assert.throws(()=>buildIntentReproducibilitySeal(value),/artifacts/);});
  it("requires a matching multi-RPC approval verification",function(){const value=input();delete value.selectionVerification;assert.throws(()=>buildIntentReproducibilitySeal(value),/verification/);const weak=input();weak.selectionVerification={...verification,rpcCount:1};assert.throws(()=>buildIntentReproducibilitySeal(weak),/verification/);});
  it("requires the exact Stage-1 readiness decision",function(){const value=input();delete value.stage1Readiness;assert.throws(()=>buildIntentReproducibilitySeal(value),/readiness/);const changed=input();changed.stage1Readiness.safeNonce="8";assert.throws(()=>buildIntentReproducibilitySeal(changed),/digest|binding/);});
  it("rejects a recomputed seal containing forged readiness",function(){const seal=buildIntentReproducibilitySeal(input());seal.stage1Readiness.safeNonce="8";const readinessBody={...seal.stage1Readiness};delete readinessBody.readinessDigest;seal.stage1Readiness.readinessDigest=canonicalDigest(readinessBody);const{sealDigest,...body}=seal;seal.sealDigest=canonicalDigest(body);assert.equal(verifyIntentReproducibilitySeal(seal),false);});
  it("rejects a recomputed seal that weakens the embedded verification policy",function(){const seal=buildIntentReproducibilitySeal(input());seal.bondSelectionVerification.rpcCount=1;const{sealDigest,...body}=seal;seal.sealDigest=canonicalDigest(body);assert.equal(verifyIntentReproducibilitySeal(seal),false);});
});
