import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import {buildExecutionReport,buildExecutionReportSubmission,collectCanonicalExecution,signExecutionReport} from "../scripts/prepare-intent-execution-report.mjs";

describe("LQC Intent v1 multi-RPC execution report preparation",function(){
  const hub="0x0000000000000000000000000000000000000010",solver="0x0000000000000000000000000000000000000011",transactionHash=ethers.id("tx"),blockHash=ethers.id("block"),sender="0x0000000000000000000000000000000000000012",data="0x12345678";
  const provider=(overrides={})=>({getNetwork:async()=>({chainId:97n}),getTransactionReceipt:async()=>({status:1,hash:transactionHash,blockHash,blockNumber:100,gasUsed:120000n,gasPrice:3n}),getTransaction:async()=>({from:sender,to:hub,data}),getBlockNumber:async()=>102,getBlock:async()=>({hash:blockHash}),...overrides});
  const evidence={intentHash:ethers.id("intent"),solver,quoteHash:ethers.id("quote"),signedRouteHash:ethers.id("route"),observedRouteHash:ethers.id("route"),expectedExecutionHash:ethers.id("execution"),observedExecutionHash:ethers.id("execution"),minimumAmountOut:"990",actualAmountOut:"995",estimatedGas:"110000",priceImpactBps:"50",marketDeviationBps:"40",deadline:1789000100};

  it("requires two agreeing finalized RPC observations",async function(){const canonical=await collectCanonicalExecution({providers:[provider(),provider()],transactionHash,hub});assert.equal(canonical.rpcCount,2);assert.equal(canonical.confirmations,3);assert.equal(canonical.gasUsed,"120000");assert.equal(ethers.isHexString(canonical.canonicalReceiptHash,32),true);await assert.rejects(collectCanonicalExecution({providers:[provider(),provider({getBlock:async()=>({hash:ethers.id("reorg")})})],transactionHash,hub}),/canonical/);await assert.rejects(collectCanonicalExecution({providers:[provider({getBlockNumber:async()=>101}),provider()],transactionHash,hub}),/finality/);});
  it("builds a bounded report using mined gas instead of caller gas",async function(){const canonical=await collectCanonicalExecution({providers:[provider(),provider()],transactionHash,hub}),report=buildExecutionReport(evidence,canonical,1789000000);assert.equal(report.gasUsed,120000n);assert.equal(report.observedBlock,100n);assert.equal(report.canonicalReceiptHash,canonical.canonicalReceiptHash);assert.throws(()=>buildExecutionReport({...evidence,deadline:1789001000},canonical,1789000000),/bounds/);});
  it("sorts distinct attesters and creates exact submitReport calldata",async function(){const canonical=await collectCanonicalExecution({providers:[provider(),provider()],transactionHash,hub}),report=buildExecutionReport(evidence,canonical,1789000000),wallets=[ethers.Wallet.createRandom(),ethers.Wallet.createRandom()],verifierAddress="0x0000000000000000000000000000000000000020",signed=await signExecutionReport(report,{verifierAddress,wallets}),artifact=JSON.parse(fs.readFileSync(new URL("../artifacts/contracts/intent-v1/LQCExecutionVerifier.sol/LQCExecutionVerifier.json",import.meta.url))),submission=buildExecutionReportSubmission(report,signed,artifact.abi),decoded=new ethers.Interface(artifact.abi).decodeFunctionData("submitReport",submission.data);assert.deepEqual(submission.attesters,[...submission.attesters].sort());assert.equal(decoded[0].intentHash,report.intentHash);assert.equal(decoded[1].length,2);assert.equal(submission.transactionOccurred,false);await assert.rejects(signExecutionReport(report,{verifierAddress,wallets:[wallets[0],wallets[0]]}),/Duplicate/);});
});
