import assert from "node:assert/strict";
import { ethers } from "ethers";
import { canonicalDigest, sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage3Readiness } from "../scripts/build-intent-stage3-readiness.mjs";

describe("LQC Intent Stage-3 governance binding readiness", function () {
  const a = n => ethers.getAddress(`0x${n.toString(16).padStart(40, "0")}`), governance = a(10), risk = a(11), guardian = a(12), treasury = a(13), bond = a(14), router = a(15), hub = a(20), quote = a(21), registry = a(22), verifier = a(23), solver = a(24), escrow = a(25), attesters = [a(30), a(31)];
  const policy = { attesterQuorum: 2, maxGasOverrunBps: 2000, maxPriceImpactBps: 500, maxMarketDeviationBps: 300, minimumBond: ethers.parseUnits("10000", 18).toString(), solverExposureLimit: ethers.parseUnits("1000", 18).toString() }, roles = { governanceSafe: governance, riskSafe: risk, guardianSafe: guardian, treasurySafe: treasury }, addresses = { LQCIntentHub: hub, LQCQuoteManager: quote, LQCSolverRegistry: registry, LQCExecutionVerifier: verifier, LQCInternalSolver: solver };
  const deploymentBody = { status: "VERIFIED_STAGE2_INTERNAL_SOLVER_DEPLOYMENT", network: { chainId: 97 }, transactionOccurred: true, deployment: { contractAddress: solver, intentHub: hub, executionRouter: router, administrator: governance } }, deployment = { ...deploymentBody, verificationDigest: canonicalDigest(deploymentBody) }, manifest = { network: { chainId: 97 }, stage: "stage3-governance-bindings", dryRun: { transactionOccurred: false }, addresses, roles, dependencies: { bondToken: bond, executionRouter: router }, policy, attesters };
  const abi = new ethers.Interface(["function owner() view returns(address)", "function settler() view returns(address)", "function guardian() view returns(address)", "function sourceEscrow() view returns(address)", "function controller() view returns(address)", "function quoteManager() view returns(address)", "function solverRegistry() view returns(address)", "function internalSolver() view returns(address)", "function pendingInternalSolver() view returns(address)", "function exposureManager() view returns(address)", "function executionVerifier() view returns(address)", "function resolver() view returns(address)", "function slashRecipient() view returns(address)", "function bondToken() view returns(address)", "function minimumBond() view returns(uint256)", "function challengeBond() view returns(uint256)", "function quorum() view returns(uint256)", "function maxGasOverrunBps() view returns(uint256)", "function maxPriceImpactBps() view returns(uint256)", "function maxMarketDeviationBps() view returns(uint256)", "function paused() view returns(bool)", "function attesterEnabled(address) view returns(bool)", "function intentHub() view returns(address)", "function executionRouter() view returns(address)", "function administrator() view returns(address)"]);
  const provider = (change = {}) => ({ getNetwork: async () => ({ chainId: BigInt(change.chainId || 97) }), getBlockNumber: async () => 700, getBlock: async () => ({ hash: change.blockHash || ethers.id("stage3") }), getCode: async target => change.noCode === target ? "0x" : "0x60016000", call: async tx => { const fn = abi.getFunction(tx.data.slice(0, 10)).name, target = tx.to.toLowerCase(), zero = ethers.ZeroAddress, state = { [hub.toLowerCase()]: { owner: governance, settler: risk, guardian, sourceEscrow: escrow, quoteManager: zero, solverRegistry: zero, internalSolver: zero, pendingInternalSolver: zero, paused: false }, [quote.toLowerCase()]: { owner: governance, guardian, solverRegistry: zero, paused: false }, [registry.toLowerCase()]: { owner: governance, guardian, bondToken: bond, minimumBond: BigInt(policy.minimumBond), challengeBond: BigInt(policy.minimumBond) / 100n, resolver: governance, slashRecipient: governance, exposureManager: zero, executionVerifier: zero, paused: false }, [verifier.toLowerCase()]: { owner: governance, guardian, quorum: 2n, maxGasOverrunBps: 2000n, maxPriceImpactBps: 500n, maxMarketDeviationBps: 300n, paused: false, attesterEnabled: false }, [solver.toLowerCase()]: { intentHub: hub, executionRouter: router, administrator: governance }, [escrow.toLowerCase()]: { controller: hub } }; let value = state[target]?.[fn]; if (change.target?.toLowerCase() === target && change.field === fn) value = change.value; if (value === undefined) throw new Error(`Missing ${target}.${fn}`); return abi.encodeFunctionResult(fn, [value]); } });
  it("admits only verified pristine contracts into Governance binding review", async function () { const result = await buildIntentStage3Readiness({ providers: [provider(), provider()], deployment, manifest }); assert.equal(result.status, "READY_FOR_GOVERNANCE_BINDING_REVIEW"); assert.equal(result.addresses.LQCInternalSolver, solver); assert.equal(result.transactionOccurred, false); assert.equal(result.readinessDigest, canonicalDigest(Object.fromEntries(Object.entries(result).filter(([key]) => key !== "readinessDigest")))); });
  it("rejects premature binding, changed immutable, missing runtime and RPC disagreement", async function () { await assert.rejects(buildIntentStage3Readiness({ providers: [provider({ target: hub, field: "quoteManager", value: quote }), provider({ target: hub, field: "quoteManager", value: quote })], deployment, manifest }), /pristine/); await assert.rejects(buildIntentStage3Readiness({ providers: [provider({ target: solver, field: "executionRouter", value: bond }), provider({ target: solver, field: "executionRouter", value: bond })], deployment, manifest }), /Solver binding/); await assert.rejects(buildIntentStage3Readiness({ providers: [provider(), provider({ noCode: solver })], deployment, manifest }), /runtime/); await assert.rejects(buildIntentStage3Readiness({ providers: [provider(), provider({ blockHash: ethers.id("fork") })], deployment, manifest }), /disagreement/); });
  it("rejects role, policy, enabled attester and tampered Stage-2 evidence", async function () { await assert.rejects(buildIntentStage3Readiness({ providers: [provider({ target: hub, field: "owner", value: risk }), provider({ target: hub, field: "owner", value: risk })], deployment, manifest }), /role/); await assert.rejects(buildIntentStage3Readiness({ providers: [provider({ target: verifier, field: "quorum", value: 3n }), provider({ target: verifier, field: "quorum", value: 3n })], deployment, manifest }), /policy/); await assert.rejects(buildIntentStage3Readiness({ providers: [provider({ target: verifier, field: "attesterEnabled", value: true }), provider({ target: verifier, field: "attesterEnabled", value: true })], deployment, manifest }), /pristine/); const changed = structuredClone(deployment); changed.deployment.contractAddress = a(99); await assert.rejects(buildIntentStage3Readiness({ providers: [provider(), provider()], deployment: changed, manifest }), /verification/); });
});
