import assert from "node:assert/strict";
import { buildIntentReproducibilitySeal,canonicalDigest,sha256 } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildIntentStage1Readiness } from "../scripts/build-intent-stage1-readiness.mjs";
import { verifyIntentStage1SealAgainstBuild } from "../scripts/verify-intent-stage1-seal.mjs";

describe("LQC Intent Stage-1 seal build verification",function(){
  const safe="0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",token="0x0000000000000000000000000000000000000030",contract="0x0000000000000000000000000000000000000020",tx=`0x${"ab".repeat(32)}`,safeTx=`0x${"cd".repeat(32)}`,digest=sha256("fixture"),revision="a".repeat(40),compilerVersion="0.8.30+commit.73712a01",contracts=["LQCIntentHub","LQCQuoteManager","LQCSolverRegistry","LQCExecutionVerifier"],inspection={results:[{token,decimals:18,observedBlock:123,network:{chainId:97},assessment:{eligible:true}}]};
  const fixture=()=>{const inspectionDigest=canonicalDigest(inspection),selection={status:"PENDING_MULTI_RPC_VERIFICATION",verificationRequired:true,transactionOccurred:true,network:{chainId:97},governanceSafe:safe,approvedBondToken:token,selectionContract:contract,inspectionDigest,approvalTransaction:tx,safeTransactionHash:safeTx,safeNonce:"7"},verification={status:"VERIFIED",chainId:97,governanceSafe:safe,approvedBondToken:token,selectionContract:contract,inspectionDigest,transactionHash:tx,safeTransactionHash:safeTx,nonce:"7",rpcCount:2,confirmations:3,transactionOccurred:true},readiness=buildIntentStage1Readiness({selection,inspection,verification}),sourceFiles=[{path:"contracts/intent-v1/A.sol",digest}],artifacts=contracts.map(contractName=>({contract:contractName,abiDigest:digest,bytecodeDigest:digest,deployedBytecodeDigest:digest})),stage1Actions=contracts.map((name,index)=>({action:`deploy-${name}`,data:`0x60${index.toString(16).padStart(2,"0")}`})),seal=buildIntentReproducibilitySeal({sourceRevision:revision,nodeVersion:"v22.0.0",packageLockDigest:digest,compilerVersion,selection,inspection,selectionVerification:verification,stage1Readiness:readiness,sourceFiles,artifacts,stage1Actions});return{seal,readiness,sourceRevision:revision,packageLockDigest:digest,compilerVersion,sourceFiles,artifacts,stage1Actions};};
  it("verifies the exact clean build without authorizing deployment",function(){const result=verifyIntentStage1SealAgainstBuild(fixture());assert.equal(result.status,"VERIFIED_FOR_STAGE1_DEPLOYMENT_REVIEW");assert.equal(result.stage1ContractCount,4);assert.equal(result.transactionOccurred,false);assert.match(result.safety,/does not authorize/i);});
  it("rejects source revision, package lock and compiler substitution",function(){for(const mutate of[value=>value.sourceRevision="b".repeat(40),value=>value.packageLockDigest=sha256("lock"),value=>value.compilerVersion="0.8.31"]){const value=fixture();mutate(value);assert.throws(()=>verifyIntentStage1SealAgainstBuild(value),/environment/);}});
  it("rejects readiness, source, artifact and init-code substitution",function(){for(const mutate of[value=>value.readiness.safeNonce="8",value=>value.sourceFiles[0].digest=sha256("source"),value=>value.artifacts[0].bytecodeDigest=sha256("artifact"),value=>value.stage1Actions[0].data="0x6009"]){const value=fixture();mutate(value);assert.throws(()=>verifyIntentStage1SealAgainstBuild(value),/readiness|source, artifact, or init code/);}});
});
