import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";

const artifact=(name,source)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${source}.sol/${name}.json`,import.meta.url)));

describe("LQC Intent v1 Composite Coordinator",function(){
  this.timeout(30000);
  const mnemonic="test test test test test test test test test test test junk",types={
    Intent:[{name:"user",type:"address"},{name:"sourceChainId",type:"uint256"},{name:"sourceToken",type:"address"},{name:"sourceAmount",type:"uint256"},{name:"destinationChainId",type:"uint256"},{name:"destinationToken",type:"address"},{name:"recipient",type:"address"},{name:"minAmountOut",type:"uint256"},{name:"deadline",type:"uint256"},{name:"nonce",type:"uint256"},{name:"salt",type:"bytes32"}],
    SolverQuote:[{name:"intentHash",type:"bytes32"},{name:"solver",type:"address"},{name:"dexId",type:"bytes32"},{name:"amountOut",type:"uint256"},{name:"solverFeeOut",type:"uint256"},{name:"gasCostOut",type:"uint256"},{name:"routeHash",type:"bytes32"},{name:"issuedAt",type:"uint256"},{name:"deadline",type:"uint256"},{name:"nonce",type:"uint256"}]
  };
  let provider,owner,user,guardian,ownerWallet,userWallet,chainId,tokenIn,tokenOut,flow,dexRegistry,executionRouter,vault,hub,escrow,bond,solverRegistry,quoteManager,planValidator,adapterRegistry,coordinator,executor,routerAdapter,vaultAdapter,dexId,swapRoute;
  const deploy=async(name,source,signer,...args)=>{const a=artifact(name,source),c=await new ethers.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c};

  beforeEach(async function(){
    provider=new ethers.BrowserProvider(ganache.provider({wallet:{mnemonic},chain:{chainId:31337},logging:{quiet:true}}));owner=await provider.getSigner(0);user=await provider.getSigner(1);guardian=await provider.getSigner(2);ownerWallet=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/0");userWallet=ethers.HDNodeWallet.fromPhrase(mnemonic,undefined,"m/44'/60'/0'/0/1");chainId=(await provider.getNetwork()).chainId;
    tokenIn=await deploy("MockERC20","mocks/MockERC20",owner,"Input","IN");tokenOut=await deploy("MockERC20","mocks/MockERC20",owner,"Output","OUT");const wbnb=await deploy("MockWBNB","mocks/MockWBNB",owner),factory=await deploy("LQCFlowFactory","LQCFlowFactory",owner,await owner.getAddress());flow=await deploy("LQCFlowRouter","LQCFlowRouter",owner,await factory.getAddress(),await wbnb.getAddress());dexRegistry=await deploy("LQCDexRegistry","router-v2/LQCDexRegistry",owner,await owner.getAddress());executionRouter=await deploy("LQCExecutionRouter","router-v2/LQCExecutionRouter",owner,await dexRegistry.getAddress(),ethers.ZeroAddress);const flowAdapter=await deploy("LQCFlowAdapter","router-v2/adapters/LQCFlowAdapter",owner,await flow.getAddress());dexId=ethers.id("LQC_FLOW");await(await dexRegistry.addDex(dexId,await flowAdapter.getAddress(),"LQC Flow",100)).wait();
    const liquidity=ethers.parseEther("10000"),liquidityDeadline=BigInt((await provider.getBlock("latest")).timestamp+3600);await(await tokenIn.mint(await owner.getAddress(),liquidity)).wait();await(await tokenOut.mint(await owner.getAddress(),liquidity)).wait();await(await tokenIn.approve(await flow.getAddress(),liquidity)).wait();await(await tokenOut.approve(await flow.getAddress(),liquidity)).wait();await(await flow.addLiquidity(await tokenIn.getAddress(),await tokenOut.getAddress(),liquidity,liquidity,0,0,await owner.getAddress(),liquidityDeadline)).wait();swapRoute=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[await tokenIn.getAddress(),await tokenOut.getAddress()]]);
    hub=await deploy("LQCIntentHub","intent-v1/LQCIntentHub",owner,await owner.getAddress(),await owner.getAddress(),await guardian.getAddress());escrow=new ethers.Contract(await hub.sourceEscrow(),artifact("LQCSourceEscrow","intent-v1/LQCSourceEscrow").abi,provider);bond=await deploy("MockERC20","mocks/MockERC20",owner,"Bond","BOND");solverRegistry=await deploy("LQCSolverRegistry","intent-v1/LQCSolverRegistry",owner,await bond.getAddress(),await owner.getAddress(),await guardian.getAddress(),ethers.parseEther("100"));quoteManager=await deploy("LQCQuoteManager","intent-v1/LQCQuoteManager",owner,await owner.getAddress(),await guardian.getAddress());await(await bond.mint(await owner.getAddress(),ethers.parseEther("100"))).wait();await(await bond.approve(await solverRegistry.getAddress(),ethers.parseEther("100"))).wait();await(await solverRegistry.depositBond(ethers.parseEther("100"))).wait();await(await solverRegistry.configureSolver(await owner.getAddress(),true,ethers.parseEther("1000"))).wait();await(await solverRegistry.setExposureManager(await hub.getAddress())).wait();await(await quoteManager.setSolverRegistry(await solverRegistry.getAddress())).wait();await(await hub.setQuoteManager(await quoteManager.getAddress())).wait();await(await hub.setSolverRegistry(await solverRegistry.getAddress())).wait();
    vault=await deploy("LQCLiquidityVault","vault/LQCLiquidityVault",owner,await tokenOut.getAddress(),await owner.getAddress(),ethers.parseEther("1000000"),"Output Vault","vOUT");planValidator=await deploy("LQCCompositePlan","intent-v1/LQCCompositePlan",owner);adapterRegistry=await deploy("LQCCompositeAdapterRegistry","intent-v1/LQCCompositeAdapterRegistry",owner,await owner.getAddress(),await guardian.getAddress());coordinator=await deploy("LQCCompositeCoordinator","intent-v1/LQCCompositeCoordinator",owner,await hub.getAddress(),await planValidator.getAddress(),await adapterRegistry.getAddress(),await owner.getAddress());executor=new ethers.Contract(await coordinator.executor(),artifact("LQCCompositeExecutor","intent-v1/LQCCompositeExecutor").abi,provider);routerAdapter=await deploy("LQCCompositeRouterAdapter","intent-v1/LQCCompositeRouterAdapter",owner,await executor.getAddress(),await executionRouter.getAddress());vaultAdapter=await deploy("LQCCompositeVaultAdapter","intent-v1/LQCCompositeVaultAdapter",owner,await executor.getAddress(),await vault.getAddress());await(await adapterRegistry.registerAdapter(await routerAdapter.getAddress(),0)).wait();await(await adapterRegistry.registerAdapter(await vaultAdapter.getAddress(),1)).wait();await(await hub.setInternalSolver(await coordinator.getAddress())).wait();await assert.rejects(coordinator.connect(user).acceptHubRole());await(await coordinator.acceptHubRole()).wait();
  });

  async function prepare(nonce,{finalMinimum}={}){
    const amountIn=ethers.parseEther("10"),swapQuote=(await flow.getAmountsOut(amountIn,[await tokenIn.getAddress(),await tokenOut.getAddress()]))[1],block=await provider.getBlock("latest"),deadline=BigInt(block.timestamp+300),minimum=finalMinimum??swapQuote-1000n,swapPayload=ethers.AbiCoder.defaultAbiCoder().encode(["bytes32","uint256","bytes"],[dexId,deadline,swapRoute]),actions=[
      {kind:0,adapter:await routerAdapter.getAddress(),tokenIn:await tokenIn.getAddress(),tokenOut:await tokenOut.getAddress(),minAmountOut:swapQuote*99n/100n,dataHash:ethers.keccak256(swapPayload)},
      {kind:1,adapter:await vaultAdapter.getAddress(),tokenIn:await tokenOut.getAddress(),tokenOut:await vault.getAddress(),minAmountOut:minimum,dataHash:ethers.keccak256("0x")}
    ],routeData=ethers.AbiCoder.defaultAbiCoder().encode(["tuple(uint8 kind,address adapter,address tokenIn,address tokenOut,uint256 minAmountOut,bytes32 dataHash)[]","bytes[]"],[actions,[swapPayload,"0x"]]),intent={user:await user.getAddress(),sourceChainId:chainId,sourceToken:await tokenIn.getAddress(),sourceAmount:amountIn,destinationChainId:chainId,destinationToken:await vault.getAddress(),recipient:await user.getAddress(),minAmountOut:minimum,deadline,nonce:BigInt(nonce),salt:ethers.id(`composite-${nonce}`)};
    await(await tokenIn.mint(await user.getAddress(),amountIn)).wait();await(await tokenIn.connect(user).approve(await escrow.getAddress(),amountIn)).wait();const intentSignature=await userWallet.signTypedData({name:"LQC Intent Hub",version:"1",chainId,verifyingContract:await hub.getAddress()},{Intent:types.Intent},intent),intentHash=await hub.hashIntent(intent);await(await hub.submitIntent(intent,intentSignature)).wait();const compositeDexId=await coordinator.COMPOSITE_DEX_ID(),solverQuote={intentHash,solver:await owner.getAddress(),dexId:compositeDexId,amountOut:minimum,solverFeeOut:0n,gasCostOut:0n,routeHash:ethers.keccak256(routeData),issuedAt:BigInt(block.timestamp),deadline:BigInt(block.timestamp+60),nonce:BigInt(nonce)},quoteSignature=await ownerWallet.signTypedData({name:"LQC Solver Quote Manager",version:"1",chainId,verifyingContract:await quoteManager.getAddress()},{SolverQuote:types.SolverQuote},solverQuote);return{amountIn,swapQuote,minimum,deadline,actions,routeData,intentHash,solverQuote,quoteSignature};
  }

  it("atomically releases escrow and completes a Router-to-Vault Intent",async function(){
    const value=await prepare(1),[planHash]=await planValidator.validateAndHash(value.intentHash,await tokenIn.getAddress(),await vault.getAddress(),await user.getAddress(),value.minimum,value.deadline,value.actions);await(await hub.executeSameChainIntent(value.intentHash,value.solverQuote,value.quoteSignature,value.routeData)).wait();const record=await hub.getIntent(value.intentHash),deposit=await escrow.getDeposit(value.intentHash);assert.equal(record.status,2n);assert.equal(record.actualAmountOut,value.minimum);assert.equal(await vault.balanceOf(await user.getAddress()),value.minimum);assert.equal(deposit.active,false);assert.equal(await executor.planUsed(planHash),true);assert.equal(await tokenIn.balanceOf(await coordinator.getAddress()),0n);assert.equal(await tokenIn.balanceOf(await executor.getAddress()),0n);assert.equal(await tokenOut.balanceOf(await executor.getAddress()),0n);
  });

  it("rejects unauthorized calls and a non-Composite route id",async function(){
    const value=await prepare(2);await assert.rejects(coordinator.connect(user).executeExactInput(value.intentHash,await coordinator.COMPOSITE_DEX_ID(),await tokenIn.getAddress(),await vault.getAddress(),value.amountIn,value.minimum,await user.getAddress(),value.deadline,value.routeData));const wrong={...value.solverQuote,dexId:ethers.id("OTHER")},signature=await ownerWallet.signTypedData({name:"LQC Solver Quote Manager",version:"1",chainId,verifyingContract:await quoteManager.getAddress()},{SolverQuote:types.SolverQuote},wrong);await assert.rejects(hub.executeSameChainIntent(value.intentHash,wrong,signature,value.routeData));assert.equal((await hub.getIntent(value.intentHash)).status,1n);assert.equal((await escrow.getDeposit(value.intentHash)).active,true);
  });

  it("rolls escrow, pool and Vault state back when the final action fails",async function(){
    const amountIn=ethers.parseEther("10"),swapQuote=(await flow.getAmountsOut(amountIn,[await tokenIn.getAddress(),await tokenOut.getAddress()]))[1],value=await prepare(3,{finalMinimum:swapQuote+1n}),before=await flow.getAmountsOut(amountIn,[await tokenIn.getAddress(),await tokenOut.getAddress()]);await assert.rejects(hub.executeSameChainIntent(value.intentHash,value.solverQuote,value.quoteSignature,value.routeData));const after=await flow.getAmountsOut(amountIn,[await tokenIn.getAddress(),await tokenOut.getAddress()]);assert.deepEqual(Array.from(after),Array.from(before));assert.equal((await hub.getIntent(value.intentHash)).status,1n);assert.equal((await escrow.getDeposit(value.intentHash)).active,true);assert.equal(await tokenIn.balanceOf(await escrow.getAddress()),amountIn);assert.equal(await vault.totalAssets(),0n);assert.equal(await tokenIn.balanceOf(await coordinator.getAddress()),0n);
  });

  it("rejects a substituted Composite plan before escrow release",async function(){
    const value=await prepare(4),decoded=ethers.AbiCoder.defaultAbiCoder().decode(["tuple(uint8 kind,address adapter,address tokenIn,address tokenOut,uint256 minAmountOut,bytes32 dataHash)[]","bytes[]"],value.routeData),actions=decoded[0].map((action,index)=>({kind:action.kind,adapter:action.adapter,tokenIn:action.tokenIn,tokenOut:action.tokenOut,minAmountOut:action.minAmountOut+(index===1?1n:0n),dataHash:action.dataHash})),changed=ethers.AbiCoder.defaultAbiCoder().encode(["tuple(uint8 kind,address adapter,address tokenIn,address tokenOut,uint256 minAmountOut,bytes32 dataHash)[]","bytes[]"],[actions,decoded[1]]);await assert.rejects(hub.executeSameChainIntent(value.intentHash,value.solverQuote,value.quoteSignature,changed));assert.equal((await escrow.getDeposit(value.intentHash)).active,true);assert.equal((await hub.getIntent(value.intentHash)).status,1n);
  });
});
