import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildBondSelectionPlan } from "../scripts/prepare-intent-bond-selection.mjs";
import { preflightBondSelectionAcrossRpcs,selectionRuntimeFingerprint,validateBondSelectionPreflight } from "../scripts/preflight-intent-bond-selection.mjs";

describe("LQC Intent Bond selection Stage-0 preflight",function(){
  const safe="0x5235e26EE4D511aE8ba1FB1cff2619Fc1D90C02A",selectionContract="0x0000000000000000000000000000000000000020",token="0x0000000000000000000000000000000000000030",inspection={results:[{token,decimals:18,network:{chainId:97},observedBlock:12345,assessment:{eligible:true}}]},artifact=JSON.parse(fs.readFileSync(path.resolve(import.meta.dirname,"../artifacts/contracts/intent-v1/LQCBondSelection.sol/LQCBondSelection.json"),"utf8")),blockHash=ethers.id("preflight-block");
  let plan;
  before(async function(){plan=await buildBondSelectionPlan({inspection,bondToken:token,selectionContract,safeNonce:7});});
  const fixture=()=>({plan,inspection,blockNumber:200,blockHash,safeCode:"0x6000",selectionCode:artifact.deployedBytecode,tokenCode:"0x6001",safeNonce:7n,governanceSafe:safe,onchainBondToken:ethers.ZeroAddress,onchainInspectionDigest:ethers.ZeroHash,approvedAt:0n});
  it("binds canonical bytecode, empty state, current nonce and exact Safe action",function(){const result=validateBondSelectionPreflight(fixture());assert.equal(result.status,"PREFLIGHT_VERIFIED");assert.equal(result.safeNonce,"7");assert.equal(result.inspectionDigest,canonicalDigest(inspection));assert.equal(result.transactionOccurred,false);});
  it("rejects a stale Safe nonce and an already-used recorder",function(){assert.throws(()=>validateBondSelectionPreflight({...fixture(),safeNonce:8n}),/stale/);assert.throws(()=>validateBondSelectionPreflight({...fixture(),onchainBondToken:token}),/initialized/);});
  it("rejects substituted runtime bytecode, governance and calldata",function(){assert.throws(()=>validateBondSelectionPreflight({...fixture(),selectionCode:"0x6000"}),/bytecode/);assert.throws(()=>validateBondSelectionPreflight({...fixture(),governanceSafe:token}),/Governance/);const changed=structuredClone(plan);changed.action.data="0x1234";assert.throws(()=>validateBondSelectionPreflight({...fixture(),plan:changed}),/calldata/);});
  it("normalizes only compiler-declared immutable runtime ranges",function(){const expected=artifact.deployedBytecode,bytes=ethers.getBytes(expected),reference=Object.values(artifact.immutableReferences)[0][0];bytes.fill(0x42,reference.start,reference.start+reference.length);assert.equal(selectionRuntimeFingerprint(ethers.hexlify(bytes)),selectionRuntimeFingerprint(expected));bytes[0]^=1;assert.notEqual(selectionRuntimeFingerprint(ethers.hexlify(bytes)),selectionRuntimeFingerprint(expected));});
  it("requires two RPCs to agree at one common block",async function(){const safeIface=new ethers.Interface(["function nonce() view returns(uint256)"]),selectionIface=new ethers.Interface(["function governanceSafe() view returns(address)","function bondToken() view returns(address)","function inspectionDigest() view returns(bytes32)","function approvedAt() view returns(uint256)"]),provider=hash=>({getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>202,getBlock:async()=>({hash}),getCode:async address=>address.toLowerCase()===selectionContract.toLowerCase()?artifact.deployedBytecode:"0x6000",call:async transaction=>{if(transaction.to.toLowerCase()===safe.toLowerCase())return safeIface.encodeFunctionResult("nonce",[7]);const name=selectionIface.getFunction(transaction.data.slice(0,10)).name;if(name==="governanceSafe")return selectionIface.encodeFunctionResult(name,[safe]);if(name==="bondToken")return selectionIface.encodeFunctionResult(name,[ethers.ZeroAddress]);if(name==="inspectionDigest")return selectionIface.encodeFunctionResult(name,[ethers.ZeroHash]);return selectionIface.encodeFunctionResult(name,[0]);}}),result=await preflightBondSelectionAcrossRpcs({providers:[provider(blockHash),provider(blockHash)],plan,inspection});assert.equal(result.rpcCount,2);await assert.rejects(preflightBondSelectionAcrossRpcs({providers:[provider(blockHash),provider(ethers.id("fork"))],plan,inspection}),/disagreement/);});
});
