import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{buildLendingStage11AuditSubmission,writeStage11Submission}from"../scripts/build-lending-stage11-audit-submission.mjs";import{verifyStage11Submission}from"../scripts/verify-lending-stage11-audit-submission.mjs";
function context(){const pb={status:"READY_FOR_EXTERNAL_REVIEW_NOT_AUDITED",sourceRevision:"ab".repeat(20),transactionOccurred:false},stage10Package={...pb,packageDigest:canonicalDigest(pb)},vb={status:"VERIFIED_LENDING_STAGE10_AUDIT_HANDOFF",packageDigest:stage10Package.packageDigest,transactionOccurred:false},stage10Verification={...vb,verificationDigest:canonicalDigest(vb)};return{stage10Package,stage10Verification}}
function bundle(){const c=context(),submission=buildLendingStage11AuditSubmission(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage11-"));writeStage11Submission(dir,submission);return{...c,submission,dir}}
describe("LQC Lending Stage 10-11 external audit submission",function(){
 it("fixes scope, questions, severities and fail-closed release gates",()=>{const s=buildLendingStage11AuditSubmission(context());assert.equal(s.status,"READY_TO_SUBMIT_NOT_AUDITED");assert.equal(s.scope.contracts.length,7);assert.equal(s.questions.length,10);assert.equal(Object.keys(s.severityPolicy).length,5);assert.match(s.releaseGates[0],/CRITICAL\/HIGH/);assert.match(s.submissionDigest,/^sha256:/)});
 it("writes and independently verifies the five-file submission",()=>{const b=bundle(),v=verifyStage11Submission({directoryPath:b.dir,stage10Package:b.stage10Package,stage10Verification:b.stage10Verification});assert.equal(v.status,"VERIFIED_LENDING_STAGE11_AUDIT_SUBMISSION");assert.equal(v.releaseBlocked,true);assert.equal(v.externalAuditComplete,false)});
 it("rejects substituted Stage-10 evidence and changed workflow files",()=>{const c=context();c.stage10Verification.packageDigest="sha256:"+"00".repeat(32);assert.throws(()=>buildLendingStage11AuditSubmission(c),/Stage-10/);let b=bundle();fs.unlinkSync(path.join(b.dir,"QUESTIONNAIRE.md"));assert.throws(()=>verifyStage11Submission({directoryPath:b.dir,stage10Package:b.stage10Package,stage10Verification:b.stage10Verification}),/file set/);b=bundle();const f=path.join(b.dir,"findings-register.json"),r=JSON.parse(fs.readFileSync(f));r.releaseBlocked=false;fs.writeFileSync(f,JSON.stringify(r));assert.throws(()=>verifyStage11Submission({directoryPath:b.dir,stage10Package:b.stage10Package,stage10Verification:b.stage10Verification}),/workflow/);b=bundle();fs.appendFileSync(path.join(b.dir,"QUESTIONNAIRE.md"),"changed");assert.throws(()=>verifyStage11Submission({directoryPath:b.dir,stage10Package:b.stage10Package,stage10Verification:b.stage10Verification}),/questionnaire|manifest/)});
 it("contains no RPC, key, signing or transaction mechanism",()=>{for(const f of["../scripts/build-lending-stage11-audit-submission.mjs","../scripts/verify-lending-stage11-audit-submission.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
