import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{buildLendingStage14ProposalIntake,evaluateStage14Proposal,writeStage14ProposalIntake}from"../scripts/build-lending-stage14-proposal-intake.mjs";import{verifyStage14ProposalIntake}from"../scripts/verify-lending-stage14-proposal-intake.mjs";
const weights={lendingAndEconomicSecurity:25,evmAndSolidityDepth:15,oracleLiquidationExperience:15,methodologyAndTooling:10,auditorTeamAndReferences:10,remediationAndRetest:10,scheduleAndAvailability:5,reportQualityAndDisclosure:5,commercialTerms:5};
function context(){const r12={status:"INTERNAL_REVIEW_ONLY_NOT_SENT",scoring:{weights,minimums:{totalScore:75,lendingAndEconomicSecurityRating:4,oracleLiquidationExperienceRating:4,remediationAndRetestRating:3}}},stage12Rfp={...r12,rfpDigest:canonicalDigest(r12)},x12={status:"VERIFIED_LENDING_STAGE12_INTERNAL_RFP",rfpDigest:stage12Rfp.rfpDigest},stage12Verification={...x12,verificationDigest:canonicalDigest(x12)},r13={status:"PUBLIC_EVIDENCE_RESEARCH_ONLY_NOT_SCORED",stage12RfpDigest:stage12Rfp.rfpDigest,candidates:["OpenZeppelin","ChainSecurity","Certora"].map(vendor=>({vendor}))},stage13Research={...r13,researchDigest:canonicalDigest(r13)},x13={status:"VERIFIED_LENDING_STAGE13_PUBLIC_RESEARCH",researchDigest:stage13Research.researchDigest},stage13Verification={...x13,verificationDigest:canonicalDigest(x13)};return{stage12Rfp,stage12Verification,stage13Research,stage13Verification}}
function bundle(){const c=context(),plan=buildLendingStage14ProposalIntake(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage14-"));writeStage14ProposalIntake(dir,plan);return{...c,plan,dir}}
function proposal(plan){return{vendor:"OpenZeppelin",proposalDigest:"sha256:"+"11".repeat(32),receivedAt:"2026-10-01T00:00:00Z",namedLeadAuditor:"Named Auditor",teamAllocation:"2 researchers",independentFixRetestCommitment:true,criticalHighAlertSla:"IMMEDIATE",scopeAcceptance:{LQCLendingCore:true,LQCLiquidationEngine:true},startDate:"2026-11-01",fieldworkDays:20,retestDays:5,finalReportDays:5,currency:"USD",basePrice:1,taxes:0,includedRetestRounds:1,publicReportAllowed:true,conflictCheck:"CLEAR",ratings:Object.fromEntries(Object.keys(plan.scoring.weights).map(k=>[k,5])),evidenceNotes:"Written proposal evidence"}}
describe("LQC Lending Stage 10-14 proposal intake gate",function(){
 it("binds the exact candidates and blocks transmission before 4-of-7 approval",()=>{const p=buildLendingStage14ProposalIntake(context());assert.deepEqual(p.candidates,["OpenZeppelin","ChainSecurity","Certora"]);assert.deepEqual(p.transmissionPackage.artifactDigests,[p.stage12RfpDigest,p.stage13ResearchDigest]);assert.equal(p.transmissionPackage.privateAuditEvidenceIncluded,false);assert.equal(p.externalTransmissionApproval.governanceSafe,"4-of-7");assert.equal(p.externalTransmissionApproval.granted,false);assert.equal(p.communicationAllowed,false);assert.equal(p.proposalIntake.proposals.length,0)});
 it("evaluates a complete written proposal without selecting a vendor",()=>{const p=buildLendingStage14ProposalIntake(context()),e=evaluateStage14Proposal({plan:p,proposal:proposal(p)});assert.equal(e.weightedTotal,100);assert.equal(e.eligible,true);assert.equal(e.selectionMade,false);assert.equal(e.disqualifiers.length,0)});
 it("rejects incomplete, unknown and technically weak proposals",()=>{const p=buildLendingStage14ProposalIntake(context());let q=proposal(p);delete q.namedLeadAuditor;assert.throws(()=>evaluateStage14Proposal({plan:p,proposal:q}),/Incomplete/);q=proposal(p);q.vendor="Other";assert.throws(()=>evaluateStage14Proposal({plan:p,proposal:q}),/Unknown/);q=proposal(p);q.ratings.oracleLiquidationExperience=2;const e=evaluateStage14Proposal({plan:p,proposal:q});assert.equal(e.eligible,false);assert.ok(e.disqualifiers.includes("technical minimum not met"))});
 it("writes and verifies a five-file zero-contact intake bundle",()=>{const b=bundle(),v=verifyStage14ProposalIntake({directoryPath:b.dir,stage12Rfp:b.stage12Rfp,stage12Verification:b.stage12Verification,stage13Research:b.stage13Research,stage13Verification:b.stage13Verification});assert.equal(v.status,"VERIFIED_LENDING_STAGE14_AWAITING_TRANSMISSION_APPROVAL");assert.equal(v.proposalCount,0);assert.equal(v.communicationAllowed,false)});
 it("rejects fabricated approval, proposal insertion and prior-evidence substitution",()=>{let b=bundle(),f=path.join(b.dir,"approval-record.json"),a=JSON.parse(fs.readFileSync(f));a.granted=true;fs.writeFileSync(f,JSON.stringify(a));assert.throws(()=>verifyStage14ProposalIntake({directoryPath:b.dir,stage12Rfp:b.stage12Rfp,stage12Verification:b.stage12Verification,stage13Research:b.stage13Research,stage13Verification:b.stage13Verification}),/unauthorized|mismatch/);const c=context();c.stage13Verification.researchDigest="sha256:"+"00".repeat(32);assert.throws(()=>buildLendingStage14ProposalIntake(c),/Stage-12 or Stage-13/)});
 it("contains no network, contact, key, signing, payment or transaction mechanism",()=>{for(const f of["../scripts/build-lending-stage14-proposal-intake.mjs","../scripts/verify-lending-stage14-proposal-intake.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/fetch\(|JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction|sendEmail|paymentIntent/)}});
});
