import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{STAGE10_FILES,buildLendingStage10AuditPackage,writeLendingStage10Package}from"../scripts/build-lending-stage10-audit-package.mjs";import{verifyLendingStage10Package}from"../scripts/verify-lending-stage10-audit-package.mjs";
const root=path.resolve(import.meta.dirname,".."),revision="ab".repeat(20),seal=(body,key)=>({...body,[key]:canonicalDigest(body)});
function evidence(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage10-evidence-")),e={};for(let i=1;i<=4;i++){const m=seal({stage:`stage${i}`,transactionOccurred:false},"manifestDigest"),v=seal({status:`VERIFIED_STAGE${i}`,manifestDigest:m.manifestDigest,transactionOccurred:true},"verificationDigest");e[`stage${i}-manifest.json`]=m;e[`stage${i}-verification.json`]=v}const p5=seal({stage:"stage5-disabled-market-initialization",transactionOccurred:false},"planDigest"),v5=seal({status:"VERIFIED_LENDING_STAGE5_DISABLED_MARKET",planDigest:p5.planDigest,transactionOccurred:true},"verificationDigest"),r6=seal({status:"READY_FOR_SEPARATE_MARKET_ACTIVATION_REVIEW",planDigest:p5.planDigest,stage5VerificationDigest:v5.verificationDigest,transactionOccurred:false},"readinessDigest"),a7=seal({status:"VERIFIED_LENDING_STAGE7_CAPPED_MARKET_ACTIVATION",planDigest:p5.planDigest,stage6ReadinessDigest:r6.readinessDigest,transactionOccurred:true},"verificationDigest"),p7=seal({status:"REVIEW_REQUIRED",marketPlanDigest:p5.planDigest,activationVerificationDigest:a7.verificationDigest,transactionOccurred:false},"pilotPlanDigest");Object.assign(e,{"stage5-plan.json":p5,"stage5-verification.json":v5,"stage6-readiness.json":r6,"stage7-activation.json":a7,"stage7-pilot.json":p7});const ds=[];for(let i=1;i<=7;i++){const x=seal({status:"ACTION_READY_FOR_SEPARATE_WALLET_REVIEW",marketPlanDigest:p5.planDigest,pilotPlanDigest:p7.pilotPlanDigest,step:i,transactionOccurred:false},"preflightDigest");e[`stage8-preflight-${i}.json`]=x;ds.push(x.preflightDigest)}e["stage9-completion.json"]=seal({status:"VERIFIED_LENDING_STAGE9_PILOT_COMPLETE",marketPlanDigest:p5.planDigest,pilotPlanDigest:p7.pilotPlanDigest,actionPreflightDigests:ds,transactionOccurred:true},"completionDigest");for(const n of STAGE10_FILES)fs.writeFileSync(path.join(dir,n),`${JSON.stringify(e[n],null,2)}\n`);return dir}
function bundle(){const source=evidence(),result=buildLendingStage10AuditPackage({root,evidenceDirectory:source,gitStatus:"",gitRevision:revision}),out=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage10-bundle-"));writeLendingStage10Package(out,result);return{source,result,out}}
describe("LQC Lending Stage 10 immutable audit package",function(){
 it("binds the exact Stage 1-9 digest chain and source revision",()=>{const dir=evidence(),r=buildLendingStage10AuditPackage({root,evidenceDirectory:dir,gitStatus:"",gitRevision:revision});assert.equal(r.package.status,"READY_FOR_EXTERNAL_REVIEW_NOT_AUDITED");assert.equal(r.package.evidenceFileCount,21);assert.match(r.package.packageDigest,/^sha256:/)});
 it("writes and independently verifies the immutable bundle",()=>{const b=bundle(),v=verifyLendingStage10Package({directoryPath:b.out,root,gitStatus:"",gitRevision:revision});assert.equal(v.status,"VERIFIED_LENDING_STAGE10_AUDIT_HANDOFF");assert.match(v.verificationDigest,/^sha256:/)});
 it("rejects dirty source, broken chains, missing, extra and modified files",()=>{const dir=evidence();assert.throws(()=>buildLendingStage10AuditPackage({root,evidenceDirectory:dir,gitStatus:" M x",gitRevision:revision}),/dirty/);const f=path.join(dir,"stage9-completion.json"),x=JSON.parse(fs.readFileSync(f));x.actionPreflightDigests[0]="sha256:"+"00".repeat(32);x.completionDigest=canonicalDigest(Object.fromEntries(Object.entries(x).filter(([k])=>k!=="completionDigest")));fs.writeFileSync(f,JSON.stringify(x));assert.throws(()=>buildLendingStage10AuditPackage({root,evidenceDirectory:dir,gitStatus:"",gitRevision:revision}),/Stage-9/);let b=bundle();fs.unlinkSync(path.join(b.out,"REVIEW.md"));assert.throws(()=>verifyLendingStage10Package({directoryPath:b.out,root,gitStatus:"",gitRevision:revision}),/file set/);b=bundle();fs.writeFileSync(path.join(b.out,"extra"),"");assert.throws(()=>verifyLendingStage10Package({directoryPath:b.out,root,gitStatus:"",gitRevision:revision}),/file set/);b=bundle();fs.appendFileSync(path.join(b.out,"REVIEW.md"),"changed");assert.throws(()=>verifyLendingStage10Package({directoryPath:b.out,root,gitStatus:"",gitRevision:revision}),/review|manifest/)});
 it("contains no RPC, key, signing or transaction mechanism",()=>{for(const f of["../scripts/build-lending-stage10-audit-package.mjs","../scripts/verify-lending-stage10-audit-package.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
