import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{verifyLendingStage9PilotCompletion}from"../scripts/verify-lending-stage9-pilot-completion.mjs";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";
const a=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),core=a(10),debtToken=a(11),collateralToken=a(12),pilot=a(13),id=ethers.id("market"),hashes=Array.from({length:7},(_,i)=>ethers.id(`pilot-${i}`)),blockHash=ethers.id("block"),tokenI=new ethers.Interface(["function allowance(address,address) view returns(uint256)","event Approval(address indexed owner,address indexed spender,uint256 value)"]),coreI=new ethers.Interface(["function collateralOf(bytes32,address) view returns(uint256)","function liquidityOf(bytes32,address) view returns(uint256)","function debtOf(bytes32,address) view returns(uint256)","event LiquiditySupplied(bytes32 indexed marketId,address indexed account,uint256 amount,uint256 shares)","event CollateralDeposited(bytes32 indexed marketId,address indexed account,uint256 amount)","event Borrowed(bytes32 indexed marketId,address indexed account,address indexed receiver,uint256 amount,uint256 shares)","event Repaid(bytes32 indexed marketId,address indexed payer,address indexed account,uint256 amount,uint256 shares)"]);
function context(){const mb={network:{chainId:97},dependencies:{lendingCore:core},market:{debtAsset:debtToken,collateralAsset:collateralToken},transactionOccurred:false},marketPlan={...mb,planDigest:canonicalDigest(mb)},actions=Array.from({length:7},(_,i)=>({id:i+1,to:[debtToken,core,collateralToken,core,core,debtToken,core][i],data:`0x${(i+1).toString(16).padStart(2,"0")}`})),pb={marketPlanDigest:marketPlan.planDigest,pilotAccount:pilot,marketId:id,amounts:{supply:"1000",collateral:"1000",borrow:"500"},orderedActions:actions,transactionOccurred:false},pilotPlan={...pb,pilotPlanDigest:canonicalDigest(pb)},preflights=actions.map((x,i)=>{const b={status:"ACTION_READY_FOR_SEPARATE_WALLET_REVIEW",marketPlanDigest:marketPlan.planDigest,pilotPlanDigest:null,step:i+1,resolvedAction:x,transactionOccurred:false};b.pilotPlanDigest=pilotPlan.pilotPlanDigest;return{...b,preflightDigest:canonicalDigest(b)}});return{marketPlan,pilotPlan,preflights}}
function event(i){let iface,address,name,args;if([0,2,5].includes(i)){iface=tokenI;address=i===2?collateralToken:debtToken;name="Approval";args=[pilot,core,i===5?503n:1000n]}else{iface=coreI;address=core;name=[,"LiquiditySupplied",,"CollateralDeposited","Borrowed",,"Repaid"][i];args=i===1?[id,pilot,1000n,1000n]:i===3?[id,pilot,1000n]:i===4?[id,pilot,pilot,500n,500n]:[id,pilot,pilot,503n,503n]}const e=iface.encodeEventLog(iface.getEvent(name),args);return{address,topics:e.topics,data:e.data}}
function provider(c,o={}){return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>o.head||220,getTransaction:async h=>{const i=hashes.indexOf(h),x=c.preflights[i].resolvedAction;return{from:pilot,to:o.badPayload&&i===3?a(99):x.to,value:0n,data:x.data}},getTransactionReceipt:async h=>{const i=hashes.indexOf(h);return{status:o.failed&&i===0?0:1,blockNumber:200+i,blockHash,index:i,logs:o.noEvent&&i===2?[]:[event(i)]}},getBlock:async()=>({hash:o.reorg?ethers.id("reorg"):blockHash}),call:async({to,data})=>{const sel=data.slice(0,10);if(to.toLowerCase()===debtToken.toLowerCase()||to.toLowerCase()===collateralToken.toLowerCase())return tokenI.encodeFunctionResult("allowance",[o.badFinal&&to.toLowerCase()===debtToken.toLowerCase()?1n:0n]);if(sel===coreI.getFunction("collateralOf").selector)return coreI.encodeFunctionResult("collateralOf",[1000n]);if(sel===coreI.getFunction("liquidityOf").selector)return coreI.encodeFunctionResult("liquidityOf",[1000n]);return coreI.encodeFunctionResult("debtOf",[o.badFinal?1n:0n])}}}
describe("LQC Lending Stage 10-9 pilot completion",function(){
 it("verifies seven ordered transactions, events and zero residual debt or allowances",async()=>{const c=context(),v=await verifyLendingStage9PilotCompletion({providers:[provider(c),provider(c)],marketPlan:c.marketPlan,pilotPlan:c.pilotPlan,actionPreflights:c.preflights,transactionHashes:hashes});assert.equal(v.status,"VERIFIED_LENDING_STAGE9_PILOT_COMPLETE");assert.equal(v.transactions.length,7);assert.equal(v.finalState.debt,"0");assert.match(v.completionDigest,/^sha256:/)});
 it("rejects failed, changed, reorged, weak, missing-event and residual-state evidence",async()=>{const c=context();for(const o of[{failed:true},{badPayload:true},{reorg:true},{head:207},{noEvent:true},{badFinal:true}])await assert.rejects(verifyLendingStage9PilotCompletion({providers:[provider(c),provider(c,o)],marketPlan:c.marketPlan,pilotPlan:c.pilotPlan,actionPreflights:c.preflights,transactionHashes:hashes}),/failed|changed|canonical|finality|event|state|disagreement/)});
 it("rejects a substituted or reordered action preflight chain",async()=>{const c=context();c.preflights[1].step=3;await assert.rejects(verifyLendingStage9PilotCompletion({providers:[provider(c),provider(c)],marketPlan:c.marketPlan,pilotPlan:c.pilotPlan,actionPreflights:c.preflights,transactionHashes:hashes}),/preflight chain/)});
 it("contains no key, signing, wallet or transaction broadcast path",()=>{const s=fs.readFileSync(new URL("../scripts/verify-lending-stage9-pilot-completion.mjs",import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction|requestAccounts/)});
});
