import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{buildLendingStage3Manifest}from"../scripts/prepare-lending-stage3-manifest.mjs";import{preflightLendingStage3AcrossRpcs}from"../scripts/preflight-lending-stage3-deployment.mjs";import{verifyLendingStage3AcrossRpcs}from"../scripts/verify-lending-stage3-deployment.mjs";import{canonicalDigest,sha256}from"../scripts/build-intent-reproducibility-seal.mjs";
const address=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),gov=address(1),guardian=address(2),treasury=address(3),registry=address(20),index=address(21),oracle=address(22),rate=address(23),deployer=address(100),blockHash=ethers.id("stage3-block"),txHash=ethers.id("core-deploy"),coreArtifact=JSON.parse(fs.readFileSync(new URL("../artifacts/contracts/lending/LQCLendingCore.sol/LQCLendingCore.json",import.meta.url))),registryInterface=new ethers.Interface(["function owner() view returns(address)","function guardian() view returns(address)","function oracle() view returns(address)"]),indexInterface=new ethers.Interface(["function owner() view returns(address)","function rateModel() view returns(address)","function core() view returns(address)"]),coreInterface=new ethers.Interface(["function owner() view returns(address)","function registry() view returns(address)","function interestIndex() view returns(address)","function liquidationEngine() view returns(address)"]);
function config(){const collateral=address(4),debt=address(5),marketId=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["address","address"],[collateral,debt]));return{schemaVersion:1,network:{chainId:97},roles:{governanceSafe:gov,guardianSafe:guardian,treasurySafe:treasury,governanceThreshold:4,governanceOwners:7,guardianThreshold:3,guardianOwners:5},market:{collateralAsset:collateral,debtAsset:debt,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000000000000000000000",borrowCap:"900000000000000000000",minBorrow:"10000000000000000000"},oracle:{collateralPrimary:address(6),collateralSecondary:address(7),debtPrimary:address(8),debtSecondary:address(9),maxStalenessSeconds:3600,maxDeviationBps:200},rate:{baseAprBps:200,slope1AprBps:800,slope2AprBps:9000,optimalUtilizationBps:8000,reserveFactorBps:1000},composite:{executor:address(10),lendingCore:address(11),supplyAdapter:address(12),adapterRegistry:address(13),marketId}}}
async function context(){const configuration=config(),{validateLendingTestnetConfig}=await import("../scripts/validate-lending-testnet-config.mjs"),approved=validateLendingTestnetConfig(configuration),stage2Body={status:"REVIEW_REQUIRED",network:{chainId:97},stage:"stage2-registry-index-deploy",configPreflightDigest:approved.preflightDigest,dependencies:{oracleManager:oracle,interestRateModel:rate},orderedActions:[{id:1},{id:2}],transactionOccurred:false},stage2Manifest={...stage2Body,manifestDigest:canonicalDigest(stage2Body)},verificationBody={status:"VERIFIED_LENDING_STAGE2_DEPLOYMENT",network:{chainId:97},manifestDigest:stage2Manifest.manifestDigest,deployments:[{contract:"LQCLendingMarketRegistry",contractAddress:registry,bindings:{owner:gov,guardian,oracle}},{contract:"LQCLendingInterestIndex",contractAddress:index,bindings:{owner:gov,rateModel:rate,core:ethers.ZeroAddress}}],transactionOccurred:true},stage2Verification={...verificationBody,verificationDigest:canonicalDigest(verificationBody)},manifest=await buildLendingStage3Manifest({config:configuration,stage2Manifest,stage2Verification});return{configuration,stage2Manifest,stage2Verification,manifest}}
function dependencyCall(to,data,bad=false){if(to.toLowerCase()===registry.toLowerCase()){const fn=registryInterface.getFunction(data.slice(0,10)).name,value=fn==="owner"?gov:fn==="guardian"?guardian:bad?address(99):oracle;return registryInterface.encodeFunctionResult(fn,[value])}const fn=indexInterface.getFunction(data.slice(0,10)).name,value=fn==="owner"?gov:fn==="rateModel"?rate:ethers.ZeroAddress;return indexInterface.encodeFunctionResult(fn,[value])}
function preProvider(o={}){return{getNetwork:async()=>({chainId:BigInt(o.chainId||97)}),getBlockNumber:async()=>100,getBlock:async()=>({hash:blockHash,baseFeePerGas:1_000_000_000n}),getTransactionCount:async()=>o.nonce??5,getBalance:async()=>o.balance??10n**18n,getCode:async target=>target.toLowerCase()===ethers.getCreateAddress({from:deployer,nonce:o.nonce??5}).toLowerCase()?(o.occupied?"0x60":"0x"):"0x6001",estimateGas:async()=>o.gas||500000n,call:async({to,data})=>dependencyCall(to,data,o.badOracle)}}
async function ready(){const c=await context();c.preflight=await preflightLendingStage3AcrossRpcs({providers:[preProvider(),preProvider()],manifest:c.manifest,deployer});return c}
function verifyProvider(c,o={}){const core=c.preflight.deployment.predictedAddress;return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>o.head||210,getTransaction:async()=>({from:deployer,to:null,nonce:5,data:o.badData?"0x69":c.manifest.orderedActions[0].data}),getTransactionReceipt:async()=>({status:o.failed?0:1,contractAddress:core,blockNumber:200,blockHash}),getBlock:async()=>({hash:o.reorg?ethers.id("reorg"):blockHash}),getCode:async()=>o.badRuntime?"0x6000":coreArtifact.deployedBytecode,call:async({data})=>{const fn=coreInterface.getFunction(data.slice(0,10)).name;let value=fn==="owner"?gov:fn==="registry"?registry:fn==="interestIndex"?index:ethers.ZeroAddress;if(o.badBinding&&fn==="registry")value=address(99);return coreInterface.encodeFunctionResult(fn,[value])}}}
describe("LQC Lending Stage 10-3 core deployment gate",function(){
 it("builds the Core only from digest-bound verified Registry and Index",async()=>{const c=await context();assert.equal(c.manifest.stage,"stage3-lending-core-deploy");assert.equal(c.manifest.orderedActions[0].contract,"LQCLendingCore");assert.deepEqual(c.manifest.dependencies.marketRegistry,registry);assert.match(c.manifest.manifestDigest,/^sha256:/)});
 it("rejects substituted Stage-2 evidence",async()=>{const c=await context(),changed=structuredClone(c.stage2Verification);changed.deployments[0].contractAddress=address(99);await assert.rejects(buildLendingStage3Manifest({config:c.configuration,stage2Manifest:c.stage2Manifest,stage2Verification:changed}),/verification/)});
 it("preflights dependency bindings, empty CREATE address and bounded gas across RPCs",async()=>{const c=await ready();assert.equal(c.preflight.status,"PREFLIGHT_VERIFIED_FOR_REVIEW");assert.equal(c.preflight.deployment.predictedAddress,ethers.getCreateAddress({from:deployer,nonce:5}));assert.equal(c.preflight.rpcCount,2)});
 it("rejects dependency drift, occupied address, RPC disagreement and insufficient gas",async()=>{const c=await context();for(const pair of[[preProvider(),preProvider({badOracle:true})],[preProvider(),preProvider({occupied:true})],[preProvider(),preProvider({nonce:6})],[preProvider({balance:1n}),preProvider({balance:1n})]])await assert.rejects(preflightLendingStage3AcrossRpcs({providers:pair,manifest:c.manifest,deployer}),/binding|already has code|disagreement|insufficient/)});
 it("verifies canonical Core runtime and immutable dependencies",async()=>{const c=await ready(),v=await verifyLendingStage3AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c)],manifest:c.manifest,preflight:c.preflight,transactionHash:txHash});assert.equal(v.status,"VERIFIED_LENDING_STAGE3_DEPLOYMENT");assert.equal(v.deployment.bindings.marketRegistry,registry);assert.match(v.verificationDigest,/^sha256:/)});
 it("rejects failed, reorged, substituted, weak-finality and misbound deployments",async()=>{const c=await ready();for(const o of[{failed:true},{reorg:true},{badData:true},{badRuntime:true},{head:201},{badBinding:true}])await assert.rejects(verifyLendingStage3AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c,o)],manifest:c.manifest,preflight:c.preflight,transactionHash:txHash}),/failed|canonical|init code|runtime|finality|binding|disagreement/)});
 it("contains no key, signing or broadcast path",()=>{for(const f of["../scripts/prepare-lending-stage3-manifest.mjs","../scripts/preflight-lending-stage3-deployment.mjs","../scripts/verify-lending-stage3-deployment.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
