import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildLendingStage1Manifest } from "../scripts/prepare-lending-stage1-manifest.mjs";
import { buildLendingStage1DeploymentReview } from "../scripts/build-lending-stage1-deployment-review.mjs";
import { prepareLendingStage1ExecutionPacket } from "../scripts/prepare-lending-stage1-execution-packet.mjs";

const finalized=JSON.parse(fs.readFileSync(new URL("../deployments/lending-stage0-finalized-config-bsc-testnet-97.json",import.meta.url))),config=finalized.config,deployer="0x7cf23bB16Ed0E1eaF58CD31c9F5a643be438C6aB";
async function fixture(){const manifest=await buildLendingStage1Manifest(config),gas=[724190n,679428n],limits=gas.map(x=>(x*120n+99n)/100n),body={schemaVersion:1,recordType:"LQC_LENDING_STAGE1_MULTI_RPC_PREFLIGHT",status:"PREFLIGHT_VERIFIED_FOR_REVIEW",network:{name:"BSC Testnet",chainId:97},manifestDigest:manifest.manifestDigest,configPreflightDigest:manifest.configPreflightDigest,deployer,blockNumber:131536271,blockHash:"0x36f6f3f883d6d1168a17568af9f2fc6b128582d9f241d2f24da3c893c395a276",baseFeePerGas:"0",conservativeGasPrice:"100000000",deployerNonce:"105",deployerBalance:"699612055927407796",requiredGasBudget:"168434200000000",rpcCount:2,deployments:manifest.orderedActions.map((action,index)=>({id:action.id,contract:action.contract,predictedAddress:ethers.getCreateAddress({from:deployer,nonce:105+index}),initCodeDigest:action.initCodeDigest,conservativeGas:gas[index].toString(),approvedGasLimit:limits[index].toString()})),totalConservativeGas:"1403618",totalApprovedGasLimit:"1684342",transactionOccurred:false,safety:"Read-only multi-RPC preflight. No wallet, key, signature, approval, deployment, token movement, or transaction."};return{manifest,preflight:{...body,preflightDigest:canonicalDigest(body)}}}
describe("LQC Lending Stage-1 deployment review and execution packet",function(){
  it("reproduces the recorded live preflight review exactly",async function(){const manifest=JSON.parse(fs.readFileSync(new URL("../deployments/lending-stage1-manifest-bsc-testnet-97.json",import.meta.url))),preflight=JSON.parse(fs.readFileSync(new URL("../deployments/lending-stage1-live-preflight-bsc-testnet-97.json",import.meta.url))),recorded=JSON.parse(fs.readFileSync(new URL("../deployments/lending-stage1-deployment-review-bsc-testnet-97.json",import.meta.url))),rebuilt=buildLendingStage1DeploymentReview({manifest,config,preflight});assert.deepEqual(recorded,rebuilt);assert.equal(recorded.reviewDigest,"sha256:cb6c10ded28b9e85247fc413a8ea4e2a64a0755555b547652fe89385bd8af589");assert.equal(recorded.budget.maximumGasBudgetTbnb,"0.0001684342")});
  it("binds the exact two live CREATE addresses and maximum budget",async function(){const f=await fixture(),review=buildLendingStage1DeploymentReview({...f,config});assert.equal(review.deployments.length,2);assert.deepEqual(review.deployments.map(x=>x.nonce),["105","106"]);assert.equal(review.budget.maximumGasBudgetTbnb,"0.0001684342");assert.equal(review.transactionOccurred,false);assert.match(review.reviewDigest,/^sha256:[0-9a-f]{64}$/)});
  it("requires the exact explicit review digest before creating an unsigned packet",async function(){const f=await fixture(),review=buildLendingStage1DeploymentReview({...f,config});for(const approvedReviewDigest of[undefined,ethers.id("wrong")])assert.throws(()=>prepareLendingStage1ExecutionPacket({...f,config,review,approvedReviewDigest}),/explicit/);const packet=prepareLendingStage1ExecutionPacket({...f,config,review,approvedReviewDigest:review.reviewDigest});assert.deepEqual(packet.transactions.map(x=>x.gasLimit),["869028","815314"]);assert.ok(packet.transactions.every(x=>x.to===null&&x.value==="0"));assert.equal(packet.transactionOccurred,false)});
  it("rejects changed preflight gas, address and review content",async function(){const f=await fixture(),review=buildLendingStage1DeploymentReview({...f,config});for(const mutate of[p=>p.deployments[0].approvedGasLimit="1",p=>p.deployments[1].predictedAddress=ethers.ZeroAddress,p=>p.requiredGasBudget="1"]){const changed=structuredClone(f.preflight);mutate(changed);const{preflightDigest:_,...body}=changed;changed.preflightDigest=canonicalDigest(body);assert.throws(()=>buildLendingStage1DeploymentReview({manifest:f.manifest,config,preflight:changed}),/mismatch/)}const changed=structuredClone(review);changed.deployments[0].nonce="999";assert.throws(()=>prepareLendingStage1ExecutionPacket({...f,config,review:changed,approvedReviewDigest:review.reviewDigest}),/invalid explicit/)});
  it("contains no key, wallet, signing or transaction submission path",function(){for(const file of["../scripts/build-lending-stage1-deployment-review.mjs","../scripts/prepare-lending-stage1-execution-packet.mjs"]){const source=fs.readFileSync(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/PRIVATE_KEY|window\.ethereum|signTransaction|eth_sendTransaction/)}});
});
