import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{buildLendingStage13Research,writeStage13Research,PUBLIC_CANDIDATES}from"../scripts/build-lending-stage13-auditor-research.mjs";import{verifyStage13Research}from"../scripts/verify-lending-stage13-auditor-research.mjs";
function context(){const rb={status:"INTERNAL_REVIEW_ONLY_NOT_SENT",scope:{contracts:["Core","Engine"]},scoring:{weights:{technical:100}},externalCommunicationOccurred:false},stage12Rfp={...rb,rfpDigest:canonicalDigest(rb)},vb={status:"VERIFIED_LENDING_STAGE12_INTERNAL_RFP",rfpDigest:stage12Rfp.rfpDigest,proposalCount:0,selectedVendor:null},stage12Verification={...vb,verificationDigest:canonicalDigest(vb)};return{stage12Rfp,stage12Verification}}
function bundle(){const c=context(),research=buildLendingStage13Research(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage13-"));writeStage13Research(dir,research);return{...c,research,dir}}
describe("LQC Lending Stage 10-13 auditor public research",function(){
 it("records three candidates using official public sources without scoring",()=>{const r=buildLendingStage13Research(context());assert.equal(r.candidates.length,3);assert.deepEqual(r.candidates.map(x=>x.vendor),["OpenZeppelin","ChainSecurity","Certora"]);assert.equal(r.status,"PUBLIC_EVIDENCE_RESEARCH_ONLY_NOT_SCORED");assert.equal(r.selectedVendor,null);for(const c of r.candidates){assert.equal(c.weightedTotal,null);assert.ok(c.evidence.length>=2);assert.ok(Object.values(c.proposalFields).every(v=>v===null))}});
 it("pins all evidence to each candidate official domain",()=>{for(const c of PUBLIC_CANDIDATES)for(const e of c.evidence)assert.ok(new URL(e.url).hostname===c.officialDomain||new URL(e.url).hostname.endsWith(`.${c.officialDomain}`))});
 it("writes and independently verifies the four-file research bundle",()=>{const b=bundle(),v=verifyStage13Research({directoryPath:b.dir,stage12Rfp:b.stage12Rfp,stage12Verification:b.stage12Verification});assert.equal(v.status,"VERIFIED_LENDING_STAGE13_PUBLIC_RESEARCH");assert.equal(v.candidateCount,3);assert.equal(v.weightedScoreCalculated,false);assert.equal(v.externalCommunicationOccurred,false)});
 it("rejects evidence substitution, invented score and unauthorized communication",()=>{let b=bundle(),f=path.join(b.dir,"auditor-research.json"),r=JSON.parse(fs.readFileSync(f));r.candidates[0].weightedTotal=99;fs.writeFileSync(f,JSON.stringify(r));assert.throws(()=>verifyStage13Research({directoryPath:b.dir,stage12Rfp:b.stage12Rfp,stage12Verification:b.stage12Verification}),/mismatch|fabricated/);b=bundle();f=path.join(b.dir,"approval-state.json");r=JSON.parse(fs.readFileSync(f));r.externalCommunicationOccurred=true;fs.writeFileSync(f,JSON.stringify(r));assert.throws(()=>verifyStage13Research({directoryPath:b.dir,stage12Rfp:b.stage12Rfp,stage12Verification:b.stage12Verification}),/unauthorized|manifest/);const c=context();c.stage12Verification.rfpDigest="sha256:"+"00".repeat(32);assert.throws(()=>buildLendingStage13Research(c),/Stage-12/)});
 it("contains no network, contact, key, signing, payment or transaction mechanism",()=>{for(const f of["../scripts/build-lending-stage13-auditor-research.mjs","../scripts/verify-lending-stage13-auditor-research.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/fetch\(|JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction|sendEmail|paymentIntent/)}});
});
