import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { canonicalDigest } from "../scripts/build-intent-reproducibility-seal.mjs";
import { buildLendingAuditHandoff,writeLendingAuditHandoff } from "../scripts/build-lending-audit-handoff.mjs";
import { verifyLendingAuditHandoff } from "../scripts/verify-lending-audit-handoff.mjs";

const root=path.resolve(import.meta.dirname,".."),revision="ab".repeat(20);
function create(){const handoff=buildLendingAuditHandoff({root,gitStatus:"",gitRevision:revision}),directory=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-lending-audit-"));writeLendingAuditHandoff(directory,handoff,root);return{directory,handoff}}
describe("LQC Lending external audit handoff",function(){
  it("binds seven contracts, 42 entry points, compiler and evidence",function(){const result=buildLendingAuditHandoff({root,gitStatus:"",gitRevision:revision});assert.equal(result.status,"READY_FOR_EXTERNAL_LENDING_AUDIT_HANDOFF");assert.equal(result.contractCount,7);assert.equal(result.stateChangingEntryCount,42);assert.equal(Object.keys(result.contracts).length,7);assert.equal(Object.keys(result.evidence).length,11);assert.equal(result.compiler.viaIR,true);assert.match(result.handoffDigest,/^sha256:[0-9a-f]{64}$/)});
  it("refuses dirty source, invalid revisions and changed audit scope",function(){assert.throws(()=>buildLendingAuditHandoff({root,gitStatus:" M file",gitRevision:revision}),/dirty worktree/);assert.throws(()=>buildLendingAuditHandoff({root,gitStatus:"",gitRevision:"short"}),/revision/);const file=path.join(root,"audit/lending-surface.json"),original=fs.readFileSync(file,"utf8");try{const scope=JSON.parse(original);scope.scope="FORGED";fs.writeFileSync(file,JSON.stringify(scope));assert.throws(()=>buildLendingAuditHandoff({root,gitStatus:"",gitRevision:revision}),/surface/)}finally{fs.writeFileSync(file,original)}});
  it("writes and independently verifies four immutable files",function(){const{directory,handoff}=create(),result=verifyLendingAuditHandoff({directoryPath:directory,root,gitStatus:"",gitRevision:revision});assert.equal(result.status,"VERIFIED_LENDING_AUDIT_HANDOFF");assert.equal(Object.keys(result.evidenceFileDigests).length,3);assert.match(result.handoffVerificationDigest,/^sha256:[0-9a-f]{64}$/);assert.throws(()=>writeLendingAuditHandoff(directory,handoff,root),/empty output/)});
  it("rejects missing, added, modified and rehashed evidence",function(){let value=create();fs.unlinkSync(path.join(value.directory,"REVIEW.md"));assert.throws(()=>verifyLendingAuditHandoff({directoryPath:value.directory,root,gitStatus:"",gitRevision:revision}),/file set/);value=create();fs.writeFileSync(path.join(value.directory,"extra.json"),"{}\n");assert.throws(()=>verifyLendingAuditHandoff({directoryPath:value.directory,root,gitStatus:"",gitRevision:revision}),/file set/);value=create();fs.appendFileSync(path.join(value.directory,"REVIEW.md"),"changed\n");assert.throws(()=>verifyLendingAuditHandoff({directoryPath:value.directory,root,gitStatus:"",gitRevision:revision}),/summary|digest/);value=create();const file=path.join(value.directory,"bundle-manifest.json"),manifest=JSON.parse(fs.readFileSync(file));manifest.packageType="FORGED";manifest.bundleDigest=canonicalDigest(Object.fromEntries(Object.entries(manifest).filter(([key])=>key!=="bundleDigest")));fs.writeFileSync(file,JSON.stringify(manifest));assert.throws(()=>verifyLendingAuditHandoff({directoryPath:value.directory,root,gitStatus:"",gitRevision:revision}),/digest|mismatch/)});
  it("contains no RPC, key, signing or transaction mechanism",function(){for(const file of["../scripts/build-lending-audit-handoff.mjs","../scripts/verify-lending-audit-handoff.mjs"]){const source=fs.readFileSync(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
