import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{buildLendingStage4Manifest}from"../scripts/prepare-lending-stage4-manifest.mjs";import{preflightLendingStage4AcrossRpcs}from"../scripts/preflight-lending-stage4-activation.mjs";import{verifyLendingStage4AcrossRpcs}from"../scripts/verify-lending-stage4-activation.mjs";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";
const a=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),gov=a(1),guardian=a(2),core=a(10),index=a(11),registry=a(12),deployer=a(100),blockHash=ethers.id("stage4"),hashes=[ethers.id("engine"),ethers.id("index-bind"),ethers.id("core-bind")],indexI=new ethers.Interface(["function owner() view returns(address)","function core() view returns(address)"]),coreI=new ethers.Interface(["function owner() view returns(address)","function registry() view returns(address)","function interestIndex() view returns(address)","function liquidationEngine() view returns(address)"]),engineI=new ethers.Interface(["function core() view returns(address)"]),safeI=new ethers.Interface(["function execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes) returns(bool)","event ExecutionSuccess(bytes32 txHash,uint256 payment)"]),engineArtifact=JSON.parse(fs.readFileSync(new URL("../artifacts/contracts/lending/LQCLiquidationEngine.sol/LQCLiquidationEngine.json",import.meta.url)));
async function context(){const m3body={stage:"stage3-lending-core-deploy",status:"REVIEW_REQUIRED",network:{chainId:97},roles:{governanceSafe:gov,guardianSafe:guardian},dependencies:{interestIndex:index},transactionOccurred:false},stage3Manifest={...m3body,manifestDigest:canonicalDigest(m3body)},v3body={status:"VERIFIED_LENDING_STAGE3_DEPLOYMENT",network:{chainId:97},manifestDigest:stage3Manifest.manifestDigest,deployment:{contractAddress:core,bindings:{marketRegistry:registry,interestIndex:index,liquidationEngine:ethers.ZeroAddress}},transactionOccurred:true},stage3Verification={...v3body,verificationDigest:canonicalDigest(v3body)},manifest=await buildLendingStage4Manifest({stage3Manifest,stage3Verification});return{stage3Manifest,stage3Verification,manifest}}
function call(to,data,{final=false,bad=false,engine}={}){let i,value;if(to.toLowerCase()===index.toLowerCase()){i=indexI;const n=i.getFunction(data.slice(0,10)).name;value=n==="owner"?gov:final?core:ethers.ZeroAddress}else if(to.toLowerCase()===core.toLowerCase()){i=coreI;const n=i.getFunction(data.slice(0,10)).name;value=n==="owner"?gov:n==="registry"?(bad?a(99):registry):n==="interestIndex"?index:final?(bad?a(99):engine):ethers.ZeroAddress}else{i=engineI;value=bad?a(99):core}const n=i.getFunction(data.slice(0,10)).name;return i.encodeFunctionResult(n,[value])}
function preProvider(o={}){const engine=ethers.getCreateAddress({from:deployer,nonce:o.nonce??5});return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>100,getBlock:async()=>({hash:blockHash,baseFeePerGas:1_000_000_000n}),getTransactionCount:async()=>o.nonce??5,getBalance:async()=>o.balance??10n**18n,getCode:async to=>to.toLowerCase()===engine.toLowerCase()?(o.occupied?"0x60":"0x"):"0x6001",estimateGas:async()=>o.gas||300000n,call:async({to,data})=>call(to,data,{bad:o.bad})}}
async function ready(){const c=await context();c.preflight=await preflightLendingStage4AcrossRpcs({providers:[preProvider(),preProvider()],manifest:c.manifest,deployer});return c}
function safeData(action){return safeI.encodeFunctionData("execTransaction",[action.to,0,action.data,0,0,0,0,ethers.ZeroAddress,ethers.ZeroAddress,"0x"])}function successLog(){const e=safeI.encodeEventLog(safeI.getEvent("ExecutionSuccess"),[ethers.id("safe"),0]);return{address:gov,topics:e.topics,data:e.data}}
function verifyProvider(c,o={}){const engine=c.preflight.predictedLiquidationEngine;return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>o.head||210,getTransaction:async h=>{const i=hashes.indexOf(h);if(i===0)return{from:deployer,to:null,nonce:5,data:o.badDeploy?"0x69":c.manifest.orderedActions[0].data};return{to:gov,data:safeData(o.badSafe&&i===2?{...c.preflight.orderedActions[i],to:a(99)}:c.preflight.orderedActions[i])}},getTransactionReceipt:async h=>{const i=hashes.indexOf(h);return{status:o.failed&&i===0?0:1,contractAddress:i===0?engine:null,blockNumber:200+i,blockHash,index:i,logs:i===0?[]:o.noEvent?[]:[successLog()] }},getBlock:async()=>({hash:o.reorg?ethers.id("reorg"):blockHash}),getCode:async()=>o.badRuntime?"0x6000":engineArtifact.deployedBytecode,call:async({to,data},block)=>call(to,data,{final:Number(block)>=210,bad:o.badFinal,engine})}}
describe("LQC Lending Stage 10-4 activation gate",function(){
 it("builds an Engine deployment and two ordered Governance bindings",async()=>{const c=await context();assert.equal(c.manifest.stage,"stage4-core-engine-bind");assert.deepEqual(c.manifest.orderedActions.map(x=>x.actor),["deployer","governance-safe","governance-safe"])});
 it("rejects substituted Stage-3 evidence",async()=>{const c=await context();c.stage3Verification.deployment.contractAddress=a(99);await assert.rejects(buildLendingStage4Manifest(c),/evidence/)});
 it("resolves the predicted Engine into the final Safe calldata across RPCs",async()=>{const c=await ready();assert.equal(c.preflight.status,"PREFLIGHT_VERIFIED_FOR_REVIEW");assert.equal(c.preflight.orderedActions[2].data.slice(-40).toLowerCase(),c.preflight.predictedLiquidationEngine.slice(2).toLowerCase())});
 it("rejects occupied, drifted and underfunded preflight state",async()=>{const c=await context();for(const ps of[[preProvider(),preProvider({occupied:true})],[preProvider(),preProvider({nonce:6})],[preProvider({bad:true}),preProvider({bad:true})],[preProvider({balance:1n}),preProvider({balance:1n})]])await assert.rejects(preflightLendingStage4AcrossRpcs({providers:ps,manifest:c.manifest,deployer}),/code|disagreement|binding|insufficient/)});
 it("verifies Engine runtime, Safe executions and final reciprocal bindings",async()=>{const c=await ready(),v=await verifyLendingStage4AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c)],manifest:c.manifest,preflight:c.preflight,transactionHashes:hashes});assert.equal(v.status,"VERIFIED_LENDING_STAGE4_ACTIVATION");assert.equal(v.bindings.interestIndexCore,core);assert.equal(v.liquidationEngine,c.preflight.predictedLiquidationEngine)});
 it("rejects failed, reorged, weak, substituted and incomplete evidence",async()=>{const c=await ready();for(const o of[{failed:true},{reorg:true},{head:201},{badDeploy:true},{badRuntime:true},{badSafe:true},{noEvent:true},{badFinal:true}])await assert.rejects(verifyLendingStage4AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c,o)],manifest:c.manifest,preflight:c.preflight,transactionHashes:hashes}),/failed|canonical|finality|deployment|runtime|inner|success|binding|disagreement/)});
 it("contains no key, signing or broadcast path",()=>{for(const f of["../scripts/prepare-lending-stage4-manifest.mjs","../scripts/preflight-lending-stage4-activation.mjs","../scripts/verify-lending-stage4-activation.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
