import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{buildLendingStage6Readiness}from"../scripts/build-lending-stage6-activation-readiness.mjs";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";
const a=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),oracle=a(10),rate=a(11),registry=a(12),index=a(13),core=a(14),engine=a(15),collateral=a(20),debt=a(21),marketId=ethers.id("market"),blockHash=ethers.id("block"),registryI=new ethers.Interface(["function getMarket(bytes32) view returns((address,address,uint8,uint8,uint16,uint16,uint16,uint128,uint128,uint128,bool))"]),oracleI=new ethers.Interface(["function getPrices(address) view returns(uint256,uint256)"]),rateI=new ethers.Interface(["function rateConfigs(bytes32) view returns(uint16,uint16,uint16,uint16,uint16,bool)"]),indexI=new ethers.Interface(["function indexStates(bytes32) view returns(uint128,uint128,uint64)","function core() view returns(address)"]),coreI=new ethers.Interface(["function marketStates(bytes32) view returns(uint128,uint128,uint128)","function totalBadDebtShares(bytes32) view returns(uint256)","function accruedReserves(bytes32) view returns(uint256)","function realizedSupplierLosses(bytes32) view returns(uint256)","function liquidationEngine() view returns(address)"]),erc20I=new ethers.Interface(["function balanceOf(address) view returns(uint256)"]);
function context(){const pb={stage:"stage5-disabled-market-initialization",network:{chainId:97},dependencies:{oracleManager:oracle,interestRateModel:rate,marketRegistry:registry,interestIndex:index,lendingCore:core,liquidationEngine:engine},market:{marketId,collateralAsset:collateral,debtAsset:debt,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000",borrowCap:"900",minBorrow:"10"},oracle:{maxDeviationBps:200},orderedActions:[],transactionOccurred:false},plan={...pb,planDigest:canonicalDigest(pb)},vb={status:"VERIFIED_LENDING_STAGE5_DISABLED_MARKET",planDigest:plan.planDigest,finalState:{marketEnabled:false},transactionOccurred:true},verification={...vb,verificationDigest:canonicalDigest(vb)};return{plan,verification}}
function provider(o={}){return{getNetwork:async()=>({chainId:BigInt(o.chainId||97)}),getBlockNumber:async()=>100,getBlock:async()=>({hash:o.reorg?ethers.id("other"):blockHash}),call:async({to,data})=>{const selector=data.slice(0,10);if(to.toLowerCase()===registry.toLowerCase())return registryI.encodeFunctionResult("getMarket",[[collateral,debt,18,18,5000,7000,500,1000,900,10,o.enabled||false]]);if(to.toLowerCase()===oracle.toLowerCase()){const asset=oracleI.decodeFunctionData("getPrices",data)[0],bad=o.badOracle&&asset.toLowerCase()===debt.toLowerCase();return oracleI.encodeFunctionResult("getPrices",bad?[100n,200n]:[100n,101n])}if(to.toLowerCase()===rate.toLowerCase())return rateI.encodeFunctionResult("rateConfigs",[200,800,9000,8000,1000,true]);if(to.toLowerCase()===index.toLowerCase()){if(selector===indexI.getFunction("core").selector)return indexI.encodeFunctionResult("core",[core]);return indexI.encodeFunctionResult("indexStates",[10n**27n,10n**27n,123n])}if(to.toLowerCase()===core.toLowerCase()){if(selector===coreI.getFunction("liquidationEngine").selector)return coreI.encodeFunctionResult("liquidationEngine",[engine]);if(selector===coreI.getFunction("marketStates").selector)return coreI.encodeFunctionResult("marketStates",[o.nonempty?1:0,0,0]);for(const n of["totalBadDebtShares","accruedReserves","realizedSupplierLosses"])if(selector===coreI.getFunction(n).selector)return coreI.encodeFunctionResult(n,[0])}return erc20I.encodeFunctionResult("balanceOf",[0])}}}
describe("LQC Lending Stage 10-6 activation readiness",function(){
 it("builds one bounded activation action only from empty disabled state",async()=>{const c=context(),r=await buildLendingStage6Readiness({providers:[provider(),provider()],plan:c.plan,stage5Verification:c.verification});assert.equal(r.status,"READY_FOR_SEPARATE_MARKET_ACTIVATION_REVIEW");assert.equal(r.emptyAccounting,true);assert.equal(r.orderedActions.length,1);assert.equal(r.riskLimits.maxLtvBps,5000);assert.equal(Object.keys(r.testDigests).length,5)});
 it("rejects enabled, nonempty, divergent Oracle and disagreeing RPC state",async()=>{const c=context();for(const ps of[[provider({enabled:true}),provider({enabled:true})],[provider({nonempty:true}),provider({nonempty:true})],[provider({badOracle:true}),provider({badOracle:true})],[provider(),provider({reorg:true})]])await assert.rejects(buildLendingStage6Readiness({providers:ps,plan:c.plan,stage5Verification:c.verification}),/disabled|empty|Oracle|disagreement/)});
 it("rejects substituted Stage-5 verification",async()=>{const c=context();c.verification.finalState.marketEnabled=true;await assert.rejects(buildLendingStage6Readiness({providers:[provider(),provider()],plan:c.plan,stage5Verification:c.verification}),/Stage-5 evidence/)});
 it("contains no key, signing, transaction or lending execution path",()=>{const s=fs.readFileSync(new URL("../scripts/build-lending-stage6-activation-readiness.mjs",import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction|supplyLiquidity\(|borrow\(|liquidate\(/)});
});
