import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { buildLendingStage1Manifest,validateLendingStage1Manifest } from "../scripts/prepare-lending-stage1-manifest.mjs";
import { preflightLendingStage1AcrossRpcs } from "../scripts/preflight-lending-stage1-deployment.mjs";

const address=index=>ethers.getAddress(`0x${index.toString(16).padStart(40,"0")}`),values=Array.from({length:13},(_,index)=>address(index+1));
function config(){const[governanceSafe,guardianSafe,treasurySafe,collateralAsset,debtAsset,collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,executor,lendingCore,supplyAdapter,adapterRegistry]=values,marketId=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["address","address"],[collateralAsset,debtAsset]));return{schemaVersion:1,network:{chainId:97},roles:{governanceSafe,guardianSafe,treasurySafe,governanceThreshold:4,governanceOwners:7,guardianThreshold:3,guardianOwners:5},market:{collateralAsset,debtAsset,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000000000000000000000",borrowCap:"900000000000000000000",minBorrow:"10000000000000000000"},oracle:{collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,maxStalenessSeconds:3600,maxDeviationBps:200},rate:{baseAprBps:200,slope1AprBps:800,slope2AprBps:9000,optimalUtilizationBps:8000,reserveFactorBps:1000},composite:{executor,lendingCore,supplyAdapter,adapterRegistry,marketId}}}
const deployer=address(100),blockHash=ethers.id("lending-stage1-block");
const provider=(options={})=>({getNetwork:async()=>({chainId:BigInt(options.chainId||97)}),getBlockNumber:async()=>500,getBlock:async()=>({hash:options.blockHash||blockHash,baseFeePerGas:1000000000n}),getTransactionCount:async()=>options.nonce??9,getBalance:async()=>options.balance??1000000000000000000n,getCode:async()=>options.code||"0x",estimateGas:async transaction=>BigInt(transaction.data===options.firstData?(options.firstGas||200000):options.gas||220000)});

describe("LQC Lending Stage-1 deployment manifest and multi-RPC preflight",function(){
  it("builds the exact Oracle and rate-model constructor deployments",async function(){const value=await buildLendingStage1Manifest(config());assert.equal(value.stage,"stage1-oracle-rate-deploy");assert.deepEqual(value.orderedActions.map(action=>action.contract),["LQCOracleManager","LQCInterestRateModel"]);assert.equal(value.orderedActions.every(action=>action.actor==="deployer"&&action.to===null),true);assert.equal(validateLendingStage1Manifest(value,config()),true);assert.match(value.manifestDigest,/^sha256:[0-9a-f]{64}$/)});
  it("rejects manifest mutation and configuration substitution",async function(){const value=await buildLendingStage1Manifest(config()),changed=structuredClone(value);changed.orderedActions[0].data="0x6000";assert.throws(()=>validateLendingStage1Manifest(changed,config()),/manifest/);const other=config();other.market.supplyCap="2000000000000000000000";assert.throws(()=>validateLendingStage1Manifest(value,other),/manifest/)});
  it("agrees across RPCs on block, nonce, empty addresses and bounded gas",async function(){const manifest=await buildLendingStage1Manifest(config()),result=await preflightLendingStage1AcrossRpcs({providers:[provider(),provider({gas:225000})],manifest,config:config(),deployer});assert.equal(result.status,"PREFLIGHT_VERIFIED_FOR_REVIEW");assert.equal(result.deployments.length,2);assert.equal(result.deployments[0].predictedAddress,ethers.getCreateAddress({from:deployer,nonce:9}));assert.equal(result.rpcCount,2);assert.match(result.preflightDigest,/^sha256:[0-9a-f]{64}$/);assert.equal(result.transactionOccurred,false)});
  it("rejects wrong chain, occupied CREATE address and RPC disagreement",async function(){const manifest=await buildLendingStage1Manifest(config());await assert.rejects(preflightLendingStage1AcrossRpcs({providers:[provider(),provider({chainId:56})],manifest,config:config(),deployer}),/chain/);await assert.rejects(preflightLendingStage1AcrossRpcs({providers:[provider(),provider({code:"0x6000"})],manifest,config:config(),deployer}),/already has code/);await assert.rejects(preflightLendingStage1AcrossRpcs({providers:[provider(),provider({nonce:10})],manifest,config:config(),deployer}),/disagreement/)});
  it("rejects material gas disagreement and insufficient tBNB",async function(){const manifest=await buildLendingStage1Manifest(config());await assert.rejects(preflightLendingStage1AcrossRpcs({providers:[provider(),provider({gas:500000})],manifest,config:config(),deployer}),/gas estimate/);await assert.rejects(preflightLendingStage1AcrossRpcs({providers:[provider({balance:1n}),provider({balance:1n})],manifest,config:config(),deployer}),/insufficient/)});
  it("contains no key, signing or transaction broadcast path",function(){for(const file of["../scripts/prepare-lending-stage1-manifest.mjs","../scripts/preflight-lending-stage1-deployment.mjs"]){const source=fs.readFileSync(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
