import assert from"node:assert/strict";import fs from"node:fs";import ganache from"ganache";import{ethers}from"ethers";
const artifact=JSON.parse(fs.readFileSync(new URL("../artifacts/contracts/lending/LQCTestnetPriceFeed.sol/LQCTestnetPriceFeed.json",import.meta.url)));
describe("LQC governance-controlled testnet price feed",function(){
 let provider,owner,next,outsider,feed;beforeEach(async()=>{provider=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));owner=await provider.getSigner(0);next=await provider.getSigner(1);outsider=await provider.getSigner(2);feed=await new ethers.ContractFactory(artifact.abi,artifact.bytecode,owner).deploy(owner.address,8,100_00000000n);await feed.waitForDeployment()});
 it("publishes a complete positive round",async()=>{const r=await feed.latestRoundData();assert.equal(r[1],100_00000000n);assert.equal(r[0],1n);assert.equal(r[4],r[0]);assert.ok(r[3]>0n)});
 it("allows only governance to update a positive answer",async()=>{await assert.rejects(feed.connect(outsider).setAnswer(90_00000000n));await assert.rejects(feed.setAnswer(0));await(await feed.setAnswer(99_00000000n)).wait();const r=await feed.latestRoundData();assert.equal(r[1],99_00000000n);assert.equal(r[0],2n)});
 it("uses two-step ownership transfer and clears the pending owner",async()=>{await(await feed.transferOwnership(next.address)).wait();await assert.rejects(feed.connect(outsider).acceptOwnership());await(await feed.connect(next).acceptOwnership()).wait();assert.equal(await feed.owner(),next.address);assert.equal(await feed.pendingOwner(),ethers.ZeroAddress);await assert.rejects(feed.setAnswer(1));await(await feed.connect(next).setAnswer(1)).wait()});
 it("rejects unsafe constructor settings",async()=>{const factory=new ethers.ContractFactory(artifact.abi,artifact.bytecode,owner);await assert.rejects(factory.deploy(ethers.ZeroAddress,8,1));await assert.rejects(factory.deploy(owner.address,19,1));await assert.rejects(factory.deploy(owner.address,8,0))});
});
