import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{verifyLendingStage7Activation}from"../scripts/verify-lending-stage7-activation.mjs";import{prepareLendingStage7Pilot}from"../scripts/prepare-lending-stage7-pilot.mjs";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";
const a=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),gov=a(1),oracle=a(10),registry=a(11),core=a(12),collateral=a(20),debt=a(21),pilot=a(30),marketId=ethers.id("market"),hash=ethers.id("activation"),blockHash=ethers.id("block"),safeI=new ethers.Interface(["function execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes) returns(bool)","event ExecutionSuccess(bytes32 txHash,uint256 payment)"]),registryI=new ethers.Interface(["function setMarketEnabled(bytes32,bool)","function getMarket(bytes32) view returns((address,address,uint8,uint8,uint16,uint16,uint16,uint128,uint128,uint128,bool))"]),oracleI=new ethers.Interface(["function getPrices(address) view returns(uint256,uint256)"]);
function context(){const pb={stage:"stage5-disabled-market-initialization",network:{chainId:97},roles:{governanceSafe:gov},dependencies:{marketRegistry:registry,oracleManager:oracle,lendingCore:core},market:{marketId,collateralAsset:collateral,debtAsset:debt,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000000",borrowCap:"900000",minBorrow:"10"},oracle:{maxDeviationBps:200},transactionOccurred:false},plan={...pb,planDigest:canonicalDigest(pb)},action={id:1,actor:"governance-safe",action:"enable-capped-isolated-market",to:registry,value:"0",data:registryI.encodeFunctionData("setMarketEnabled",[marketId,true])},rb={status:"READY_FOR_SEPARATE_MARKET_ACTIVATION_REVIEW",planDigest:plan.planDigest,orderedActions:[action],riskLimits:{maxLtvBps:5000},transactionOccurred:false},readiness={...rb,readinessDigest:canonicalDigest(rb)};return{plan,readiness,action}}
function log(){const e=safeI.encodeEventLog(safeI.getEvent("ExecutionSuccess"),[ethers.id("safe"),0]);return{address:gov,topics:e.topics,data:e.data}}function provider(c,o={}){const action=o.badPayload?{...c.action,data:"0x1234"}:c.action;return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>o.head||210,getTransaction:async()=>({to:gov,data:safeI.encodeFunctionData("execTransaction",[action.to,0,action.data,0,0,0,0,ethers.ZeroAddress,ethers.ZeroAddress,"0x"])}),getTransactionReceipt:async()=>({status:o.failed?0:1,blockNumber:200,blockHash,logs:o.noEvent?[]:[log()]}),getBlock:async()=>({hash:o.reorg?ethers.id("reorg"):blockHash}),call:async({to})=>to.toLowerCase()===registry.toLowerCase()?registryI.encodeFunctionResult("getMarket",[[collateral,debt,18,18,5000,7000,500,1000000,900000,10,o.badPolicy?false:true]]):oracleI.encodeFunctionResult("getPrices",o.badOracle?[100,200]:[100,101])}}
describe("LQC Lending Stage 10-7 activation and pilot",function(){
 it("verifies the exact Safe activation and unchanged capped policy",async()=>{const c=context(),v=await verifyLendingStage7Activation({providers:[provider(c),provider(c)],plan:c.plan,stage6Readiness:c.readiness,transactionHash:hash});assert.equal(v.status,"VERIFIED_LENDING_STAGE7_CAPPED_MARKET_ACTIVATION");assert.equal(v.activation.confirmations,11)});
 it("rejects failed, reorged, weak, changed and unsafe activation evidence",async()=>{const c=context();for(const o of[{failed:true},{reorg:true},{head:201},{badPayload:true},{noEvent:true},{badPolicy:true},{badOracle:true}])await assert.rejects(verifyLendingStage7Activation({providers:[provider(c),provider(c,o)],plan:c.plan,stage6Readiness:c.readiness,transactionHash:hash}),/failed|canonical|finality|payload|success|policy|Oracle|disagreement/)});
 it("builds a seven-action exact-approval pilot below 0.1 percent caps",async()=>{const c=context(),activation=await verifyLendingStage7Activation({providers:[provider(c),provider(c)],plan:c.plan,stage6Readiness:c.readiness,transactionHash:hash}),p=prepareLendingStage7Pilot({plan:c.plan,activationVerification:activation,pilotAccount:pilot,supplyAmount:"1000",collateralAmount:"1000",borrowAmount:"500"});assert.equal(p.orderedActions.length,7);assert.equal(p.transactionOccurred,false);assert.match(p.pilotPlanDigest,/^sha256:/)});
 it("rejects oversized, below-minimum and substituted pilot plans",async()=>{const c=context(),activation=await verifyLendingStage7Activation({providers:[provider(c),provider(c)],plan:c.plan,stage6Readiness:c.readiness,transactionHash:hash});for(const x of[["1001","1000","500"],["1000","1000","9"],["1000","1000","1001"]])assert.throws(()=>prepareLendingStage7Pilot({plan:c.plan,activationVerification:activation,pilotAccount:pilot,supplyAmount:x[0],collateralAmount:x[1],borrowAmount:x[2]}),/0.1%/);activation.marketId=ethers.id("changed");assert.throws(()=>prepareLendingStage7Pilot({plan:c.plan,activationVerification:activation,pilotAccount:pilot,supplyAmount:"1000",collateralAmount:"1000",borrowAmount:"500"}),/evidence/)});
 it("contains no key, signing or transaction broadcast path",()=>{for(const f of["../scripts/verify-lending-stage7-activation.mjs","../scripts/prepare-lending-stage7-pilot.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
