import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { buildLendingStage1Manifest } from "../scripts/prepare-lending-stage1-manifest.mjs";
import { preflightLendingStage1AcrossRpcs } from "../scripts/preflight-lending-stage1-deployment.mjs";
import { verifyLendingStage1DeploymentAcrossRpcs } from "../scripts/verify-lending-stage1-deployment.mjs";
import { buildLendingStage2Manifest } from "../scripts/prepare-lending-stage2-manifest.mjs";

const address=index=>ethers.getAddress(`0x${index.toString(16).padStart(40,"0")}`),values=Array.from({length:13},(_,index)=>address(index+1)),deployer=address(100),canonicalBlock=ethers.id("lending-stage1-canonical"),hashes=[ethers.id("lending-oracle-deploy"),ethers.id("lending-rate-deploy")],artifact=(name,source)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${source}.sol/${name}.json`,import.meta.url)));
function config(){const[governanceSafe,guardianSafe,treasurySafe,collateralAsset,debtAsset,collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,executor,lendingCore,supplyAdapter,adapterRegistry]=values,marketId=ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["address","address"],[collateralAsset,debtAsset]));return{schemaVersion:1,network:{chainId:97},roles:{governanceSafe,guardianSafe,treasurySafe,governanceThreshold:4,governanceOwners:7,guardianThreshold:3,guardianOwners:5},market:{collateralAsset,debtAsset,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000000000000000000000",borrowCap:"900000000000000000000",minBorrow:"10000000000000000000"},oracle:{collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,maxStalenessSeconds:3600,maxDeviationBps:200},rate:{baseAprBps:200,slope1AprBps:800,slope2AprBps:9000,optimalUtilizationBps:8000,reserveFactorBps:1000},composite:{executor,lendingCore,supplyAdapter,adapterRegistry,marketId}}}
const preflightProvider=()=>({getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>190,getBlock:async()=>({hash:ethers.id("preflight"),baseFeePerGas:1000000000n}),getFeeData:async()=>({gasPrice:1000000000n}),getTransactionCount:async()=>7,getBalance:async()=>1000000000000000000n,getCode:async()=>"0x",estimateGas:async()=>200000n});
async function context(){const configuration=config(),manifest=await buildLendingStage1Manifest(configuration),preflight=await preflightLendingStage1AcrossRpcs({providers:[preflightProvider(),preflightProvider()],manifest,config:configuration,deployer});return{configuration,manifest,preflight}}
function verificationProvider(context,options={}){const addresses=context.preflight.deployments.map(value=>value.predictedAddress),runtimes=[artifact("LQCOracleManager","lending/LQCOracleManager").deployedBytecode,artifact("LQCInterestRateModel","lending/LQCInterestRateModel").deployedBytecode];return{getNetwork:async()=>({chainId:BigInt(options.chainId||97)}),getBlockNumber:async()=>options.head||210,getTransaction:async hash=>{const index=hashes.indexOf(hash);return index<0?null:{from:deployer,to:null,value:0n,nonce:7+index,data:options.badData&&index===0?"0x6000":context.manifest.orderedActions[index].data}},getTransactionReceipt:async hash=>{const index=hashes.indexOf(hash);return index<0?null:{status:options.failed&&index===0?0:1,contractAddress:options.badAddress&&index===0?ethers.ZeroAddress:addresses[index],blockNumber:200+index,blockHash:canonicalBlock,index,gasUsed:100000n+BigInt(index),gasPrice:1000000000n}},getBlock:async()=>({hash:options.reorg?ethers.id("reorg"):canonicalBlock}),getCode:async target=>{const index=addresses.findIndex(value=>value.toLowerCase()===target.toLowerCase());return options.badRuntime&&index===0?"0x6000":runtimes[index]}}}

describe("LQC Lending Stage-1 verification and Stage-2 manifest",function(){
  it("verifies two finalized deployments and exact compiled runtime across RPCs",async function(){const value=await context(),result=await verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value)],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes});assert.equal(result.status,"VERIFIED_LENDING_STAGE1_DEPLOYMENT");assert.equal(result.deployments.length,2);assert.equal(result.deployments[0].confirmations,11);assert.match(result.verificationDigest,/^sha256:[0-9a-f]{64}$/);assert.equal(result.transactionOccurred,true)});
  it("rejects wrong init code, address, canonical block and runtime",async function(){const value=await context();for(const options of[{badData:true},{badAddress:true},{reorg:true},{badRuntime:true}])await assert.rejects(verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value,options)],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes}),/init code|address|canonical|runtime/)});
  it("rejects failed or weak-finality receipts and duplicate hashes",async function(){const value=await context();await assert.rejects(verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value,{failed:true})],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes}),/missing or failed/);await assert.rejects(verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value,{head:201}),verificationProvider(value,{head:201})],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes}),/finality/);await assert.rejects(verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value)],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:[hashes[0],hashes[0]]}),/unique/)});
  it("builds Stage-2 Registry and Index only from verified Stage-1 addresses",async function(){const value=await context(),verification=await verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value)],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes}),stage2=await buildLendingStage2Manifest({config:value.configuration,stage1Verification:verification});assert.equal(stage2.stage,"stage2-registry-index-deploy");assert.deepEqual(stage2.orderedActions.map(item=>item.contract),["LQCLendingMarketRegistry","LQCLendingInterestIndex"]);assert.equal(stage2.dependencies.oracleManager,verification.deployments[0].contractAddress);assert.equal(stage2.dependencies.interestRateModel,verification.deployments[1].contractAddress);assert.match(stage2.manifestDigest,/^sha256:[0-9a-f]{64}$/)});
  it("rejects rehashed Stage-1 verification substitution",async function(){const value=await context(),verification=await verifyLendingStage1DeploymentAcrossRpcs({providers:[verificationProvider(value),verificationProvider(value)],manifest:value.manifest,config:value.configuration,preflight:value.preflight,transactionHashes:hashes});verification.deployments[0].contractAddress=address(999);await assert.rejects(buildLendingStage2Manifest({config:value.configuration,stage1Verification:verification}),/verification/)});
  it("contains no key, signing or transaction submission path",function(){for(const file of["../scripts/verify-lending-stage1-deployment.mjs","../scripts/prepare-lending-stage2-manifest.mjs"]){const source=fs.readFileSync(new URL(file,import.meta.url),"utf8");assert.doesNotMatch(source,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
