import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 4/1 Collateral Deposit / Withdraw",function(){
 this.timeout(30000);let p,o,g,u,c,d,oracle,reg,model,index,core,id;const dep=async(n,s,sg,...x)=>{const z=art(n,s),k=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await k.waitForDeployment();return k};const gas={gasLimit:1_000_000n};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true},wallet:{totalAccounts:5}}));o=await p.getSigner(0);g=await p.getSigner(1);u=await p.getSigner(2);c=await dep("MockERC20","mocks/MockERC20",o,"COL","COL");d=await dep("MockERC20","mocks/MockERC20",o,"DEBT","DEBT");const cp=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,100_00000000n),cs=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,100_00000000n),dp=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,1_00000000n),ds=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,1_00000000n);oracle=await dep("LQCOracleManager","lending/LQCOracleManager",o,o.address,g.address);await(await oracle.configureAsset(c.target,cp.target,cs.target,3600,200)).wait();await(await oracle.configureAsset(d.target,dp.target,ds.target,3600,200)).wait();reg=await dep("LQCLendingMarketRegistry","lending/LQCLendingMarketRegistry",o,o.address,g.address,oracle.target);const cfg={collateralAsset:c.target,debtAsset:d.target,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:ethers.parseEther("100"),borrowCap:ethers.parseEther("1000"),minBorrow:ethers.parseEther("10"),enabled:true};await(await reg.configureMarket(cfg)).wait();id=await reg.marketId(c.target,d.target);model=await dep("LQCInterestRateModel","lending/LQCInterestRateModel",o,o.address,g.address);await(await model.configureRate(id,{baseAprBps:0,slope1AprBps:0,slope2AprBps:0,optimalUtilizationBps:8000,reserveFactorBps:0,enabled:true})).wait();index=await dep("LQCLendingInterestIndex","lending/LQCLendingInterestIndex",o,o.address,model.target);await(await index.initializeMarket(id)).wait();core=await dep("LQCLendingCore","lending/LQCLendingCore",o,o.address,reg.target,index.target);await(await index.setCore(core.target)).wait();await(await c.mint(u.address,ethers.parseEther("10"))).wait();await(await c.connect(u).approve(core.target,ethers.MaxUint256)).wait();});
 it("deposits exact collateral into user and market accounting",async()=>{const x=ethers.parseEther("2");await(await core.connect(u).depositCollateral(id,x,gas)).wait();assert.equal(await core.collateralOf(id,u.address),x);assert.equal((await core.marketStates(id)).totalCollateral,x);assert.equal(await c.balanceOf(core.target),x);});
 it("rejects zero collateral and cap overflow without accounting drift",async()=>{await assert.rejects(core.connect(u).depositCollateral(id,0n));const x=ethers.parseEther("101");await assert.rejects(core.connect(u).depositCollateral(id,x));assert.equal(await core.collateralOf(id,u.address),0n);assert.equal((await core.marketStates(id)).totalCollateral,0n);});
 it("withdraws exact collateral to a chosen receiver when debt-free",async()=>{const x=ethers.parseEther("2");await(await core.connect(u).depositCollateral(id,x,gas)).wait();await(await core.connect(u).withdrawCollateral(id,x,o.address,gas)).wait();assert.equal(await core.collateralOf(id,u.address),0n);assert.equal((await core.marketStates(id)).totalCollateral,0n);assert.equal(await c.balanceOf(o.address),x);});
 it("rejects zero amount, zero receiver, and over-withdraw atomically",async()=>{const x=ethers.parseEther("2");await(await core.connect(u).depositCollateral(id,x,gas)).wait();await assert.rejects(core.connect(u).withdrawCollateral(id,0n,u.address));await assert.rejects(core.connect(u).withdrawCollateral(id,1n,ethers.ZeroAddress));await assert.rejects(core.connect(u).withdrawCollateral(id,x+1n,u.address));assert.equal(await core.collateralOf(id,u.address),x);assert.equal((await core.marketStates(id)).totalCollateral,x);});
});