import assert from"node:assert/strict";import fs from"node:fs";import{ethers}from"ethers";import{preflightLendingStage2AcrossRpcs}from"../scripts/preflight-lending-stage2-deployment.mjs";import{verifyLendingStage2AcrossRpcs}from"../scripts/verify-lending-stage2-deployment.mjs";import{canonicalDigest,sha256}from"../scripts/build-intent-reproducibility-seal.mjs";
const address=n=>ethers.getAddress(`0x${n.toString(16).padStart(40,"0")}`),deployer=address(100),gov=address(1),guardian=address(2),oracle=address(6),rate=address(7),blockHash=ethers.id("stage2-block"),hashes=[ethers.id("registry"),ethers.id("index")],art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url))),contracts=["LQCLendingMarketRegistry","LQCLendingInterestIndex"],runtimes=[art(contracts[0],"lending/LQCLendingMarketRegistry").deployedBytecode,art(contracts[1],"lending/LQCLendingInterestIndex").deployedBytecode],interfaces=[new ethers.Interface(["function owner() view returns(address)","function guardian() view returns(address)","function oracle() view returns(address)"]),new ethers.Interface(["function owner() view returns(address)","function rateModel() view returns(address)","function core() view returns(address)"])];
function manifest(){const actions=contracts.map((contract,i)=>({id:i+1,actor:"deployer",action:`deploy-${i}`,contract,to:null,value:"0",data:`0x60${i}`,initCodeDigest:sha256(`0x60${i}`)})),body={status:"REVIEW_REQUIRED",network:{chainId:97},stage:"stage2-registry-index-deploy",configPreflightDigest:sha256("config"),stage1VerificationDigest:sha256("stage1"),roles:{governanceSafe:gov,guardianSafe:guardian},dependencies:{oracleManager:oracle,interestRateModel:rate},orderedActions:actions,transactionOccurred:false};return{...body,manifestDigest:canonicalDigest(body)}}
const preProvider=(o={})=>({getNetwork:async()=>({chainId:BigInt(o.chainId||97)}),getBlockNumber:async()=>100,getBlock:async()=>({hash:blockHash,baseFeePerGas:o.baseFee??0n}),getFeeData:async()=>({gasPrice:o.gasPrice??100_000_000n}),getTransactionCount:async()=>o.nonce??5,getBalance:async()=>o.balance??10n**18n,getCode:async()=>o.code||"0x",estimateGas:async()=>o.gas||200000n});
async function context(){const m=manifest(),p=await preflightLendingStage2AcrossRpcs({providers:[preProvider(),preProvider()],manifest:m,deployer});return{m,p}}
function verifyProvider(c,o={}){const addresses=c.p.deployments.map(x=>x.predictedAddress);return{getNetwork:async()=>({chainId:97n}),getBlockNumber:async()=>o.head||210,getTransaction:async h=>{const i=hashes.indexOf(h);return{from:deployer,to:null,nonce:5+i,data:o.badData&&i===0?"0x69":c.m.orderedActions[i].data}},getTransactionReceipt:async h=>{const i=hashes.indexOf(h);return{status:o.failed&&i===0?0:1,contractAddress:addresses[i],blockNumber:200+i,blockHash,index:i}},getBlock:async()=>({hash:o.reorg?ethers.id("reorg"):blockHash}),getCode:async a=>runtimes[addresses.findIndex(x=>x.toLowerCase()===a.toLowerCase())],call:async({to,data})=>{const i=addresses.findIndex(x=>x.toLowerCase()===to.toLowerCase()),iface=interfaces[i],fn=iface.getFunction(data.slice(0,10)).name;let value=gov;if(fn==="guardian")value=guardian;if(fn==="oracle")value=o.badOracle?address(99):oracle;if(fn==="rateModel")value=rate;if(fn==="core")value=ethers.ZeroAddress;return iface.encodeFunctionResult(fn,[value])}}}
describe("LQC Lending Stage-2 preflight and deployment verification",function(){
 it("preflights two CREATE addresses and bounded gas across RPCs",async()=>{const c=await context();assert.equal(c.p.status,"PREFLIGHT_VERIFIED_FOR_REVIEW");assert.equal(c.p.deployments.length,2);assert.equal(c.p.deployments[0].predictedAddress,ethers.getCreateAddress({from:deployer,nonce:5}));assert.equal(c.p.conservativeGasPrice,"100000000");assert.equal(c.p.totalApprovedGasLimit,"480000");assert.equal(c.p.requiredGasBudget,"48000000000000")});
 it("rejects occupied addresses, RPC disagreement and insufficient gas funds",async()=>{const m=manifest();await assert.rejects(preflightLendingStage2AcrossRpcs({providers:[preProvider(),preProvider({code:"0x60"})],manifest:m,deployer}),/already has code/);await assert.rejects(preflightLendingStage2AcrossRpcs({providers:[preProvider(),preProvider({nonce:6})],manifest:m,deployer}),/disagreement/);await assert.rejects(preflightLendingStage2AcrossRpcs({providers:[preProvider({balance:1n}),preProvider({balance:1n})],manifest:m,deployer}),/insufficient/)});
 it("verifies canonical runtime and Registry-Index dependency bindings",async()=>{const c=await context(),v=await verifyLendingStage2AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c)],manifest:c.m,preflight:c.p,transactionHashes:hashes});assert.equal(v.status,"VERIFIED_LENDING_STAGE2_DEPLOYMENT");assert.equal(v.deployments.length,2);assert.match(v.verificationDigest,/^sha256:/)});
 it("rejects failed, reorged, substituted or weak-finality evidence",async()=>{const c=await context();for(const o of[{failed:true},{reorg:true},{badData:true},{badOracle:true},{head:201}])await assert.rejects(verifyLendingStage2AcrossRpcs({providers:[verifyProvider(c),verifyProvider(c,o)],manifest:c.m,preflight:c.p,transactionHashes:hashes}),/failed|canonical|init code|binding|finality|disagreement/)});
 it("contains no key, signing or broadcast path",()=>{for(const f of["../scripts/preflight-lending-stage2-deployment.mjs","../scripts/verify-lending-stage2-deployment.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/PRIVATE_KEY|signTransaction|eth_sendTransaction/)}});
});
