import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{buildLendingStage12Rfp,writeStage12Rfp}from"../scripts/build-lending-stage12-audit-rfp.mjs";import{verifyStage12Rfp}from"../scripts/verify-lending-stage12-audit-rfp.mjs";
function context(){const sb={status:"READY_TO_SUBMIT_NOT_AUDITED",scope:{contracts:Array.from({length:7},(_,i)=>`C${i}`)},fixedRiskPolicy:{maxLtvBps:5000},transactionOccurred:false},stage11Submission={...sb,submissionDigest:canonicalDigest(sb)},vb={status:"VERIFIED_LENDING_STAGE11_AUDIT_SUBMISSION",submissionDigest:stage11Submission.submissionDigest,transactionOccurred:false},stage11Verification={...vb,verificationDigest:canonicalDigest(vb)};return{stage11Submission,stage11Verification}}
function bundle(){const c=context(),rfp=buildLendingStage12Rfp(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage12-"));writeStage12Rfp(dir,rfp);return{...c,rfp,dir}}
describe("LQC Lending Stage 10-12 audit RFP",function(){
 it("uses a 100-point technical-first score and explicit disqualifiers",()=>{const r=buildLendingStage12Rfp(context());assert.equal(Object.values(r.scoring.weights).reduce((a,b)=>a+b,0),100);assert.equal(r.scoring.weights.lendingAndEconomicSecurity,25);assert.equal(r.scoring.weights.commercialTerms,5);assert.equal(r.scoring.automaticDisqualifiers.length,6);assert.equal(r.status,"INTERNAL_REVIEW_ONLY_NOT_SENT")});
 it("writes and independently verifies the five-file internal RFP",()=>{const b=bundle(),v=verifyStage12Rfp({directoryPath:b.dir,stage11Submission:b.stage11Submission,stage11Verification:b.stage11Verification});assert.equal(v.status,"VERIFIED_LENDING_STAGE12_INTERNAL_RFP");assert.equal(v.scoreWeightTotal,100);assert.equal(v.proposalCount,0);assert.equal(v.externalCommunicationOccurred,false)});
 it("rejects Stage-11 substitution, vendor preselection and changed RFP files",()=>{const c=context();c.stage11Verification.submissionDigest="sha256:"+"00".repeat(32);assert.throws(()=>buildLendingStage12Rfp(c),/Stage-11/);let b=bundle(),f=path.join(b.dir,"quote-comparison.json"),q=JSON.parse(fs.readFileSync(f));q.selectedVendor="Vendor A";fs.writeFileSync(f,JSON.stringify(q));assert.throws(()=>verifyStage12Rfp({directoryPath:b.dir,stage11Submission:b.stage11Submission,stage11Verification:b.stage11Verification}),/unauthorized/);b=bundle();fs.appendFileSync(path.join(b.dir,"RFP.md"),"changed");assert.throws(()=>verifyStage12Rfp({directoryPath:b.dir,stage11Submission:b.stage11Submission,stage11Verification:b.stage11Verification}),/RFP|manifest/);b=bundle();fs.writeFileSync(path.join(b.dir,"extra"),"");assert.throws(()=>verifyStage12Rfp({directoryPath:b.dir,stage11Submission:b.stage11Submission,stage11Verification:b.stage11Verification}),/file set/)});
 it("contains no network, vendor contact, key, signing or payment mechanism",()=>{for(const f of["../scripts/build-lending-stage12-audit-rfp.mjs","../scripts/verify-lending-stage12-audit-rfp.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/fetch\(|JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction|sendEmail|paymentIntent/)}});
});
