import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 4/2 Supply / Withdraw",function(){
 this.timeout(30000);let p,o,g,l,c,d,reg,core,id;const dep=async(n,s,sg,...x)=>{const z=art(n,s),k=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await k.waitForDeployment();return k};const gas={gasLimit:1_000_000n};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true},wallet:{totalAccounts:5}}));o=await p.getSigner(0);g=await p.getSigner(1);l=await p.getSigner(2);c=await dep("MockERC20","mocks/MockERC20",o,"COL","COL");d=await dep("MockERC20","mocks/MockERC20",o,"DEBT","DEBT");const cp=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,100_00000000n),cs=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,100_00000000n),dp=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,1_00000000n),ds=await dep("MockPriceFeed","mocks/MockPriceFeed",o,8,1_00000000n),oracle=await dep("LQCOracleManager","lending/LQCOracleManager",o,o.address,g.address);await(await oracle.configureAsset(c.target,cp.target,cs.target,3600,200)).wait();await(await oracle.configureAsset(d.target,dp.target,ds.target,3600,200)).wait();reg=await dep("LQCLendingMarketRegistry","lending/LQCLendingMarketRegistry",o,o.address,g.address,oracle.target);await(await reg.configureMarket({collateralAsset:c.target,debtAsset:d.target,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:ethers.parseEther("1000"),borrowCap:ethers.parseEther("400"),minBorrow:ethers.parseEther("10"),enabled:true})).wait();id=await reg.marketId(c.target,d.target);const model=await dep("LQCInterestRateModel","lending/LQCInterestRateModel",o,o.address,g.address);await(await model.configureRate(id,{baseAprBps:200,slope1AprBps:800,slope2AprBps:9000,optimalUtilizationBps:8000,reserveFactorBps:1000,enabled:true})).wait();const index=await dep("LQCLendingInterestIndex","lending/LQCLendingInterestIndex",o,o.address,model.target);await(await index.initializeMarket(id)).wait();core=await dep("LQCLendingCore","lending/LQCLendingCore",o,o.address,reg.target,index.target);await(await index.setCore(core.target)).wait();await(await d.mint(l.address,ethers.parseEther("1000"))).wait();await(await d.connect(l).approve(core.target,ethers.MaxUint256)).wait();});
 it("supplies exact debt assets and mints indexed lender shares",async()=>{const x=ethers.parseEther("100");await(await core.connect(l).supplyLiquidity(id,x,gas)).wait();assert.equal(await core.liquidityOf(id,l.address),x);assert.equal(await d.balanceOf(core.target),x);assert.ok((await core.marketStates(id)).totalSupplyShares>0n);});
 it("rejects zero supply and supply-cap overflow without drift",async()=>{await assert.rejects(core.connect(l).supplyLiquidity(id,0n));await assert.rejects(core.connect(l).supplyLiquidity(id,ethers.parseEther("1001")));assert.equal(await core.liquidityOf(id,l.address),0n);assert.equal(await d.balanceOf(core.target),0n);});
 it("withdraws exact available liquidity to receiver and burns shares",async()=>{const x=ethers.parseEther("100");await(await core.connect(l).supplyLiquidity(id,x,gas)).wait();const before=await core.liquiditySharesOf(id,l.address);await(await core.connect(l).withdrawLiquidity(id,ethers.parseEther("40"),o.address,gas)).wait();assert.equal(await d.balanceOf(o.address),ethers.parseEther("40"));assert.ok((await core.liquiditySharesOf(id,l.address))<before);});
 it("rejects zero/zero-receiver and claim overflow atomically",async()=>{const x=ethers.parseEther("100");await(await core.connect(l).supplyLiquidity(id,x,gas)).wait();const shares=await core.liquiditySharesOf(id,l.address);await assert.rejects(core.connect(l).withdrawLiquidity(id,0n,l.address));await assert.rejects(core.connect(l).withdrawLiquidity(id,1n,ethers.ZeroAddress));await assert.rejects(core.connect(l).withdrawLiquidity(id,x+1n,l.address));assert.equal(await core.liquiditySharesOf(id,l.address),shares);});
});