import assert from "node:assert/strict";
import fs from "node:fs";
import { ethers } from "ethers";
import { validateLendingTestnetConfig } from "../scripts/validate-lending-testnet-config.mjs";

const addresses=Array.from({length:11},(_,index)=>ethers.getAddress(`0x${(index+1).toString(16).padStart(40,"0")}`));
function fixture(){const[governanceSafe,guardianSafe,treasurySafe,collateralAsset,debtAsset,collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,executor,lendingCore]=addresses,supplyAdapter=ethers.getAddress("0x"+"0c".padStart(40,"0")),marketId=ethers.solidityPackedKeccak256(["address","address"],[collateralAsset,debtAsset]);return{schemaVersion:1,network:{chainId:97},roles:{governanceSafe,guardianSafe,treasurySafe,governanceThreshold:4,governanceOwners:7,guardianThreshold:3,guardianOwners:5},market:{collateralAsset,debtAsset,collateralDecimals:18,debtDecimals:18,maxLtvBps:5000,liquidationThresholdBps:7000,liquidationBonusBps:500,supplyCap:"1000000000000000000000",borrowCap:"900000000000000000000",minBorrow:"10000000000000000000"},oracle:{collateralPrimary,collateralSecondary,debtPrimary,debtSecondary,maxStalenessSeconds:3600,maxDeviationBps:200},rate:{baseAprBps:200,slope1AprBps:800,slope2AprBps:9000,optimalUtilizationBps:8000,reserveFactorBps:1000},composite:{executor,lendingCore,supplyAdapter,marketId}}}

describe("LQC Lending testnet configuration preflight",function(){
  it("accepts only the fixed conservative BSC testnet policy",function(){const result=validateLendingTestnetConfig(fixture());assert.equal(result.status,"PASS_LENDING_TESTNET_CONFIG_PREFLIGHT");assert.equal(result.checks.length,11);assert.match(result.preflightDigest,/^sha256:[0-9a-f]{64}$/);assert.equal(result.transactionOccurred,false)});
  it("rejects wrong chain, weakened Safe policy and shared roles",function(){let value=fixture();value.network.chainId=56;assert.throws(()=>validateLendingTestnetConfig(value),/chain 97/);value=fixture();value.roles.governanceThreshold=3;assert.throws(()=>validateLendingTestnetConfig(value),/Safe policy/);value=fixture();value.roles.guardianSafe=value.roles.governanceSafe;assert.throws(()=>validateLendingTestnetConfig(value),/distinct/)});
  it("rejects weakened risk limits and unsafe caps",function(){for(const [field,value] of [["maxLtvBps",5100],["liquidationThresholdBps",7100],["liquidationBonusBps",600]]){const input=fixture();input.market[field]=value;assert.throws(()=>validateLendingTestnetConfig(input),/risk policy/)}const input=fixture();input.market.borrowCap=input.market.supplyCap;assert.throws(()=>validateLendingTestnetConfig(input),/caps/)});
  it("rejects reused or weak Oracle feeds and unsafe rates",function(){let value=fixture();value.oracle.debtSecondary=value.oracle.debtPrimary;assert.throws(()=>validateLendingTestnetConfig(value),/four distinct/);value=fixture();value.oracle.maxStalenessSeconds=3601;assert.throws(()=>validateLendingTestnetConfig(value),/dual feeds/);value=fixture();value.rate.slope2AprBps=20000;assert.throws(()=>validateLendingTestnetConfig(value),/interest/)});
  it("rejects Composite market substitution and contains no network or transaction path",function(){const value=fixture();value.composite.marketId=ethers.id("OTHER");assert.throws(()=>validateLendingTestnetConfig(value),/binding/);const source=fs.readFileSync(new URL("../scripts/validate-lending-testnet-config.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction/)});
});
