import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{canonicalDigest}from"../scripts/build-intent-reproducibility-seal.mjs";import{buildLendingStage15Hardening,writeStage15Hardening}from"../scripts/build-lending-stage15-preaudit-hardening.mjs";import{verifyStage15Hardening}from"../scripts/verify-lending-stage15-preaudit-hardening.mjs";
const sourceDirectory=path.resolve(new URL("..",import.meta.url).pathname);
function context(){const p={status:"AWAITING_EXTERNAL_TRANSMISSION_APPROVAL",communicationAllowed:false,externalCommunicationOccurred:false},stage14Plan={...p,intakeDigest:canonicalDigest(p)},v={status:"VERIFIED_LENDING_STAGE14_AWAITING_TRANSMISSION_APPROVAL",intakeDigest:stage14Plan.intakeDigest},stage14Verification={...v,verificationDigest:canonicalDigest(v)};return{stage14Plan,stage14Verification,sourceDirectory}}
function bundle(){const c=context(),hardening=buildLendingStage15Hardening(c),dir=fs.mkdtempSync(path.join(os.tmpdir(),"lqc-stage15-"));writeStage15Hardening(dir,hardening);return{...c,hardening,dir}}
describe("LQC Lending Stage 10-15 pre-audit hardening",function(){
 it("pins the economic, core and interest tests with explicit hardening coverage",()=>{const h=buildLendingStage15Hardening(context());assert.equal(Object.keys(h.testEvidence).length,3);assert.equal(Object.keys(h.coverage).length,8);assert.equal(h.coverage.longHorizonAccrualAndRounding,"COVERED_36_MONTHS");assert.equal(h.status,"CODE_HARDENED_TESTNET_EXECUTION_PENDING")});
 it("keeps all nine real testnet gates pending and blocks audit start",()=>{const h=buildLendingStage15Hardening(context());assert.equal(h.testnetExecutionGates.length,9);assert.ok(h.testnetExecutionGates.every(g=>!g.completed&&g.evidenceDigest===null));assert.equal(h.auditStartAllowed,false);assert.equal(h.externalCommunicationAllowed,false)});
 it("writes and independently verifies the four-file hardening bundle",()=>{const b=bundle(),v=verifyStage15Hardening({directoryPath:b.dir,stage14Plan:b.stage14Plan,stage14Verification:b.stage14Verification,sourceDirectory:b.sourceDirectory});assert.equal(v.status,"VERIFIED_LENDING_STAGE15_CODE_HARDENED_EXECUTION_PENDING");assert.equal(v.completedTestnetGates,0);assert.equal(v.auditStartAllowed,false)});
 it("rejects changed tests, fabricated execution and Stage-14 substitution",()=>{let b=bundle(),f=path.join(b.dir,"testnet-execution-checklist.json"),x=JSON.parse(fs.readFileSync(f));x.gates[0].completed=true;fs.writeFileSync(f,JSON.stringify(x));assert.throws(()=>verifyStage15Hardening({directoryPath:b.dir,stage14Plan:b.stage14Plan,stage14Verification:b.stage14Verification,sourceDirectory:b.sourceDirectory}),/fabricated|manifest/);const c=context();c.stage14Verification.intakeDigest="sha256:"+"00".repeat(32);assert.throws(()=>buildLendingStage15Hardening(c),/Stage-14/)});
 it("contains no RPC, key, signing, deployment, audit-contact or transaction mechanism",()=>{for(const f of["../scripts/build-lending-stage15-preaudit-hardening.mjs","../scripts/verify-lending-stage15-preaudit-hardening.mjs"]){const s=fs.readFileSync(new URL(f,import.meta.url),"utf8");assert.doesNotMatch(s,/JsonRpcProvider|PRIVATE_KEY|signTransaction|eth_sendTransaction|sendEmail|deploy\(/)}});
});
