import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),context={};
vm.runInNewContext(fs.readFileSync(path.join(root,'app/recovery-store.js'),'utf8'),context);
const fingerprint=`0x${'ab'.repeat(32)}`,hash=`0x${'12'.repeat(32)}`,key='pending:test';
class MemoryStorage{constructor(){this.values=new Map()}getItem(name){return this.values.has(name)?this.values.get(name):null}setItem(name,value){this.values.set(name,String(value))}removeItem(name){this.values.delete(name)}}
class RacingStorage extends MemoryStorage{arm(value){this.remainingReads=2;this.racingValue=value}getItem(name){if(this.remainingReads){this.remainingReads--;if(this.remainingReads===0)this.values.set(name,this.racingValue)}return super.getItem(name)}}
const make=(storage=new MemoryStorage(),now=()=>1_000_000)=>context.LQCRecoveryStore.create({storage,key,deploymentFingerprint:fingerprint,isTransactionHash:value=>/^0x[0-9a-f]{64}$/i.test(value),now});
const owner=`0x${'56'.repeat(20)}`,quote={amountOut:9n,execution:{sender:owner,recipient:owner,minimumAmountOut:8n}},settlement={recipient:owner,minimumAmountOut:8n};

describe('LQC pending execution recovery store',function(){
  it('round-trips a valid pending execution including bigint fields',function(){const store=make();assert.equal(store.state().state,'none');store.remember(hash,quote,settlement);const record=store.state();assert.equal(record.state,'valid');assert.equal(record.value.anchorQuote.amountOut,9n);assert.equal(store.clear(hash),true);assert.equal(store.state().state,'none')});
  it('fails closed on corrupted, wrong-deployment, and future-dated records',function(){const storage=new MemoryStorage(),store=make(storage);storage.setItem(key,'{');assert.equal(store.state().state,'invalid');storage.setItem(key,JSON.stringify({version:1,deploymentFingerprint:`0x${'cd'.repeat(32)}`,transactionHash:hash,anchorQuote:{},settlementContext:{},submittedAt:1_000_000}));assert.equal(store.state().state,'invalid');storage.setItem(key,JSON.stringify({version:1,deploymentFingerprint:fingerprint,transactionHash:hash,anchorQuote:{},settlementContext:{},submittedAt:1_300_001}));assert.equal(store.state().state,'invalid')});
  it('proves a full recovery reservation can be written, read, and removed',function(){const storage=new MemoryStorage(),store=make(storage);store.assertAvailable(quote);assert.equal(storage.getItem(store.reservationKey),null)});
  it('blocks signing when storage rejects, changes, or retains the reservation',function(){const stores=[{getItem:()=>null,setItem(){throw new Error('quota')},removeItem(){}},{getItem:()=>'{changed}',setItem(){},removeItem(){}},{value:null,getItem(){return this.value},setItem(_,value){this.value=value},removeItem(){}}];for(const storage of stores)assert.throws(()=>make(storage).assertAvailable(quote),/PendingExecutionStorageUnavailable/)});
  it('verifies the submitted recovery record was durably stored',function(){const storage={value:null,getItem(){return this.value},setItem(){this.value='{changed}'},removeItem(){this.value=null}},store=make(storage);assert.throws(()=>store.remember(hash,quote,settlement),/PendingExecutionStorageUnavailable/)});
  it('allows an idempotent write and an explicitly linked same-plan speed-up replacement',function(){const store=make(),replacement=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);store.remember(hash,quote,settlement);store.remember(replacement,quote,settlement,hash);assert.equal(store.state().value.transactionHash,replacement)});
  it('rejects an unlinked or incorrectly linked hash replacement',function(){const store=make(),replacement=`0x${'34'.repeat(32)}`,wrong=`0x${'56'.repeat(32)}`;store.remember(hash,quote,settlement);assert.throws(()=>store.remember(replacement,quote,settlement),/Conflict/);assert.throws(()=>store.remember(replacement,quote,settlement,wrong),/Conflict/);assert.equal(store.state().value.transactionHash,hash)});
  it('persists one idempotent cancellation hash without replacing the original recovery identity',function(){const store=make(),cancellation=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);store.rememberCancellation(hash,cancellation);store.rememberCancellation(hash,cancellation);const record=store.state();assert.equal(record.value.transactionHash,hash);assert.equal(record.value.cancellationHash,cancellation);assert.equal(store.clear(cancellation),false);assert.equal(store.clear(hash),true)});
  it('rejects malformed, identical, or wrong-trade cancellation updates',function(){const store=make(),other=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);assert.throws(()=>store.rememberCancellation(hash,hash),/Conflict/);assert.throws(()=>store.rememberCancellation(other,`0x${'56'.repeat(32)}`),/Conflict/);assert.throws(()=>store.rememberCancellation(hash,'0x12'),/Conflict/)});
  it('rejects overwriting a recorded cancellation with a different hash',function(){const store=make(),first=`0x${'34'.repeat(32)}`,second=`0x${'56'.repeat(32)}`;store.remember(hash,quote,settlement);store.rememberCancellation(hash,first);assert.throws(()=>store.rememberCancellation(hash,second),/Conflict/);assert.equal(store.state().value.cancellationHash,first)});
  it('never erases a recorded cancellation through a later submit or replacement write',function(){const store=make(),cancellation=`0x${'34'.repeat(32)}`,replacement=`0x${'56'.repeat(32)}`;store.remember(hash,quote,settlement);store.rememberCancellation(hash,cancellation);assert.throws(()=>store.remember(hash,quote,settlement),/Conflict/);assert.throws(()=>store.remember(replacement,quote,settlement,hash),/Conflict/);const record=store.state();assert.equal(record.value.transactionHash,hash);assert.equal(record.value.cancellationHash,cancellation)});
  it('compares transaction identities case-insensitively across every transition',function(){const store=make(),upperHash=hash.toUpperCase(),replacement=`0x${'ab'.repeat(32)}`,cancellation=`0x${'cd'.repeat(32)}`;store.remember(hash,quote,settlement);store.remember(replacement,quote,settlement,upperHash);assert.throws(()=>store.rememberCancellation(replacement,replacement.toUpperCase()),/Conflict/);store.rememberCancellation(replacement.toUpperCase(),cancellation);store.rememberCancellation(replacement,cancellation.toUpperCase());assert.equal(store.clear(replacement.toUpperCase()),true)});
  it('rejects a conflicting pending plan and never clears a newer transaction',function(){const store=make(),replacement=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);assert.throws(()=>store.remember(replacement,{...quote,amountOut:10n},settlement),/PendingExecutionStorageConflict/);assert.equal(store.clear(replacement),false);assert.equal(store.state().value.transactionHash,hash);assert.equal(store.clear(hash),true)});
  it('never lets a stale recovery task clear a newer cancellation record',function(){const store=make(),cancellation=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);const stale=store.state().value;store.rememberCancellation(hash,cancellation);assert.equal(store.clear(hash,stale),false);const current=store.state().value;assert.equal(current.cancellationHash,cancellation);assert.equal(store.clear(hash,current),true)});
  it('never overwrites a record changed by another tab between read and write',function(){const storage=new RacingStorage(),store=make(storage),replacement=`0x${'34'.repeat(32)}`,cancellation=`0x${'56'.repeat(32)}`;store.remember(hash,quote,settlement);const current=JSON.parse(storage.getItem(key)),newer=JSON.stringify({...current,cancellationHash:cancellation});storage.arm(newer);assert.throws(()=>store.remember(replacement,quote,settlement,hash),/Conflict/);assert.equal(storage.getItem(key),newer);storage.setItem(key,JSON.stringify(current));storage.arm(newer);assert.throws(()=>store.rememberCancellation(hash,cancellation),/Conflict/);assert.equal(storage.getItem(key),newer)});
  it('rejects changing the recovery plan even when the transaction hash is unchanged',function(){const store=make();store.remember(hash,quote,settlement);assert.throws(()=>store.remember(hash,{...quote,amountOut:10n},settlement),/PendingExecutionStorageConflict/);assert.throws(()=>store.remember(hash,quote,{...settlement,minimumAmountOut:7n}),/PendingExecutionStorageConflict/);const record=store.state();assert.equal(record.value.anchorQuote.amountOut,9n);assert.equal(record.value.settlementContext.minimumAmountOut,8n)});
  it('preserves the first submission time across idempotent writes and linked replacements',function(){let clock=1_000_000;const storage=new MemoryStorage(),store=make(storage,()=>clock),replacement=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);const original=storage.getItem(key);clock=1_100_000;store.remember(hash,quote,settlement);assert.equal(storage.getItem(key),original);store.remember(replacement,quote,settlement,hash);const record=store.state();assert.equal(record.value.transactionHash,replacement);assert.equal(record.value.submittedAt,1_000_000)});
  it('fails closed when an application payload validator rejects account binding',function(){const storage=new MemoryStorage(),validatePayload=value=>value.anchorQuote.execution.sender===value.settlementContext.recipient,store=context.LQCRecoveryStore.create({storage,key,deploymentFingerprint:fingerprint,isTransactionHash:value=>/^0x[0-9a-f]{64}$/.test(value),validatePayload,now:()=>1_000_000});store.remember(hash,quote,settlement);assert.equal(store.state().state,'valid');const tampered=JSON.parse(storage.getItem(key));tampered.settlementContext.recipient=`0x${'78'.repeat(20)}`;storage.setItem(key,JSON.stringify(tampered));assert.equal(store.state().state,'invalid')});
  it('reports an invalid fail-closed state when submitted-trade storage cannot be read',function(){const storage={getItem(){throw new Error('denied')},setItem(){},removeItem(){}},store=make(storage);assert.equal(store.state().state,'invalid')});
  it('retains a submitted trade without throwing when recovery removal is unavailable',function(){const storage=new MemoryStorage(),store=make(storage);store.remember(hash,quote,settlement);storage.removeItem=()=>{throw new Error('denied')};assert.equal(store.clear(hash),false);assert.equal(store.state().state,'valid')});
  it('rejects malformed transaction hashes before writing a recovery record',function(){const storage=new MemoryStorage(),store=make(storage);assert.throws(()=>store.remember('0x12',quote,settlement),/InvalidPendingExecutionRecord/);assert.equal(storage.getItem(key),null)});
  it('rejects application-invalid recovery payloads before writing',function(){const storage=new MemoryStorage(),store=context.LQCRecoveryStore.create({storage,key,deploymentFingerprint:fingerprint,isTransactionHash:value=>/^0x[0-9a-f]{64}$/.test(value),validatePayload:()=>false,now:()=>1_000_000});assert.throws(()=>store.remember(hash,quote,settlement),/InvalidPendingExecutionRecord/);assert.equal(storage.getItem(key),null)});
  it('validates the complete cancellation record before writing it',function(){const storage=new MemoryStorage(),validatePayload=value=>value.cancellationHash===undefined,store=context.LQCRecoveryStore.create({storage,key,deploymentFingerprint:fingerprint,isTransactionHash:value=>/^0x[0-9a-f]{64}$/.test(value),validatePayload,now:()=>1_000_000}),cancellation=`0x${'34'.repeat(32)}`;store.remember(hash,quote,settlement);const original=storage.getItem(key);assert.throws(()=>store.rememberCancellation(hash,cancellation),/InvalidPendingExecutionRecord/);assert.equal(storage.getItem(key),original);assert.equal(store.state().value.cancellationHash,undefined)});
});
