import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/7 Execution Router boundaries",function(){
 this.timeout(30000);let p,o,u,r,e,a,b,x;const dep=async(n,s,sg,...z)=>{const v=art(n,s),c=await new ethers.ContractFactory(v.abi,v.bytecode,sg).deploy(...z);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true},wallet:{totalAccounts:3}}));o=await p.getSigner(0);u=await p.getSigner(1);r=await dep("LQCDexRegistry","router-v2/LQCDexRegistry",o,o.address);e=await dep("LQCExecutionRouter","router-v2/LQCExecutionRouter",o,r.target,ethers.ZeroAddress);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");x=await dep("MockReentrantExecutionAdapter","mocks/MockReentrantExecutionAdapter",o,e.target,ethers.id("X"));await(await r.addDex(ethers.id("X"),x.target,"X",1)).wait();});
 it("rejects zero, identical-token, zero-amount, zero-minimum, and expired execution before moving funds",async()=>{const dl=BigInt((await p.getBlock("latest")).timestamp+60);await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),ethers.ZeroAddress,b.target,1n,1n,u.address,dl,"0x"));await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),a.target,a.target,1n,1n,u.address,dl,"0x"));await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),a.target,b.target,0n,1n,u.address,dl,"0x"));await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),a.target,b.target,1n,0n,u.address,dl,"0x"));await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),a.target,b.target,1n,1n,u.address,dl-120n,"0x"));});
 it("rejects disabled execution adapters before pulling user tokens",async()=>{await(await a.mint(u.address,100n)).wait();await(await a.connect(u).approve(e.target,100n)).wait();await(await r.setDexEnabled(ethers.id("X"),false)).wait();const before=await a.balanceOf(u.address),dl=BigInt((await p.getBlock("latest")).timestamp+60);await assert.rejects(e.connect(u).swapExactInput(ethers.id("X"),a.target,b.target,100n,1n,u.address,dl,"0x"));assert.equal(await a.balanceOf(u.address),before);assert.equal(await a.balanceOf(e.target),0n);});
 it("rolls back balances and approvals when an adapter reenters",async()=>{await(await a.mint(u.address,100n)).wait();await(await a.connect(u).approve(e.target,100n)).wait();const before=await a.balanceOf(u.address),dl=BigInt((await p.getBlock("latest")).timestamp+60);await assert.rejects(async()=>{const tx=await e.connect(u).swapExactInput(ethers.id("X"),a.target,b.target,100n,1n,u.address,dl,"0x",{gasLimit:2_000_000n});await tx.wait();});assert.equal(await a.balanceOf(u.address),before);assert.equal(await a.balanceOf(e.target),0n);assert.equal(await a.allowance(e.target,x.target),0n);});
 it("rejects malformed split plans before consuming funds",async()=>{const dl=BigInt((await p.getBlock("latest")).timestamp+60),one=[{dexId:ethers.id("X"),amountIn:100n,amountOutMinimum:1n,routeData:"0x"}];await assert.rejects(e.connect(u).swapSplitExactInput(a.target,b.target,100n,1n,u.address,dl,one));const dup=[...one,{...one[0]}];await assert.rejects(e.connect(u).swapSplitExactInput(a.target,b.target,200n,1n,u.address,dl,dup));const wrong=[one[0],{dexId:ethers.id("Y"),amountIn:50n,amountOutMinimum:1n,routeData:"0x"}];await assert.rejects(e.connect(u).swapSplitExactInput(a.target,b.target,200n,1n,u.address,dl,wrong));});
 it("rejects best-route metadata misalignment and no executable route",async()=>{const dl=BigInt((await p.getBlock("latest")).timestamp+60);await assert.rejects(e.connect(u).swapBestExactInput(a.target,b.target,100n,1n,u.address,dl,[],[]));await(await r.setDexEnabled(ethers.id("X"),false)).wait();await assert.rejects(e.connect(u).swapBestExactInput(a.target,b.target,100n,1n,u.address,dl,["0x"],[0n]));});
});