import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/2 Pancake V2 Adapter boundaries",function(){
 this.timeout(30000);let p,o,user,a,b,router,adapter;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);user=await p.getSigner(1);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");router=await dep("MockPartialSpendRouter","mocks/MockPartialSpendRouter",o);adapter=await dep("PancakeV2Adapter","router-v2/adapters/PancakeV2Adapter",o,router.target);});
 it("rejects zero and undeployed router endpoints",async()=>{const z=art("PancakeV2Adapter","router-v2/adapters/PancakeV2Adapter"),F=new ethers.ContractFactory(z.abi,z.bytecode,o);await assert.rejects(F.deploy(ethers.ZeroAddress));await assert.rejects(F.deploy(user.address));});
 it("reports execution support and validates encoded route endpoints",async()=>{assert.equal(await adapter.supportsExecution(),true);const good=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[a.target,b.target]]);assert.equal(await adapter.quoteExactInput(a.target,b.target,123n,good),123n);const short=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[a.target]]);await assert.rejects(adapter.quoteExactInput(a.target,b.target,123n,short));const wrong=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[b.target,a.target]]);await assert.rejects(adapter.quoteExactInput(a.target,b.target,123n,wrong));});
 it("rejects a partial-spend downstream router and rolls back funds and approval",async()=>{const amount=ethers.parseEther("10"),data=ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[a.target,b.target]]);await(await a.mint(user.address,amount)).wait();await(await b.mint(router.target,amount)).wait();await(await a.connect(user).approve(adapter.target,amount)).wait();const before=await a.balanceOf(user.address);await assert.rejects(async()=>{const tx=await adapter.connect(user).executeExactInput(a.target,b.target,amount,1n,user.address,BigInt((await p.getBlock("latest")).timestamp+3600),data,{gasLimit:2_000_000n});await tx.wait();});assert.equal(await a.balanceOf(user.address),before);assert.equal(await a.balanceOf(adapter.target),0n);assert.equal(await a.allowance(adapter.target,router.target),0n);assert.equal(await b.balanceOf(user.address),0n);});
});