import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/8 Best Execution Proof boundaries",function(){
 this.timeout(30000);let p,o,u,v,a,b;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);v=await dep("LQCBestExecutionProof","router-v2/LQCBestExecutionProof",o);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");});
 const request=async()=>{const z=await p.getBlock("latest");return {chainId:(await p.getNetwork()).chainId,tokenIn:a.target,tokenOut:b.target,amountIn:1000n,recipient:u.address,slippageBps:100,validUntil:BigInt(z.timestamp+300)}};
 const result=async(req,id,adapter,gross,gas,fee,priority,route="0x1234",block=77n)=>{const hash=await v.computeRouteHash(req,block,id,adapter,route,gross,gas,fee);return {dexId:id,adapter,quoteBlock:block,grossAmountOut:gross,gasCostInTokenOut:gas,protocolFeeInTokenOut:fee,netAmountOut:gross-gas-fee,minimumAmountOut:gross*9900n/10000n,priority,routeHash:hash}};
 it("accepts an internally consistent selected quote and deterministic proof hash",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1200n,10n,5n,7);assert.equal(await v.verifySelectedQuote(req,x,"0x1234"),true);assert.notEqual(await v.proofHash(req,x),ethers.ZeroHash);});
 it("rejects route, cost, net-output, minimum-output, and adapter tampering",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1200n,10n,5n,7);for(const y of [{...x,gasCostInTokenOut:11n},{...x,netAmountOut:x.netAmountOut+1n},{...x,minimumAmountOut:x.minimumAmountOut+1n},{...x,adapter:u.address}])assert.equal(await v.verifySelectedQuote(req,y,"0x1234"),false);assert.equal(await v.verifySelectedQuote(req,x,"0xabcd"),false);});
 it("proves the highest net candidate and rejects a non-best selection",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1200n,100n,0n,1),y=await result(req,ethers.id("B"),u.address,1150n,10n,0n,1);assert.equal(await v.verifyBestCandidate(req,[x,y],["0x1234","0x1234"],1),true);assert.equal(await v.verifyBestCandidate(req,[x,y],["0x1234","0x1234"],0),false);});
 it("enforces priority then earliest-index tie breaking",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1100n,0n,0n,5),y=await result(req,ethers.id("B"),u.address,1100n,0n,0n,9);assert.equal(await v.verifyBestCandidate(req,[x,y],["0x1234","0x1234"],1),true);const z=await result(req,ethers.id("C"),a.target,1100n,0n,0n,9);assert.equal(await v.verifyBestCandidate(req,[y,z],["0x1234","0x1234"],0),true);assert.equal(await v.verifyBestCandidate(req,[y,z],["0x1234","0x1234"],1),false);});
 it("rejects duplicate DEX candidates, quote-block drift, and invalid selected indexes",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1100n,0n,0n,1),dup=await result(req,ethers.id("A"),u.address,1000n,0n,0n,1),drift=await result(req,ethers.id("B"),u.address,1000n,0n,0n,1,"0x1234",78n);assert.equal(await v.verifyBestCandidate(req,[x,dup],["0x1234","0x1234"],0),false);assert.equal(await v.verifyBestCandidate(req,[x,drift],["0x1234","0x1234"],0),false);assert.equal(await v.verifyBestCandidate(req,[x],["0x1234"],1),false);});
 it("binds candidate order into the best-candidate proof hash",async()=>{const req=await request(),x=await result(req,ethers.id("A"),o.address,1100n,0n,0n,1),y=await result(req,ethers.id("B"),u.address,1000n,0n,0n,1),h1=await v.bestCandidateProofHash(req,[x,y],0),h2=await v.bestCandidateProofHash(req,[y,x],1);assert.notEqual(h1,h2);});
});