import assert from "node:assert/strict";
import fs from "node:fs";
describe("Router 2.0 Proof Gateway history receipt independent verifier",function(){
  const js=fs.readFileSync(new URL("../app/router2-proof-gateway-history-receipt-verify-testnet.js",import.meta.url),"utf8"),html=fs.readFileSync(new URL("../app/router2-proof-gateway-history-receipt-verify-testnet.html",import.meta.url),"utf8");
  it("is independent and never requests an account or transaction",function(){assert.match(html,/독립검증 · 거래 없음/);assert.doesNotMatch(js,/eth_requestAccounts|eth_sendTransaction|getSigner\(|localStorage/);});
  it("strictly validates both exact V1 envelopes",function(){assert.match(js,/function exact\(value,keys\)/);assert.match(js,/LQC_PROOF_GATEWAY_EXECUTION_HISTORY_V1/);assert.match(js,/LQC_PROOF_GATEWAY_HISTORY_VERIFICATION_V1/);});
  it("recomputes every archive and the ordered archive root",function(){assert.match(js,/history\.entries\.map\(verifyArchive\)/);assert.match(js,/Archive Hash가 일치하지 않습니다/);assert.match(js,/ethers\.keccak256\(ethers\.concat\(entries\.map\(entry=>entry\.archiveHash\)\)\)/);});
  it("recomputes the verification hash and checks freshness",function(){assert.match(js,/computed\.toLowerCase\(\)!==verificationHash\.toLowerCase\(\)/);assert.match(js,/MAX_AGE_MS=15\*60\*1000/);assert.match(js,/MAX_FUTURE_MS=5\*60\*1000/);});
  it("checks the claimed block remains canonical without signing",function(){assert.match(js,/provider\.getBlock\(receipt\.latestBlockNumber\)/);assert.match(js,/block\.hash\.toLowerCase\(\)!==receipt\.latestBlockHash\.toLowerCase\(\)/);assert.match(js,/receiptConfirmations<12/);});
  it("rejects stale RPC state and rechecks every archived transaction",function(){assert.match(js,/MAX_LATEST_AGE_MS=2\*60\*1000/);assert.match(js,/for\(const entry of verifiedEntries\)/);assert.match(js,/provider\.getTransactionReceipt\(entry\.transactionHash\)/);assert.match(js,/provider\.getTransaction\(entry\.transactionHash\)/);});
  it("pins signer gateway runtime and consumed proof for every trade",function(){assert.match(js,/transaction\.from\.toLowerCase\(\)!==SIGNER/);assert.match(js,/ethers\.keccak256\(code\)!==GATEWAY_RUNTIME_HASH/);assert.match(js,/contract\.consumedProof\(entry\.execution\.proofHash\)/);assert.doesNotMatch(js,/eth_requestAccounts|eth_sendTransaction|getSigner\(/);});
  it("rejects archive amounts and allowances outside the reviewed scope",function(){assert.match(js,/entry\.executionFinal\.amountIn!==AMOUNT\.toString\(\)/);assert.match(js,/entry\.execution\.actualAmountOut!==entry\.executionFinal\.amountOut/);assert.match(js,/entry\.executionFinal\.residualAllowance!=="0"/);});
  it("decodes the canonical gateway event and matches proof route and amounts",function(){assert.match(js,/ProofBoundSwapExecuted/);assert.match(js,/gatewayInterface\.parseLog\(eventLog\)/);assert.match(js,/event\.args\.proofHash\.toLowerCase\(\)!==entry\.execution\.proofHash\.toLowerCase\(\)/);assert.match(js,/event\.args\.dexId\.toLowerCase\(\)!==FLOW/);assert.match(js,/event\.args\.amountOut\.toString\(\)!==final\.amountOut/);});
  it("decodes and constrains the exact gateway execution calldata",function(){assert.match(js,/gatewayInterface\.parseTransaction/);assert.match(js,/parsed\.name!=="executeBestCandidate"/);assert.match(js,/requestData\.chainId!==97n/);assert.match(js,/requestData\.tokenIn\.toLowerCase\(\)!==TLQC/);assert.match(js,/requestData\.tokenOut\.toLowerCase\(\)!==WBNB/);assert.match(js,/requestData\.amountIn!==AMOUNT/);});
  it("pins the selected flow adapter and recomputes proof from calldata",function(){assert.match(js,/selected\.dexId\.toLowerCase\(\)!==FLOW/);assert.match(js,/selected\.adapter\.toLowerCase\(\)!==ADAPTER/);assert.match(js,/ethers\.keccak256\(proofCode\)!==PROOF_RUNTIME_HASH/);assert.match(js,/proofContract\.bestCandidateProofHash\(requestData,candidates,selectedIndex\)/);assert.match(js,/computedProof\.toLowerCase\(\)!==entry\.execution\.proofHash\.toLowerCase\(\)/);});
});
