import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/6 Split Optimizer boundaries",function(){
 this.timeout(30000);let p,o,r,s,a,b;const dep=async(n,x,sg,...z)=>{const v=art(n,x),c=await new ethers.ContractFactory(v.abi,v.bytecode,sg).deploy(...z);await c.waitForDeployment();return c};const add=async(id,num,pri)=>{const x=await dep("MockExecutableQuoteAdapter","mocks/MockExecutableQuoteAdapter",o,num,100);await(await r.addDex(ethers.id(id),x.target,id,pri)).wait();return x};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);r=await dep("LQCDexRegistry","router-v2/LQCDexRegistry",o,o.address);s=await dep("LQCSplitOptimizer","router-v2/LQCSplitOptimizer",o,r.target);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");});
 it("rejects invalid amounts, parts, route metadata, and route caps",async()=>{await assert.rejects(s.quoteOptimalSplit(a.target,b.target,0n,[],[],2));await assert.rejects(s.quoteOptimalSplit(a.target,b.target,10n,[],[],1));await assert.rejects(s.quoteOptimalSplit(a.target,b.target,10n,[],[],11));await assert.rejects(s.quoteOptimalSplitCapped(a.target,b.target,10n,[],[],2,0));await add("A",100,1);await assert.rejects(s.quoteOptimalSplit(a.target,b.target,10n,[],[],2));});
 it("allocates the full input exactly with deterministic remainder handling",async()=>{await add("A",100,1);const x=await s.quoteOptimalSplit(a.target,b.target,101n,["0x"],[0n],4);assert.equal(x.amountsIn[0],101n);assert.equal(x.totalAmountOut,101n);assert.equal(x.totalNetAmountOut,101n);});
 it("charges a route cost only when opening a route",async()=>{await add("A",110,1);await add("B",109,100);const x=await s.quoteOptimalSplit(a.target,b.target,100n,["0x","0x"],[20n,0n],4);assert.equal(x.amountsIn.reduce((z,v)=>z+v,0n),100n);assert.equal(x.totalNetAmountOut,x.totalAmountOut-(x.amountsIn[0]>0n?20n:0n));});
 it("isolates disabled and quote-failing routes",async()=>{const bad=await add("BAD",200,100),good=await add("GOOD",100,1);await(await bad.setQuoteFailure(true)).wait();let x=await s.quoteOptimalSplit(a.target,b.target,100n,["0x","0x"],[0n,0n],4);assert.equal(x.amountsIn[0],0n);assert.equal(x.amountsIn[1],100n);await(await bad.setQuoteFailure(false)).wait();await(await r.setDexEnabled(ethers.id("BAD"),false)).wait();x=await s.quoteOptimalSplit(a.target,b.target,100n,["0x","0x"],[0n,0n],4);assert.equal(x.amountsIn[0],0n);assert.equal(x.amountsIn[1],100n);good;});
 it("respects maxRoutes and uses priority as marginal-net tie breaker",async()=>{await add("LOW",100,1);await add("HIGH",100,99);const x=await s.quoteOptimalSplitCapped(a.target,b.target,100n,["0x","0x"],[0n,0n],4,1);assert.equal(x.amountsIn[0],0n);assert.equal(x.amountsIn[1],100n);});
 it("fails closed when every executable marginal quote is uneconomic",async()=>{await add("A",100,1);await assert.rejects(s.quoteOptimalSplit(a.target,b.target,100n,["0x"],[100n],4));});
});