import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/1 DEX Registry boundaries",function(){
 this.timeout(30000);let p,o,pause,attacker,r,a1,a2;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);pause=await p.getSigner(1);attacker=await p.getSigner(2);r=await dep("LQCDexRegistry","router-v2/LQCDexRegistry",o,o.address);a1=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,100,100);a2=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,101,100);});
 it("rejects invalid IDs, EOAs, and unauthorized registration without registry drift",async()=>{await assert.rejects(r.addDex(ethers.ZeroHash,a1.target,"bad",1));await assert.rejects(r.addDex(ethers.id("EOA"),attacker.address,"bad",1));await assert.rejects(r.connect(attacker).addDex(ethers.id("X"),a1.target,"bad",1));assert.equal(await r.dexCount(),0n);});
 it("registers a reviewed adapter once and exposes deterministic metadata",async()=>{const id=ethers.id("DEX_A");await(await r.addDex(id,a1.target,"DEX A",7)).wait();const d=await r.getDexDetails(id);assert.equal(await r.dexCount(),1n);assert.equal(await r.dexIdAt(0),id);assert.equal(d.adapter,a1.target);assert.equal(d.enabled,true);assert.equal(d.priority,7n);assert.equal(d.name,"DEX A");assert(d.addedAt>0n);await assert.rejects(r.addDex(id,a2.target,"dup",9));});
 it("lets pauseAdmin disable but never enable or reconfigure a DEX",async()=>{const id=ethers.id("DEX_A");await(await r.addDex(id,a1.target,"DEX A",7)).wait();await(await r.setPauseAdmin(pause.address)).wait();await(await r.connect(pause).setDexEnabled(id,false)).wait();assert.equal((await r.getDex(id)).enabled,false);await assert.rejects(r.connect(pause).setDexEnabled(id,true));await assert.rejects(r.connect(pause).updateDex(id,a2.target,8));await assert.rejects(r.connect(attacker).setDexEnabled(id,false));});
 it("requires disable-before-update and preserves identity while changing adapter",async()=>{const id=ethers.id("DEX_A");await(await r.addDex(id,a1.target,"DEX A",7)).wait();await assert.rejects(r.updateDex(id,a2.target,8));await(await r.setDexEnabled(id,false)).wait();await(await r.updateDex(id,a2.target,8)).wait();const d=await r.getDexDetails(id);assert.equal(d.adapter,a2.target);assert.equal(d.priority,8n);assert.equal(d.name,"DEX A");});
 it("removes only disabled entries and keeps swapped indexes coherent",async()=>{const x=ethers.id("A"),y=ethers.id("B"),z=ethers.id("C");await(await r.addDex(x,a1.target,"A",1)).wait();await(await r.addDex(y,a1.target,"B",2)).wait();await(await r.addDex(z,a1.target,"C",3)).wait();await assert.rejects(r.removeDex(y));await(await r.setDexEnabled(y,false)).wait();await(await r.removeDex(y)).wait();assert.equal(await r.dexCount(),2n);assert.equal(await r.dexIdAt(0),x);assert.equal(await r.dexIdAt(1),z);assert.equal((await r.getDex(z)).priority,3n);await assert.rejects(r.getDex(y));});
 it("keeps ownership transfer two-step and prevents takeover",async()=>{await assert.rejects(r.connect(attacker).beginOwnershipTransfer(attacker.address));await(await r.beginOwnershipTransfer(attacker.address)).wait();await assert.rejects(r.acceptOwnership());assert.equal(await r.owner(),o.address);await(await r.connect(attacker).acceptOwnership()).wait();assert.equal(await r.owner(),attacker.address);assert.equal(await r.pendingOwner(),ethers.ZeroAddress);});
});