import assert from "node:assert/strict";import fs from "node:fs";import ganache from "ganache";import {ethers} from "ethers";
const artifact=(name,source)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${source}.sol/${name}.json`,import.meta.url)));
describe("LQC proof-bound gateway EVM",function(){this.timeout(30000);let provider,owner,tokenA,tokenB,registry,router,adapter,proof,gateway,request,candidates,routes;
beforeEach(async()=>{provider=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));owner=await provider.getSigner();const F=(n,s,...a)=>new ethers.ContractFactory(artifact(n,s).abi,artifact(n,s).bytecode,owner).deploy(...a);
tokenA=await F("MockERC20","mocks/MockERC20","A","A");tokenB=await F("MockERC20","mocks/MockERC20","B","B");const w=await F("MockWBNB","mocks/MockWBNB");const fac=await F("LQCFlowFactory","LQCFlowFactory",await owner.getAddress());await Promise.all([tokenA.waitForDeployment(),tokenB.waitForDeployment(),w.waitForDeployment(),fac.waitForDeployment()]);const flow=await F("LQCFlowRouter","LQCFlowRouter",await fac.getAddress(),await w.getAddress());registry=await F("LQCDexRegistry","router-v2/LQCDexRegistry",await owner.getAddress());await Promise.all([flow.waitForDeployment(),registry.waitForDeployment()]);router=await F("LQCExecutionRouter","router-v2/LQCExecutionRouter",await registry.getAddress(),ethers.ZeroAddress);adapter=await F("LQCFlowAdapter","router-v2/adapters/LQCFlowAdapter",await flow.getAddress());proof=await F("LQCBestExecutionProof","router-v2/LQCBestExecutionProof");await Promise.all([router.waitForDeployment(),adapter.waitForDeployment(),proof.waitForDeployment()]);gateway=await F("LQCProofBoundExecutionGateway","router-v2/LQCProofBoundExecutionGateway",await proof.getAddress(),await router.getAddress());await gateway.waitForDeployment();const amount=ethers.parseEther("10000");await (await tokenA.mint(await owner.getAddress(),amount)).wait();await (await tokenB.mint(await owner.getAddress(),amount)).wait();await (await tokenA.approve(await flow.getAddress(),amount)).wait();await (await tokenB.approve(await flow.getAddress(),amount)).wait();const b=await provider.getBlock("latest");await (await flow.addLiquidity(await tokenA.getAddress(),await tokenB.getAddress(),amount,amount,0,0,await owner.getAddress(),b.timestamp+3600)).wait();await (await tokenA.mint(await owner.getAddress(),ethers.parseEther("100"))).wait();const id=ethers.id("FLOW");await (await registry.addDex(id,await adapter.getAddress(),"Flow",100)).wait();routes=[ethers.AbiCoder.defaultAbiCoder().encode(["address[]"],[[await tokenA.getAddress(),await tokenB.getAddress()]])];request={chainId:(await provider.getNetwork()).chainId,tokenIn:await tokenA.getAddress(),tokenOut:await tokenB.getAddress(),amountIn:ethers.parseEther("10"),recipient:await owner.getAddress(),slippageBps:100,validUntil:BigInt(b.timestamp+300)};const q=await adapter.quoteExactInput(request.tokenIn,request.tokenOut,request.amountIn,routes[0]);const quoteBlock=await provider.getBlockNumber();const routeHash=await proof.computeRouteHash(request,quoteBlock,id,await adapter.getAddress(),routes[0],q,0,0);candidates=[{dexId:id,adapter:await adapter.getAddress(),quoteBlock,grossAmountOut:q,gasCostInTokenOut:0,protocolFeeInTokenOut:0,netAmountOut:q,minimumAmountOut:q*9900n/10000n,priority:100,routeHash}];await (await tokenA.approve(await gateway.getAddress(),request.amountIn)).wait();});
it("executes one proven route and blocks replay",async()=>{const before=await tokenB.balanceOf(await owner.getAddress());await (await gateway.executeBestCandidate(request,candidates,routes,0)).wait();assert((await tokenB.balanceOf(await owner.getAddress()))>before);await assert.rejects(async()=>{const replay=await gateway.executeBestCandidate(request,candidates,routes,0);await replay.wait();});});
it("rejects a forged minimum and registry adapter change",async()=>{const forged=[{...candidates[0],minimumAmountOut:candidates[0].minimumAmountOut-1n}];await assert.rejects(gateway.executeBestCandidate(request,forged,routes,0));await (await registry.setDexEnabled(candidates[0].dexId,false)).wait();await (await registry.removeDex(candidates[0].dexId)).wait();await assert.rejects(gateway.executeBestCandidate(request,candidates,routes,0));});});





