import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/4 Quote Router boundaries",function(){
 this.timeout(30000);let p,o,u,r,q,a,b;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);r=await dep("LQCDexRegistry","router-v2/LQCDexRegistry",o,o.address);q=await dep("LQCQuoteRouter","router-v2/LQCQuoteRouter",o,r.target);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");});
 it("rejects invalid request boundaries and metadata cardinality",async()=>{await assert.rejects(q.quoteBest(ethers.ZeroAddress,b.target,1n,[]));await assert.rejects(q.quoteBest(a.target,a.target,1n,[]));await assert.rejects(q.quoteBest(a.target,b.target,0n,[]));const net={chainId:(await p.getNetwork()).chainId,tokenIn:a.target,tokenOut:b.target,amountIn:1n,recipient:u.address,slippageBps:0,validUntil:BigInt((await p.getBlock("latest")).timestamp+60)};await assert.rejects(q.quoteBestNet(net,["0x"],[],[]));});
 it("isolates a failed adapter and selects a surviving quote",async()=>{const bad=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,200,100),good=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,150,100);await(await r.addDex(ethers.id("BAD"),bad.target,"bad",100)).wait();await(await r.addDex(ethers.id("GOOD"),good.target,"good",90)).wait();await(await bad.setQuoteFailure(true)).wait();const x=await q.quoteBest(a.target,b.target,100n,["0x","0x"]);assert.equal(x.dexId,ethers.id("GOOD"));assert.equal(x.amountOut,150n);});
 it("uses priority only as deterministic tie-breaker",async()=>{const low=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,1,1),high=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,1,1);await(await r.addDex(ethers.id("LOW"),low.target,"low",10)).wait();await(await r.addDex(ethers.id("HIGH"),high.target,"high",20)).wait();const x=await q.quoteBest(a.target,b.target,100n,["0x","0x"]);assert.equal(x.dexId,ethers.id("HIGH"));});
 it("ignores disabled DEX entries even when they quote more",async()=>{const high=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,2,1),low=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,1,1),hid=ethers.id("HIGH");await(await r.addDex(hid,high.target,"high",100)).wait();await(await r.addDex(ethers.id("LOW"),low.target,"low",10)).wait();await(await r.setDexEnabled(hid,false)).wait();const x=await q.quoteBest(a.target,b.target,100n,["0x","0x"]);assert.equal(x.amountOut,100n);});
 it("selects positive net output and binds selected route metadata",async()=>{const x=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,2,1),id=ethers.id("X");await(await r.addDex(id,x.target,"x",7)).wait();const block=await p.getBlock("latest"),req={chainId:(await p.getNetwork()).chainId,tokenIn:a.target,tokenOut:b.target,amountIn:100n,recipient:u.address,slippageBps:100,validUntil:BigInt(block.timestamp+60)},res=await q.quoteBestNet(req,["0x1234"],[10n],[5n]);assert.equal(res.grossAmountOut,200n);assert.equal(res.netAmountOut,185n);assert.equal(res.minimumAmountOut,198n);assert.equal(res.dexId,id);assert.notEqual(res.routeHash,ethers.ZeroHash);});
 it("fails closed when every quote fails or costs consume gross output",async()=>{const x=await dep("MockRouterV2DexAdapter","mocks/MockRouterV2DexAdapter",o,1,1);await(await r.addDex(ethers.id("X"),x.target,"x",1)).wait();const block=await p.getBlock("latest"),req={chainId:(await p.getNetwork()).chainId,tokenIn:a.target,tokenOut:b.target,amountIn:100n,recipient:u.address,slippageBps:0,validUntil:BigInt(block.timestamp+60)};await assert.rejects(q.quoteBestNet(req,["0x"],[60n],[40n]));await(await x.setQuoteFailure(true)).wait();await assert.rejects(q.quoteBest(a.target,b.target,100n,["0x"]));});
});