import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 2/9 Risk / Emergency Control boundaries",function(){
 this.timeout(30000);let p,o,riskAdmin,pause,attacker,r,a,b,id;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true},wallet:{totalAccounts:5}}));o=await p.getSigner(0);riskAdmin=await p.getSigner(1);pause=await p.getSigner(2);attacker=await p.getSigner(3);r=await dep("LQCRiskRegistry","router-v2/LQCRiskRegistry",o,o.address,riskAdmin.address);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");id=ethers.id("DEX");await(await r.setExecutor(o.address)).wait();await(await r.setPauseAdmin(pause.address)).wait();await(await r.setTokenLimits(a.target,true,100n,200n)).wait();await(await r.setTokenLimits(b.target,true,1000n,1000n)).wait();await(await r.setDexTokenCap(id,a.target,80n)).wait();});
 it("allows emergency pause by risk or pause admin but resume only by owner",async()=>{await(await r.connect(pause).pauseSwaps()).wait();assert.equal(await r.swapsPaused(),true);await assert.rejects(r.connect(pause).resumeSwaps());await assert.rejects(r.connect(riskAdmin).resumeSwaps());await(await r.resumeSwaps()).wait();await(await r.connect(riskAdmin).pauseSwaps()).wait();assert.equal(await r.swapsPaused(),true);});
 it("prevents emergency admins from expanding token or DEX risk",async()=>{await assert.rejects(r.connect(riskAdmin).reduceLimits(a.target,101n,200n));await assert.rejects(r.connect(riskAdmin).reduceDexTokenCap(id,a.target,81n));await assert.rejects(r.connect(pause).reduceLimits(a.target,50n,100n));const lim=await r.tokenLimits(a.target);assert.equal(lim.maxPerTransaction,100n);assert.equal(await r.dexTokenCap(id,a.target),80n);});
 it("rolls back daily usage on DEX, transaction, daily, duplicate, and pause rejection",async()=>{const usage=async()=>BigInt((await r.dailyUsage(a.target)).amount);assert.equal(await usage(),0n);for(const call of [()=>r.consumeSwap(a.target,b.target,[id],[81n]),()=>r.consumeSwap(a.target,b.target,[id,id],[40n,40n])]){await assert.rejects(call());assert.equal(await usage(),0n);}await(await r.consumeSwap(a.target,b.target,[id],[80n])).wait();assert.equal(await usage(),80n);await assert.rejects(r.consumeSwap(a.target,b.target,[id],[80n]));assert.equal(await usage(),80n);await(await r.connect(pause).pauseSwaps()).wait();await assert.rejects(r.consumeSwap(a.target,b.target,[id],[1n]));assert.equal(await usage(),80n);});
 it("rejects unauthorized executor and governance mutations",async()=>{await assert.rejects(r.connect(attacker).consumeSwap(a.target,b.target,[id],[1n]));await assert.rejects(r.connect(attacker).setExecutor(attacker.address));await assert.rejects(r.connect(attacker).setRiskAdmin(attacker.address));await assert.rejects(r.connect(attacker).setPauseAdmin(attacker.address));await assert.rejects(r.connect(attacker).setTokenLimits(a.target,true,999n,999n));await assert.rejects(r.connect(attacker).setDexTokenCap(id,a.target,999n));});
 it("keeps ownership two-step and does not implicitly transfer emergency roles",async()=>{await(await r.beginOwnershipTransfer(attacker.address)).wait();await assert.rejects(r.acceptOwnership());await(await r.connect(attacker).acceptOwnership()).wait();assert.equal(await r.owner(),attacker.address);assert.equal(await r.riskAdmin(),riskAdmin.address);assert.equal(await r.pauseAdmin(),pause.address);assert.equal(await r.executor(),o.address);});
});