import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
const pack=(tokens,fees)=>{let x=tokens[0].slice(2);for(let i=0;i<fees.length;i++)x+=fees[i].toString(16).padStart(6,"0")+tokens[i+1].slice(2);return "0x"+x};
describe("LQC official 2/3 Pancake V3 Adapter boundaries",function(){
 this.timeout(30000);let p,o,user,a,b,c,q,s,v;const dep=async(n,src,sg,...x)=>{const z=art(n,src),k=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await k.waitForDeployment();return k};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);user=await p.getSigner(1);a=await dep("MockERC20","mocks/MockERC20",o,"A","A");b=await dep("MockERC20","mocks/MockERC20",o,"B","B");c=await dep("MockERC20","mocks/MockERC20",o,"C","C");q=await dep("MockV3Quoter","mocks/MockV3Quoter",o,2);s=await dep("MockV3SwapRouter","mocks/MockV3SwapRouter",o,2);v=await dep("PancakeV3ExecutionAdapter","router-v2/adapters/PancakeV3ExecutionAdapter",o,q.target,s.target,o.address,2);await(await v.setFeeTierAllowed(2500,true)).wait();await(await v.setPoolAllowed(a.target,b.target,2500,true)).wait();});
 it("rejects malformed, endpoint-mismatched, unapproved-fee, and unapproved-pool routes",async()=>{await assert.rejects(v.quoteExactInput(a.target,b.target,1n,"0x1234"));await assert.rejects(v.quoteExactInput(b.target,a.target,1n,pack([a.target,b.target],[2500])));await assert.rejects(v.quoteExactInput(a.target,b.target,1n,pack([a.target,b.target],[500])));await(await v.setFeeTierAllowed(500,true)).wait();await assert.rejects(v.quoteExactInput(a.target,b.target,1n,pack([a.target,b.target],[500])));});
 it("enforces max hops before quoting",async()=>{await(await v.setPoolAllowed(b.target,c.target,2500,true)).wait();const ok=pack([a.target,b.target,c.target],[2500,2500]);assert.equal(await v.quoteExactInput(a.target,c.target,5n,ok),10n);const d=await dep("MockERC20","mocks/MockERC20",o,"D","D");const tooMany=pack([a.target,b.target,c.target,d.target],[2500,2500,2500]);await assert.rejects(v.quoteExactInput(a.target,d.target,5n,tooMany));});
 it("keeps fee/pool configuration and ownership owner-only with two-step transfer",async()=>{await assert.rejects(v.connect(user).setFeeTierAllowed(500,true));await assert.rejects(v.connect(user).setPoolAllowed(a.target,b.target,2500,false));await assert.rejects(v.connect(user).beginOwnershipTransfer(user.address));await(await v.beginOwnershipTransfer(user.address)).wait();await assert.rejects(v.acceptOwnership());await(await v.connect(user).acceptOwnership()).wait();assert.equal(await v.owner(),user.address);});
 it("executes an allowed route with exact input, minimum output, deadline, and zero residual approval",async()=>{const amount=100n,path=pack([a.target,b.target],[2500]),deadline=BigInt((await p.getBlock("latest")).timestamp+3600);await(await a.mint(user.address,amount)).wait();await(await b.mint(s.target,amount*2n)).wait();await(await a.connect(user).approve(v.target,amount)).wait();const out=await v.connect(user).executeExactInput.staticCall(a.target,b.target,amount,amount*2n,user.address,deadline,path);assert.equal(out,amount*2n);await(await v.connect(user).executeExactInput(a.target,b.target,amount,amount*2n,user.address,deadline,path)).wait();assert.equal(await b.balanceOf(user.address),amount*2n);assert.equal(await a.balanceOf(v.target),0n);assert.equal(await a.allowance(v.target,s.target),0n);});
 it("rejects expired execution before moving user funds",async()=>{const amount=100n,path=pack([a.target,b.target],[2500]),before=await a.balanceOf(user.address);await(await a.mint(user.address,amount)).wait();await(await a.connect(user).approve(v.target,amount)).wait();const funded=await a.balanceOf(user.address);await assert.rejects(v.connect(user).executeExactInput(a.target,b.target,amount,1n,user.address,BigInt((await p.getBlock("latest")).timestamp-1),path));assert.equal(await a.balanceOf(user.address),funded);assert.equal(await a.balanceOf(v.target),0n);before;});
});