import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 3/2 Vault Withdraw boundaries",function(){
 this.timeout(30000);let p,o,u,other,v,t;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);other=await p.getSigner(2);t=await dep("MockERC20","mocks/MockERC20",o,"Asset","AST");v=await dep("LQCLiquidityVault","vault/LQCLiquidityVault",o,t.target,o.address,1000000n,"Share","SH");await(await t.mint(u.address,100000n)).wait();await(await t.connect(u).approve(v.target,ethers.MaxUint256)).wait();await(await v.connect(u).deposit(10000n,u.address)).wait();});
 it("withdraws exact assets while rounding shares upward",async()=>{const shares=await v.connect(u).withdraw.staticCall(3333n,u.address,u.address);await(await v.connect(u).withdraw(3333n,u.address,u.address)).wait();assert.equal(await t.balanceOf(u.address),93333n);assert.equal(await v.totalAssets(),6667n);assert.equal(shares,3333n);});
 it("redeems exact shares at current accounted share price",async()=>{const shares=2000n,expected=await v.convertToAssets(shares),before=await t.balanceOf(u.address);await(await v.connect(u).redeem(shares,u.address,u.address)).wait();assert.equal((await t.balanceOf(u.address))-before,expected);assert.equal(await v.balanceOf(u.address),9000n-2000n);});
 it("requires delegated allowance and consumes the exact share allowance",async()=>{const shares=await v.connect(u).withdraw.staticCall(1000n,other.address,u.address);await assert.rejects(v.connect(other).withdraw(1000n,other.address,u.address));await(await v.connect(u).approve(other.address,shares)).wait();await(await v.connect(other).withdraw(1000n,other.address,u.address,{gasLimit:500_000n})).wait();assert.equal(await v.allowance(u.address,other.address),0n);assert.equal(await t.balanceOf(other.address),1000n);});
 it("rejects zero or vault receiver and preserves shares/assets",async()=>{const bs=await v.balanceOf(u.address),ba=await v.totalAssets();await assert.rejects(v.connect(u).withdraw(1n,ethers.ZeroAddress,u.address));await assert.rejects(v.connect(u).withdraw(1n,v.target,u.address));assert.equal(await v.balanceOf(u.address),bs);assert.equal(await v.totalAssets(),ba);});
 it("fails closed when requested assets exceed idle liquidity",async()=>{const Adapter=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await Adapter.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(8000n,0)).wait();await(await v.allocateToStrategy(8000n)).wait();const bs=await v.balanceOf(u.address);await assert.rejects(v.connect(u).withdraw(2001n,u.address,u.address));assert.equal(await v.balanceOf(u.address),bs);assert.equal(await v.strategyDebt(),8000n);});
});