import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 3/5 Vault Cap / Risk boundaries",function(){
 this.timeout(30000);let p,o,u,v,t;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);t=await dep("MockERC20","mocks/MockERC20",o,"Asset","AST");v=await dep("LQCLiquidityVault","vault/LQCLiquidityVault",o,t.target,o.address,10000n,"Share","SH");await(await t.mint(u.address,50000n)).wait();await(await t.connect(u).approve(v.target,ethers.MaxUint256)).wait();});
 it("accepts deposit exactly at cap and rejects one wei above without drift",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const before=await t.balanceOf(u.address);await assert.rejects(v.connect(u).deposit(1n,u.address));assert.equal(await v.totalAssets(),10000n);assert.equal(await t.balanceOf(u.address),before);});
 it("never allows governance to set deposit cap below accounted assets",async()=>{await(await v.connect(u).deposit(5000n,u.address)).wait();await assert.rejects(v.setDepositCap(4999n));await(await v.setDepositCap(5000n)).wait();assert.equal(await v.depositCap(),5000n);});
 it("enforces strategy cap at the exact boundary and rejects excess exposure",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const A=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(4000n,0)).wait();await(await v.allocateToStrategy(4000n)).wait();await assert.rejects(v.allocateToStrategy(1n));assert.equal(await v.strategyDebt(),4000n);});
 it("prevents strategy cap reduction below current debt and excessive configured loss",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const A=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(4000n,0)).wait();await(await v.allocateToStrategy(3000n)).wait();await assert.rejects(v.setStrategyLimits(2999n,0));await assert.rejects(v.setStrategyLimits(4000n,2001));assert.equal(await v.strategyDebt(),3000n);});
 it("prevents unsolicited donations from expanding strategy risk capacity",async()=>{await(await v.connect(u).deposit(5000n,u.address)).wait();await(await t.mint(o.address,5000n)).wait();await(await t.transfer(v.target,5000n)).wait();const A=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(10000n,0)).wait();await assert.rejects(v.allocateToStrategy(5001n));await(await v.allocateToStrategy(5000n)).wait();assert.equal(await v.strategyDebt(),5000n);assert.equal(await v.idleAssets(),5000n);});
});