import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 3/3 Vault Accounting boundaries",function(){
 this.timeout(30000);let p,o,u,v,t;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);t=await dep("MockERC20","mocks/MockERC20",o,"Asset","AST");v=await dep("LQCLiquidityVault","vault/LQCLiquidityVault",o,t.target,o.address,1000000n,"Share","SH");await(await t.mint(u.address,100000n)).wait();await(await t.connect(u).approve(v.target,ethers.MaxUint256)).wait();});
 it("keeps totalAssets equal to accounted assets rather than raw token balance",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();await(await t.mint(o.address,5000n)).wait();await(await t.transfer(v.target,5000n)).wait();assert.equal(await v.totalAssets(),10000n);assert.equal(await v.idleAssets(),15000n);assert.equal(await v.accountedIdleAssets(),10000n);});
 it("preserves share price across proportional deposit and redeem",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const before=await v.convertToAssets(1000n);await(await t.mint(o.address,5000n)).wait();await(await t.approve(v.target,5000n)).wait();await(await v.deposit(5000n,o.address)).wait();assert.equal(await v.convertToAssets(1000n),before);});
 it("keeps totalAssets unchanged when accounted idle assets move to strategy",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const A=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(4000n,0)).wait();await(await v.allocateToStrategy(4000n)).wait();assert.equal(await v.totalAssets(),10000n);assert.equal(await v.accountedIdleAssets(),6000n);assert.equal(await v.strategyDebt(),4000n);});
 it("reduces accounted assets only by recognized strategy loss",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const A=new ethers.ContractFactory(art("MockLossyStrategyAdapter","mocks/MockLossyStrategyAdapter").abi,art("MockLossyStrategyAdapter","mocks/MockLossyStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(5000n,1000)).wait();await(await v.allocateToStrategy(5000n)).wait();await(await s.setLossBps(1000)).wait();await(await v.recallFromStrategy(1000n)).wait();assert.equal(await v.totalAssets(),9900n);assert.equal(await v.strategyDebt(),4000n);});
 it("keeps locked minimum shares represented in total supply after user exits",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const shares=await v.balanceOf(u.address);await(await v.connect(u).redeem(shares,u.address,u.address)).wait();assert.equal(await v.totalSupply(),1000n);assert.equal(await v.balanceOf(ethers.ZeroAddress),1000n);assert.equal(await v.totalAssets(),1000n);});
});