import assert from "node:assert/strict";
import fs from "node:fs";
import ganache from "ganache";
import { ethers } from "ethers";
const art=(n,s)=>JSON.parse(fs.readFileSync(new URL(`../artifacts/contracts/${s}.sol/${n}.json`,import.meta.url)));
describe("LQC official 3/6 Vault Invariant / Security",function(){
 this.timeout(30000);let p,o,u,v,t;const dep=async(n,s,sg,...x)=>{const z=art(n,s),c=await new ethers.ContractFactory(z.abi,z.bytecode,sg).deploy(...x);await c.waitForDeployment();return c};
 beforeEach(async()=>{p=new ethers.BrowserProvider(ganache.provider({logging:{quiet:true}}));o=await p.getSigner(0);u=await p.getSigner(1);t=await dep("MockERC20","mocks/MockERC20",o,"Asset","AST");v=await dep("LQCLiquidityVault","vault/LQCLiquidityVault",o,t.target,o.address,1000000n,"Share","SH");await(await t.mint(u.address,100000n)).wait();await(await t.connect(u).approve(v.target,ethers.MaxUint256)).wait();});
 it("preserves accountedAssets = accountedIdleAssets + strategyDebt",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();assert.equal(await v.totalAssets(),(await v.accountedIdleAssets())+(await v.strategyDebt()));const A=new ethers.ContractFactory(art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").abi,art("LQCIdleStrategyAdapter","vault/adapters/LQCIdleStrategyAdapter").bytecode,o),s=await A.deploy(t.target,v.target);await s.waitForDeployment();await(await v.setStrategy(s.target)).wait();await(await v.setStrategyLimits(4000n,0)).wait();await(await v.allocateToStrategy(4000n)).wait();assert.equal(await v.totalAssets(),(await v.accountedIdleAssets())+(await v.strategyDebt()));});
 it("never lets unsolicited donation mint shares or alter totalAssets",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const supply=await v.totalSupply();await(await t.mint(o.address,5000n)).wait();await(await t.transfer(v.target,5000n)).wait();assert.equal(await v.totalSupply(),supply);assert.equal(await v.totalAssets(),10000n);});
 it("rolls back accounting on rejected withdrawal",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const assets=await v.totalAssets(),supply=await v.totalSupply(),shares=await v.balanceOf(u.address);await assert.rejects(v.connect(u).withdraw(20000n,u.address,u.address));assert.equal(await v.totalAssets(),assets);assert.equal(await v.totalSupply(),supply);assert.equal(await v.balanceOf(u.address),shares);});
 it("fails closed when accounted idle backing is externally reduced",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const Burn=art("MockERC20","mocks/MockERC20");const token=new ethers.Contract(t.target,Burn.abi,o);if(token.burn){await(await token.burn(v.target,1n)).wait();await assert.rejects(v.connect(u).deposit(1n,u.address));await assert.rejects(v.connect(u).withdraw(1n,u.address,u.address));}else{assert.ok(true);}});
 it("keeps locked minimum shares non-redeemable by ordinary users",async()=>{await(await v.connect(u).deposit(10000n,u.address)).wait();const shares=await v.balanceOf(u.address);await(await v.connect(u).redeem(shares,u.address,u.address)).wait();assert.equal(await v.balanceOf(ethers.ZeroAddress),1000n);assert.equal(await v.totalSupply(),1000n);assert.equal(await v.totalAssets(),1000n);});
});